### ISSUE TITLE
Arc loader not autobooting (but manually working)

### ISSUE THREAD

**Issue by TouCam4** [AuxXxilium/arc#1006]
Hi, everybody!

The loader seems to work, but, after a reboot ordered from inside the DSM, the PC stays waiting in the menu, If I press <Enter> it works, but the PC will not have a keyboard and also I won't be there to press any key...

I must sasy that the same problem happens with some other loaders, arc a included.

I tried the directboot method, with the same problem. Changing the model does not solve the problem.

Finally I uploaded the config with 276HT6E3P code.

May you help me?

Thank you in advance!

**Comment by AuxXxilium** [comment]
if this happens, you have ghost inputs from your keyboard or something else. than the boot in grub will be paused and waiting for user interaction

**Comment by TouCam4** [comment]
Oh, my Godness!

I unplug the keyboard and the mouse (maybe a ghost could be using them...). The problem persists.

I disable the onboard serial port and volià!

Maybe a noisy serial port? But the serial used IRQ4 and I believe this interrupt is only used by the serial port, so how is it possible?

Thank you very much for your help!

I hope this will help someone with the same problem.

**Comment by AuxXxilium** [comment]
to disable serial ports is written in wiki. if ppl don't read the wiki, i can't help. 🤦‍♂️

**Comment by TouCam4** [comment]
Let's see, I haven't complained at any time!

I just have to thank you for your work, but I had read the wiki, although not all of it, and I did see something about "Disable Serial Console in ILO, IPMI and so on...", but bear in mind that I don't know what they are ILO and IPMI and I have still tried disabling the serial port.

Thanks, again.

Perhaps it would be interesting to make explicit mention in the wiki of "disabling the serial port", for non-experts, it is an idea.

And thanks again!

**Comment by AuxXxilium** [comment]
most ilo and ipmi cause this issue. that's why i mentioned these two.
