### ISSUE TITLE
V23.03.03 DS923+ no Serial Number

### ISSUE THREAD

**Issue by RJSUTH** [AuxXxilium/arc#101]
DS923+ shows serial number on first boot, but not after DSM is installed

**Comment by AuxXxilium** [comment]
Please give me a screen from arc -sysinfo and the boot cmdline shown on boot

**Comment by RJSUTH** [comment]
![image](https://user-images.githubusercontent.com/122780513/222894486-a7b4e74a-98fc-4b04-8dc7-cb5bd60c187e.png)


![IMG_9237](https://user-images.githubusercontent.com/122780513/222894752-edf64cfc-f33d-4e75-9ab1-cafd8ea4dc1a.jpg)

![image](https://user-images.githubusercontent.com/122780513/222894527-e1fc4bd9-acfc-40eb-b441-fcc8ec8d0c45.png)

**Comment by AuxXxilium** [comment]
Do not use Syno assistant, look in "Control Panel - Info-Center" in DSM for the SN

you see SN is given at boot.

**Comment by RJSUTH** [comment]
![image](https://user-images.githubusercontent.com/122780513/222896496-0ad0d7fe-bb24-4f91-bc18-c3a405ea808a.png)

**Comment by AuxXxilium** [comment]
Don't know where the issue is. Other models are working. DS923+ makes this issue. Looks like SN isn't given to DSM.

**Comment by RJSUTH** [comment]
I would use DS3622xs+ but there is a problem with Cold Startup with more than 2 DIsks (i have 4 Disks as Raid5).

Booting hang in a loop with this messages ifi have all 4 disks inserted.
IF i pull 2 out then DSM Starts correctly.

I have this issue with several hardware equipment: Thecus NAS, HP-54NL. Fujitus TX1320-M3

I hope u can fix the issues 


 201.310925] Call Trace:
[  201.313651]  [<ffffffffa0132ebe>] acpi_idle_do_entry+0x3e/0x40 [processor]
[  201.321322]  [<ffffffffa0132f15>] acpi_idle_enter_bm+0x55/0x130 [processor]
[  201.329092]  [<ffffffffa01331dd>] acpi_idle_enter+0x19d/0x280 [processor]
[  201.336667]  [<ffffffff814840f5>] cpuidle_enter_state+0xf5/0x2c0
[  201.343371]  [<ffffffff814842f2>] cpuidle_enter+0x12/0x20
[  201.349394]  [<ffffffff8108af29>] cpu_startup_entry+0x299/0x320
[  201.356001]  [<ffffffff810b5109>] ? clockevents_config_and_register+0x29/0x30
[  201.363964]  [<ffffffff81030a2a>] start_secondary+0x10a/0x110
[  201.370377] Code: 08 c0 ff ff 0f 01 c8 48 8b 86 08 c0 ff ff a8 08 75 19 8b 05 1a 48 9a 00 85 c0 7e 07 0f 00 2d 27 8b 5d 00 89 f8 44 89 c1 0f 01 c9 <65> 48 8b 04 25 44 48 00 00 f0 80 a0 0a c0 ff ff df 0f ae f0 48
[  201.637340] udevd[4928]: timeout: killing 'ata_id --export /dev/sdc' [4933]
[  201.645115] udevd[4928]: slow: 'ata_id --export /dev/sdc' [4933]
[  202.652349] udevd[4928]: timeout: killing 'ata_id --export /dev/sdc' [4933]
[  202.660121] udevd[4928]: slow: 'ata_id --export /dev/sdc' [4933]
[  203.667357] udevd[4928]: timeout: killing 'ata_id --export /dev/sdc' [4933]
[  203.675130] udevd[4928]: slow: 'ata_id --export /dev/sdc' [4933]
[  204.682367] udevd[4928]: timeout: killing 'ata_id --export /dev/sdc' [4933]
[  204.690140] udevd[4928]: slow: 'ata_id --export /dev/sdc' [4933]
[  205.697376] udevd[4928]: timeout: killing 'ata_id --export /dev/sdc' [4933]
[  205.705147] udevd[4928]: slow: 'ata_id --export /dev/sdc' [4933]

**Comment by AuxXxilium** [comment]
With 3622 and 4021 there is no issue like this. So it depends on your Bios config.

923 is a bigger problem.

**Comment by RJSUTH** [comment]
You are right, for 3622 and 4021 i have to deactivate Hyperthreading for Core I3-7100 in Bios.

**Comment by AuxXxilium** [comment]
this is possible. you can try to deactivate memory remap and activate ht again. that should fix the issue.

**Comment by AuxXxilium** [comment]
I found the SN issue in DS923 - it's a bug in DSM, so we have to wait for syno, I can't fix it. because the serial is written to /etc/synoinfo.conf and /etc.defaults/synoinfo.conf but not loaded by system.

**Comment by RJSUTH** [comment]
> this is possible. you can try to deactivate memory remap and activate ht again. that should fix the issue.

Unfortunately, there is no setting option for this in the Fujitsu Bios.
Then I leave HT off

**Comment by RJSUTH** [comment]
I tried DS923+ again without ARC Patch, now DSM has a serial, maybe an issue with ARC Patch?

**Comment by AuxXxilium** [comment]
No. Blocked Serial. i changed it in latest release.

**Comment by RJSUTH** [comment]
Perfect!
