### ISSUE TITLE
No network after booting loader

### ISSUE THREAD

**Issue by petroionut26** [AuxXxilium/arc#1013]
I have no network(or everthing freezes, only orange led blinks on nic) after loader boots up on QC5000M-ITX/PH with RTL8111GR, even though in config everthing seems to be ok with r8168..

**Comment by petroionut26** [comment]
In config mode i have ip, i can connect to ip and port 7681

I have uploaded sysinfo, GQERMFLT4.

**Comment by AuxXxilium** [comment]
select amd model for your apu. the network doesn't start because there is something else earlier wrong. check bios settings with wiki and select native amd model.

**Comment by petroionut26** [comment]
With sa6400 everything works, even home assistant runing in VMM. Quickconnect also working. Thanks alof for this awsome loader!
