### ISSUE TITLE
custom myds923

### ISSUE THREAD

**Issue by TheTaran** [AuxXxilium/arc#1025]
{"model":"DS1823xs+","version":"7.2","format":"img","addons":["codecpatch","cpuinfo","dbgutils","deduplication","dsmconfigbackup","expands","photosfacepatch","surveillancepatch"]}

**Comment by Keywan2009** [comment]
Hi TheTaran,

Could you please send me your PW script you mention in 
 How to create an automation to update applications that are in ConfigMgr? #165 
I have done that with PowerShell. That's pretty simple. If you need some code, let mi know.

I want to upgrade my created application in Ruckzuck automatically
