### ISSUE TITLE
ESXI VM arc.vmdk hinzufügen fehlerhaft

### ISSUE THREAD

**Issue by RRonGit** [AuxXxilium/arc#104]
Umgebung: 

ESXI Host Version : ESXi-7.0U3k-21313628-standard

Ich habe die Dateien arc.vmdk und die arc-flat.vmdk auf den ESXi Host hochgeladen.

Die Disk arc.vmdk kann nicht zur VM hinzugefügt werden siehe Screenshot.

Das Problem besteht erst nach dem ich den ESXi Host auf Version ESXi-7.0U3k-21313628-standard geupdatet habe.

![esxi](https://user-images.githubusercontent.com/11077414/222925642-3242917d-370d-42b2-9b06-62a6debcd706.jpg)

**Comment by AuxXxilium** [comment]
Ja ist ein bekannter Bug von ESXI. Bei 8.0 haben sie es mit der neuesten Version gefixt. Bei 7.0u3 ging es bis g glaube.

**Comment by RRonGit** [comment]
ok vielen Dank für den Hinweis.
Mit der Hilfe deines Videos (https://www.youtube.com/watch?v=W1qffK3thw4) startet der Loader und ich kann soweit alles konfigurieren.
Doch leider beim ersten Boot ist die IP, die in der Konsole angezeigt wird, nicht ping bar, resp. nur kurz drei Pings gehen dann ist der Ping weg und das Webgui für die Einrichtung der Synology ist entsprechend auch nicht erreichbar

**Comment by AuxXxilium** [comment]
Schau mal in meinem Github Wiki. Du musst die Mac Adressänderungen freigeben.

**Comment by RRonGit** [comment]
Habe ich eingestellt geht aber leider trotzdem nicht.

![image](https://user-images.githubusercontent.com/11077414/222928115-9dd9620c-8725-4db2-9229-e4752a59f4ec.png)

**Comment by AuxXxilium** [comment]
Dann hast du es wohl in einer anderen Option gesperrt. Nutze 3 verschiedene ESXi Server gerade und es geht auf allen 3. Da passt irgendwas in deinen Einstellungen nicht.

**Comment by AuxXxilium** [comment]
Liegt deine Arc Disk auch wirklich aus Sata 0:0?

**Comment by RRonGit** [comment]
Ja die xp06_1.vmdk ist die Arc Disk, habe schon ein paar Synologys mit deinem Loader zum laufen gebracht, bisher klappte das super gut bis zum Update des ESXi Hosts....

![image](https://user-images.githubusercontent.com/11077414/222928495-a015e29d-ee4e-43f9-a246-9eaa6e7bab08.png)

**Comment by AuxXxilium** [comment]
Keine Ahnung was die wieder geändert haben. Habe mit Absicht auf 7.0u3 die letzten Updates nicht gemacht.

**Comment by RRonGit** [comment]
Ok danke für deine Hilfe, ich versuche den Patch, das Update auf dem ESXi Host rückgängig zu machen.

**Comment by AuxXxilium** [comment]
Dein 1. Post, zeigt mir nur dass sie die Bugs von den ersten 2 8.0 Release in 7.0u3 eingebaut haben. Manchmal frage ich mich, ob die ihre Sachen noch überprüfen.

**Comment by RRonGit** [comment]
Ich habe nun ein Rollback auf die ESXi Version ESXi-7.0U3g-20328353-standard gemacht, nun funktioniert  das Ganze wieder.
