### ISSUE TITLE
time on bios isnt correct. May be bios time set by Arc loader on Germany (GMT+1). Pleasse check to real time

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#1044]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
Simply no! There is no Time/Timezone Setting in Arc. So the Time you set in your Bios is wrong.

**Comment by TTTnas** [comment]
I am in Moscow GMT+3. I set correct time on Bios but after sometime the time will be lost 3 hours (minutes is correct). I think it is GMT+1 where you are. May be
I want to use Weak by RTC to turn on machine everyday. On DSM it doesnt work
