### ISSUE TITLE
AME doesn't work

### ISSUE THREAD

**Issue by m5a3x6** [AuxXxilium/arc#1049]
Hello! Please help! I have DS3622xs+ installed with arc patch. amepatch was not installed. Quick connect works properly, everything is fine. However, I am unable to activate AME. He says check your Internet connection, but everything is fine with the Internet, I tried different DNS, including 8.8.8.8. Please tell me how can I activate AME?

Thank you!

**Comment by AuxXxilium** [comment]
do the thing mentioned above, than i can try to help.

**Comment by m5a3x6** [comment]
![image](https://github.com/AuxXxilium/arc/assets/27850763/9a16792a-2d06-496a-b352-a53367c5a50a)
![image](https://github.com/AuxXxilium/arc/assets/27850763/36620741-ac9b-4379-9888-a46d0b5aae81)
![image](https://github.com/AuxXxilium/arc/assets/27850763/b7c45300-c782-4dc5-a409-c243b04613e4)
![image](https://github.com/AuxXxilium/arc/assets/27850763/d11c3f5e-fe07-48ba-933c-4599ad2078e5)

**Comment by AuxXxilium** [comment]
Update Loader

**Comment by m5a3x6** [comment]
Just a couple of hours ago I tried to update the bootloader. However, after the success message and after a reboot, the old version of the bootloader is displayed :/
![image](https://github.com/AuxXxilium/arc/assets/27850763/3b606ff8-6755-4373-ad57-38d120acf039)
Looks like I'm doing something wrong :(

**Comment by m5a3x6** [comment]
Hm. Or maybe the problem is that the loader is written to the m2 drive? and loading is performed from it.
I did not set up write protection. Just burned the image via balena and inserted the disc into nas.
Sorry for my stupid questions(

**Comment by AuxXxilium** [comment]
you can use a stick and clone function inside arc.

**Comment by m5a3x6** [comment]
I flashed a new loader. But I still get an error when starting AME :(
But now the error is different. Previously it was written about problems with the Internet. Now it's just "Unable to complete the operation. Please contact support"
new sysinfo upload C8F84DFLE

**Comment by AuxXxilium** [comment]
than there is something wrong in your system or network. looks like there is no stable connection to syno api.

**Comment by m5a3x6** [comment]
Oh.. I'll try without arcpatch but with amepatch. AME is more important than quickconnect :/
Thank you
