### ISSUE TITLE
Firs HDD empty and don't see 27's HDD

### ISSUE THREAD

**Issue by igitlin** [AuxXxilium/arc#1099]
Use ARC 24.4.13.
but first HDD as empty and i don't see my second SSD.
How to i can configure loader for use all my 24x HDD and 2x SSD?

**Screenshots**
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/474a4ea1-339c-4378-bd93-fb3171e18ca9)
FULL SysInfo CJPMJ6Z6Q
**Hardware**
SuperMicroX10SRA-F Xeon E5-2650v4 /64Gb ECC REG / LSI9300-i16 (15x3Tb) + LSI9300-i16 (9x6Tb)+(2xSSD512Gb)

**Comment by igitlin** [comment]
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/8e3d460a-9ef0-4303-943d-49cf78805b58)
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/8c471663-fb18-492e-a55d-485a048e66fb)
i try to change Sort HDD set to false or true, but first drive is empty.
Why did the disks move one position and not return to their place?

**Comment by AuxXxilium** [comment]
need user config filer also. looks like config issue. btw use sa6400 for this amount of disks!

**Comment by igitlin** [comment]
i try use default user config and try to edit
drive =32
hdd = 32
usb =0

try to 

drive =27
hdd = 27
usb =0
now i try this user config
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/37c3d1df-bc89-4b6e-aba1-158e11ade5e3)

**Comment by igitlin** [comment]
SA6400 see all drives but doesn't see Mellanox 312A dual net
2NY5A9A7P

**Comment by AuxXxilium** [comment]
> i try use default user config and try to edit
> 
> drive =32
> 
> hdd = 32
> 
> usb =0
> 
> 
> 
> try to 
> 
> 
> 
> drive =27
> 
> hdd = 27
> 
> usb =0
> 
> now i try this user config
> 
> ![изображение](https://github.com/AuxXxilium/arc/assets/30923527/37c3d1df-bc89-4b6e-aba1-158e11ade5e3)
> 
> 

this will not help with your issue. i need the full user config not only parts!

**Comment by igitlin** [comment]
how to export user config?

**Comment by AuxXxilium** [comment]
disk limit is only removable for dt models like sa6400. use sa6400 and activate custom kernel. if your bios settings are corrct you will have everything you want.

**Comment by igitlin** [comment]
> disk limit is only removable for dt models like sa6400. use sa6400 and activate custom kernel. if your bios settings are corrct you will have everything you want.
Yes i try start SA6400 - all disks work, but doesn't work Mellatox 10Gb - DSM see only 2 nic on MoBo 2x 1Gb
Acr in synoinfo display all 4 nic and 2x 1Gb and 2x 10Gb MLX4 added

**Comment by AuxXxilium** [comment]
i told you some messages earlier, that we can't reload modules which are included in dsm stock kernel. so you should switch to custom kernel.

**Comment by igitlin** [comment]
> i told you some messages earlier, that we can't reload modules which are included in dsm stock kernel. so you should switch to custom kernel.
I apologize for asking stupid questions, but I'm trying to figure out how to install the SA6400 and still have 10GB working

1. I reset Loader, select models SA6400, select patches, select HW MAC,
2. select DSM 7.2
3. select addons 
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/e353c5e7-ce40-4f93-b7f6-c84a9b1f251f)
4. next i want to make changes 
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/e6a3256c-20c3-47b4-a364-e676dc40cb2a)
Sysinfo
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/51dcde8c-1808-4478-adba-6d653389e8c4)
Full Sysinfo F93ZMG9QB
5. Show DSM Options, select Kernel as Custom
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/ed9d379c-07d6-4456-8951-ff93e77b3d36)

Need to choose something else?
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/1b1b9cda-4f34-4cc6-8867-fcc967595de7)
build loader
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/e8e9ce1a-2f88-42cb-974c-81d875054c24)
Full Sysinfo BGYPRYHZD
After build and reboot only one NIC - 1Gb, no 10Gb.
![изображение](https://github.com/AuxXxilium/arc/assets/30923527/ee45891c-427c-4536-87e7-bfeb4777c60f)

I'm completely confused, I chose the custom kernel but I still don't see the 10GB network adapters

**Comment by igitlin** [comment]
[user-config.zip](https://github.com/AuxXxilium/arc/files/14984804/user-config.zip)
[jrExit.zip](https://github.com/AuxXxilium/arc/files/14984805/jrExit.zip)
