### ISSUE TITLE
J3455 boost processor, low perfomance

### ISSUE THREAD

**Issue by petroionut26** [AuxXxilium/arc#1103]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

My hardware is GA-J3455N-D3H (rev. 1.0), and only working solution is to build sa6400 loader, but in seeting info cpu_clock is 798Mhz, in "cat /proc/cpuinfo | grep Mhz" i see 2.2ghz and geekbench results are: https://browser.geekbench.com/v6/cpu/5726582). Anything else failes to boot, kernel panic i think, also image dissapears on boot procces.

Also i have uploaded my fullinfo code: FAEYA9AEX

**Comment by AuxXxilium** [comment]
cpu info is only optical and read out while boot, if your cpu is at 800mhz at this time, it will show 800mhz. but has nothing to do with cpu speed at all. performance scaling will be done by acpi cmd inside dsm.
