### ISSUE TITLE
the newest loader is not working with all DT Modell with DSM version 7.1 42962 

### ISSUE THREAD

**Issue by nemesis122** [AuxXxilium/arc#1109]
Hi Christian 
the newest loader is not working with all DT Modells as example DS 923+ / SAE6400 when DSM 7.1 is installing with DSM 7.2 is working 
Tested On the Gen8 / in VMware /in Virtualbox / the issue is no drive detected.
Pls let me know when you need more information 
thank you very much and have a great time.
BR
Michael

**Comment by nemesis122** [comment]
with 24.4.7 it was working DSM version 7.1 could you have pls a look at this case thank you

**Comment by AuxXxilium** [comment]
do what is mentioned above, than i can take a look.

**Comment by nemesis122** [comment]
With the newest Loader Version all DT ( Searchtree Models) as example 923+ ot SAE6400 are not wotking when you want install DSM 7.1 

with DSM 7.2 the Models are working so in this Case there is a Problem with the newerst Loader when you want install DSM 7.1 and chosse DT Modell as example 923+ or SAE6400
