### ISSUE TITLE
Hdd dont sleep

### ISSUE THREAD

**Issue by dvbmaniak** [AuxXxilium/arc#1117]
**Hardware**
Laptop board Lenovo 300E (Pentium 5000, 4GB DDR4) /
Networkcontroller-  AMAZONBASICS Adapter USB 3.0 (1Gbit) / 
Storagecontroller- [Solidigm P41 Plus PCIe Gen4 NVMe 512 GB 2230 (for ssd cache), 
and M.2 do Sata3.0 adapter (6 sata port) Chipset: ASM1166 (2x hdd Toshiba mq04ab2200)
Boot Pen Adata 16GB

Problems drives do not go to sleep after 10 minutes (dsm settings in control panel 10minutes).

**Comment by AuxXxilium** [comment]
bios settings not correct. check wiki

**Comment by dvbmaniak** [comment]
this is a physical machine, not docker, not wm
openmediavault no problem disc sleep
truenas no problem disc sleep
testting Unraid
