### ISSUE TITLE
Kernel panic with HP ProLiant Microserevr

### ISSUE THREAD

**Issue by schubduese42** [AuxXxilium/arc#114]
Hello,
i have problems on startup with the arc loader and i've got the kernel panic error with current version v23.03.23 and older versions too.
There are any missing kernel modules?

Thanks in advance for help.

![IMG_3356](https://user-images.githubusercontent.com/5667240/227710666-29dfc012-2870-4e95-90f4-61ae82e581e8.jpg)
![IMG_3357](https://user-images.githubusercontent.com/5667240/227710671-0a64df5d-4237-46af-ab24-ae27569c375c.jpg)
![IMG_3358](https://user-images.githubusercontent.com/5667240/227710675-1053a941-cc58-4062-8f5d-45933c009716.jpg)
[lscpu.txt](https://github.com/AuxXxilium/arc/files/11068586/lscpu.txt)
[lspci.nn.txt](https://github.com/AuxXxilium/arc/files/11068587/lspci.nn.txt)
[lspci.nnk.txt](https://github.com/AuxXxilium/arc/files/11068588/lspci.nnk.txt)

**Comment by AuxXxilium** [comment]
Looks like a Bios issue. Try to disable Secure VM Mode and PowerNow. The N40L are bugy. They need a special Bios Setting, but i don't know them. You will find the solution in Xpeno Forum.

**Comment by schubduese42** [comment]
Thanks for help.
I had figured out that the problem was my USB-Stick according to the log message.

`Initramfs unpacking failed: XZ-compressed data is corrupt`

![IMG_3362](https://user-images.githubusercontent.com/5667240/227733116-5bc77725-9ad6-4eb9-8493-54218e40426a.JPG)

With an USB-Stick with more performance it works fine.
