### ISSUE TITLE
7.2 working slow on every level

### ISSUE THREAD

**Issue by P-h-o-e-n-i-x** [AuxXxilium/arc#1140]
Hello, installed ARC 7.2 DS3622xs+ on i7-4790, MSI Z87-G45 GAMING with 32GB ram and 4x10TB HDD with 2x256 SSD for cache.
The machine is running very slow on every level (installing packages, moving files, connecting with it, running container manager...)

**Screenshots**
<img width="809" alt="Screen Shot 2024-04-17 at 11 56 34" src="https://github.com/AuxXxilium/arc/assets/8360572/77cc79ed-c17d-472c-9f3b-4f69f5813c78">

I have made 4-5 machines with lower specs and have no issues with them. 
Tried new install from scratch same thing. 
What could it be?

**Comment by nemesis122** [comment]
it seems that your cpu is not running with the correct powerschema see "CPU Clock Rate"
maybe it is rleated to this setting check that is set Power
![power](https://github.com/AuxXxilium/arc/assets/12814981/ff7827c1-db86-4205-a07c-d0521fd04c7d)

**Comment by AuxXxilium** [comment]
> Hello, installed ARC 7.2 DS3622xs+ on i7-4790, MSI Z87-G45 GAMING with 32GB ram and 4x10TB HDD with 2x256 SSD for cache.
> 
> The machine is running very slow on every level (installing packages, moving files, connecting with it, running container manager...)
> 
> 
> 
> **Screenshots**
> 
> <img width="809" alt="Screen Shot 2024-04-17 at 11 56 34" src="https://github.com/AuxXxilium/arc/assets/8360572/77cc79ed-c17d-472c-9f3b-4f69f5813c78">
> 
> 
> 
> I have made 4-5 machines with lower specs and have no issues with them. 
> 
> Tried new install from scratch same thing. 
> 
> What could it be?
> 
> 
> 
> 

if there is 800mhz. it doesn't tell us anything and it has no effect to dsm at all. 

you bios settings are wrong, this cause the issue, because the cpu doesn't support acpi commmands or is set to lowest boot frequency.
