### ISSUE TITLE
Key Manager mount doesn't work

### ISSUE THREAD

**Issue by mdstoll** [AuxXxilium/arc#1146]
**Describe the Bug**
The (auto) mounting of encrypted volumes by the Key Manager isn't working.

I updated ARC and rebooted the device. Manual mounting with the key in the keymanager doesn't work. Auto maunting doesn't work either. 

Cypher is Machine Key

**Screenshots**
<img width="416" alt="Scherm­afbeelding 2024-04-17 om 18 58 41" src="https://github.com/AuxXxilium/arc/assets/22054619/2f76605c-3405-4bb7-9b8f-0239bb4f127b">
<img width="584" alt="Scherm­afbeelding 2024-04-17 om 18 57 06" src="https://github.com/AuxXxilium/arc/assets/22054619/a7cfb5ac-3e3a-47ad-b7dd-caa8d5091dfa">
<img width="383" alt="Scherm­afbeelding 2024-04-17 om 18 56 58" src="https://github.com/AuxXxilium/arc/assets/22054619/f0c008e8-7270-4cc1-a785-f76324d2b232">
<img width="750" alt="Scherm­afbeelding 2024-04-17 om 18 56 50" src="https://github.com/AuxXxilium/arc/assets/22054619/2ae383a8-bea6-4857-917b-9e4b4b6b320a">

**Hardware**
ZimaBoard
Intel N3450
8GB Ram (7GB Assigned)
1TB NVMe SSD

ESXi 6.0
Arc Version 24.4.17

**Comment by mdstoll** [comment]
Manual mounting with the key works. I refreshed the key in the key manager but no improvement.

**Comment by AuxXxilium** [comment]
key will be deleted by any update. read wiki! if you don't use key backup function or download it manually over sftp.
