### ISSUE TITLE
"Arc Update Mode" breaks "ARC Loader" 24.4.19 -> 24.4.20

### ISSUE THREAD

**Issue by ctout76** [AuxXxilium/arc#1181]
**Describe the Bug**
"Arc Update Mode" breaks "ARC Loader" -> Tested from version 24.4.19 to 24.4.20

Error Message:
Update LKMs: Error downloading Updatefile

**Hardware**
Oracle VM Virtual Box

**Comment by AuxXxilium** [comment]
if you had joined discord you will see that you should use clean reinstall.
