### ISSUE TITLE
Migration Redpill Recovery to ARC

### ISSUE THREAD

**Issue by zorzibus** [AuxXxilium/arc#1203]
Hello,

Comming from RR Loader (version 23.11.8), I'm trying to migrate my DSM (ESXI VM) to ARC Loader (version 24.4.21).
DSM is up to date (version 7.2.1-69057 update 5) on DS3622xs
But after building the ARC loader, the DSM control panel doesn't want to open (still loading)
I know that I have to force reinstall DSM (thanks to grub menu) but the first time I boot with this menu, It propose me the recovery menu (not the migration).
And If I recover DSM (because I don't have any other option), next I can reach the reinstall menu but It fail (corrupt pat file)

Many thanks for your help and sorry for my english ;-)

ESXI 8.0U2 Server
ESXI VM version : 8.0U2
ARC Loader on : SATA 0:0
HDD on : SATA 0:1

ARC Loader options :
SataRemap
Addons : addincards, codecpatch, cpuinfo, hdddb, reboottoloader and setrootpw

**Comment by AuxXxilium** [comment]
read wiki workarounds
