### ISSUE TITLE
Sort SAS drives

### ISSUE THREAD

**Issue by nvgoldendog** [AuxXxilium/arc#1228]
I am running an Intel Storage Server S2600WTTF which has 24 bays in front and 2 bays in the back, so total of 26 bays. I also have an LSI SAS Controller megaraid which is in JBOD mode. I am using ARC Loader 24.4.21 and chassis type selected is RS4021xs+ since controller is not supported on DT type. When DSM loads and in the storage manager, it shows I have 13 disks, which is correct, but I only have 11 in the front (Hot swap back plane starts at 0 and Synology see's it as 1) and disk12 and 13 are really 25 & 26 to Synology or to RAID controller 24 & 25). Is there a way to map the drives out as they are SAS. I see lots of people asking about SATA but in this case it is SAS

These  are the Addon's I included. 
![image](https://github.com/AuxXxilium/arc/assets/41464533/1affabd4-8e85-495e-9779-db29d19f6b30)

From Storage controller, the last two are on ports 24 & 25.
![image](https://github.com/AuxXxilium/arc/assets/41464533/5dca61e9-efa9-4062-a4fc-175ff0a7c233)

**Additional Context**
Add any other Context or Screenshots about the Feature request here.

**Comment by AuxXxilium** [comment]
Use Sataport / DiskIdXMap to move drives if there are more than 1 controller.

if all disks are connected to the same controller, it depends on sorting by controller.

if you use a raid controller, why do you not use hardware raid mode?

**Comment by nvgoldendog** [comment]
Hi AuxXxilium.  Thanks so much for getting back to me so fast.

Can you instruct me on  where in the User Config file  (what section) do I add the command and is the command **sata_remap: 12>25:13>26** ? Also, If I have 26 pjhysical drive bays total is there a way to use the RS4021xs+ to support the extra drives?  Like here as an example: 
![image](https://github.com/AuxXxilium/arc/assets/41464533/23908ddb-64a2-4b5e-8e81-9ecc2f60885e)

My current config is as follows:

![image](https://github.com/AuxXxilium/arc/assets/41464533/b4e90c55-c7ec-4257-ba8e-92d24679bc18)

Also, I noticed today that when I went into the loader and updated it to 24.4.21 at the end of the update I see this error at the bottom of the page:

![image](https://github.com/AuxXxilium/arc/assets/41464533/17bd3ad7-369f-40dc-b790-cc508acd1794)

I also noticed the same thing with the last 3 prior builds. I did not see it with Arc 24.4.15

Just for sakes of sanity I made an entire new flash write image so I could start from scratch. I got the same error. Not sure what it affects just yet. 

Just now I selected from the loader Option S Change Storage Map. Screen goes blank and then shows for a brief seconf this message on the lower right part of the screen:

![image](https://github.com/AuxXxilium/arc/assets/41464533/71d64184-9c7d-49c2-9d34-4b2410bbaee4)

**Comment by AuxXxilium** [comment]
use latest build, .21 got a rebuild later

**Comment by nvgoldendog** [comment]
No, I was not aware that you can only have 8 drives. Why does the model say 24 drives then?

Can I setup the array in the controller and somehow be able to manage it in Xpenology with that addin for LSI controllers? Or what exactly does that Addin do?

**Comment by AuxXxilium** [comment]
8 per controller! not 8 in all!

it's the management utility for lsi

**Comment by mjpcomp** [comment]
@AuxXxilium - so you can create a RAID on the LSI card and use it within DSM? But it will just appear as a single "disk" to DSM, right?

**Comment by AuxXxilium** [comment]
create the drives in bios utility of lsi controller

**Comment by nvgoldendog** [comment]
How will I be able to manage the controller in DSM? I am setting up an active / passive SAN and will need some way to get alerts when a drive fails. I assume that the DSM is just going to see 1 drive of the total volume I make in the RAID bios, right or wrong?

**Comment by nvgoldendog** [comment]
How will I be able to manage the controller in DSM? I am setting up an active / passive SAN. Oh, the raid controller I have goes to a 36 port SAS expander, so it supports up to 36 drives. I think that is what you are getting confused on, right?

**Comment by AuxXxilium** [comment]
select SA6400 and try again, should be the best for your hardware

**Comment by nvgoldendog** [comment]
Thanks. I tried that and when it boots up the DSM it sits for a while then the server reboots. It warns me that it is not supported to use a HBA with the DT model, so it kind of makes sense

**Comment by AuxXxilium** [comment]
no on sa6400 it is possible, but it's the only one.

**Comment by nvgoldendog** [comment]
So why then when I use the SA6400 after the ARC loader loads up and launched DSM does it sit for a while and then just reboot?
I don't have that problem with any of the non DT builds.

**Comment by AuxXxilium** [comment]
without the mentioned parts that i need for bugreports i can't help here anymore.

**Comment by nvgoldendog** [comment]
Sorry, which parts would you like?

**Comment by AuxXxilium** [comment]
read mentioned informations for bugreports in arc github readme file. because you havn't selected the template for bugreports there is everything mentioned.
