### ISSUE TITLE
build for DS423+ problem with Quickconnect

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#1234]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
Build DS423+ - Quickconnect doesnt working: System is busy. Please try after 5 min. I tried many times but not result. When i change to DS920+ - Quickconnect is working normally
**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
system is busy indicates that background tasks are running and blocking this. sometimes a reboot fix this, sometimes you have to wait a day after installation.

sometimes there is an issue with dns server or syno server (many api issues the last months).
