### ISSUE TITLE
Update Arc breaks the whole system

### ISSUE THREAD

**Issue by fengyuan213** [AuxXxilium/arc#1253]
**Describe the Bug**
I just updated Arc from 24.4 to 24.4.23, it goes smoothly for the update, however when update finished, it seems to messup everything with encodings of configurations, which leads to unable to use the arc at all, even building a new loader
**Screenshots**
some Errors for running sysinfo
<img width="775" alt="image" src="https://github.com/AuxXxilium/arc/assets/26819159/5bcaa5ab-0b89-49c7-855b-24d5d662b753">
<img width="727" alt="image" src="https://github.com/AuxXxilium/arc/assets/26819159/a491dda7-af01-4786-b834-3e6eb5feadaf">
<img width="734" alt="image" src="https://github.com/AuxXxilium/arc/assets/26819159/3e412d96-e122-4045-abfd-f70278c99edd">

If i want to choose a new model to start a brand new configuration, it seems to be invaild configurations and does not work.
<img width="749" alt="image" src="https://github.com/AuxXxilium/arc/assets/26819159/dedef9cd-1b0a-416f-9c3a-27372fc06a97">
Here is a screen shot of "cat" in an example of invalid configuration file, did the encoding broken?
<img width="690" alt="image" src="https://github.com/AuxXxilium/arc/assets/26819159/a4e019f1-20f3-42f4-8080-2942db555d62">

**Hardware**
Hardware information is shown above. Please help

**Comment by AuxXxilium** [comment]
use update function inside arc if automatic update fails on your system.
