### ISSUE TITLE
FR: Add virtiofs.ko for epyc7002-7.2-5.10.55

### ISSUE THREAD

**Issue by comicchang** [AuxXxilium/arc#1255]
**Is your Feature request related to a Problem? Please describe.**
I would like to try out [virtio-fs](https://virtio-fs.gitlab.io/) on xpenology, but unfortunately, the virtio fs kernel module is not available in the [arc-modules repository](https://github.com/AuxXxilium/arc-modules). Could you please consider adding this module? Thank you.

**Additional Context**

**Comment by AuxXxilium** [comment]
will not work, tested multiple times.
