### ISSUE TITLE
CPU 800mhz

### ISSUE THREAD

**Issue by xdxxp6qp** [AuxXxilium/arc#1304]
Hello, a new platform has been built. On asus rog b760i gaming and i3 12100 and ds3622xs+, the processor frequency is now limited to 800 mhz. what can be done about this?![image](https://github.com/AuxXxilium/arc/assets/70141403/1b7ece44-3721-46b8-8266-8eede0cea944)

**Comment by AuxXxilium** [comment]
and again,about the 50th time, it's only the freq that cpu using at the time of boot, there it will be read out. has no effect on system performance. but dsm need to have enabled acpi settings in bios.

**Comment by xdxxp6qp** [comment]
я извеняюсь. но замедленее реально заметно. кратное увелечение по запуску виртуальных машин. отзывчевость интерфейса оставляет желать лучшего. и это после b75 xeon 1270v2.

**Comment by AuxXxilium** [comment]
read my message and do what i wrote!
