### ISSUE TITLE
Arc UpdateNotify Failed

### ISSUE THREAD

**Issue by naeemsufian** [AuxXxilium/arc#1332]
**Describe the Bug**
/bin/bash: 1: command not found
**Screenshots**
![Screenshot 2024-05-02 012627](https://github.com/AuxXxilium/arc/assets/136690353/e7bccdf8-ab73-43b6-85e9-94ae3c5ceb64)

**Hardware**
Hardware Informations : CPU Core i7 6700 / Board -HP Z240 Workstation/ Networkcontroller = e1000e / Storagecontroller= SCSI -sata / ...

Running on proxmox as vm with Q35 UEFI  Networkcontroller = e1000
![Screenshot 2024-05-02 013549](https://github.com/AuxXxilium/arc/assets/136690353/a5b3e415-07cf-4eb4-93bb-4b0614c1c95c)

![Screenshot 2024-05-02 013221](https://github.com/AuxXxilium/arc/assets/136690353/afc40210-0c93-4274-b311-db9a208e0cc2)

**Comment by AuxXxilium** [comment]
And what do you want to tell me? use latest version and it will work.

**Comment by naeemsufian** [comment]
Thanks for reply and your hardwork for synology user
its a fresh install using latest arc version arc-24.5.1 only UpdateNotify Failed.
there is only one task (UpdateNotify)

**Comment by naeemsufian** [comment]
Script Not working /usr/bin/updatenotify.sh
i change it to  
/bin/bash /usr/bin/updatenotify.sh
Now it works

**Comment by AuxXxilium** [comment]
script is working. but you need the new version, so you have to delete your old entry in tasks and reboot.

**Comment by naeemsufian** [comment]
> script is working. but you need the new version, so you have to delete your old entry in tasks and reboot.

![Screenshot 2024-05-02 131842](https://github.com/AuxXxilium/arc/assets/136690353/8a237625-3e81-4b5a-9360-a6c2fab097dd)
It works for me . like this

**Comment by AuxXxilium** [comment]
so you call bash to open a bash that opens a bash script. 🙈

it's working on all of my systems oob with 24.5.1 but i did a dsm reinstall on all my systems to remove old files from dsm system partition.

**Comment by naeemsufian** [comment]
> so you call bash to open a bash that opens a bash script. 🙈
> 
> it's working on all of my systems oob with 24.5.1 but i did a dsm reinstall on all my systems to remove old files from dsm system partition.

Yes you are right if i reinstall dsm it works

**Comment by AuxXxilium** [comment]
yes because some old files are in your system partition. 😉
