### ISSUE TITLE
ARC failed 23.04.03 / ARPL Failed  / only ARPL 1.03b is working 

### ISSUE THREAD

**Issue by nemesis122** [AuxXxilium/arc#134]
Hi Christian 
Please could you help in this case what is the here the Problem ?
Gen8 with E3 1230v2 8 Threads CPU same bio seetings as my other Gne8 8 with I3 Cpu 4 Threads both have the same bios settings!

Gen8 with 1230v2 Cpu all Information attached goes always failed with eudev has failed.
Gen8 with i3 CPU is working same Loader same bios settings.
The buiild was complete!
Log file attached 
![ARC Sysinfo](https://user-images.githubusercontent.com/12814981/230424105-784551fb-f077-45bd-a17c-9f0fb7af8ae8.png)
[ARC v23.04.03 Failed.txt](https://github.com/AuxXxilium/arc/files/11172026/ARC.v23.04.03.Failed.txt)
![systemgen8](https://user-images.githubusercontent.com/12814981/230424112-9d1b3a9b-eb66-4e04-bf90-93fa919123fd.png)

**Comment by AuxXxilium** [comment]
Disable HT and try again.

**Comment by nemesis122** [comment]
:-)
Hi Chrisitan do you mean Hypertreading ?? and the Gen8 Micorserver has  no uefi boot in my opinion or im wrong  maybe in ILO because in  Bios there is no option to boot uefi
is it possible that ARPL 1.03b has not eudev for matching the devices ?
I will try thank you

**Comment by nemesis122** [comment]
[ARC v23.04.03 Failed.txt](https://github.com/AuxXxilium/arc/files/11172184/ARC.v23.04.03.Failed.txt)

**Comment by nemesis122** [comment]
And Models with DT it is working

**Comment by nemesis122** [comment]
on Sataportmap 5 there is the  SSD maybe this is the problem?

**Comment by AuxXxilium** [comment]
Please scroll down in Arc - Sysinfo. i need the full information to tell you whats wrong.

and yes i mean hyperthreading. it can be the problem with boot. the log file tells me nothing why eudev failed.

**Comment by nemesis122** [comment]
![1](https://user-images.githubusercontent.com/12814981/230431071-ff22044d-b4b8-456c-80a1-8fab83b50d82.png)
![2](https://user-images.githubusercontent.com/12814981/230431073-ae2978aa-409f-4416-9f91-38b3bb96c132.png)

**Comment by AuxXxilium** [comment]
Delete SataRemap in userconfig and try again

**Comment by nemesis122** [comment]
with HT disabled it is working  3622 4021 etc sata Devices 
BUT the DT Device Tree Modells also all are working when HT is on as example 1520+  Do you know why?

**Comment by AuxXxilium** [comment]
because of a problem with this xeon series. don't know why, but i know it is there.

**Comment by nemesis122** [comment]
thank you for this great support :-) i wish you very nice Easter have a nice time my friend see ya

**Comment by nemesis122** [comment]
After reboot with HT disabled it has the same error anyway i go with DT devices :-)

**Comment by AuxXxilium** [comment]
Do you have deleted the sata remap in config?

**Comment by nemesis122** [comment]
i will create now a new usb and try again
![yep](https://user-images.githubusercontent.com/12814981/230439045-e262579b-bd22-453f-b51b-4cad1f77284a.png)

**Comment by nemesis122** [comment]
yep deletet

**Comment by AuxXxilium** [comment]
should be fixed in v23.04.08
