### ISSUE TITLE
Cannot install DSM through reinstall/recovery mode

### ISSUE THREAD

**Issue by rjsg42** [AuxXxilium/arc#1340]
**Describe the Bug**
After doing an update to 24.4.25, the Panel Control inside DSM does not work. After reading the wiki, I've tried to reinstall DSM throught the recovery/reinstall mode but it always says file corrupted not matter what version I tried. (I've tried 7.2.1 69057 and  7.2.1 69057 Update 5 pat files, also trying to get it from internet using the installer).

I've also tried doing reinstall keeping the config or not keeping the config without success (in this second case it says "cannot format"

I've just installed last ARC version (24.5.2) but the problems are still happening.

**Screenshots**

![image](https://github.com/AuxXxilium/arc/assets/9213109/a87a92f6-f14a-48fa-92e4-f3ccda94ce1f)
![image](https://github.com/AuxXxilium/arc/assets/9213109/59121063-1505-412d-b89f-933f7d8390e8)
![image](https://github.com/AuxXxilium/arc/assets/9213109/d93cb503-c54d-484b-acc2-1b52f8229037)

**Hardware**
HP Microserver Gen8 Running ESX 6.7

`May  2 10:50:55  install.cgi: install.c:571 Unknown param localinstallreq=false
May  2 10:50:55  install.cgi: install.c:571 Unknown param _dc=1714647056541
May  2 10:50:55  install.cgi: ninstaller.c:699 Dev: sda, DiskPath: /dev/sda, Partition version: 8
May  2 10:50:55  install.cgi: ninstaller.c:140 Mount partion /dev/md0 /tmpRoot
May  2 10:50:55  kernel: [  362.142117] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
May  2 10:50:55  kernel: [  362.168925] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
May  2 10:50:55  install.cgi: ninstaller.c:169 umount partition /tmpRoot
May  2 10:50:56  install.cgi: ninstaller.c:140 Mount partion /dev/md0 /tmpRoot
May  2 10:50:56  kernel: [  362.908606] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
May  2 10:50:56  kernel: [  362.920741] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
May  2 10:50:56  install.cgi: ninstaller.c:169 umount partition /tmpRoot
May  2 10:50:56  install.cgi: ninstaller.c:140 Mount partion /dev/md0 /tmpRoot
May  2 10:50:56  kernel: [  362.957541] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
May  2 10:50:56  kernel: [  362.970342] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
May  2 10:50:56  install.cgi: ninstaller.c:511 fail to get admin port from /tmpRoot/etc/synoinfo.conf... try another way
May  2 10:50:56  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:50:56  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:50:56  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:50:56  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:50:56  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:50:56  updater: updater.c:5977 Start of the updater...
May  2 10:50:56  updater: util/check_patch_support_hw_revision.cpp:63 This patch supports HW revision of this machine
May  2 10:50:56  updater: child exit normally with [0]
May  2 10:50:58  install.cgi: ninstaller.c:899 Executing /tmpRoot//.syno/patch/updater -a /tmpRoot [0]
May  2 10:50:58  install.cgi: ninstaller.c:911 Recover image has the same version as flash does; no need to recover
May  2 10:50:58  install.cgi: ninstaller.c:1307 SYSTEM_NORMAL, [Recoverable=0]
May  2 10:50:58  install.cgi: ninstaller.c:169 umount partition /tmpRoot
May  2 10:50:58  install.cgi: ninstaller.c:1222(FillUpgradeVolumeInfo): gszUpgradeVolDev = /dev/md0 
May  2 10:50:58  install.cgi: ninstaller.c:1223(FillUpgradeVolumeInfo): gszUpgradeVolMnt = /tmpData 
May  2 10:50:58  install.cgi: ninstaller.c:1331 gblSupportRaid: 1, gSysStatus: 1, gblCreateDataVol: 0, gblSystemRecoverable: 0
May  2 10:50:58  install.cgi: synoupgrade.c:785 system status = 1
May  2 10:50:58  install.cgi: ninstaller.c:140 Mount partion /dev/md0 /tmpData
May  2 10:50:58  kernel: [  365.005234] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
May  2 10:50:58  kernel: [  365.026857] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
May  2 10:50:58  install.cgi: ninstaller.c:1390 FreeSize = 607485952 bytes
May  2 10:51:00  getty[25313]: tcgetattr: Input/output error^M
May  2 10:51:07  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:07  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:07  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:07  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:07  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:10  getty[25502]: tcgetattr: Input/output error^M
May  2 10:51:12  inetd[6690]: telnet/tcp: bind: Address already in use
May  2 10:51:12  inetd[6845]: telnet/tcp: bind: Address already in use
May  2 10:51:14  inetd[7251]: telnet/tcp: bind: Address already in use
May  2 10:51:15  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:15  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:15  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:15  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:15  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:20  getty[25725]: tcgetattr: Input/output error^M
May  2 10:51:22  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:22  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:22  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:22  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:22  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:24  install.cgi: generic_hash.c:80 Generic hash: /tmpData//@autoupdate/DSM_DS3622xs%2B_69057.pat: eeba4a8c83895a96bff2648d04016fa651b23809fa5caaebfda6e3a086bc065f
May  2 10:51:24  install.cgi: Remove /tmpData/upd@te...cmd=[/bin/rm -rf /tmpData/upd@te > /dev/null 2>&1]
May  2 10:51:24  install.cgi: Create /tmpData/upd@te...cmd=[/bin/mkdir -p /tmpData/upd@te > /dev/null 2>&1]
May  2 10:51:24  install.cgi: ninstaller.c:1443 Extracting SynoArchive [/tmpData/upd@te.pat][/tmpData/upd@te]
May  2 10:51:24  install.cgi: lib/synoarchive.c:440 synoinstall: synoarchive: [/tmpData/upd@te.pat][OPEN] Type: System
May  2 10:51:24  install.cgi: lib/synoarchive.c:84 synoinstall: synoarchive: [/tmpData/upd@te.pat][INIT] [/tmpData/upd@te]
May  2 10:51:24  install.cgi: lib/synoarchive.c:92 synoinstall: synoarchive: [/tmpData/upd@te.pat][OPEN] Start
May  2 10:51:25  kernel: [  391.897700] perf interrupt took too long (2518 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
May  2 10:51:25  install.cgi: lib/synoarchive.c:102 synoinstall: synoarchive: [/tmpData/upd@te.pat][OPEN] End: [Success][3688618971][0.866s]
May  2 10:51:25  install.cgi: lib/synoarchive.c:286 synoinstall: synoarchive: [/tmpData/upd@te.pat][EXTRACT_ALL] Start
May  2 10:51:28  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:28  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:28  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:28  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:28  synodiskport: disk/disk_rule_junior.c:109 Failed to get target on Virtual SATA Hard Drive 00000001 69057.4
May  2 10:51:29  install.cgi: ardchive_write_data_block failed. [Write failed]
May  2 10:51:29  install.cgi: Unknown Error: [28]
May  2 10:51:29  install.cgi: copy_data failed. extract filename: [/tmpData/upd@te/hda1.tgz]
May  2 10:51:29  install.cgi: lib/synoarchive.c:299 synoinstall: synoarchive: [/tmpData/upd@te.pat][EXTRACT_ALL] End: [Fail][24][4.138s]
May  2 10:51:29  install.cgi: lib/synoarchive.c:314 Extract failed [/tmpData/upd@te.pat]
May  2 10:51:29  install.cgi: lib/synoarchive.c:229 synoinstall: synoarchive: [/tmpData/upd@te.pat][FREE]
May  2 10:51:29  install.cgi: ninstaller.c:1465 Failed to extract patch due to unknown format.
May  2 10:51:29  install.cgi: ninstaller.c:1493 Extraction failed [/tmpData/upd@te.pat][/tmpData/upd@te]
May  2 10:51:30  install.cgi: RemoveUpgradeFile: Remove /tmpData/upd@te.pat...
May  2 10:51:30  install.cgi: ninstaller.c:1588 set error code [-13]
May  2 10:51:30  inetd[9295]: telnet/tcp: bind: Address already in use
May  2 10:51:30  getty[26068]: tcgetattr: Input/output error^M
May  2 10:51:30  install.cgi: ninstaller.c:2059(ErrFHOSTDoUpgrade) err=[-1]
May  2 10:51:30  install.cgi: ninstaller.c:2063(ErrFHOSTDoUpgrade) retv=[-13]
May  2 10:51:30  install.cgi: install.c:496 Upgrade for migration by the download patch fail.
May  2 10:51:30  install.cgi: install.c:785 Upgrade by download patch fail.
Jan  1 00:00:00  install.cgi: ninstaller.c:169 umount partition /tmpData`

**Comment by AuxXxilium** [comment]
you can't install thru recovery mode. you need to boot to "DSM Reinstall Mode" - Do you have read the Release Informations for 24.5.1/2? Yes you have to reinstall to fix these panel and it is working. i use arc in about 20 different vm configs in esxi. no issues there.
