### ISSUE TITLE
Update arpl

### ISSUE THREAD

**Issue by ErRanCham** [AuxXxilium/arc#135]
In menu.sh. Update menu -> update arpl. The packages detected and upgraded are “arpl v1.1-beta2a”
Could you modified it to upgrade to your package in this repository?

Thank u!

<img width="640" alt="image" src="https://user-images.githubusercontent.com/130142000/230582431-eca306c7-3e57-4dfa-9ebe-2896de26e128.png">

**Comment by ErRanCham** [comment]
Please dont modify "update addons" menu.. I need it to fetch i915 driver. tks~

**Comment by AuxXxilium** [comment]
do not use menu.sh - use arc.sh
