### ISSUE TITLE
Request to add nvmesystem addon into other models

### ISSUE THREAD

**Issue by DanielLien1984** [AuxXxilium/arc#1383]
**Is your Feature request related to a Problem? Please describe.**
Seems like currently only SA6400 can use nvmesystem addon but I want to try to use NVMe disk as system disk on other models and I don't have any SATA/SCSI disk available. Please consider to add this addon/function into other models. Thanks!

**Additional Context**
![image](https://github.com/AuxXxilium/arc/assets/87376036/86c450ff-af9b-4a58-b90f-64b60b9de5ec)

**Comment by AuxXxilium** [comment]
not possible, because we need dsm linux kernel version 5.x and all other are on 4.x
