### ISSUE TITLE
Bootloader USB appears in DMS as a USB drive

### ISSUE THREAD

**Issue by ithakaa** [AuxXxilium/arc#142]
Is there any way to hide the USB bootloader from DSM ?

**Comment by ithakaa** [comment]
> yes, set user rights to noone

Can you explain what you mean please?

**Comment by AuxXxilium** [comment]
set in dsm shared folders permissions to noone.

**Comment by ithakaa** [comment]
Thanks but it only means the shares are not visible

The USB drive is still visibly mounted with the icon at the top right of the screen
