### ISSUE TITLE
DS423+ can't use Quickconnect: Quickconnect server is busy. Please try again after 5 minutes

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#1453]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
I tried many times with any hardware. This is issue of build. Please help.
**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![Screenshot 2024-05-10 235803](https://github.com/AuxXxilium/arc/assets/166336902/735cf6d4-e6e8-434a-8218-a2ef80370d7c)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
model DS423+, msi h110i, intel core i5-4440, ddr3 8gb

**Comment by AuxXxilium** [comment]
you have seen the comment: arc patch (if available).
