### ISSUE TITLE
Is it possible to install intel-microcode?

### ISSUE THREAD

**Issue by mndti** [AuxXxilium/arc#1496]
Hello,

First, thank you for the excellent work.

I would like to know if it is possible for you to add intel-microcode or if you could give me any tips/information on how to add it.

I'm using the SA6400 model, on the following hardware (Bare Metal):
CPU: Intel N5100 x86-x64.
RAM: 12GB DDR4
iGPU: Intel UHD Graphics
LAN: 4x, Intel i225-V, 2.5G
DISKS: nvme: 256GB / HDD: 1TB

The system is working perfectly, however I have problems with Synology Virtual Machine Manager (VMM). The guest restarts randomly.

Why intel-microcode? I did several tests on this mini-pc, both with proxmox as host and openwrt as host and it had the same behavior. I was only able to solve it by installing intel-microcode.

I apologize for the English.

**Comment by AuxXxilium** [comment]
no
