### ISSUE TITLE
ARC 1.1.4 beta

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/arc#15]
i tried to install arc 1.1.4 beta on a new sata disk, but on mine with all my disks working and also with the 32gb disk with DSM already installed and configured.
At the first start this message appears: after completion
![image](https://user-images.githubusercontent.com/31816231/205297738-3473d8e0-2897-49ff-8efb-91a45446d55c.png)

![image](https://user-images.githubusercontent.com/31816231/205298179-521e49c3-05dd-4117-948c-1181f36bfb70.png)

**Comment by AuxXxilium** [comment]
You should share more informations. Like Hardware and config view in loader (overview of "edit user config")

**Comment by wifi75** [comment]
Yes,
![image](https://user-images.githubusercontent.com/31816231/205302472-38bcb45f-904d-438f-a220-08fd281126e8.png)

ARPL now it works perfectly,
then from proxmox I change the boot disk and select sata 4 on which ARC 1.1.4 beta is installed.

**Comment by AuxXxilium** [comment]
Boot disk has to be at same place. and wich setup have you shown in "edit userconfig" in arc menu

**Comment by AuxXxilium** [comment]
Please try this: https://github.com/AuxXxilium/arc/releases/tag/v22.12.02-beta

**Comment by jeff25** [comment]
works as soon you delete Sata0 and map new disk as SATA0... can be closed.

**Comment by wifi75** [comment]
Hello, I tried to install ne arc 22.12.02
but there are same problem:
![image](https://user-images.githubusercontent.com/31816231/205622901-d98e0538-6f1b-4389-b67e-f4b6ae79ea1f.png)

**Comment by AuxXxilium** [comment]
Try the 22.12.04-dev or set your config to sata

**Comment by AuxXxilium** [comment]
And why do you have an scsi controller in this config and all storage mapped as sata? there is something wrong. 

i need a screenshot from arc - advanced settings - sysinfo/systeminfo. than i can tell you more.

**Comment by AuxXxilium** [comment]
I think your config is the problem. But i don't and won't use Proxmox at all. 

I have a Video in my Youtube channel with the right settings for the vm. you can look at this.

**Comment by wifi75** [comment]
vole solo dirti che utilizzo arl 1.0.16 senza nessun problema, sulla stessa vm.

**Comment by AuxXxilium** [comment]
btw you should remove the scsi controller and everything is ok.

**Comment by AuxXxilium** [comment]
all your disks mapped to the sata controller.

**Comment by wifi75** [comment]
hello, since the scsi controller cannot be eliminated, I tried to change the voice as in the picture:
![image](https://user-images.githubusercontent.com/31816231/205645982-7128ecaf-bd89-4401-ad0b-6f2440f7988b.png)
![image](https://user-images.githubusercontent.com/31816231/205646080-261308d1-61e2-47df-80b4-3405116200dc.png)

seems to be ok now, I'll do further tests..
