### ISSUE TITLE
Problem in Storage Manager using a SCSI data drive in a Proxmox VM

### ISSUE THREAD

**Issue by maiux** [AuxXxilium/arc#1545]
**Describe the Bug**
I made a Proxmox VM with SATA:0 imported from arc.img (latest / yesterday - 24.5.16) and a SCSI drive that I want to use as data drive, using DriveIdxMap (activeports or max ports, does not make difference). Once full installed, if I create a volume using Storage Manager (SCSI data disk is seen as SATA but in my ignorance it can be completely normal), I will see 2 storage pools and one of them has the new volume in it. If I remove the volume, Storage Manager remains in an inconsistent state with one storage pool without volumes and does not allow to create a new volume neither remove the storage pool.

**Screenshots**
![immagine](https://github.com/AuxXxilium/arc/assets/278691/0e3ed979-01d0-44ca-bb4d-71573cdbced3)
<img width="148" alt="immagine" src="https://github.com/AuxXxilium/arc/assets/278691/3601f19b-11d6-4f6a-a77e-22249944871b">
F5DZ9WRNB
![immagine](https://github.com/AuxXxilium/arc/assets/278691/65501255-5f3c-4f5b-aae2-4121da43caa2)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/bc82780e-7c82-44f9-adb9-8802fcaf3f75)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/13ade044-441e-41cf-bb0e-f401ac018c32)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/79e63847-6261-4acd-82ce-1f20be6ec34e)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/295b99ba-e959-493b-8e23-1f051b0bc27a)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/4c0bee0d-4f1c-4c07-8629-6b327ebfb415)
![immagine](https://github.com/AuxXxilium/arc/assets/278691/fafc78b1-8a62-4811-aab1-2132a1e0212c)

**Hardware**
<img width="1275" alt="immagine" src="https://github.com/AuxXxilium/arc/assets/278691/98789242-201e-495e-a342-4a0426db21cf">

Many thanks for your help

**Comment by AuxXxilium** [comment]
These Portmap Options are only for Sata Controller: https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Loader-Portmap

Why do you have 2 Sata Controller in VM Config? DSM will show your Disks as Sata, this is nothing to worry about.

I don't know why you get 2 Pools with 1 Disk.

**Comment by maiux** [comment]
Really don't know why. This sysinfo is with no SATA drives attached and arc.img boot from SCSI: C8FABUGLJ

**Comment by AuxXxilium** [comment]
Wrong code, but where is your problem? it lookes like, something went wrong with your dsm installation.

**Comment by maiux** [comment]
Found why: it's for the CD-ROM. Check this configuration: E8SFNLAG7 (maybe it does not come out), but in these screenshots yes:
<img width="857" alt="immagine" src="https://github.com/AuxXxilium/arc/assets/278691/6fd4b35f-e6e4-4628-bca0-4fc976d533a4">
<img width="857" alt="immagine" src="https://github.com/AuxXxilium/arc/assets/278691/385cec09-dba7-4044-be25-d75dda52914f">
<img width="857" alt="immagine" src="https://github.com/AuxXxilium/arc/assets/278691/fc9b0113-5959-4bd8-8b90-33f1d822ebbd">

**Comment by AuxXxilium** [comment]
where is your problem? i only see a healthy storagepool?!

**Comment by maiux** [comment]
> Wrong code, but where is your problem? it lookes like, something went wrong with your dsm installation.

I was trying to make an optimal configuration using SATA as boot loader and SCSI for data disk (because under VM is way much performant), and I got stuck with this twin "Storage Pool" problem. If I use SATA for data disk, I see only one storage pool and config is consistent. If I use SCSI as data disk, I got the two storage pool and if I delete it I get an inconsistent situation (I can't recreate it) - check the screenshots on the first post

**Comment by maiux** [comment]
> where is your problem? i only see a healthy storagepool?!

Check the last screenshot of the first post: healty but 0 bytes allocated - it's an inconsistent config

**Comment by AuxXxilium** [comment]
if you delete all storage pool, what will happen?

**Comment by maiux** [comment]
> if you delete all storage pool, what will happen?

you click on Remove and nothing happens

**Comment by AuxXxilium** [comment]
Reboot?

**Comment by maiux** [comment]
the same

**Comment by AuxXxilium** [comment]
boot to config mode, use format disks function in dev section.

**Comment by maiux** [comment]
If I can ask, for my knowledge: how SCSI drives are seen by DSM? How loader make them work under DSM?

**Comment by AuxXxilium** [comment]
They are seed as SATA since DSM can't use them oob. My ESXi SCSI Controllers are working and others don't have these issue with Proxtrash.

**Comment by maiux** [comment]
> They are seed as SATA since DSM can't use them oob. My ESXi SCSI Controllers are working and others don't have these issue with Proxtrash.

Oh, I see. Good luck.

**Comment by maiux** [comment]
BTW, I was only using the wrong loader: yours. With another loader works like a charm.

**Comment by AuxXxilium** [comment]
and which loader?

**Comment by maiux** [comment]
I bet you are smart enough to find it by yourself. Thank for your time.

**Comment by AuxXxilium** [comment]
i know 20 different, so tell me.

**Comment by r0bb10** [comment]
> **Describe the Bug** I made a Proxmox VM with SATA:0 imported from arc.img (latest / yesterday - 24.5.16) and a SCSI drive that I want to use as data drive, using DriveIdxMap (activeports or max ports, does not make difference). Once full installed, if I create a volume using Storage Manager (SCSI data disk is seen as SATA but in my ignorance it can be completely normal), I will see 2 storage pools and one of them has the new volume in it. If I remove the volume, Storage Manager remains in an inconsistent state with one storage pool without volumes and does not allow to create a new volume neither remove the storage pool.

mm works here, sata0 as arc.img and scsi0 as first disk, works on a DVA3221 build.. if i remove the storage pool 1 it unmounts the volume correctly and removes the pool, creation also works.


https://github.com/AuxXxilium/arc/assets/16479888/a9fd01f6-847f-4264-aff1-93c3831fb870
