### ISSUE TITLE
Upgraded Arc Loader - No reboot and no force-reinstall DSM option on grub

### ISSUE THREAD

**Issue by waazdakka** [AuxXxilium/arc#1588]
**Describe the Bug**
Hello,
I just upgraded my ARC Loader to the last version using the automatic updater, and the loader boot in loop in Arc Loader. 
I read in the Wiki I should force-reinstall DSM, but I don't have the option in grub.

I'm using Proxmox.

And I don't have the space to add manually all the URL of the PAT file from Synology Download center...

Thanks for your help!!

**Screenshots**
<img width="1195" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/3d527bb6-0a84-4504-98c7-a87d924c33be">
<img width="828" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/5e3783d8-fdc8-4a84-bf86-d9859f98e5f6">
<img width="882" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/455fb18d-64e3-4731-ab26-990ed6063db6">

**Hardware**
Proxmox

**Comment by AuxXxilium** [comment]
network issue on your side. can't do anything

**Comment by waazdakka** [comment]
I made ping from ARC and it worked. What would be the network issue ?

**Comment by AuxXxilium** [comment]
check your network. there is something that will block the connection! dns, adguard, firewall, ...

**Comment by waazdakka** [comment]
I checked all I could: I don't have anything on my network which could block the connexion.
Is it possible to host the pat on another server rather than on synology's server?

**Comment by AuxXxilium** [comment]
use offline mode

**Comment by Salamandar** [comment]
> network issue on your side. can't do anything

I can confirm the reported URL (http://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_DS3622XS%2B_69057.pat) returns 404 on multiple networks (home, work, GSM). It looks like it's not an issue on @waazdakka 's side.

**Comment by AuxXxilium** [comment]
yes syno download server is offline if this is true

**Comment by waazdakka** [comment]
Ok, I activated the offline mode, and uploaded from the web browser the pat file.
<img width="1558" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/e0449b00-21ee-4ce8-9455-12dec5a14fcf">

But I still get an error: 
<img width="207" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/22eef32e-eab1-4446-bd5b-60b062749659">

**Comment by waazdakka** [comment]
Yes I've uploaded the 7.2.1-69057 (With Update 1) file (global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_DS3622xs%2B_69057.pat)

**Comment by AuxXxilium** [comment]
than you did something wrong and not followed the instruction on screen

**Comment by waazdakka** [comment]
Hmmm OK il not sure of what I could have done wrong but now what should I do to recover it?

**Comment by waazdakka** [comment]
And so... Lost all the datas?

**Comment by AuxXxilium** [comment]
no? why you should? you should only start with loader from scratch, not format anything!

**Comment by waazdakka** [comment]
Oh. So I can start again from this screen, choose model and following the steps?
<img width="499" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/60316336-d117-4549-933a-0d03c78187f0">

**Comment by AuxXxilium** [comment]
so it's correct, start with choosing a model

**Comment by AuxXxilium** [comment]
looks like there are only 4 disks connected. can't help without screenshot or code from arc - sysinfo

**Comment by waazdakka** [comment]
I have 6 disks connected:

<img width="701" alt="Capture d’écran 2024-05-21 à 20 06 58" src="https://github.com/AuxXxilium/arc/assets/9380081/c1e24933-1245-4120-ad6f-9f3fca684d17">

<img width="414" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/cd746b26-1edc-49d8-8e6d-35bb46957122">

<img width="1350" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/957e0833-c7b4-4738-841c-ee87e6daad89">

(And just in case, I've updated to your last release and it seems to have a small issue when building the loader:
<img width="828" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/c414622f-f2c5-4271-b48a-da2f2e81dce9"> )

I tried all options but AHCI

**Comment by waazdakka** [comment]
Ok I found something:
<img width="503" alt="image" src="https://github.com/AuxXxilium/arc/assets/9380081/cad33ae5-e455-4fad-b9ae-12a9d5e139ba">
The second disk should be the 16.4 To and not the 1To... Strange behaviour

**Comment by AuxXxilium** [comment]
proxmox, look at my latest video for correct settings

**Comment by waazdakka** [comment]
Ok, I've tried several settings, with "Max ports" and change the type of SCSI controller to VMware PVSCSI I got back my drive (but not the correct type of NAS. I'll make some tests to see if I can obtain the right setting

Simple question, what about the 5th SataPortMap option, if I want to set up the SataPortMap by my self? I tried it but I don't see how to customize it before building the loader

(And so you know, since last release yesterday, you have an error during the building with an unexpected " ] " :) )

Thanks again for your support!

**Comment by AuxXxilium** [comment]
i was looking around for this issue and it is know and wanted by proxmox that we can't use more disks, there is a vm config workaround in web that will work. has nothing to do with arc, it proxmox and same issue with every linux os!

**Comment by AuxXxilium** [comment]
Ok, I've tried several settings, with "Max ports" and change the type of SCSI controller to VMware PVSCSI I got back my drive (but not the correct type of NAS. I'll make some tests to see if I can obtain the right setting

Portmap doesn't have any effect for other controller than sata controller!
