### ISSUE TITLE
Dell Precision T7600 Intel RAiD Controller C600

### ISSUE THREAD

**Issue by Angel038-2** [AuxXxilium/arc#1589]
Hi,

I run the latest release of ARC 24.5.20, i have a Dell Precision T7600 with a onboard RAID controller (Intel C600).
In ARC config i can see all my disks on the RAID controller but on DSM i only have the SATA SSD Drive i add to make flash cache.
I try to edit the SataportMap config but nothing change.
Actually i run:
SataPortMap = 11
DiskIdxMap = 0000

Could you help me?

**Comment by Angel038-2** [comment]
ok so it will be better to use a real RAID Card to use my disks?
Thank you for your reactivity

**Comment by AuxXxilium** [comment]
or use ahci with raid inside dsm

**Comment by Angel038-2** [comment]
AHCI is enable in BIOS, and i only can disable the raid controller.

**Comment by AuxXxilium** [comment]
disable intel raid in bios, set these ports to use AHCI and everything will work.

**Comment by Angel038-2** [comment]
i try

**Comment by Angel038-2** [comment]
i try and the disks still not appear in DSM, i will test with a real raid controller card.

**Comment by AuxXxilium** [comment]
don't use raid, use a hba. if you use a hardware raid or something like this, your disks need to be configured correct in controller, can't be controlled by system.
