### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by bolavefasfas** [AuxXxilium/arc#1595]
Not an issue 
just questions 
- what is arc patch ?
- why were people freking out does it consearn security ?
- will I be able to use synology active backup without arc patch if yes good if not how to use it without arc patch ?
---

on unriad as vm 
- I want to passthrough 1 additional disk 2 for arc complete disk to avoid .img formation of data stored in active backup 
the arc will be in primary disk in .img and the data in the passthough disk which I will sceduled keep a clone of if something goes wong will I be able to recover using that cloned data ?

**Comment by AuxXxilium** [comment]
arc patch is based on valid data for using syno services. but some guys thought they should sell the data that was open for everyone who use arc. so i thought about this situation and it encrypted the patch data, the other option was remove it completely.

the loader also work without arc patch. it's only for 1 feature, you will find more informations in wiki.

**Comment by bolavefasfas** [comment]
> * will I be able to use synology active backup without arc patch if yes good if not how to use it without arc patch ?

1. Will I be able to use synology active backup without arc patch if yes good if not how to use it without arc patch ?

2. And I want to use arc patch, its still there right ? Because without that active backup wont work.

**Comment by AuxXxilium** [comment]
> > * will I be able to use synology active backup without arc patch if yes good if not how to use it without arc patch ?
> 
> 1. Will I be able to use synology active backup without arc patch ?
>    if the answer is know how to use/enable arch patch as you removed it?
> 2. And I want to use arc patch, its still there right ? Because without that active backup wont work.
> 3. you can tell me about passthough disk on proxmos, as on unriad process might be similar I will connect dots.
> 
> I am not concerned about loader ik it works without arc patch though I need arch patch for active backup which needs serial number which is fixed by arc patch.

1. yes but you need to activate it manually - https://auxxxilium.github.io/arc/activation.html

2. yes it is, read wiki

3. i don't use these "trash" hypervisor. sorry

**Comment by bolavefasfas** [comment]
> > > * will I be able to use synology active backup without arc patch if yes good if not how to use it without arc patch ?
> > 
> > 
> > 
> > 1. Will I be able to use synology active backup without arc patch ?
> >    if the answer is know how to use/enable arch patch as you removed it?
> > 2. And I want to use arc patch, its still there right ? Because without that active backup wont work.
> > 3. you can tell me about passthough disk on proxmos, as on unriad process might be similar I will connect dots.
> > 
> > I am not concerned about loader ik it works without arc patch though I need arch patch for active backup which needs serial number which is fixed by arc patch.
> 
> 1. yes but you need to activate it manually - https://auxxxilium.github.io/arc/activation.html
> 2. yes it is, read wiki
> 3. i don't use these "trash" hypervisor. sorry

What hypervisor do you recomend ?
