### ISSUE TITLE
custom oCa

### ISSUE THREAD

**Issue by ocaflash** [AuxXxilium/arc#1615]
{"model":"DS920+","version":"7.2","addons":["addincards","amepatch","bootwait","codecpatch","cpuinfo","dbgutils","deduplication","dsmconfigbackup","expands","hdddb","i915","lsiutil","multismb3","nvmevolume","photosfacepatch","powersched","reboottoloader","sanmanager-repair","sorfnetif","storagepanel","surveillancepatch"],"macsys":"hardware","customkernel":"official","format":"img"}

**Comment by AuxXxilium** [comment]
`Activate Addons (Select only needed Addons!!!):` i don't know why noone can read.
