### ISSUE TITLE
Incorrect setup of resolv.conf via static IP setting

### ISSUE THREAD

**Issue by Ubsefor** [AuxXxilium/arc#1632]
**Describe the Bug**
`/etc/resolv.conf` resets itself after network interface is brought online, so resolving dns is not possible.

I suggest changing `/etc/resolv.conf.head` or `/etc/resolv.conf.tail` to address this issue:
init.sh -> set defined static IP to netdev -> set gw for netdev -> append `/etc/resolv.conf.head` or `/etc/resolv.conf.tail` with nameserver x.x.x.x -> make netdev online -> restart dhcpd -> wait for ip, check online services API accessibility and such...
This should allow correct dns resolution before bringing up arc menu.

**Screenshots**
Does not matter

**Hardware**
Does not matter

**Comment by Ubsefor** [comment]
Apparently, my suggestion has not lead to fixing this, sorry :/
I suggest doing the next thing (as it is defined in [raspberry pi images](https://forums.raspberrypi.com/viewtopic.php?t=140252)):
Append `/etc/dhcpcd.conf` with interface name, followed by static ip configuration, like
```
interface ${ETH}
static ip_address=${IP}/${NETMASK}
static routers=${GATEWAY}
static domain_name_servers=${NAMESERVER}
```

After that restart S41dhcpcd, it should generate a correct `/etc/resolv.conf` (which is actually a symlink to `/tmp/resolv.conf`)

Another simpler solution may be making `/etc/resolv.conf` immutable by `chattr +i /etc/resolv.conf` after changing it.

**Comment by AuxXxilium** [comment]
the solution i added, is working in my systems without any issue.
