### ISSUE TITLE
Feature Request: Automatic Arc Update and Configuration Backup on Reboot/Shutdown

### ISSUE THREAD

**Issue by bolavefasfas** [AuxXxilium/arc#1641]
- Request for an automatic update feature for Arc to the latest version upon system reboot or shutdown, with subsequent automatic restart.

- How to set backup of the configraton if something breaks after auto update I should be able to roll back easily.

**Comment by AuxXxilium** [comment]
setup a dsm task with "loader-reboot.sh update"

**Comment by bolavefasfas** [comment]
> setup a dsm task with "loader-reboot.sh update"

Thanks for letting me know its possible 

I mean to ask what code to fill in loader-reboot.sh ?

**Comment by AuxXxilium** [comment]
you don't need any code, just build a task or use ssh with this command (inside dsm) and it will work.

**Comment by bolavefasfas** [comment]
Thanks for replying now I understand
