### ISSUE TITLE
DSM Extraction failed

### ISSUE THREAD

**Issue by DanielLien1984** [AuxXxilium/arc#1650]
**Describe the Bug**
I loaded latest version image (24.5.24) into virtual machine and boot up, then config it from scratch. When it comes to download pat, looks like it doesn't download it and failed after a while. So I changed it to offline mode and manually upload the image into /tmp/upload folder but it still failed immediately. 
![image](https://github.com/AuxXxilium/arc/assets/87376036/8bb9590b-d1fb-4c99-a6cc-e6ad552e0b00)

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![image](https://github.com/AuxXxilium/arc/assets/87376036/2090b008-6a72-4654-8215-5d4b993f2ca3)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
It's PVE environment and it worked in previous version of ARC.

**Comment by DanielLien1984** [comment]
Update: I rollback to version 24.5.22 and it worked immediately. Looks like code bug in latest version.

**Comment by AuxXxilium** [comment]
> Update: I rollback to version 24.5.22 and it worked immediately. Looks like code bug in latest version.

the fun of your report is, there is nothing changed in this function between .22 and .24 - i think it was a connection issue in your vm.
