### ISSUE TITLE
Hi auxXxilium men this Bild have  bug  dont puss the models to install say certifica-te espired "in the command line " cam you make , new One .on the moment i dont have screenshot to send you but tomorro i wild send you . By and good night 

### ISSUE THREAD

**Issue by natasrcpt** [AuxXxilium/arc#1705]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by natasrcpt** [comment]
![IMG_20240530_112819](https://github.com/AuxXxilium/arc/assets/80817415/67f2df75-6433-4d08-9e8d-d92ed29295f8)
![IMG_20240530_112826](https://github.com/AuxXxilium/arc/assets/80817415/d2c715a4-e061-409f-86f2-3ee58a721d51)
![IMG_20240530_112743](https://github.com/AuxXxilium/arc/assets/80817415/b0a6dbc3-3be4-4321-b408-d51130fe5977)
error

**Comment by AuxXxilium** [comment]
check your bios time

**Comment by natasrcpt** [comment]
You're right, it was my mistake, sorry, now it's working
