### ISSUE TITLE
Interface Issues Across Models: Icon Display Failure, Sluggish Search, and Unresponsive Settings in Package Center

### ISSUE THREAD

**Issue by bolavefasfas** [AuxXxilium/arc#1762]
**Describe the Bug**
Icons and pic are not showing up in package centre.
Search is very slow or non functional.
settings is non responsive or wont open.

Tried fresh install for 3 diffrent model still wont work.

![image](https://github.com/AuxXxilium/arc/assets/82230241/c9ac8e89-e7fc-4b9a-a4b1-dd83fa587c55)
![image](https://github.com/AuxXxilium/arc/assets/82230241/809a839a-3637-4852-a621-419e763f987d)
![image](https://github.com/AuxXxilium/arc/assets/82230241/60c64be5-bd23-4afe-bbbd-b58c10d76866)
![image](https://github.com/AuxXxilium/arc/assets/82230241/801e5f3e-5c04-4267-8555-89434ec2a598)
![image](https://github.com/AuxXxilium/arc/assets/82230241/b6029957-bdf5-4299-afaf-51bed627f95d)
![image](https://github.com/AuxXxilium/arc/assets/82230241/f67747bf-63b1-4a12-90a3-96cebe6db8b3)
Settings not opening 

after multiple tries got this 
"
![image](https://github.com/AuxXxilium/arc/assets/82230241/4f46fc94-e259-437d-8971-cc948cee6322)
"
**Hardware**
Running it in a vm 
Gigabyte Technology Co., Ltd. H510M H
i5-11400
Running the arc.ing on nvme and disk on hdd exos tried both on same nvme still same issue 

This was tnot the case earlier 4 verisons ago 
now that I have updated it started
I have the vm up and running if you want to test anything on it.

**Comment by AuxXxilium** [comment]
issue on syno servers not from loader, also happens with original device since some weeks.
