### ISSUE TITLE
Bug External USB HDDs Recognized as Internal HDD

### ISSUE THREAD

**Issue by naeemsufian** [AuxXxilium/arc#1784]
**Describe the Bug**
usb external hard disk mount. synology consider it as internel hard disk instead of external. arc-24.5.12 works fine.  But other arc any updated version not working with external hdds... any suggestion?

**Hardware**
HP240 Workstation : Proxmox VM

**Comment by AuxXxilium** [comment]
> **Describe the Bug**
> 
> usb external hard disk mount. synology consider it as internel hard disk instead of external. arc-24.5.12 works fine.  But other arc any updated version not working with external hdds... any suggestion?
> 
> 
> 
> **Hardware**
> 
> HP240 Workstation : Proxmox VM
> 
> 

read wiki please

**Comment by naeemsufian** [comment]
> external usb hard disk mount Problem Synology consider it as internel hard disk instead of external arc-24.5.12 works fine. But other arc any updated version not working with external hdds.
> 
> **Hardware** HP240 Workstation : Proxmox (synology DS918+ as VM) HP800G2 Virtual box ![Screenshot 2024-06-04 113953](https://private-user-images.githubusercontent.com/136690353/336337187-867be61b-3416-4904-9cfd-704d42bc01ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQ1NTcsIm5iZiI6MTcxNzQ4NDI1NywicGF0aCI6Ii8xMzY2OTAzNTMvMzM2MzM3MTg3LTg2N2JlNjFiLTM0MTYtNDkwNC05Y2ZkLTcwNGQ0MmJjMDFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNjU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmU1N2IwZThmNzM4MzE1YmQxYjk2YmQxNDRiOTExMWI3NjA5MTliODMwNjgwNDMzNzkxYzViNjRjYzBhZjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fP0_kdyeXFRfLALrrt2wbh1tOkICYsBV6kHzoTu42No) ![Screenshot 2024-06-04 113117](https://private-user-images.githubusercontent.com/136690353/336337223-734196f1-831e-4d41-b46e-2caa643e895a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQ1NTcsIm5iZiI6MTcxNzQ4NDI1NywicGF0aCI6Ii8xMzY2OTAzNTMvMzM2MzM3MjIzLTczNDE5NmYxLTgzMWUtNGQ0MS1iNDZlLTJjYWE2NDNlODk1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNjU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmQ2YjExMTllNGZhZWNlODgyZjUyNjJjODY3NmZjMGNjNTExMWM1OTcyZDY2MmViM2ZhOGZkMDQ3YmRmYWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qki8__5_fIR8q77LzqrFFk-ka_6g74GpKJvNLugaLMs)
