### ISSUE TITLE
can’t establish a connection to the server at SERVER:7304.

### ISSUE THREAD

**Issue by benisai** [AuxXxilium/arc#1825]
**Describe the Bug**

Unable to connect
Firefox can’t establish a connection to the server at 10.0.0.219:7304.

**Screenshots**
<img width="1465" alt="image" src="https://github.com/AuxXxilium/arc/assets/59147467/2b48a930-0e6b-40dc-a181-4cb1851b105c">

**Hardware**
ugreen 2 bay

**Comment by benisai** [comment]
![image](https://github.com/AuxXxilium/arc/assets/59147467/26d00f88-cf89-449c-954e-b0f1fbb73e8c)

**Comment by AuxXxilium** [comment]
webfileserver makes some trouble, but we don't need it.
