### ISSUE TITLE
Intel® Dual-Core Celeron® J1800 SoC (2,41 ГГц): Your cpu does not have AES support for hardwareebcrypt in DSM

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#1851]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
Intel® Dual-Core Celeron® J1800 SoC (2,41 ГГц): Your cpu does not have AES support for hardwareebcrypt in DSM. Please help to fix!
**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![IMG_20240608_164547](https://github.com/AuxXxilium/arc/assets/166336902/873892bc-56e4-4ee5-8a95-f65363300d6e)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
it‘s only a warning to not use hardware encryption, nothing else.

**Comment by AuxXxilium** [comment]
https://www.intel.de/content/www/de/de/products/sku/78866/intel-celeron-processor-j1800-1m-cache-up-to-2-58-ghz/specifications.html

your cpu doesn’t have aes support, so the message is correct
