### ISSUE TITLE
DSM bootet nicht

### ISSUE THREAD

**Issue by RJSUTH** [AuxXxilium/arc#186]
Hallo
Ich nutze ARC auf ESXI als VM. Seit Version 23.4.3 boote DSM nicht mehr.
Der Cursor in ARC blinkt weiter.

![image](https://user-images.githubusercontent.com/122780513/235368630-1c039a09-75ef-4a03-80c9-cef512932e37.png)

**Comment by AuxXxilium** [comment]
Dann nutze mal einen anderen USB Stick.

**Comment by RJSUTH** [comment]
Ich nutze keine USB Stick, sondern virtuelle HDs in VMWARE ESXi. Bis V23.4.2 hat es problemlos funktioniert

![image](https://user-images.githubusercontent.com/122780513/235370056-a84626c7-3e72-4a5b-8e2d-81ca96203d7b.png)

**Comment by AuxXxilium** [comment]
Ich teste jede Version selbst in VM und habe keine Fehler. Einmal als nonDT und einmal als DT. Beide laufen ohne Probleme.

**Comment by jeff25** [comment]
Bei mir bootet es auch nicht mehr.  ich habe es nur wegbekommen als ich auf "Autoboot " gestellt hatte. Verhalten unter Proxmox

**Comment by jeff25** [comment]
Sorry "Direct boot" auf Yes hat es dann wieder zum laufen gebracht

![image](https://user-images.githubusercontent.com/4502963/235371144-255070db-3eb8-41c1-a552-89eefdc5d92e.png)

**Comment by AuxXxilium** [comment]
Ok habe eine Idee warum aber verstehe nichts dass es eine VM nicht schafft.

**Comment by RJSUTH** [comment]
Ich habe die alte VMDK gelöscht und durch die aktuelle ersetzt. Jetzt bootet DSM wieder. Ich habe außer den ARC Updates nichts an der VM geändert. Scheinbar hat das Update nicht richtig funktioniert?

**Comment by jeff25** [comment]
habe nuna uch gelöscht und neu installiert dann ging es auch ohne Direct boot. Das update scheint wohl nicht zu funktionieren  von  23.4.3

**Comment by AuxXxilium** [comment]
Ja weil Änderungen am Grundsystem vorgenommen wurden.

Austausch des Image oder Erstellung eines neuen Stick sind eh empfohlen.

**Comment by RJSUTH** [comment]
Es kann aber kein großes Problem sein, da ja mit "Direct Boot: True" DSM ja bootetß

Ein neu erstellen des USB Sticks erfordert ja größere Änderungen, da DSM selbst ja auch angepasst werden muss und mein Raid5 dann neu geprüft wird, was 2 Tage dauert.

Wäre schön wenn das gefixt werden könnte

**Comment by AuxXxilium** [comment]
Ich kann da nichts fixen, weil die Sperre drin ist, wenn der USB Stick zu langsam ist oder nicht USB 3.0 und der Port auch nicht. Wenn ich die Sperre raus nehme, schlägt die Installation bei ca. 65% fehl.

**Comment by AuxXxilium** [comment]
Bzw. USB Stick erstellen ist eh der einzige Weg weil die Basis ein Update bekommen hat!

**Comment by RJSUTH** [comment]
ok, danke für die Info

**Comment by AuxXxilium** [comment]
Und zur Info: SHR, Raid5 und Raid6 sind der letzte Schrott. Sorry wenn ich das so direkt sagen muss. Sie täuschen eine Datensicherheit vor (Welche im Extremfall nicht existiert) und verlangsamen das System bis zum Umfallen.

**Comment by RJSUTH** [comment]
was wäre dann die richtige Lösung?

**Comment by AuxXxilium** [comment]
Aus IT'ler Sicht ein richtiger Raid - 1 (ab 2 Platten) oder 10 (ab 4 Platten).
