### ISSUE TITLE
H/W transcoding in VideoStation is not working with CPU>=Gen11 on SA6400

### ISSUE THREAD

**Issue by alekc70** [AuxXxilium/arc#1870]
**Describe the Bug**
H/W transcoding in VideoStation is not working with CPU>=Gen11 on SA6400

But i915 driver seems to me work well.
Log:
sh-4.4# lsmod | grep i915
i915 2650112 0
i2c_algo_bit 16384 1 i915
drm_buddy 20480 1 i915
intel_gtt 20480 1 i915
drm_display_helper 110592 1 i915
drm_kms_helper 98304 2 drm_display_helper,i915
ttm 53248 1 i915
drm 393216 6 drm_kms_helper,drm_display_helper,drm_buddy,i915 ,ttm
drm_mipi_dsi 20480 2 i915,drm
i915_compat 24576 3 drm_display_helper,i915,drm
dmabuf 61440 8 drm_kms_helper,drm_mipi_dsi,drm_display_helper,d rm_buddy,i915,ttm,i915_compat,drm
sh-4.4# dmesg | grep i915
[ 26.974349] i915 0000:00:02.0: [drm] Transparent Hugepage support is recommen ded for optimal performance on this platform!
[ 26.987080] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem ,decodes=none:owns=io+mem
[ 26.997823] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adls_ dmc_ver2_01.bin (v2.1)
[ 27.028260] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin ve rsion 70.20.0
[ 27.037366] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin versi on 7.9.3
[ 27.048420] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workload s
[ 27.056671] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[ 27.063385] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[ 27.077236] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[ 27.092448] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[ 27.100417] i915 display info: display version: 12
[ 27.105678] i915 display info: cursor_needs_physical: no
[ 27.111515] i915 display info: has_cdclk_crawl: no
[ 27.116785] i915 display info: has_cdclk_squash: no
[ 27.122142] i915 display info: has_ddi: yes
[ 27.126739] i915 display info: has_dp_mst: yes
[ 27.131632] i915 display info: has_dsb: yes
[ 27.136227] i915 display info: has_fpga_dbg: yes
[ 27.141294] i915 display info: has_gmch: no
[ 27.145897] i915 display info: has_hotplug: yes
[ 27.150890] i915 display info: has_hti: yes
[ 27.155493] i915 display info: has_ipc: yes
[ 27.160081] i915 display info: has_overlay: no
[ 27.164952] i915 display info: has_psr: yes
[ 27.169535] i915 display info: has_psr_hw_tracking: no
[ 27.175177] i915 display info: overlay_needs_physical: no
[ 27.181102] i915 display info: supports_tv: no
[ 27.185989] i915 display info: has_hdcp: yes
[ 27.198963] i915 display info: has_dmc: yes
[ 27.203570] i915 display info: has_dsc: yes
sh-4.4# ls /dev/dri/
by-path card0 renderD128

**Screenshots**
56TV5YSYR
![photo1717942713](https://github.com/AuxXxilium/arc/assets/172167411/b694499b-70c6-4540-b382-beee45d9a5ba)
![photo1717942718](https://github.com/AuxXxilium/arc/assets/172167411/254b3aac-7e13-4659-b45a-42e5bdb012aa)

**Hardware**
CPU: i5-12400
DMI H610M-HDV/M.2
model: SA6400
version: 7.2(69057u5)

**Comment by AuxXxilium** [comment]
1. set correct cmdline option for your system
2. check bios settings

**Comment by alekc70** [comment]
@AuxXxilium Christian thanks for fast answer.
1. What is correct cmd line?
2. What bios settings to be checked?
3. Ok I'll do it but seems to it will not help 
4. AME is working  from the box without patching (in photos face recognition is working as well)

**Comment by AuxXxilium** [comment]
> @AuxXxilium Christian thanks for fast answer.
> 
> 1. What is correct cmd line?
> 2. What bios settings to be checked?
> 3. Ok I'll do it but seems to it will not help
> 4. AME is working  from the box without patching (in photos face recognition is working as well)

read wiki, there are all informations you need.

**Comment by alekc70** [comment]
So I've updated arc loader to latest one and I've tried addition cmd "i915.enable_guc=2" line but it wasn't help.
Please give me a hint

![photo1717946312](https://github.com/AuxXxilium/arc/assets/172167411/1692905a-73b0-44f9-b05f-3937f00edef0)
![photo1717946320](https://github.com/AuxXxilium/arc/assets/172167411/ca77bb42-2023-41cc-8ae0-81b3a65a9bd1)
![photo1717946345](https://github.com/AuxXxilium/arc/assets/172167411/b238b942-35eb-4919-a3f4-7eb692fb6cce)
![image](https://github.com/AuxXxilium/arc/assets/172167411/50842020-95b4-430b-bf41-4178f32a220b)

**Comment by AuxXxilium** [comment]
you havn't done what i wrote, so conversation end!
