### ISSUE TITLE
DS3617xs Serial looks invalid

### ISSUE THREAD

**Issue by mahmoudhamadeh** [AuxXxilium/arc#1890]
**Describe the Bug**
I am upgrading from ARC version 24.5.12 to version 24.6.9 using the actual serial number (SN) and MAC address combination for my Synology DS3617xs device.

While setting up the loader with ARC 24.5.12, I selected the correct model as usual. However, when I entered the actual serial number, I received an error message stating "Serial looks invalid" Despite this, the setup provided an option to continue.

Everything else is functioning correctly. I was able to boot the loader and connect to my Synology account as usual. I just want to report the error message regarding the invalid serial number.

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/26927138/db39536a-b342-4119-a073-725aadb594f2)
![image](https://github.com/AuxXxilium/arc/assets/26927138/f95b728c-949c-4c59-9350-73e015c6abce)

**Hardware**
VM on Proxmox 4 cores i5-12600H
PCI Passthrough 3x NVME
10gbe Virtio nic

**Comment by AuxXxilium** [comment]
It looks invalid because syno has rewritten the serial table in their systems. if it is working, leave it as it is. it's only a warning.
