### ISSUE TITLE
custom syno

### ISSUE THREAD

**Issue by Magdiver** [AuxXxilium/arc#1897]
{"model":"DS3622xs+","version":"7.2","addons":["acpid","addincards","amepatch","bootwait","codecpatch","cpuinfo","dbgutils","deduplication","dsmconfigbackup","expands","hdddb","lsiutil","multismb3","nvmecache","nvmevolume","photosfacepatch","powersched","reboottoloader","sanmanager-repair","sorfnetif","storagepanel","surveillancepatch"],"macsys":"custom","customkernel":"official","format":"dyn"}

**Comment by AuxXxilium** [comment]
The next who can't read! 🤦‍♂️ Please read the text before you do anything!
