### ISSUE TITLE
custom 2024-06-11

### ISSUE THREAD

**Issue by incognosman** [AuxXxilium/arc#1899]
{"model":"DS920+","version":"7.2","addons":["acpid","addincards","amepatch","bootwait","codecpatch","cpuinfo","dbgutils","deduplication","dsmconfigbackup","expands","hdddb","i915","lsiutil","multismb3","nvmecache","nvmevolume","photosfacepatch","powersched","reboottoloader","sanmanager-repair","sorfnetif","storagepanel","surveillancepatch"],"macsys":"custom","customkernel":"official","format":"img"}

**Comment by AuxXxilium** [comment]
The next who can't read! 🤦‍♂️ Please read the text before you do anything!
