### ISSUE TITLE
Infinite loop under "Select model"  serials.yml and platform.yml not found

### ISSUE THREAD

**Issue by TheLinuxGuy** [AuxXxilium/arc#1907]
**Describe the Bug**
Upgraded to 24.6.11 via "full upgrade" on the loader, was previously running 24.6.10.

**Screenshots**
Sysinfo upload code BYJY6XTLS

Screen recording of this bug...
![Screen Recording 2024-06-11 at 10 40 52 PM (1)](https://github.com/AuxXxilium/arc/assets/713411/593cb18d-2d3e-41eb-b3dc-d835dbd023d0)

**Hardware**
Proxmox VM with two SCSI disks.

**Comment by AuxXxilium** [comment]
i wrote a notice in release. so do this!
