### ISSUE TITLE
recover the backup in .img file ?

### ISSUE THREAD

**Issue by Odroid13** [AuxXxilium/arc#197]
Thank you for your work,

Would it be possible to add an option to directly recover the loader file in .img format because it is much easier for the backup.

Thanks

**Comment by AuxXxilium** [comment]
not possibleAm 05.05.2023 um 09:04 schrieb Odroid13 ***@***.***>:﻿
Thank you for your work,
Would it be possible to add an option to directly recover the loader file in .img format because it is much easier for the backup.
Thanks

**Comment by wjz304** [comment]
you can used dd 

backup:
```
# backup disk.img.gz,
dd if=`blkid | grep 'LABEL="ARPL3"' | cut -d3 -f1` | gzip > backup.img.gz
# output  or upload transfer.sh 
curl -skL --insecure -w '\n' --upload-file backup.img.gz https://transfer.sh
```

recover:
```shell
# download backup 
curl -kL -o /tmp/backup.img.gz https://https://transfer.sh
# uninstalling the mounted bootloader disk
umount /mnt/p1 /mnt/p2 /mnt/p3
# decompress and write to the bootloader disk
gzip -dc backup.img.gz | dd of=`blkid | grep 'LABEL="ARPL3"' | cut -d3 -f1` bs=1M conv=fsync
```

**Comment by AuxXxilium** [comment]
> you can used dd
> 
> backup:
> 
> ```
> # backup disk.img.gz,
> dd if=`blkid | grep 'LABEL="ARPL3"' | cut -d3 -f1` | gzip > backup.img.gz
> # output  or upload transfer.sh 
> curl -skL --insecure -w '\n' --upload-file backup.img.gz https://transfer.sh
> ```
> 
> recover:
> 
> ```shell
> # download backup 
> curl -kL -o /tmp/backup.img.gz https://https://transfer.sh
> # uninstalling the mounted bootloader disk
> umount /mnt/p1 /mnt/p2 /mnt/p3
> # decompress and write to the bootloader disk
> gzip -dc /tmp/backup.img.gz | dd of=`blkid | grep 'LABEL="ARPL3"' | cut -d3 -f1` bs=1M conv=fsync
> ```

thanks, but are you sure that we should change images in a running system?

**Comment by wjz304** [comment]
The system is running in RAM, as long as the bootloader disk is umount, this operation is not a problem,
But if this is done, it should be restarted after dd is completed.

I sometimes do this to test the old version

**Comment by Odroid13** [comment]
> The system is running in RAM, as long as the bootloader disk is umount, this operation is not a problem, But if this is done, it should be restarted after dd is completed.
> 
> I sometimes do this to test the old version

Thank you for your feedback, however I really wanted to create an image file mainly of the loader and not the complete distribution?

arc loader.img 1Go
Classic Loader 160MB

**Comment by AuxXxilium** [comment]
it's possible, yes. but sometimes we need to change more than only the loader files, so we have to backup and restore the full partitions, if not the loader will not work.

**Comment by wjz304** [comment]
> > The system is running in RAM, as long as the bootloader disk is umount, this operation is not a problem, But if this is done, it should be restarted after dd is completed.
> > I sometimes do this to test the old version
> 
> Thank you for your feedback, however I really wanted to create an image file mainly of the loader and not the complete distribution?
> 
> arc loader.img 1Go Classic Loader 160MB

https://github.com/AuxXxilium/arc/issues/197#issuecomment-1536511241
the "backup":
The output img. gz is equivalent to a complete snapshot of the system when you execute the command

**Comment by Odroid13** [comment]
> > > The system is running in RAM, as long as the bootloader disk is umount, this operation is not a problem, But if this is done, it should be restarted after dd is completed.
> > > I sometimes do this to test the old version
> > 
> > 
> > Thank you for your feedback, however I really wanted to create an image file mainly of the loader and not the complete distribution?
> > arc loader.img 1Go Classic Loader 160MB
> 
> [#197 (comment)](https://github.com/AuxXxilium/arc/issues/197#issuecomment-1536511241) the "backup": The output img. gz is equivalent to a complete snapshot of the system when you execute the command

Thanks

**Comment by AuxXxilium** [comment]
@wjz304 thanks for your work, looks like we can use this.

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/236948442-db5279e1-f968-4783-a7bb-d52f63c0596d.png)
不太行啊，zip 比gz 还大，而且不能流式打包....
