### ISSUE TITLE
Error On Launch Initramf unpacking failed: X2-compressed data is corrupt

### ISSUE THREAD

**Issue by fengyuan213** [AuxXxilium/arc#1977]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function![image](https://github.com/AuxXxilium/arc/assets/26819159/fa8373d8-55fb-4ab9-83de-4e6a427e0cf7) provide the Code!!! <- IMPORTANT
Initramf unpacking failed: X2-compressed data is corrupt

Environment is physical machine with an intel cpu, by flashing the entire image onto an entire disk.

**Comment by AuxXxilium** [comment]
corrupted image or wrong flashed.
