### ISSUE TITLE
No issue but questions

### ISSUE THREAD

**Issue by TineUser** [AuxXxilium/arc#199]
Now, after having successfully mounted the physical disks via LSI SAS controller with ARC there are some more questions:

1. Will update of ARC work by using the update menu functions in the loader like ARPL?
2. Will updating a clustered DSM with minor updates, like updating from 7.1 Update 4 to 7.1 Update 5, work without reconfiguring the loader manually on each cluster node like ARPL vs. as it is needed when running TCRP as loader?
3. Is it possible to update DSM from 7.1 Update 5 to 7.2 RC when switching build number in ARC and uploading the 7.2 RC PAT file to the DSM without losing the settings and data? I see that DSM 7.2 RC is an available build in ARC.

I'm thinking about two ways to recover my cluster:

1. With the now running DSM I can rebuild the cluster and after this I switch the other node to ARC, too. But then I'm still staying on DSM 7.1 Update 5. But I may have to rebuild the cluster twice which is taking a lot of time.
2. I first update the node with ARC to DSM 7.2 RC, rsync the data from the former cluster node (only the changes should be rsynced which is fast) to the DSM 7.2 RC system, switch the former cluster node to ARC, update this node to DSM 7.2 RC and the rebuild the cluster.

**Comment by AuxXxilium** [comment]
You can update to 7.2 RC if you want it. I wait with all my sensitive data nas for final release. I know some bugs in RC. Have 7.2 on my Test Setups running, for the most things, it looks like stable.

Version Updates between Updates is possible without loosing anything. If you load DSM 7.2 RC .pat in DSM the Loader will dedect, patch and boot it. -> Short: Yes you can. ;)

**Comment by TineUser** [comment]
Great, thank you. I thought that RC is the final release of 7.2. 7.2 RC is officially availabe from Synology. So this is why I'm thinking about updating to DSM 7.2 RC before reclustering.

Which bugs in DSM 7.2 RC do you know?

And what about updating the ARC by the menu function in the loader and updating a clustered DSM with minor updates, like updating from 7.1 Update 4 to 7.1 Update 5, without reconfiguring the loader manually on each cluster node like ARPL vs. as it is needed when running TCRP as loader?

**Comment by AuxXxilium** [comment]
Loader updates, should work like ARPL.

The issues in 7.2 are in Filestation and with some Apps i use. It's to risky for me.

**Comment by TineUser** [comment]
Which other apps?

**Comment by TineUser** [comment]
So HyperBackup, too? This would be too risky for me, too.
