### ISSUE TITLE
Create a new serial number for DSM

### ISSUE THREAD

**Issue by TineUser** [AuxXxilium/arc#202]
It would be great to have an option to create a new serial number. Or is this already possible and I didn't find the option?

**Comment by AuxXxilium** [comment]
it is possible, if you do not select "arc patch" while select model. if you do this, you will loose working syno services.

**Comment by TineUser** [comment]
> it is possible, if you do not select "arc patch" while select model. if you do this, you will loose working syno services.

I don't understand what you mean with "lose working syno services".

**Comment by AuxXxilium** [comment]
If you use arc with arc patch - all syno services are working. can't tell you more here.
