### ISSUE TITLE
Information processor ?

### ISSUE THREAD

**Issue by Odroid13** [AuxXxilium/arc#208]
Thank you for your work, I'm a fan of your loader ^^
Your project is progressing very quickly.

In the Synology information with the redpill loader, the processor information is identical to that of the real Synology and I find it better.
<img width="796" alt="Capture d’écran 2023-05-06 à 19 03 51" src="https://user-images.githubusercontent.com/97029183/236638265-626f92ca-d7f1-4d39-b963-d00d8fbb623c.png">

In Proxmox with your Arc loader, it does not display the correct information. I would like it to display the real processor name of the DS1621xs of the real Synology

<img width="869" alt="Capture d’écran 2023-05-06 à 19 08 44" src="https://user-images.githubusercontent.com/97029183/236638295-dc75846c-88b8-4cc0-8a9d-74916d557dc6.png">

Thanks

**Comment by AuxXxilium** [comment]
no it won't because you selected KVM and not HOST as cpu type in proxmox or unraid. it's a config fault by yours.

**Comment by Odroid13** [comment]
> no it won't because you selected KVM and not HOST as cpu type in proxmox or unraid. it's a config fault by yours.

When I select host, it gives me the real information of my processor and I don't want it.
Thanks

**Comment by AuxXxilium** [comment]
if you want the syno cpu name, remove cpuinfo addon and everything is good.

**Comment by Odroid13** [comment]
> if you want the syno cpu name, remove cpuinfo addon and everything is good.
> 
> all other user want to have the cpu showing that is installed in system.

Thank you ^^
