### ISSUE TITLE
ARC 23.5.13-nemodules - switch from ARPL - DSM install hangs at 99%

### ISSUE THREAD

**Issue by TineUser** [AuxXxilium/arc#210]
ARC is really great :-). Good work.

After successfully switching the productive cluster from TCRP to ARC I want to switch my testcluster from ARPL to ARC, too. First I want to switch to ARC with DSM 7.1.1 and after this with a working DSM cluster I want to update DSM to 7.2 RC.

But the switch to ARC doesn't work as expected: After configuring the boot loader (ARC 23.5.13-nemodules, no ARC patch) and rebooting the installation of DSM begins, takes a long time and then hangs at 99%. With the productive cluster this took only seconds and DSM was ready.

The test cluster is based on ESXi 8.0 U1 with 2 virtual SATA controller and 2 virtual disks: A 1 GB disk with the boot loader and a 21 GB disk with data.

**Comment by AuxXxilium** [comment]
There is a new version. So no need to report everything as bug! Or write it in Discord.

**Comment by AuxXxilium** [comment]
i updated my esxi to 8.0 u1 yesterday and have no problems at all. it's my debug setup for arc loader.

**Comment by TineUser** [comment]
Thank you. The release 23.5.14 helped to finish with the installation of DSM. Now there's a new strange thing:

The cluster is running but it shows the wrong model in the pictures:

![image](https://user-images.githubusercontent.com/77736099/236685819-7b27596a-afd0-40a3-a65a-65a998994769.png)

And now the storage pool is broken with all settings. I recreate the storage pool now. It's only the test cluster.

**Comment by AuxXxilium** [comment]
Looks like 7.2 RC is not bug free. It's a RC and not stable. Found more bugs in RC, thats why i use 7.1.1 for my sensitive data nas.

**Comment by TineUser** [comment]
I'm still on DSM 7.1.1.

**Comment by AuxXxilium** [comment]
thats strange, i never used cluster. only sync to external location.

**Comment by TineUser** [comment]
The right models are shown in the productive cluster but there I have more disks connected. But I think the right models were shown in the test cluster before switching to ARC. And you can see in the screenshot that the nodes are of model DS3622xs+ but it shows the DS918 I think.

**Comment by AuxXxilium** [comment]
Is it showing the correct model in storage manager?

**Comment by TineUser** [comment]
See my post with the screenshot above your post.

**Comment by AuxXxilium** [comment]
looks like high availability has a bug. don't know

**Comment by AuxXxilium** [comment]
can't try this by my own. looks like heartbeat wont work.

**Comment by TineUser** [comment]
Now I updated the test cluster to 7.2 RC.

First you have to update the active server:

1. Go to Configure Boot Loader
2. Reselect the model to switch to DSM build 7.2 RC
3. Build the Loader
4. Boot the Loader
5. Go to http://<IP adress>:5000
6. Start recovery and upload the new PAT file to the DSM
7. Some times later browser goes to http://<IP adress>:5001 and updates the installed packages
8. Finish.

This worked without issues. After that you can update the passive server. Here you only go through steps 1 to 6. Some times later the passive server should apear in the app "Synology High Availability" and cluster status should be OK.

But the pictures of the server models in the cluster are still wrong.

**Comment by AuxXxilium** [comment]
you can look in /etc/synoinfo.conf and /etc.defaults/synoinfo.conf if the right model is inside both files.

**Comment by TineUser** [comment]
> can't try this by my own. looks like heartbeat wont work.

No, the heartbeat is working. If this won't work the cluster wouldn't work correctly.

**Comment by AuxXxilium** [comment]
no heartbeat in my configs wont work. thats why i can't try it.

**Comment by TineUser** [comment]
> you can look in /etc/synoinfo.conf and /etc.defaults/synoinfo.conf if the right model is inside both files.

When DSM is running or in the loader configuration environment?

**Comment by AuxXxilium** [comment]
dsm running

**Comment by TineUser** [comment]
/etc/synoinfo.conf:

```
unique="synology_broadwellnk_3622xs+"
upnpmodelname="DS918+"

```

/etc.defaults/synoinfo.conf:

```
unique="synology_broadwellnk_3622xs+"
upnpmodelname="DS3622xs+"
```

I checked this for my productive cluster: Both files are set like /etc.defaults/synoinfo.conf in the test environment.

How should I change `upnpmodelname="DS918+"` in /etc/synoinfo.conf in the test cluster? By the boot loader configuration of both servers or by editing the file of the running cluster?

**Comment by AuxXxilium** [comment]
looks like you upgraded from 918?

**Comment by TineUser** [comment]
No I didn't upgrade from 918. Because of the serial number in the synoinfo.conf file I should change the upnpmodelname in each server file by the boot loader configuration, right?

**Comment by AuxXxilium** [comment]
it's possible that your serial isn't correct for selected model. that can be a cause.

**Comment by TineUser** [comment]
I can't change the model by editing the synoinfo.conf file in the boot loader configuration because this option isn't listed in the synoinfo part. I can add new lines but I don't know what happens when adding this.

The serial is recreated as new serial by switching to ARC and with upgrading to DSM 7.2 RC. In both steps I had always to select the model. So the serial should be automatically created for the selected model and this is DS3622xs+.

**Comment by AuxXxilium** [comment]
autogenerated serial should be correct. don't know why you don't use are patch but ok.

you have to edit the files in dsm, we can't access them from loader side.

**Comment by TineUser** [comment]
I don't use patch because I don't know what it's used for. In productive cluster I use patch because I didn't change the selcetion but then I had to manually change the serial of one server and the MAC adresses of mac1. Two same serial numbers in a cluster could be problem I guess.

I cant change the file because I don't have the permission to do this. So I try to add the value by adding this to the synoinfo options in the loader.

**Comment by AuxXxilium** [comment]
you have permissions. type: sudo -i

should everyone know, who is using anything from syno.

**Comment by TineUser** [comment]
The thing with the pictures isn't a functional issue. The HA cluster is working. And it's the test environment. But it's confusing.

**Comment by AuxXxilium** [comment]
same for me. don't know where the issue is.

**Comment by TineUser** [comment]
Today I had the idea to recreate the cluster. After having done this the pictures of the shown system models are still the DS918. Really strange.
