### ISSUE TITLE
2 LAN Adapter don’t work

### ISSUE THREAD

**Issue by Nurtech15** [AuxXxilium/arc#213]
I have the newest version of arc loader and i want to bond my network and it doesn’t work is this a bug or or should it not work?

**Comment by AuxXxilium** [comment]
![Screenshot 2023-05-08 183717](https://user-images.githubusercontent.com/67025065/236880343-b6bf8814-3ded-4be1-a286-3a089d269e73.png)

**Comment by Nurtech15** [comment]
Thanks it works
