### ISSUE TITLE
release 24.6.25 doesn't read entered MAC

### ISSUE THREAD

**Issue by lazarg-bf** [AuxXxilium/arc#2141]
**Describe the Bug**
If i try to add my own MAC, the field where i configure the MAC, doesn't take the input after clicking OK.
It just returns the default MAC, and doesn't move forward.
the behaviour is the same, regardless of what MAC i'm entering.

This was working fine on release 24.6.24

**Screenshots**
<img width="365" alt="Screenshot 2024-06-26 at 18 05 47" src="https://github.com/AuxXxilium/arc/assets/58518253/6b8651cf-6bfb-44eb-81d3-d442f1f56f05">

after i hit OK i get this

<img width="367" alt="Screenshot 2024-06-26 at 18 06 00" src="https://github.com/AuxXxilium/arc/assets/58518253/8dd3cf88-b0b7-4c05-8ee9-1fd182a94e1c">

**Hardware**
Trying to run DS920+ in Vmware

**Comment by AuxXxilium** [comment]
it does. mac only visible for dsm system. not for user. we use hardwaremac for boot. we don‘t need to set them to the adapter!
