### ISSUE TITLE
ARC 23.5.16: No disks of LSI SAS controller mounted

### ISSUE THREAD

**Issue by TineUser** [AuxXxilium/arc#216]
After updating ARC from 23.5.15 to 23.5.16 the physical disks attached to a passthroughed LSI SAS controller are not mounted anymore. I have running ARC on ESXi 8.0 U1 VMs.

ARC sees the disks:

![image](https://user-images.githubusercontent.com/77736099/237004276-8b9ee55d-7507-49d4-ad2a-2084e435dc74.png)

But in DSM the disks are not mounted. You see the active server with all disks (ARC 23.5.15) and the passive server (ARC 23.5.16):

![image](https://user-images.githubusercontent.com/77736099/237004440-8ef25aba-82e1-47f2-89f8-cd232d302578.png)

Btw. the shown model in the Synology HA app depends on the amount of mounted disks:

![image](https://user-images.githubusercontent.com/77736099/237004782-bc500a4b-6709-4295-937b-1e8f0c452e35.png)

**Comment by AuxXxilium** [comment]
have you tried to reboot?

**Comment by AuxXxilium** [comment]
please update modules in arc, rebuild and try again.

**Comment by TineUser** [comment]
Done but without success. The disks aren't mounted in DSM. ARC sees the disks.

**Comment by AuxXxilium** [comment]
arc and dsm have nothing to do with each other. both use own modules

**Comment by AuxXxilium** [comment]
one more question: do you have made complete update?

**Comment by TineUser** [comment]
> "lspci -nnk

Working NAS:

0000:00:00.0 Class [0600]: Device [8086:7190] (rev 01)
        Subsystem: Device [15ad:1976]
0000:00:01.0 Class [0604]: Device [8086:7191] (rev 01)
0000:00:07.0 Class [0601]: Device [8086:7110] (rev 08)
        Subsystem: Device [15ad:1976]
0000:00:07.1 Class [0101]: Device [8086:7111] (rev 01)
        Subsystem: Device [15ad:1976]
0000:00:07.3 Class [0680]: Device [8086:7113] (rev 08)
        Subsystem: Device [15ad:1976]
0000:00:07.7 Class [0880]: Device [15ad:0740] (rev 10)
        Subsystem: Device [15ad:0740]
0000:00:0f.0 Class [0300]: Device [15ad:0405]
        Subsystem: Device [15ad:0405]
0000:00:11.0 Class [0604]: Device [15ad:0790] (rev 02)
0000:00:15.0 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.1 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.2 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.3 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.4 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.5 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.6 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:15.7 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.0 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.1 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.2 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.3 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.4 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.5 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.6 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:16.7 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.0 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.1 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.2 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.3 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.4 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.5 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.6 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:17.7 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.0 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.1 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.2 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.3 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.4 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.5 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.6 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:00:18.7 Class [0604]: Device [15ad:07a0] (rev 01)
        Kernel driver in use: pcieport
0000:02:00.0 Class [0106]: Device [15ad:07e0]
        DeviceName: sata0
        Subsystem: Device [15ad:07e0]
        Kernel driver in use: ahci
0000:02:01.0 Class [0106]: Device [15ad:07e0]
        DeviceName: sata1
        Subsystem: Device [15ad:07e0]
        Kernel driver in use: ahci
0000:02:02.0 Class [0c03]: Device [15ad:0774]
        DeviceName: usb
        Subsystem: Device [15ad:1976]
        Kernel driver in use: uhci_hcd
0000:02:03.0 Class [0c03]: Device [15ad:0770]
        DeviceName: ehci
        Subsystem: Device [15ad:0770]
        Kernel driver in use: ehci-pci
0000:03:00.0 Class [0200]: Device [15ad:07b0] (rev 01)
        DeviceName: Ethernet0
        Subsystem: Device [15ad:07b0]
        Kernel driver in use: vmxnet3
0000:0b:00.0 Class [0200]: Device [15ad:07b0] (rev 01)
        DeviceName: Ethernet1
        Subsystem: Device [15ad:07b0]
        Kernel driver in use: vmxnet3
0000:13:00.0 Class [0107]: Device [1000:0087] (rev 05)
        DeviceName: pciPassthru0
        Subsystem: Device [1000:3030]
        Kernel driver in use: mpt3sas
0001:09:00.0 Class [0106]: Device [1b4b:9235] (rev 11)
0001:0c:00.0 Class [0106]: Device [1b4b:9235] (rev 11)

**Comment by TineUser** [comment]
> one more question: do you have made complete update?

Today in the morning? No. I updated all items separately.
Today in th evening? No. I updated Addons, LKMs and Modules.

**Comment by AuxXxilium** [comment]
you can go back to .15, i removed latest build.

**Comment by TineUser** [comment]
OK, in the morning the rollback to 23.5.15 didn't work but now it worked. And the model is shown correctly (it took a long time until this was corrected but again, the picture is related to the amount of mounted disks):

![image](https://github.com/AuxXxilium/arc/assets/77736099/fd96525e-dbae-4ec1-b9a7-c4647a736cca)

**Comment by AuxXxilium** [comment]
rollback is only working if i remove the latest release from github.
