### ISSUE TITLE
ttyd's version

### ISSUE THREAD

**Issue by wjz304** [AuxXxilium/arc#219]
hello,
I found that the current 2022.02 buildroot comes with ttyd version 1.6.3, which does not support lrzsz well,
Can you help me take a look at the version of your ttyd?
![image](https://github.com/AuxXxilium/arc/assets/5615843/14b65fc0-f6fd-4fe1-a5d3-d364930bf26c)

**Comment by wjz304** [comment]
root@arpl:/opt/arpl# ttyd -v
ttyd version 1.7.3

**Comment by AuxXxilium** [comment]
@wjz304 buildroot 2022.02 has more bugs. that's why i have changed.

**Comment by wjz304** [comment]
I updated it, but there is still a probability of lszrz making errors under web ttyd.

**Comment by wjz304** [comment]
> do you know this version? looks like he has fixed some bugs.
> 
> https://github.com/tsl0922/ttyd

yes, now,  it is v1.7.3 in 2023.02.x, 
But there is still a probability of interrupting the transmission, perhaps due to the browser, as there is no interruption under SSH

I am looking for other solutions,

**Comment by AuxXxilium** [comment]
we can add a small webserver to br and let the user download and upload the files via php or html.

**Comment by wjz304** [comment]
Yes, I am testing httpd, but it requires users to actively click on it,

**Comment by AuxXxilium** [comment]
nginx is possible too

**Comment by wjz304** [comment]
For now, I use httpd for web and lszrz for ssh.  I can't think of a better solution,
![923485aeddbb00fef9f34f16724ccf2b](https://github.com/AuxXxilium/arc/assets/5615843/34dd5ade-9332-4f14-ad77-aa4c4f42c484)

**Comment by AuxXxilium** [comment]
i've seen this, not sure if this is the final way. for now it's a possible way to go.
