### ISSUE TITLE
Don't boot DVA3221/3219

### ISSUE THREAD

**Issue by alekc70** [AuxXxilium/arc#2197]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
Don't boot DVA3221/3219 after build loader.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![image](https://github.com/AuxXxilium/arc/assets/172167411/9e842fe1-bd87-44eb-bf21-bd818926b23c)
![image](https://github.com/AuxXxilium/arc/assets/172167411/8625c580-4677-4752-9a73-bc509f21a75e)
![image](https://github.com/AuxXxilium/arc/assets/172167411/a045baa3-3b10-48f4-a97a-8e286f145e48)
![image](https://github.com/AuxXxilium/arc/assets/172167411/0942a925-c7f7-4ccc-acbd-db942769035f)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
There is full information on screenshots

Log files bellow:
[jrExit.zip](https://github.com/user-attachments/files/16040308/jrExit.zip)

**Comment by AuxXxilium** [comment]
first: why using such an old version?
second: system was still booting while you turned it off

**Comment by alekc70** [comment]
I left the computer on for 4 hours. Could you please check the log file to see what the problem might be?
[jrExit.zip](https://github.com/user-attachments/files/16041925/jrExit.zip)
