### ISSUE TITLE
No Loader Disk found on proxmox

### ISSUE THREAD

**Issue by jeff25** [AuxXxilium/arc#223]
**Describe the bug**
Got message no loader disk found on proxmox installation.

**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.

**Additional context**
23.5.18 works from backup as always.

**Comment by jeff25** [comment]
only happens if i deploy new .img file. Using updater works....

**Comment by AuxXxilium** [comment]
Set Loader disk to Sata 0:0 or bind the image as usb device.
