### ISSUE TITLE
loader is hanging on run /init as init process

### ISSUE THREAD

**Issue by dawauz** [AuxXxilium/arc#2236]
Like the title.
My hardware is a pc, which had jun loader but that one is crashing after boot.
I tried the arc loader, but it hangs on run /init as init process
what could that be?

![image](https://github.com/AuxXxilium/arc/assets/34133251/e8f40b25-d95d-4376-ba1d-9c3a3b4ceae4)

**Comment by AuxXxilium** [comment]
no usb 3.0 stick/port

**Comment by dawauz** [comment]
well the computer hasn't usb 3 at all, the stick is also 2.0.

**Comment by AuxXxilium** [comment]
than it takes time, if it will load.

**Comment by AuxXxilium** [comment]
btw it's clearly written:

- 4GB USB 3.0 Drive
- min. 4GB Ram

I guess you don't match both.

**Comment by dawauz** [comment]
Well I dont match that, you;'re right. 
Can you advise me, I had an installation with Juns loader but that one i faulty. Can I move over the disks to another PC, (with usb 3 and so on) an save my data?
Propbably is the raid set out of sync and should it be repaired.
