### ISSUE TITLE
What is required to get Arc Loader working on a hypervisor?

### ISSUE THREAD

**Issue by pitOOf** [AuxXxilium/arc#2240]
Hello,

I am having trouble getting Arc Loader to work on a hypervisor. I have successfully installed arc-24.7.1.vhdx without any errors, but the IP address becomes inaccessible afterward.

Could anyone provide guidance on what is required to ensure Arc Loader functions correctly in this environment?

Thank you for your assistance!

**Comment by AuxXxilium** [comment]
hyper-v issue

**Comment by pitOOf** [comment]
Is there no solution yet?

**Comment by pitOOf** [comment]
> hyper-v issue

Is it not possible to run a working image on hyper-v yet?
