### ISSUE TITLE
System rebooting on startup (using 7.2)

### ISSUE THREAD

**Issue by rosscullen** [AuxXxilium/arc#2271]
**Describe the Bug**
System rebooting after about 3 seconds on shell prompt. Potential kernal panic is what I think you mentioned on previous issue #2251
- No additional modules added (other than defaults selected
- Building using model DS918+
- Build appears to boot ok with DSM 7.1 but issues with DSM 7.2.
- Using latest version (24.7.2 and also 24.7.3)

**Screenshots**
5VFEVFSAC

**Hardware**
Intel i7-9700T 2.0GHz-4.3GHz Octa-Core CPU 8th Gen (Coffee Lake)
ASRock H370M-ITX/ac LGA1151 Motherboard
16GB RAM
6 SATA3 Ports, 1 Ultra M.2 Slot
Dual Intel® Gigabit LAN
Intel® 802.11ac WiFi + BT 4.2 (disabled RC)

Many thanks!

**Comment by AuxXxilium** [comment]
remove the console from addons and it should work
