### ISSUE TITLE
Maybe filesystem corrupted after 7.2 migration

### ISSUE THREAD

**Issue by AlbertoNobile** [AuxXxilium/arc#2338]
**Describe the Bug**
Hi guys,
I need you help :)

Today I upgraded my 6.2 installation to 7.1 and then to 7.2 with arc loader (latest version).

The process was smooth and I booted into the new system without any issue, so I verified the storage manager status and I saw a warning with a button to recheck the filesystem (I don't exactly remember the button label). I decided to reboot the NAS before rechecking the file system and now DSM can't mount my disks.
I can't log in via DSM but I can via SSH so I collect the dmesg (in attachment)
[log.txt](https://github.com/user-attachments/files/16124076/log.txt)

Because the first boot was good, I would like to run a DSM Reinstall Mode but in arc.sh the function is missing. I can try via Grub but I don't have a monitor connected, so can you write the grub menu entry for this function? so I can try to activate it in "blind" mode. thx

**Screenshots**
Sysinfo:
![Screenshot 2024-07-08 at 09 26 48](https://github.com/AuxXxilium/arc/assets/134401252/370b6a6d-8a16-4b07-8389-1e18b72730d4)

**Hardware**
HP N40L

**Comment by AuxXxilium** [comment]
reading wiki and the warning on first page will help.

**Comment by AlbertoNobile** [comment]
Hi @AuxXxilium, thank you for your comment.
I've read the wiki a lot before posting but I can't find any useful info to resolve my issue, for sure it's my fault.
For the DSM Reinstall Mode entry, I expanded all the menu but I can't find it:
![Screenshot 2024-07-08 at 10 20 44](https://github.com/AuxXxilium/arc/assets/134401252/7ccea846-2999-4a49-8c0c-e5f37f9ff120)

**Comment by AuxXxilium** [comment]
there is a big warning on first page because of dsm 6 -> 7

don't expand the sections, use power menu in main menu - lowest section

**Comment by AlbertoNobile** [comment]
![Screenshot 2024-07-08 at 10 58 42](https://github.com/AuxXxilium/arc/assets/134401252/4a6713b1-c9df-4757-8d00-a2de054f5352)
here the screen ho power menu. I've chosen "Reinstall Mode" and now I have to reinstall the bootloader, so DSM Reinstall process didn't start. Maybe have I to use another menu entry?

**Comment by AlbertoNobile** [comment]
Besides the possibility of restarting the system in DSM Reinstall Mode, do you have any suggestions for solving the very first problem? If I were to format the partitions that do not contain my data, do you think it would solve the issue?

**Comment by AuxXxilium** [comment]
why reinstall the bootloader? it starts to dsm reinstall screen. nothing else. but this is only possibrl if your disks are working like they should.

**Comment by AlbertoNobile** [comment]
I don't know why, but if I choose Reinstall Mode, the system reboot in Arc Config mode without any configuration. So I have to rebuild the loader now

**Comment by AuxXxilium** [comment]
i don't know, i tried from mobile and it is working. have to wait until i'm at home.

**Comment by AlbertoNobile** [comment]
Update with the last test :)
after rebuilding the loader, the system started in DSM Reinstall Mode. I started the reinstallation process, and the progress bar slowly reached 3%, then suddenly jumped to 100%.
Unfortunately the situation didn't change: I can login only via ssh and volume1 is not mounted

**Comment by AuxXxilium** [comment]
![image](https://github.com/AuxXxilium/arc/assets/67025065/1f2af44b-97dc-43a7-bac6-a89edccf896b)

sdx1 = grub
sdx2 = synoboot
sdx3 = data (dsm7)
sdx5 = data (dsm6/jun)

so the mount points are wrong.

**Comment by AlbertoNobile** [comment]
great, thank you for your help. Can you suggest the next step to resolve the problem?

**Comment by AlbertoNobile** [comment]
also the leader sees the same mount points:
![Screenshot 2024-07-08 at 13 15 21](https://github.com/AuxXxilium/arc/assets/134401252/a02c8b5f-cf31-4598-802c-433d2b558d28)

**Comment by AuxXxilium** [comment]
this says nothing, it will see every partition on disk. but your numbers and sizes are wrong for dsm. the only possible way is trying to use recovery mode and grep the file in webterminal or go back to 6.2 and backup your file from there. atm i don't see another way to get your files.

**Comment by AuxXxilium** [comment]
if i look at the partition sizes, they will not work with dsm 7. so we need to format your disks, but loosing the data on it, without backup isn't an option.

**Comment by AlbertoNobile** [comment]
It's very strange because I used 7.1 without issues and 7.2 at the first boot was ok. After the first reboot I had problems

**Comment by AuxXxilium** [comment]
possible dsm 7.1 had a compatibility mode. you can also downgrade back to 7.1 and try this again.

**Comment by AuxXxilium** [comment]
and btw why do you use directboot? you shouldn't need it with your hardware.

**Comment by AlbertoNobile** [comment]
accordingly to the wiki:
If you have the problem that your DSM does not start properly: Set Directboot to true. (Some HP systems (mainly HP Microservers only work with Directboot.)

Also I found different users with the same hw that use Directboot to resolve boot issue

**Comment by AuxXxilium** [comment]
should work without, since about 2 months. there is much work done in this time.

**Comment by AlbertoNobile** [comment]
ok, I didn't know it. btw I downgrade to 7.1 but it doesn't mount the partition. do you know how can I force it?

**Comment by AlbertoNobile** [comment]
honestly I think that I need to fscheck the partition: when the 7.2 worked, the storage manager warned that the volume needed to be checked. I rebooted the system without the check and maybe this is was the mistake.
Now I need to understand how to do it via command line. I try to get some more support on your discord, hope someone could help :)

**Comment by AuxXxilium** [comment]
i don't know if one of the guys, who are very good in linux and dsm, is online atm.
