### ISSUE TITLE
Installing the latest Arc loader on Proxmox

### ISSUE THREAD

**Issue by meloserj** [AuxXxilium/arc#2361]
Hi Christian and all valued members, 
I am a newbie who doesn't find a forum (don't use discord) to ask my question, but if you can help me I really appreciate your kind help.
I installed the latest Arc loader on my proxmox server, which has linux bond on its 2 interfaces.
But when I run the Arc loader, I faced below error:
virtio_net (Unknown): LINK LOCAL (No DHCP server found)
And then no Github connection could made.
I changed the network driver to vmxnet but still no success. All my other VM's getting their DHCP IP from my router without any issue.
So I removed the bond0 in my proxmox and the issue resolved. (I used vmxnet this time)
May you please help me to understand if the issue is from my proxmox side or Arc loader limitation?
Thanks a lot for your kind support

**Comment by AuxXxilium** [comment]
bonds inside arc not supported. issue depends on your proxtrash settings.
