### ISSUE TITLE
Kernel panic after add second ethernet card on proxmox 

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/arc#239]
hello, with previous versions it worked, in practice if I try to add a second network card in proxmox with a different vlan and start dms it freezes with a kernel panic message, see the screenshot.
How come?

![image](https://github.com/AuxXxilium/arc/assets/31816231/15a8e70b-e7fa-449d-9e16-bde67147be49)

**Comment by AuxXxilium** [comment]
do you see the warnings all around? you should rebuilt first, before report es bug.

**Comment by wifi75** [comment]
I do not understand what you mean...

**Comment by AuxXxilium** [comment]
Rebuild Loader

**Comment by wifi75** [comment]
> Rebuild Loader

still doesn't work after rebuild

**Comment by AuxXxilium** [comment]
than don't know, it's possible that proxmox forces this issue or anything else.

try a different network adapter selection in proxmox, if this doesn't work, i can't help.

btw: i tried proxmox so often and i still think, it's trash. they won't to be the one who you can do everything with it, same like unraid, and nothing in this systems is really brought to an end. it's can not be that i need in a hypervisor that has to be stable and fast in service, to setup something with a commandline. proxmox is in my eyes, only an early alpha and far away from a good solution or alternative to esxi.

**Comment by AuxXxilium** [comment]
try 23.5.36 after github completed the build step
