### ISSUE TITLE
Addon deduplication is working?

### ISSUE THREAD

**Issue by zozito** [AuxXxilium/arc#2411]
**Describe the Bug**
Hi team,

I've enabled the deduplication addon, but after build the loader I don't have the option to allow the deduplication and show the saved space 

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

![image](https://github.com/user-attachments/assets/efd49d50-8d78-4239-a384-705febca6309)

- **With addon enabled**

![image](https://github.com/user-attachments/assets/7e2c6230-1bbd-4847-9c6e-ade1cb2ae1ad)
Note: I don't know if I need to enable the hdddb addon but, since the drives need to be recognized by DSM as Synology SSDs to allow the deduplication I thought that is the correct way.

![image](https://github.com/user-attachments/assets/80502b28-a92f-4810-8f90-3119aacb126a)

- **If I don't enable the addon.**

![image](https://github.com/user-attachments/assets/321b9e49-7042-498d-a4e0-b27dd4851df3)

![image](https://github.com/user-attachments/assets/94906055-0aa2-4609-bf7a-33e3a961e214)

I tried the project Synology_HDD_db and Synology_enable_Deduplication from 007 revad and the script works well

- **with 007 revad script.**

![image](https://github.com/user-attachments/assets/c522e10d-40fd-43e0-9aad-e777207b2bb4)

**Hardware**
The system is installed in a proxmox vm, with 5 vdrives with ssd enabled 
16gb of vRAM
CPU 12 Cores

**Comment by zozito** [comment]
I dind't used any options when I executed the scripts

Simply used

/volume1/homes/admin/HD/syno_enable_dedupe.sh
/volume1/homes/admin/HD/syno_hdd_db.sh

Thank you

**Comment by AuxXxilium** [comment]
you know that these addons need a system reboot after dsm installation?

**Comment by zozito** [comment]
I think I already did, but I'm not sure, I can try again to see the results.

could I active the addon without reinstall the DSM? 

Thank you

**Comment by AuxXxilium** [comment]
don't do anything after you used a custom script, this will break the installation.
