### ISSUE TITLE
doesn't read entered MAC (dsm system no see MAC too)

### ISSUE THREAD

**Issue by aarpro** [AuxXxilium/arc#2425]
**Describe the Bug**
I have completely updated (on a new flash) on version 24.7.10 (from 24.4.7)
even though I entered my MAC and serial number, my router, DSM and Synology Assistant read real MAC (SN is ok)
my second server on the version 24.4.7 works on my entered MAC and entered SN is OK

**Screenshots**
![2024-07-12_225939](https://github.com/user-attachments/assets/de3ecc05-27b2-42f0-b9df-d762b16e216c)
![2024-07-12_225838](https://github.com/user-attachments/assets/dd5caa68-00ec-4ef4-85e6-da5e32981bf7)
![2024-07-12_225141](https://github.com/user-attachments/assets/d4ffd031-f336-4401-a887-b519df106c80)
![2024-07-12_225041](https://github.com/user-attachments/assets/a7c7c40b-64c3-4fcd-9acf-b280b3716122)
![2024-07-12_224500](https://github.com/user-attachments/assets/718a5839-a9cb-45b4-8e9f-b4f6bd921f71)

**Hardware**
![2024-07-12_230658](https://github.com/user-attachments/assets/7056444f-5ff5-4c28-b0de-f49d787ce772)

**Comment by AuxXxilium** [comment]
to use custom mac we don't need to apply them to the adapter and break wol with changing the mac. we only need the mac inside the cmdline and it is working!

**Comment by aarpro** [comment]
> and it is working!
it is possible locally
but account.synology.com now no see my server - error QuickConnect and Synology DDNS
