### ISSUE TITLE
First boot stuck on network 

### ISSUE THREAD

**Issue by OXOTH1K** [AuxXxilium/arc#2462]
First boot on 24.2.29-24.7.14 stuck on init network stack. I can see logs not at all versions. Reboot not helps.
My specs:
- Asrock H310CM-DVs
- CPU Intel QTJ2 (works on old redpill)
- 16GB RAM

![Screen](https://github.com/user-attachments/assets/35ef3b6a-6f33-4689-8dad-81f5c0755a10)

**Comment by AuxXxilium** [comment]
check your bios settings.

**Comment by OXOTH1K** [comment]
I was checked all what I can. Reset to default and checked again. What kind of settings can make this trouble?

**Comment by AuxXxilium** [comment]
pxe boot, fastboot, silentboot, ...

**Comment by OXOTH1K** [comment]
Fasboot disabled
Serial console haven’t config for setup

**Comment by OXOTH1K** [comment]
May be I can change something in boot config for more logs?

**Comment by OXOTH1K** [comment]
Im so sorry. Reflash bios was solved problem.
