### ISSUE TITLE
Error in function Delete Synoinfo item(s)...

### ISSUE THREAD

**Issue by vinhnguyen1104** [AuxXxilium/arc#257]
1.I am unable to perform some Synoinfo deletions. It hangs itself to go to the Add/edit Synoinfo Item menu.
![screenshot_1684919802](https://github.com/AuxXxilium/arc/assets/111233433/dda029d3-8ae7-41c4-bdb4-41c06f84729f)
2. In synoinfo added **support_memory_compatibilty: no**
![screenshot_1684920148](https://github.com/AuxXxilium/arc/assets/111233433/4ea10248-aef7-4afe-92d2-db5659eddfda)
But in etc.defaults/synoinfo.conf
**support_memory_compatibilty: yes**
![screenshot_1684920600](https://github.com/AuxXxilium/arc/assets/111233433/09060119-fbe0-4aea-a45d-700776caee65)
It caused the message Ram is not recommended by Synology.
![screenshot_1684920862](https://github.com/AuxXxilium/arc/assets/111233433/bd4f3472-d73a-417e-a84c-92f1faeb8393)

I'm using ARC 23.5.55

**Comment by AuxXxilium** [comment]
rebuild stick and try again
