### ISSUE TITLE
Since EFI, the Proxmox commands no longer work?

### ISSUE THREAD

**Issue by Odroid13** [AuxXxilium/arc#259]
Thank you for your work and your updates.

I just updated the Loader arc23.5.28 to arc23.5.55. Now it is no longer possible to compile without switching the VM to EFI.

https://github.com/AuxXxilium/arc/assets/97029183/fc8023b5-47c1-4374-99c2-63b12c124980

Since the obligation to be in EFI , the commands from proxmox shutdown or reboot no longer work, I don't really understand this choice because everything was working fine?
The VM in i440FX or Q35, commands from Proxmox no longer work.
Before this update the VM remained by default: SeaBios / i440FX and everything worked perfectly.

Thanks ^^

**Comment by AuxXxilium** [comment]
i had to add this check in this build because we found multiple bugs in non efi systems, that i try to fix atm

**Comment by Odroid13** [comment]
> i had to add this check in this build because we found multiple bugs in non efi systems, that i try to fix atm

Ok, Thanks

**Comment by Odroid13** [comment]
I tried the latest version but still the problem with Proxmox drivers Virtio not working.
In my opinion it is since the passage in EFI !!

Thanks

**Comment by AuxXxilium** [comment]
no it isn't. i removed efi check because i fixed the issue yesterday. 

virtio is also back in latest release. .60 so it should work. if not, please add serial console to proxmox vm and send me output after boot.

**Comment by AuxXxilium** [comment]
@Odroid13 can you make Update Modules and check again?

**Comment by Odroid13** [comment]
I'll post my test results anyway.

With Arc Loader 23.5.60.2

When I default to SeaBios.
Vm does not start

In UEFI OVMF
It works but no possibility to turn off the VM from Proxmox.

Video 1 :

https://streamable.com/f56b51

Video 2 :

https://streamable.com/x1fzkw

**Comment by AuxXxilium** [comment]
First, don't try .60.2, use .64 instead. 

In 7.2 RC there was still no acpi. so no way for powerdown with button press or outside from dsm.

**Comment by Odroid13** [comment]
> First, don't try .60.2, use .64 instead.
> 
> In 7.2 RC there was still no acpi. so no way for powerdown with button press or outside from dsm.

In version 7.2 RC everything works perfectly with your Loader 23.5.28 ^^ .

The VM is by default in Proxmox.

Watch the video please:

https://github.com/AuxXxilium/arc/assets/97029183/5361f724-15dd-4037-9ae5-7fed066a7ce4


Thanks

**Comment by AuxXxilium** [comment]
it's marked as working on, i know the issue and try to fix it

**Comment by AuxXxilium** [comment]
try latest version, if not working: go to update menu - switch to beta modules and report back

**Comment by Odroid13** [comment]
> try latest version, if not working: go to update menu - switch to beta modules and report back

No good erreur Etho

<img width="820" alt="Capture d’écran 2023-05-26 à 07 58 05" src="https://github.com/AuxXxilium/arc/assets/97029183/62594545-61af-4cef-a9af-d6e324c56a42">

**Comment by AuxXxilium** [comment]
bios is not showinn ip there. until next patch. but you should be able to connect to dsm. efi should work without any issue.

**Comment by Odroid13** [comment]
Still does not work.

I created a normal loader and Beta version.

Video normal version

https://github.com/AuxXxilium/arc/assets/97029183/08b876cf-8418-45c2-a672-fa6b1a5fe436


Video Beta Loader



https://github.com/AuxXxilium/arc/assets/97029183/88f3611d-9d62-4941-b86e-21bbe56c786d

**Comment by AuxXxilium** [comment]
in your video of beta, i don't see the step where you load the beta modules from update menu.

**Comment by Odroid13** [comment]
> in your video of beta, i don't see the step where you load the beta modules from update menu.


^^

https://github.com/AuxXxilium/arc/assets/97029183/d5fd7c05-ad91-44f5-a57b-778d5486051f

**Comment by AuxXxilium** [comment]
then it's a problem with final version of dsm 7.2. the beta modules are the same, that you have reported to be working.

**Comment by Odroid13** [comment]
> then it's a problem with final version of dsm 7.2. the beta modules are the same, that you have reported to be working.

No, nothing with the DSM Final version.
I just did a test with the Arpl-i18n loader and it works perfectly in DSM 7.2 Final (DS920+).
The problem comes from elsewhere, you have to look for the cause and hoping that you will find it because I like your work ^^


https://github.com/AuxXxilium/arc/assets/97029183/8c81de89-abd0-40c0-99cd-1d821ba8af93

**Comment by AuxXxilium** [comment]
after i'm at home, let me try something. i will compile it with his modules. to clear that is a modules issue and nothing else.

**Comment by Odroid13** [comment]
> after i'm at home, let me try something. i will compile it with his modules. to clear that is a modules issue and nothing else.

Ok, Thanks ^^

**Comment by AuxXxilium** [comment]
Should be fixed in .100 release.

**Comment by Odroid13** [comment]
Hello, I just did a new test with the arc-23.5.100a version.

You did a good job, it works again with default machine with Proxmox.


https://github.com/AuxXxilium/arc/assets/97029183/d5bd44e4-5251-4f44-85ac-27b2e1d0b14e





Bios: default (Seabios)
Machine: default (i440FX)
<img width="525" alt="Capture d’écran 2023-05-27 à 08 10 54" src="https://github.com/AuxXxilium/arc/assets/97029183/0758af87-1879-4eda-ac5e-80dcf7a5db02">


The only thing wrong is the ip address.
It's not a big deal because with Synology Assistant we can find it.

<img width="803" alt="Capture d’écran 2023-05-27 à 07 35 34" src="https://github.com/AuxXxilium/arc/assets/97029183/bb49d043-5c8c-47ac-af4f-0fa80c8bc530">

Attention I will always report if I encounter another problem ^^
Thanks
