### ISSUE TITLE
cannot obtain a valid IP

### ISSUE THREAD

**Issue by wjz304** [AuxXxilium/arc#261]
Hi, 
Have you encountered any issues with not being able to dhcp?

In PVE, vmxnet3 cannot obtain a valid IP address
Some r8125 in physical machines are also unable to obtain IP addresses,

According to the test, these will be alleviated after canceling the MAC of cmdline. But it's not a very good solution.
Have you ever encountered it? Or have any insights?

**Comment by AuxXxilium** [comment]
yes i have. But only if we use nonefi systems. was yesterday looking to find the issue but havn't it. i removed your model-conffig patches that are network related, after this i got ip's.

**Comment by AuxXxilium** [comment]
second is, we patched the lkm to get 8 networkadapter working, but there is an issue, that the cmdline can't handle this. look in my lkm for first workaround. 2 commits are related to this.

**Comment by wjz304** [comment]
EFI can also occur, and the order in which udev identifies network cards can also have an impact,

**Comment by wjz304** [comment]
Jim3ma's suggestion is to solidify the IP address instead of relying on cmdline input, but I have not found an effective way at present

**Comment by AuxXxilium** [comment]
oh, i missed to read a word. i will try to find a way today.

**Comment by AuxXxilium** [comment]
i had to much coffee today

**Comment by AuxXxilium** [comment]
so a little workaround:

we grep all mac and write them out to config. let them read at boot and write to device. so we can be sure, the mac table is always the same. and we fix the order of devices. because we have the mac in the right place. 

one problem with this solution is, that i was not able to write the mac in non efi mode. i can assign the correct mac but the loader doesn't get it. if i fix this, dsm doesn't use the mac i want.

more work today.

**Comment by wjz304** [comment]
I really rarely test non efi mode
I should do more testing

**Comment by AuxXxilium** [comment]
same for me, i see the only way to get this working to move the mac swtich to an addon for nonEFI.

**Comment by wjz304** [comment]
> same for me, i see the only way to get this working to move the mac swtich to an addon for nonEFI.

I am also considering removing the MAC settings from LKM and placing them in Addons

**Comment by AuxXxilium** [comment]
would be the best way for us. will try it today, we can write the mac to synoinfo.conf like the sn is already written, and grep this from there.

**Comment by wjz304** [comment]
I'm not sure if the pci location of buildroot is consistent with that of syno. I feel like something needs to be able to label which network card

**Comment by AuxXxilium** [comment]
thats another point. first is that we need something to apply the mac without using cmdline

**Comment by AuxXxilium** [comment]
i think we should be able to write out the hardware mac to a file and load them from this, regardless of order of the adapter. we have everytime the same mac (but can be on different adapter). this is fixing the ip issue for now.

**Comment by AuxXxilium** [comment]
the issue is in lkm - we have to find it there, all other solutions runs into a kernel panic caused by lkm while boot

**Comment by EliotFR44** [comment]
Hi, idk if it's the same problem but i can't obtain a valid dhcp ip.
It's strange because it works during the installation procedure.
I use a passthought pcie 2.5gbps lan ethernet card.

A picture : 
![lolil](https://github.com/AuxXxilium/arc/assets/39886697/842a4150-14cb-4325-8593-0caa06ab8a05)

**Comment by AuxXxilium** [comment]
> Hi, idk if it's the same problem but i can't obtain a valid dhcp ip. It's strange because it works during the installation procedure. I use a passthought pcie 2.5gbps lan ethernet card.
> 
> A picture : ![lolil](https://user-images.githubusercontent.com/39886697/241425603-842a4150-14cb-4325-8593-0caa06ab8a05.PNG)

you will get an ip, look in your router, but the ip can be different than the shown one or no ip is shown, and you get one. we know about this.

but this is only happening if you doesn't use uefi for boot.

**Comment by EliotFR44** [comment]
Hi,

I use EFI for boot, not the secure boot but the EFI boot : 
![image](https://github.com/AuxXxilium/arc/assets/39886697/4dfea7fb-59e9-48e6-a27c-d2bc930f8fa1)

I obtain an IP on my router, with the right mac address : 
![image](https://github.com/AuxXxilium/arc/assets/39886697/b2d580db-6aa0-44d1-90b3-497e43e0f244)

But i can't open http://192.168.1.61:5000/, i can't ping this address and i can search this nas on synology assistant.

**Comment by AuxXxilium** [comment]
@wjz304 I found an issue, in our logic for setting mac.

if we set the mac in boot.sh to show the correct ip, dsm is not able to set the same while boot, because we load the kernel with kexec. if i use directboot in my tests, everything is fine, directboot is loading dsm kernelin grub directly.

**Comment by wjz304** [comment]
> @wjz304 I found an issue, in our logic for setting mac.
> 
> if we set the mac in boot.sh to show the correct ip, dsm is not able to set the same while boot, because we load the kernel with kexec. if i use directboot in my tests, everything is fine, directboot is loading dsm kernelin grub directly.

Thank you for your test, 
![33ZP(L0_BU5T9%IEMWO_`OE](https://github.com/AuxXxilium/arc/assets/5615843/abadf3e2-6a90-484a-95a2-bdf291add16c)

**Comment by wjz304** [comment]
> @wjz304 I found an issue, in our logic for setting mac.
> 
> if we set the mac in boot.sh to show the correct ip, dsm is not able to set the same while boot, because we load the kernel with kexec. if i use directboot in my tests, everything is fine, directboot is loading dsm kernelin grub directly.

我使用PVE测试，在切换到 DirectBoot 后，它并没有缓解.

当我补全了ifcfg-eth* 后似乎有所缓解。
```
for N in `seq 0 7`; do
echo -e "DEVICE=eth${N}\nBOOTPROTO=dhcp\nONBOOT=yes\nIPV6INIT=dhcp\nIPV6_ACCEPT_RA=1" > "${RAMDISK_PATH}/etc/sysconfig/network-scripts/ifcfg-eth${N}"
done
```
![image](https://github.com/AuxXxilium/arc/assets/5615843/b62e6c13-cb60-4982-8117-b2b9feaa8ebe)

**Comment by TineUser** [comment]
> Hi, idk if it's the same problem but i can't obtain a valid dhcp ip. It's strange because it works during the installation procedure. I use a passthought pcie 2.5gbps lan ethernet card.
> 
> A picture : ![lolil](https://user-images.githubusercontent.com/39886697/241425603-842a4150-14cb-4325-8593-0caa06ab8a05.PNG)

I have the same issue with ARC 23.5.101 on a Dell PowerEdge T20. I have to manually set the hardware MAC address to get DSM running. When booting I see the URL for DSM is shown with the IP address but at the end I see the same message about th einterface not being operational.

With older ARC versions there were no issues with the NICs. So I don't understand why there are so much changes regarding NICs making so much problems.

**Comment by AuxXxilium** [comment]
because we try to find a way to get nonEFI boot working with custom mac. that wasn't working for a long time.

wait for .104

**Comment by TineUser** [comment]
Using .104 doesn't change the situation. Instead of an orange background of the warning it's now with black background but it's still there. But DSM is booting and can be accessed by the IP address.

**Comment by AuxXxilium** [comment]
this is not a warning - only a message that you can't type any command in this interface after dsm is loading

**Comment by TineUser** [comment]
And I thought the network interface is meant...

**Comment by EliotFR44** [comment]
How to fix my problem : 

With the 104b, the bootloader will boot with 2 IP adress : 
![image](https://github.com/AuxXxilium/arc/assets/39886697/753bbb3e-1aec-4607-911e-72178c068390)

One for SynologyNAS and one for IDK what.
The IP display on the screen is the IDK what IP.

To fix it, a just rebuild the bootload and set my true MAC address on the advanced settings.

It works perfectly now 👍 

![image](https://github.com/AuxXxilium/arc/assets/39886697/c3b70cd3-d592-4ea0-a476-f333cdab337f)

**Comment by AuxXxilium** [comment]
the .104b should work without any problem. it's possible that you get a different ip shown in you boot screen if you use nonEFI/BIOS/Legacy Mode to boot.
