### ISSUE TITLE
Loader DSM 7.2  Driver Virtio ?

### ISSUE THREAD

**Issue by Odroid13** [AuxXxilium/arc#262]
Me again ^^
Ok, I redid several tests as it should.

VM: arc23.5.60 & DSM 7.2-64561
It is the compilation in 7.2 Beta that poses a problem with Proxmox driver VirTio (I cannot turn off the machine from Proxmox)
It's weird because with version 7.2 RC the Virtio drivers work

VM: arc23.5.60 & 7.1.1update 5
On DSM 7.1.1update 5 and loader 23.5.60 everything works fine on Proxmox. 👍 

Thanks :

**Comment by AuxXxilium** [comment]
which build of loader was your 7.2 rc? i went back to old modules from rc yesterday, so that should be included in .60.

**Comment by Odroid13** [comment]
> 7.2 has no ACPI support, so you can only use shutdown from inside dsm, for now.
> 
> it's not sure that we find a solution the next days.

Ok :(

I'll post my test results anyway.
-------------------------------------------

With Arc Loader 23.5.60.2

When I default to SeaBios.
Vm does not start

------------------------------------------
In UEFI OVMF
It works but no possibility to turn off the VM from Proxmox.

Video 1 : 

https://streamable.com/f56b51


Video 2 : 

https://streamable.com/x1fzkw
