### ISSUE TITLE
Cannot boot with 23.5.60

### ISSUE THREAD

**Issue by MaxenceCauderlier** [AuxXxilium/arc#263]
Hi here

Big thank for your awesome works.
However, since I can't install Arc with mod patch cause My HP Proliant Gen8 have no EFI with 2.5.55, I tried to install 23.5.60.
I saw you removed EFI condition to install arc mod, but with this new version my baremetal dont boot on the USB key.
No problem with earlier versions.
Any idea ?
Thanks

**Comment by AuxXxilium** [comment]
go back to old version

**Comment by haldi4803** [comment]
Seems to be fixed on v23.5.64
Updated from v.23.5.55 inside the Loader. No ModPatch.
Getting into config works.
![image](https://github.com/AuxXxilium/arc/assets/17104473/cd2be2d2-022d-4524-9840-58d228bdcf87)

Booting DSM also works. Gen8 with xpenology takes a WHILE to fully boot. But works fine.

![image](https://github.com/AuxXxilium/arc/assets/17104473/f72f8291-a483-4c6e-8a4a-a5b713985dde)
