### ISSUE TITLE
LSI 9211-8i not working with ESXI and 23.5.60

### ISSUE THREAD

**Issue by nikos1988** [AuxXxilium/arc#264]
**Describe the bug**
ESXi 8.0 VM with LSI HBA passed through. This is working fine with 23.5.55 and all attached disks are recognized.
With 23.5.60 it is not working anymore. No disks are recognized.

**Comment by AuxXxilium** [comment]
why a second bug report? it‘s already in state „working on“. look bugreports below. 

to fix this, you can try to deselect the scsi_tansport_sas module from modules.

**Comment by nikos1988** [comment]
Oh sorry, i thought that report was because of a bad PSU and he fixed it.

**Comment by AuxXxilium** [comment]
it's still open and not closed.

but you tell me, that the new modules worked for you before i went back to old one that worked for him. 


difficult thing.

**Comment by AuxXxilium** [comment]
can you please try latest version and report back?

**Comment by nikos1988** [comment]
Hi, nope not working with latest version. No HBA disks are recognized. Also upgrading the loader destroyed my local key vault for volume encryption.
I have a backup of the old loader and it is only a test VM but maybe that should be considered for future upgrades?

**Comment by nikos1988** [comment]
Also i am on DSM 7.2-64561 for testing full volume encryption

**Comment by AuxXxilium** [comment]
please try beta modules, you can add them in update menu - switch to beta modules.

**Comment by nikos1988** [comment]
- Upgrade the loader to 23.5.64.2
- reboot
- Choose model, ARC patch, MAC, etc... and did not build
- Update Menu -> Switch to Beta Modules (23.5.64.3)
- Build loader and boot
- Still no disks at LSI HBA :(

**Comment by TineUser** [comment]
And what is the solution?

**Comment by AuxXxilium** [comment]
wait for .104

**Comment by nikos1988** [comment]
It is still working for me with 23.5.55 and when i upgrade to 23.6.21e the LSI HBA disks are not found.

**Comment by nikos1988** [comment]
Nope, also not working with 23.6.21a.

**Comment by AuxXxilium** [comment]
than tell me please, how he got it working: https://github.com/AuxXxilium/arc/issues/293

scroll down please

**Comment by AuxXxilium** [comment]
for your information, the dell perc h200 is a lsi 2008

**Comment by nikos1988** [comment]
Nope, still not showing any disks attached to the LSI 2008. It is running IT-Firmware btw, not IR-Firmware.

**Comment by nikos1988** [comment]
What PCI ID is correct then? And why is it working with 23.5.55?

**Comment by AuxXxilium** [comment]
because there is no support for raid

**Comment by AuxXxilium** [comment]
I flashed my LSI 2008 to HBA mode today, it will work in 23.6.22

**Comment by nikos1988** [comment]
![grafik](https://github.com/AuxXxilium/arc/assets/1401772/361214f2-74fd-42a4-95d7-49369ee9c246)

**Comment by AuxXxilium** [comment]
try the .22 - my controller is working

**Comment by nikos1988** [comment]
Yes, it is working now :) Thank you!
