### ISSUE TITLE
diskhibernationfix on HP Gen8

### ISSUE THREAD

**Issue by haldi4803** [AuxXxilium/arc#267]
Hi,

i tried the diskhibernationfix (beta) but as soon as it boots DSM the connection gets lost.
Screenshot:
![HibernationFIX_network](https://github.com/AuxXxilium/arc/assets/17104473/ad44275a-009a-4afe-8697-b5d2ba72fb69)

You can see that it pings for a few seconds, as it displays IP, then connection gets lost.

System:
![image](https://github.com/AuxXxilium/arc/assets/17104473/4dc62fd6-8e24-482f-825e-40776e1cd9df)

root@arpl:/opt/arpl# lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 Processor Family DRAM Controller [8086:0108] (rev 09)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:0101] (rev 09)
00:06.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:010d] (rev 09)
00:1a.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 [8086:1c2d] (rev 05)
00:1c.0 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:1c10] (rev b5)
00:1c.4 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:1c18] (rev b5)
00:1c.6 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [8086:1c1c] (rev b5)
00:1c.7 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 8 [8086:1c1e] (rev b5)
00:1d.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 [8086:1c26] (rev 05)
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev a5)
00:1f.0 ISA bridge [0601]: Intel Corporation C204 Chipset LPC Controller [8086:1c54] (rev 05)
00:1f.2 RAID bus controller [0104]: Intel Corporation 6 Series/C200 Series Desktop SATA RAID Controller [8086:1c04] (rev 05)
01:00.0 System peripheral [0880]: Hewlett-Packard Company Integrated Lights-Out Standard Slave Instrumentation & System Support [103c:3306] (rev 05)
01:00.1 VGA compatible controller [0300]: Matrox Electronics Systems Ltd. MGA G200EH [102b:0533]
01:00.2 System peripheral [0880]: Hewlett-Packard Company Integrated Lights-Out Standard Management Processor Support and Messaging [103c:3307] (rev 05)
01:00.4 USB controller [0c03]: Hewlett-Packard Company Integrated Lights-Out Standard Virtual USB Controller [103c:3300] (rev 02)
02:00.0 Memory controller [0580]: Hewlett Packard Enterprise Device [1590:005f]
03:00.0 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe [14e4:165f]
03:00.1 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe [14e4:165f]
04:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller [1912:0014] (rev 03)
root@arpl:/opt/arpl#

root@arpl:/opt/arpl# lspci -nnk
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 Processor Family DRAM Controller [8086:0108] (rev 09)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:0101] (rev 09)
        Subsystem: Hewlett-Packard Company Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [103c:330b]
        Kernel driver in use: pcieport
00:06.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:010d] (rev 09)
        Subsystem: Hewlett-Packard Company Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [103c:330b]
        Kernel driver in use: pcieport
00:1a.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 [8086:1c2d] (rev 05)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family USB Enhanced Host Controller [103c:330d]
        Kernel driver in use: ehci-pci
00:1c.0 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:1c10] (rev b5)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [103c:330d]
        Kernel driver in use: pcieport
00:1c.4 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:1c18] (rev b5)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [103c:330d]
        Kernel driver in use: pcieport
00:1c.6 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [8086:1c1c] (rev b5)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [103c:330d]
        Kernel driver in use: pcieport
00:1c.7 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 8 [8086:1c1e] (rev b5)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family PCI Express Root Port 8 [103c:330d]
        Kernel driver in use: pcieport
00:1d.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 [8086:1c26] (rev 05)
        Subsystem: Hewlett-Packard Company 6 Series/C200 Series Chipset Family USB Enhanced Host Controller [103c:330d]
        Kernel driver in use: ehci-pci
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev a5)
        Subsystem: Hewlett-Packard Company 82801 PCI Bridge [103c:330d]
00:1f.0 ISA bridge [0601]: Intel Corporation C204 Chipset LPC Controller [8086:1c54] (rev 05)
00:1f.2 RAID bus controller [0104]: Intel Corporation 6 Series/C200 Series Desktop SATA RAID Controller [8086:1c04] (rev 05)
        Subsystem: Hewlett Packard Enterprise 6 Series/C200 Series Desktop SATA RAID Controller [1590:006c]
        Kernel driver in use: ahci
01:00.0 System peripheral [0880]: Hewlett-Packard Company Integrated Lights-Out Standard Slave Instrumentation & System Support [103c:3306] (rev 05)
        Subsystem: Hewlett-Packard Company iLO4 [103c:3381]
01:00.1 VGA compatible controller [0300]: Matrox Electronics Systems Ltd. MGA G200EH [102b:0533]
        Subsystem: Hewlett-Packard Company iLO4 [103c:3381]
01:00.2 System peripheral [0880]: Hewlett-Packard Company Integrated Lights-Out Standard Management Processor Support and Messaging [103c:3307] (rev 05)
        Subsystem: Hewlett-Packard Company iLO4 [103c:3381]
01:00.4 USB controller [0c03]: Hewlett-Packard Company Integrated Lights-Out Standard Virtual USB Controller [103c:3300] (rev 02)
        Subsystem: Hewlett-Packard Company iLO4 [103c:3381]
        Kernel driver in use: uhci_hcd
02:00.0 Memory controller [0580]: Hewlett Packard Enterprise Device [1590:005f]
        DeviceName: Memory Controller
        Subsystem: Hewlett Packard Enterprise Device [1590:005f]
03:00.0 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe [14e4:165f]
        DeviceName: NIC Port 1
        Subsystem: Hewlett-Packard Company NC332i Adapter [103c:2133]
        Kernel driver in use: tg3
        Kernel modules: tg3
03:00.1 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe [14e4:165f]
        DeviceName: NIC Port 2
        Subsystem: Hewlett-Packard Company NC332i Adapter [103c:2133]
        Kernel driver in use: tg3
        Kernel modules: tg3
04:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller [1912:0014] (rev 03)
        Subsystem: Hewlett-Packard Company uPD720201 USB 3.0 Host Controller [103c:1996]
        Kernel driver in use: xhci_hcd
root@arpl:/opt/arpl#

simply deactivating the addon and rebuilding the loader makes everything work fine again.

**Comment by AuxXxilium** [comment]
is possible, you selected it and it's marked as "beta". so no need for bugreport, please. it's far away from final, and on your system the disk hibernation is working without this.

**Comment by haldi4803** [comment]
Uhm.... this MIGHT Not be diskhibernationfix related.... activating the "CPUinfo" addon resulted in the same behaviour.

**Comment by AuxXxilium** [comment]
all non beta addons are stable and used over months.
