### ISSUE TITLE
Can't boot after upgrade to 23.5.102

### ISSUE THREAD

**Issue by ciddikedi** [AuxXxilium/arc#274]
![image](https://github.com/AuxXxilium/arc/assets/44272243/65508b3b-59ad-42e6-bc9d-8a04823bc527)
![image](https://github.com/AuxXxilium/arc/assets/44272243/c026e281-90dd-43e7-be63-509e7c75be93)

The problem started after upgrading from version 23.5.55

**Comment by AuxXxilium** [comment]
try .100a and report back
