### ISSUE TITLE
The modules for dvb do not seem to work correctly

### ISSUE THREAD

**Issue by cvc90** [AuxXxilium/arc#275]
Hi!, I have two USB tuners, which are compatible with Tvheadend, but I can't load them in the system, to share them through Docker, but I can see them through lsusb.

My System info
-----------------
![image](https://github.com/AuxXxilium/arc/assets/76731844/b93966a0-8481-4675-86e1-12fb2c187b83)

Sample photo of lsusb output
--------------------
![image](https://user-images.githubusercontent.com/76731844/206602181-1830df0f-6887-481b-b997-a5aaf2c61fa0.png)

Tried putting your firmware in /lib/firmware, but I don't see it loading.

The devices are

- [Dvbsky s960 v2](https://www.linuxtv.org/wiki/index.php/DVBSKY_S960) --> [Download firmware](http://dvbsky.net/download/linux/firmware.zip)
- [Sony PlayTV](https://linuxtv.org/wiki/index.php/Sony_PlayTV_dual_tuner_DVB-T) --> [Download firmware](http://www.wi-bw.tfh-wildau.de/~pboettch/home/files/dvb-usb-dib0700-1.20.fw)

The modules for dvb do not seem to work correctly, I see that the dmesg command marks the following errors and it still isn't linked to a device in /dev/dvb*, all this has been tested in the latest version of Arc and all the modules and addons have also been updated.

dvb_usb_dib0700: Unknown symbol dib0090_get_tune_state (err 0)
dvb_usb_dib0700: Unknown symbol dib7000m_get_i2c_master (err 0)
dvb_usb_dib0700: Unknown symbol dib0070_ctrl_agc_filter (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_set_tune_state (err 0)
dvb_usb_dib0700: Unknown symbol dvb_usb_get_hexline (err 0)
dvb_usb_dib0700: Unknown symbol rc_repeat (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_set_dc_servo (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_set_i2c_adapter (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_pwm_gain_reset (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_fw_pid_filter_ctrl (err 0)
dvb_usb_dib0700: Unknown symbol dib7000m_pid_filter (err 0)
dvb_usb_dib0700: Unknown symbol dib3000mc_i2c_enumeration (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_fw_set_component_bus_speed (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_get_tuner_interface (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_get_component_bus_interface (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_fw_pid_filter (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_get_current_gain (err 0)
dvb_usb_dib0700: Unknown symbol rc_keydown (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_firmware_post_pll_init (err 0)
dvb_usb_dib0700: Unknown symbol dib3000mc_get_tuner_i2c_master (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_dcc_freq (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_i2c_enumeration (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_set_slave_frontend (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_get_wbd_target (err 0)
dvb_usb_dib0700: Unknown symbol dib0070_wbd_offset (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_set_gpio (err 0)
dvb_usb_dib0700: Unknown symbol dvb_usb_device_init (err 0)
dvb_usb_dib0700: Unknown symbol dib0090_gain_control (err 0)
dvb_usb_dib0700: Unknown symbol dvb_usb_device_exit (err 0)
dvb_usb_dib0700: Unknown symbol dibx000_i2c_set_speed (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_get_slave_frontend (err 0)
dvb_usb_dib0700: Unknown symbol dib9000_get_i2c_master (err 0)
dvb_usb_dib0700: Unknown symbol dib7000m_pid_filter_ctrl (err 0)
dvb_usb_dvbsky: Unknown symbol m88ds3103_get_agc_pwm (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_reset_resume (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_suspend (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_disconnect (err 0)
dvb_usb_dvbsky: Unknown symbol rc_keydown (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_probe (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_generic_rw_locked (err 0)
dvb_usb_dvbsky: Unknown symbol dvb_usbv2_resume (err 0)
dvb_usb_v2: Unknown symbol rc_register_device (err 0)
dvb_usb_v2: Unknown symbol rc_free_device (err 0)
dvb_usb_v2: Unknown symbol rc_allocate_device (err 0)
dvb_usb_v2: Unknown symbol rc_unregister_device (err 0)

UPDATE 3: Performing the insmod command on most of the dvb modules, shows an error of "Unknown symbol in module", except dvb-core, these errors indicate that there is an error in the compiled modules, Could you update the module or recompile it?

**Comment by AuxXxilium** [comment]
possible but without any information, i can't to anything. read guidline for bugreport!

**Comment by AuxXxilium** [comment]
which version of DSM is selected? Which version of arc do you use .... and so on!

**Comment by AuxXxilium** [comment]
and another question:

```
DSM

USB devices (Wi-Fi dongle, Bluetooth dongle, 3G/4G dongle, USB DAC/speaker, and DTV dongle) are no longer supported. If your Synology NAS is currently connected via a wireless dongle, it will be disconnected after the update.
```

do you have read releasenotes from DSM? If we get them work, it will be luck.

**Comment by cvc90** [comment]
I have updated the main post with the requested information.

**Comment by AuxXxilium** [comment]
use 7.1.1 for now and remove unused/unneeded addons! never select ALL!

**Comment by cvc90** [comment]
Well, I will continue in 7.2.0 waiting for the possible solution and what you tell me about all the modules I have to do tests, usually only the necessary modules are selected.

**Comment by AuxXxilium** [comment]
you need more modules than you will see on the first look. much of them are related to each other. so best you select all modules.

**Comment by cvc90** [comment]
With the "all modules" option it still shows the same errors.

**Comment by AuxXxilium** [comment]
it's possible yes, syno dropped usb support, the quote is from syno release notes. so don't know if we can fix this or add this back.

**Comment by cvc90** [comment]
In case it helps you, this was added by @fbelavenuto( fbelavenuto/arpl-modules#125 ) at my request, but he doesn't have time now and he abandoned his ARPL project

**Comment by AuxXxilium** [comment]
no it doesn't because the modules are based on latest source.

**Comment by AuxXxilium** [comment]
do you have tried to update your firmware on these sticks?
