### ISSUE TITLE
as of version arc-23.5.100a does not recognize sas disks

### ISSUE THREAD

**Issue by diegomtnz** [AuxXxilium/arc#277]
Hello, thanks for the work.
In the arc-23.5.100a version, the sas controller recognizes me perfectly in TI mode, in later versions it does not recognize the sas disks

**Comment by AuxXxilium** [comment]
so you say, 100a was working. later don't?

**Comment by AuxXxilium** [comment]
wait for .104

**Comment by AuxXxilium** [comment]
would be nice, if you can check .104
