### ISSUE TITLE
Changing mac2 address does not change in DSM

### ISSUE THREAD

**Issue by viettq7a2** [AuxXxilium/arc#281]
I have change mac2 address in user-config, save and then reboot but in DSM - Info Center, the mac2 address is still the same, please fix it

**Comment by AuxXxilium** [comment]
if you use a system without EFI boot, we can't fix mac atm. if you use an EFI system, everything is fine. more information would be fine.

**Comment by viettq7a2** [comment]
So you mean that the mac2 I changed in user-config is actually working, although in the Info Center show the different one. And the system I used is EFI.

**Comment by AuxXxilium** [comment]
yes. other question, why do you need to change second mac?

**Comment by viettq7a2** [comment]
I change because I found real mac/sn, mac1 show exactly like in user-config, but not for mac2, I just want to know it works or not, thank you for your reply

**Comment by AuxXxilium** [comment]
you don't need. use arc patch while selection and everything is fine. no need to change something.

**Comment by AuxXxilium** [comment]
we only need the mac1 ;)
