### ISSUE TITLE
Kein Legacy Boot?

### ISSUE THREAD

**Issue by blackhawk1977** [AuxXxilium/arc#282]
Unterstützt der Arc Loader kein Legacy Boot? UEFI funktioniert, aber mein HP ProLiant Microserver Gen8 hat kein UEFI

**Comment by AuxXxilium** [comment]
Unterstützt er und funktioniert auch. Microserver sind ein Sonderfall, genau wegen diesen Geräten ist der Directboot drin. Bei manchen läuft es ohne Directboot, bei manchen musst du den Directboot an schalten.

**Comment by blackhawk1977** [comment]
Wo muss ich Directboot einschalten? Im BIOS?

**Comment by AuxXxilium** [comment]
im arc loder in der advanced section. steht auch alles hier im wiki.

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Direct-Boot-Option

**Comment by blackhawk1977** [comment]
Ja das habe ich gelesen, aber das Image startet gar nicht vom Stick. Auch nicht die configuration. USB Boot wird übersprungen und stattdessen PXE Boot versucht. Am Stick wird es nicht liegen, da ARPL schon vom Stick bootet

**Comment by AuxXxilium** [comment]
Welche Version nutzt du denn?

**Comment by blackhawk1977** [comment]
104b

**Comment by AuxXxilium** [comment]
die geht definiv, habe ich auch im Legacy mode im Einsatz.

**Comment by AuxXxilium** [comment]
Habe es gerade nochmal getestet. Stick im Legacy Mode läuft ohne Probleme. Bitte flash mal den Stick neu.

**Comment by blackhawk1977** [comment]
Ich versuche das bereits seit gestern Abend. 5 verschiedene Sticks, mit Rufus und Etcher versucht. Etliche male neu geflasht. ARPL image funktioniert jedes mal im Microserver, ARC image überspringt den USB Boot und landet bei PXE Boot. Am Dell Notebook funktioniert der Stick mit dem ARC Image im UEFI Mode, da komme ich ganz normal in die config. An der Microserver Boot config kann es ja normal auch nicht liegen, dass GRUB nicht gestartet wird, oder? Dann dürfte ARPL ja auch nicht starten, richtig? Oder hab ich da einen Denkfehler?

**Comment by AuxXxilium** [comment]
Wir nutzen eine neuere GRUB Version. Kann eigentlich nur Bios liegen. Da andere mit Microserver es ja auch ohne Probleme nutzen. Hatte gestern Abend erst einen im Chat. Schau mal im Bios ob der Stick als Bootdevice drin steht und ausgewählt ist.

**Comment by blackhawk1977** [comment]
Im BIOS tauchen die Sticks nicht einzeln auf, nur generell USB KeyDrive. Welche Grub Version benutzt ihr? ARPL nutzt GRUB 2.06, welche Problemlos startet. Habe es eben auch noch mal mit einer MicroSD Card probiert, aber da ist es genau so wie bei USB Sticks. ARPL startet grub, ich kann konfigurieren und DSM starten, bei ARC wird das booten direkt ignoriert. 

Hatten die anderen, bei denen es läuft, auch den Microserver Gen8?

**Comment by AuxXxilium** [comment]
ja Gen8 und auch Gen7 sind dabei.

**Comment by blackhawk1977** [comment]
Ich habe es nun hinbekommen, allerdings über Umwege. Die Versin 23.4.0 bootet bei mir, so das ich wenigstens bis zur config komme und dort habe ich dann über update menu auf die aktuelle geupdatet, welche dann auch startet. Aber alle neuen bis hin zu 23.5.100a habe ich versucht, alle booten bei mir nicht.

**Comment by AuxXxilium** [comment]
die 60er booten mit legacy nicht, ab .100 muss es wieder gehen.

**Comment by AuxXxilium** [comment]
![image](https://github.com/AuxXxilium/arc/assets/67025065/7f5b0108-eca8-450e-aeae-579add154027)

legacy boot mit .104 aber schon auf dem weg zur .105

**Comment by blackhawk1977** [comment]
Ja ich weiß das es im Grunde funktioniert. Auf meinem gen8 aber eben nicht. Die 23.4.0 hat funktioniert und ich konnte darüber ein online Update auf 23.5.104b machen. Somit läuft nun alles 🙂👍

**Comment by AuxXxilium** [comment]
wundert mich trotzdem sehr, weil das laufen muss, habe es auch auf einem HP DL360 gen9 mit deaktivierten UEFI getestet. Lief auch. :/

**Comment by nemesis122** [comment]
bei mir laufen alle loader auf den gen8 ohne probleme
ARC THE BEST
ARPL
MSHELL
TINYCORE
und alle dsm 6 loaders

**Comment by AuxXxilium** [comment]
Brauchst den hpsa für deine HP Server? Muss das Modul als optional setzen weil es die LSI Controller zerlegt.
