### ISSUE TITLE
Can't Create nvme volume on Synology High avaibility 

### ISSUE THREAD

**Issue by delta-whiplash** [AuxXxilium/arc#2830]
**Is your Feature request related to a Problem? Please describe.**
I have 2 mini PC with 1 nvme drive each 
I want to use synology HA on them

As I have only one disk on each one I used the SA6400 to let arc install synology on my nvme drive
I successfully setuped the High avaibillity but I could not create a volume I have this error : 

![image](https://github.com/user-attachments/assets/dbc99417-1dea-4bf9-9b73-141fcf5e93e4)
![image](https://github.com/user-attachments/assets/00b63076-08aa-46ff-ad61-892cc324f584)

What could I do ?

**Comment by AuxXxilium** [comment]
nothing. mnvme only isn't supported by syno and it was a little wonder to find a way to use it for SA6400.

**Comment by delta-whiplash** [comment]
🥲
