### ISSUE TITLE
I have two network cards and DSM only loads one of them

### ISSUE THREAD

**Issue by cvc90** [AuxXxilium/arc#287]
Hi, I have two network cards and DSM only loads one of them. When it loads "ARC" it seems to load correctly and both have IPs correctly, but once the system loads only one interface (eth0) is available, the second interface does not seem to be available (eth1).

In the configuration and edited the MACS of these two devices and in previous versions everything worked correctly.

My System info
-----------------
![image](https://github.com/AuxXxilium/arc/assets/76731844/b93966a0-8481-4675-86e1-12fb2c187b83)

**Comment by AuxXxilium** [comment]
please don't spam report!
