### ISSUE TITLE
Reboot script

### ISSUE THREAD

**Issue by ITNetSystem** [AuxXxilium/arc#289]
I add a reboot addon during assembly, but the task does not appear in the DSM scheduler. The powersched addon also does not work
![image](https://github.com/AuxXxilium/arc/assets/135026873/25b3332b-56b7-400a-8efa-f4dcacdc5734)

**Comment by ITNetSystem** [comment]
> how does you find out that powersched doesn't work?

When the powerscheduler addon is enabled, a warning appears in the DSM that the planned shutdown task could not be completed. In principle, I do not use this, because I have a 24/7 DSM, just when I was on the apl loader, there was no such message. I am more interested in the reboot script, which does not appear in the scheduler.

**Comment by AuxXxilium** [comment]
first: you can call reboot on your own or build a task: "/usr/bin/arc-reboot.sh config" is the command

second: yes it's possible, arpl was not supporting 7.2 and there are so many changes around. and for your information: it's 1:1 the same script like in arpl was.

**Comment by ITNetSystem** [comment]
1. Yes, I know that I can create a task myself, I just wanted to let you know that the task is not created automatically.
2. Very strange, there was the same message on the first arpl releases, but then it disappeared.

**Comment by AuxXxilium** [comment]
1. thanks
2. it's 100% same code as latest arpl
