### ISSUE TITLE
23.6.0

### ISSUE THREAD

**Issue by ITNetSystem** [AuxXxilium/arc#296]
The storage manager amd san manger from DSM is missing

**Comment by ITNetSystem** [comment]
![image](https://github.com/AuxXxilium/arc/assets/135026873/7032a80f-3744-48ca-9155-0480152a6396)

**Comment by ITNetSystem** [comment]
![image](https://github.com/AuxXxilium/arc/assets/135026873/f79e2891-a323-4aca-ae8f-06cb56eebf84)

**Comment by AuxXxilium** [comment]
Guy, are you kidding me? We can't change anything in dsm. so you have an issue in your installation. while install dsm you download the original image from syno. so there is no change in system.

**Comment by AuxXxilium** [comment]
It's a problem with your system. Because it's working on all other.

**Comment by AuxXxilium** [comment]
wait for 23.6.1 and everything should be fine.
