### ISSUE TITLE
Support for XCP-ng 8.2.1

### ISSUE THREAD

**Issue by al-indigo** [AuxXxilium/arc#2989]
I know that Arc works good in KVM/qemu environments, but there a lot of situations when only Xen / XCP-ng is available.

I have tried Arc 24.08.11 on XCP-ng 8.2.1 and Arc itself loads and allows to build bootloader without a problem in UEFI mode. It allows to update itself too.

In the config mode it indicates that the only compatible version is SA6400 / epyc7002 and allows to customize everything as usual.

But after loader installation the system turn off almost instantly when I try to boot in DSM mode. After the last screenshot the system shuts down in several seconds (I suppose kernel panic)

Can you support XCP-ng as virtualization platform?

![image](https://github.com/user-attachments/assets/c6df10e6-fb0f-45c3-9de4-ff08682dffa6)

![image](https://github.com/user-attachments/assets/a6c233a9-8447-49ba-a582-a94da2cf11cd)

![image](https://github.com/user-attachments/assets/60331036-f015-4392-bbe2-52be0bf71ea5)

**Comment by AuxXxilium** [comment]
simply no, it's xen based.ö
