### ISSUE TITLE
RS4021xs+ on Proxmox Volume Encryption (unlock fails)

### ISSUE THREAD

**Issue by nikos1988** [AuxXxilium/arc#300]
Just tried version 23.6.2 on Proxmox with 2 virtual disks and tried to create an encrypted volume.
It looks like the volume ist created but it fails to unlock.

desmg -T shows:
[Fri Jun  2 15:09:02 2023] device-mapper: table: 249:3: crypt: Error allocating crypto tfm
[Fri Jun  2 15:09:02 2023] device-mapper: ioctl: error adding target to table

Looks like the kernel is missing the right crypto configuration?!

**Comment by AuxXxilium** [comment]
Please provide serial log from Proxmox. Without this, it is not possible to find the issue. With ESXi everything is working, so i can't fix it without your logfile.

**Comment by nikos1988** [comment]
My ESXi VM with 23.5.55 is working fine with encrypted volumes. Could it be CPU features? I tried KVM64 and host CPU (i5-12500)

**Comment by AuxXxilium** [comment]
I use it on baremetal 12500, let me try and look into log file.

**Comment by AuxXxilium** [comment]
your log file is nearly empty.

**Comment by nikos1988** [comment]
scroll down a bit. it is the complete startup log

**Comment by nikos1988** [comment]
when i try to unlock the volume only this pops up in the serial log:

[  749.533422] device-mapper: table: 249:3: crypt: Error allocating crypto tfm
[  749.534024] device-mapper: ioctl: error adding target to table

**Comment by AuxXxilium** [comment]
i need complete log incl. bootlog

**Comment by nikos1988** [comment]
<img width="724" alt="pve" src="https://github.com/AuxXxilium/arc/assets/1401772/96c6861e-cf96-4631-b8c9-3f4170ef985c">

**Comment by AuxXxilium** [comment]
have you tried to add the disks to a sata controller and not scsi?

**Comment by nikos1988** [comment]
I tried with the real ssd disk on the passed ASM1166 controller card and it does not work too.

**Comment by AuxXxilium** [comment]
i need some time, to find the issue.

**Comment by nikos1988** [comment]
Is your ESXI VM with loader 23.6.2 and encrypted volumes working fine?

**Comment by AuxXxilium** [comment]
i don't know, i'm looking thru all files because of build issue in github. have to check more things atm.

**Comment by nikos1988** [comment]
I just compared /proc/crypto between my ESXI and Proxmox VM. The Proxmox VM has a lot less supported crypto algorithms
[crypto_esxi.txt](https://github.com/AuxXxilium/arc/files/11636087/crypto_esxi.txt)
[crypto_pve.txt](https://github.com/AuxXxilium/arc/files/11636089/crypto_pve.txt)

**Comment by AuxXxilium** [comment]
so it's possible that this issue is proxmox related

**Comment by AuxXxilium** [comment]
Please try with 23.6.21

**Comment by nikos1988** [comment]
Hi, i can confirm it works now with 23.6.21e. But only after completely resetting and reinstalling DSM. The DSM installation with the previous loader 23.6.2 was corrupted. Not even resetting the local encryption vault helped.
