### ISSUE TITLE
Hyper-v doesn't work

### ISSUE THREAD

**Issue by martsaez04** [AuxXxilium/arc#3021]
Hi,

thanks a lot for your time to this project!

I'm testing the new [24.8.dev] in a hyper-v but unfortunately, it doesn't works, the system remains frozen as there:

![arc](https://github.com/user-attachments/assets/215db838-4c66-4f19-b0ec-c25f543edb11)

**Comment by AuxXxilium** [comment]
and? it's still in testing and not all configurations are working.

**Comment by martsaez04** [comment]
Sorry AuxXxilium, I just want to help :-)

Thanks a lot for your patience
