### ISSUE TITLE
all Loader bigger as 23.5.53 in virtual envirormetns like VMware Workstation / VMM /virtualbox the maschine will crash

### ISSUE THREAD

**Issue by nemesis122** [AuxXxilium/arc#308]
Hi Auxxxilium 
all Loader bigger as 23.5.53 in virtual envirormens like VMware Workstation / VMM /virtualbox the maschine will crash.
Steps to reproduce doing en install any modell tested with 3622 / 920+ DSM Version 7.1.42962 in virtual envoriments 
create the loader with ARC Patch without etc/ 
the issue is happen with uefi and MBR / without addons / with Addons 
first boot configure the loader all is fine 
[VBox.log](https://github.com/AuxXxilium/arc/files/11643084/VBox.log)
[VBoxHardening.log](https://github.com/AuxXxilium/arc/files/11643085/VBoxHardening.log)
[vmware.log](https://github.com/AuxXxilium/arc/files/11643086/vmware.log)
[vmware-0.log](https://github.com/AuxXxilium/arc/files/11643087/vmware-0.log)

and by the Second boot when DSM is installed the virtual Maschine  is going off and in the log stays the virtual Maschine is destoyed.

________________________________

with the loader 23.5.53 the Loader is working

**Comment by AuxXxilium** [comment]
No and no. Everything is working. Use latest version! .100b was also stable. Exchange you bootimage and do not use inplace upgrade.

**Comment by AuxXxilium** [comment]
Look issue report from yesterday, Proxmox is working (but has no crypto support - Proxmox issue) and he rechecked ESXi for crypto support that is working. If you look in my last Livestream in Youtube you will see that ESXi is working here, too.
