### ISSUE TITLE
qemu-qa

### ISSUE THREAD

**Issue by frezeen** [AuxXxilium/arc#309]
enabled qemu-qa addon but proxmox dont find qemu agent running in DSM VM.

VM setting:
q35
cpu: host

![image](https://github.com/AuxXxilium/arc/assets/38480611/77ba8f11-48d3-4643-82ed-5486ad91467f)

i think we miss virtio-serial module

**Comment by AuxXxilium** [comment]
possible, is still beta state and ported from: https://github.com/jim3ma/arpl-addons

so try a report to jim.
