### ISSUE TITLE
Can't get the IP when installing Arcloader.

### ISSUE THREAD

**Issue by zico82a** [AuxXxilium/arc#3120]
Hi,

I tried to install ARCLoader under Proxmox.  However,  the automated config process was terminated due to the NIC cannot get the  IP address from DHCP server then the IP was set to 169.254.20.153.  The Arcloader was running in offline mode in this case and the installation process cannot go further.   Below are the software and hardware details for my envirnoment.   Could you please shed some light on how to go thru the issue.  

Hardware: X86 machine with Intel E1230V2 CPU and Intel X710 NIC
OS : Windows Server 2019
VM: The PROXMOX is run under Hyper-V in the server and PROXMOX is able to get the IP from the DHCP server normallly.  
  
![ScreenHunter_1](https://github.com/user-attachments/assets/34dcd851-9418-4095-a8fb-457f59ab559d)

**Comment by AuxXxilium** [comment]
running proxmox in hypervisor will fail everytime, i never found a way to get an ip inside a proxmox vm while proxmox is installed in an hypervisor.
