### ISSUE TITLE
Loader cannot get IP after building

### ISSUE THREAD

**Issue by mekler22** [AuxXxilium/arc#3138]
**Describe the Bug**
I've built the loader properly, but when I ping the machine, I get my own PC ip with "destination host unreachable"

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![image](https://github.com/user-attachments/assets/0e9bfd97-8acc-42fe-b9c6-db3818a14172)

A9BJYTHNA

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
Vendor: Asrock/Z370 Gaming-ITX/ac, BIOS L4.31B 04/01/2021
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Memory: 31GB

**Comment by mekler22** [comment]
Also, Tried setting static IP. Same result.

**Comment by AuxXxilium** [comment]
switch to non -next version, if this will not work, check bios setting -> wiki.

**Comment by mekler22** [comment]
> switch to non -next version, if this will not work, check bios setting -> wiki.

I will try that. However, I should mention that I have been running RR loader version 24.7.0 successfully (I keep it on a separate USB stick, and was able to revert to it). But any RR version past that fails the same. With same Bios settings. The loader (both RR and ARC) seems to boot fine at first, gets a IP address, and continues to DSM. But then the machine becomes un-pingable. I cannot check any log or display output as with this Asrock motherboard, even with HDMI connected, it won't show anything.

**Comment by mekler22** [comment]
Using the non -next version helped. I managed to boot into DSM. Thanks.
