### ISSUE TITLE
quickconnect The serial number of your product is invalid.

### ISSUE THREAD

**Issue by MaCeLMp4** [AuxXxilium/arc#3174]
**Describe the Bug**
The serial number of your product is invalid. 

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![Screenshot 2024-08-25 182121](https://github.com/user-attachments/assets/684919c9-38c2-4ec0-bcff-e3061bfbbe20)

**Comment by AuxXxilium** [comment]
and? read wiki and find your issue
