### ISSUE TITLE
DVA1622 Disk Full .pma

### ISSUE THREAD

**Issue by sumonchai** [AuxXxilium/arc#3194]
DVA1622 Disk Full .pma

Schedule 
find /volume1/@appstore/SurveillanceStation/local_display/.config/chromium-local-display/BrowserMetrics/ -name "*.pma" -delete

**Additional Context**
Link How o delete
(https://community.synology.com/enu/forum/1/post/123385)

 Can add to addon for DVA16XX  ?
 Thank you.

**Comment by AuxXxilium** [comment]
disable local display will fix this issue. know bug in dsm.
