### ISSUE TITLE
Update Mode halts if custom mac is defined

### ISSUE THREAD

**Issue by Ubsefor** [AuxXxilium/arc#3195]
**Describe the Bug**
Reboot to "Update mode" does not proceed with rebuilding loader, if custom MAC address was defined previously; it awaits custom MAC address input in automated rebuild mode

**Screenshots**
<img width="1283" alt="Safari 2024-08-27 13 10 29" src="https://github.com/user-attachments/assets/9869734c-afe8-4b54-85ad-74347c94a234">
<img width="1283" alt="Safari 2024-08-27 13 11 58" src="https://github.com/user-attachments/assets/84766235-6853-4db6-9b1b-fbcd0cb6085f">
<img width="1283" alt="Safari 2024-08-27 13 13 33" src="https://github.com/user-attachments/assets/8411a717-67b3-4a17-852f-449983018659">
<img width="1283" alt="Untitled (20)" src="https://github.com/user-attachments/assets/df47bf23-fbfc-4f8e-9f56-c816c278e2b7">

NOTE: It gets MAC address from the network card (virtual in my case) by default.

**Hardware**
VMware ESXi 8.0 Update 3, Virtual USB UEFI Boot, 8GB RAM, 4 vCPU cores

**Comment by AuxXxilium** [comment]
fixed in next release
