### ISSUE TITLE
USB mobile hard disk is identified as local disk by mistake

### ISSUE THREAD

**Issue by amilys** [AuxXxilium/arc#3196]
**Describe the Bug**
arc 24.08.26

24.08.26 In this version, the boot process will mount an external USB mobile hard drive as a SCSI hard disk, resulting in one additional local disk in Synology.
If you create a storage pool with this mobile hard drive, an error alert will appear indicating that the partition in the storage pool is corrupted after the next reboot. This is because partitions are destroyed when they are booted and mounted during system restarts

**Hardware**
DS918+ minisfrom U820

**Comment by amilys** [comment]
![image](https://github.com/user-attachments/assets/a0903191-f674-4c13-b938-a42fd67920c9)

**Comment by AuxXxilium** [comment]
nothing wrong, read wiki

**Comment by amilys** [comment]
Thank you, I have seen it
 https://auxxxilium.tech/wiki/arc-loader-arc-loader/optionen/
