### ISSUE TITLE
"This interface will not be operational." and DSM not reachable

### ISSUE THREAD

**Issue by tobi1449** [AuxXxilium/arc#320]
**Describe the bug**
I'm trying to move an existing DSM 7.0 installation running under proxmox from the original arpl to arc. 
I've replaced the loader drive and rebuilt the image, but when I try to start DSM, it finds the eth0 device, prints the correct IP and finishes with "This interface will not be operational.".
DSM itself is also not reachable, I can't even ping the IP.
**Screenshots**
![grafik](https://github.com/AuxXxilium/arc/assets/1286524/8705deaa-80fb-4fd2-af11-98db55312f6c)
![grafik](https://github.com/AuxXxilium/arc/assets/1286524/2c03ba10-6860-415e-badc-14575e9c67f4)

**Additional context**
The network adapter is a RTL8125B, I've tried passing it as Intel E1000 (this worked with arpl before) and Virtio device.
The Cmdline arguments are identical (with the exception of "withefi" or "noefi" depending on whether I activate UEFI or not).

**Comment by AuxXxilium** [comment]
Try it without selecting all addons. i bet you don't know what you have done.

**Comment by tobi1449** [comment]
> i bet you don't know what you have done

Safe bet. Still, neither only selecting acpid and cpuinfo (those are also selected for my working arpl loader) nor deselecting all addons changes anything.

**Comment by AuxXxilium** [comment]
use only stock addons and set your vm like: 

https://forums.unraid.net/topic/125203-guide-install-dsm-71-on-unraid-6103-2022/

replace tcrp/tinycore with arc
