### ISSUE TITLE
Can't install fresh 7.2.2 with DS918+ model, others models work - ARC 24.08.27

### ISSUE THREAD

**Issue by oswaldinimtb** [AuxXxilium/arc#3209]
Can't install fresh DSM 7.2.2 with real SN/MAC with DS918+ model. My test VM kept getting stuck on 56% with error "Failed to install the file. the file is probably corrupted (13)". VM just shuts down.

There is no problem when I install 7.2.2 on a DS920+ or ​​DVA1622 model. After installation, I can change the model to DS918+.
 
**Hardware**
Proxmox 8.2.4 | i3-8100 | 16GB RAM | 2x250GB SSD

**Comment by AuxXxilium** [comment]
already fixed in next version
