### ISSUE TITLE
Can’t build current loader 918+

### ISSUE THREAD

**Issue by 5olu7ion** [AuxXxilium/arc#321]
**Describe the bug**
After clicking on build the loader, the image can’t be downloaded from Synology upstream.
arc: build 23.6.31a
Synology Target: 7.2-64561 (Not 100% sure, maybe it was 7.2-64570, I can verify tomorrow)

**Screenshots**
First line says: Cleaning Cache
![IMG_0509](https://github.com/AuxXxilium/arc/assets/113297102/4ff5020b-3cb7-4b9f-a579-f74711f9d931)

**Comment by AuxXxilium** [comment]
you try to build an old version, syno removed these files, so it's not possible anymore. you have to reselect the model and version for build.
