### ISSUE TITLE
23.6.31b (7.2 does not work and 7.1.1 does work)

### ISSUE THREAD

**Issue by diegomtnz** [AuxXxilium/arc#323]
I suppose you know that in the last loader 7.2 still doesn't work, but 7.1.1 does work, I leave a video for people to see:

https://youtu.be/95950c5tv3Q

I leave you DSM_DS920+_64561.pat and DSM_RS4021xs+_64561.pat
in case you can include them in the loader to patch them instead of downloading them from synology, since I downloaded them in case they were worth it to install it without downloading

**Comment by AuxXxilium** [comment]
https://forums.unraid.net/topic/125203-guide-install-dsm-71-on-unraid-6103-2022/

use this settings for your vm

**Comment by diegomtnz** [comment]
I leave you DSM_DS920+_64561.pat and DSM_RS4021xs+_64561.pat
in case you can include them in the loader to patch them instead of downloading them from synology, since I downloaded them in case they were worth it to install it without downloading

http://diegovlc.com:5000/sharing/8WyHFlDH9
http://diegovlc.com:5000/sharing/nJJPd5PYk

**Comment by AuxXxilium** [comment]
we need the files from syno because of hash values. any other will not work and 64561 isn't supported anymore.

**Comment by diegomtnz** [comment]
> https://forums.unraid.net/topic/125203-guide-install-dsm-71-on-unraid-6103-2022/
> 
> use this settings for your vm and replace tcrp with arc.
> 
> in your video, you try to load an old dsm 7.2 that is removed from syno.



> we need the files from syno because of hash values. any other will not work and 64561 isn't supported anymore.

ok

**Comment by AuxXxilium** [comment]
correct, because syno replaced 64561 with 64570. it's the first time they do this move. this should be an update but they made a new version and replaced the old.

**Comment by diegomtnz** [comment]
Well, it will be a matter of waiting to update.
anyway thanks for the work

**Comment by AuxXxilium** [comment]
the new link is still in 23.6.31a/b

**Comment by diegomtnz** [comment]
> 

I have updated the loader from the same loader and I have been able to install the new version, I am recording a video, when I finish I will upload it

**Comment by diegomtnz** [comment]
dsm 7.2-64570 work fine
![DSM](https://github.com/AuxXxilium/arc/assets/15325404/de39176d-2c4a-4815-96cd-9b932795bfc2)

https://youtu.be/KjXY-SFuhdY

**Comment by diegomtnz** [comment]
when I have time I will do a tutorial on how I install it in proxmox without usb

**Comment by AuxXxilium** [comment]
Sounds good, because i have no Proxmox here and can't delete one of my ESXi servers to install proxmox.

if you want, you can share the link to your tutorial and i can add this to my wiki.

**Comment by diegomtnz** [comment]
> Sounds good, because i have no Proxmox here and can't delete one of my ESXi servers to install proxmox.
> 
> if you want, you can share the link to your tutorial and i can add this to my wiki.

Well, I still have to do the tutorial, I'll record it on video and pass it on to you, it's very easy, but I had to do a lot of tests before, hehehe

**Comment by diegomtnz** [comment]
> > 
> 
> I have updated the loader from the same loader and I have been able to install the new version, I am recording a video, when I finish I will upload it

Video ARC loader PROXMOX without USB:
https://www.youtube.com/watch?v=BVwKy9zXgQg

It is hidden from youtube, it can only be seen with the link.
Exclusively for your github
Any help or contribution to your channel, I will be delighted.
thanks for the work

**Comment by AuxXxilium** [comment]
Thank you, i will add it to Wiki Section for Proxmox
