### ISSUE TITLE
Can't sign in to NAS by QC on DS920+ and DVA1622 with DSM 7.2.2. But Sync with Photo, Driver client by QC... is working normally. In DS920+ - my own MAC. Please help!

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#3285]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
Can't sign in to NAS by QC on DS920+ and DVA1622 with DSM 7.2.2. But Sync with Photo, Driver client by QC... is working normally. In DS920+ - my own MAC. Please help!
**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![Screenshot 2024-09-04 210930](https://github.com/user-attachments/assets/f974999d-d8c9-4d7d-aa20-66156273e6e9)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
issue on your side, can't help

**Comment by TTTnas** [comment]
I have 2 same DS920+. On DS920+ with DSM 7.2.1 QC is working normally. On DS920+ with DSM 7.2.2 arc 24.09.01 - can't connect to QC by web. On DVA1622 with DSM 7.2.2 arc 24.09.01 - the same problem!!!
Issue is not on my Side!
