### ISSUE TITLE
I have 2 same DS920+. On DS920+ with DSM 7.2.1 QC is working normally. On DS920+ with DSM 7.2.2 arc 24.09.01 - can't connect to QC by web. On DVA1622 with DSM 7.2.2 arc 24.09.01 - the same problem!!! Issue is not on my Side!

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#3287]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.
I have 2 same DS920+. On DS920+ with DSM 7.2.1 QC is working normally. On DS920+ with DSM 7.2.2 arc 24.09.01 - can't connect to QC by web. On DVA1622 with DSM 7.2.2 arc 24.09.01 - the same problem!!!
Issue is not on my Side!
**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
issue on your side! just checked every model, every QC is working!!!

**Comment by TTTnas** [comment]
QC is working, yes. But can't connect to nas on quickconnect.to!!!

**Comment by AuxXxilium** [comment]
so your freaking network is the issue, not the loader or dsm or qc or anything else!

**Comment by TTTnas** [comment]
i can sync files with my devices by QC (Synology Photos, Synology Driver client, Surverilance...). But can't connect to nas by quickconnect.to. At work nor at home!! At home I try connect by IP - it is normally, but connect by QC - can't sigh in!!

**Comment by AuxXxilium** [comment]
you blocked it! is it so difficult to understand that the issue is caused by YOU. Arc Patch + DS920 enabled:
![Screenshot 2024-09-04 204646](https://github.com/user-attachments/assets/e20e285a-9f0c-448f-93b6-6aadf316c6ed)

**Comment by AuxXxilium** [comment]
if you block the traffic qc need, it's not a fault by anyone else than YOU

**Comment by TTTnas** [comment]
ths. I don't understand why ((

**Comment by TTTnas** [comment]
After your test Now i can go to DS920+ by QC.
 But on DVA1622 the problem remains!!! Did you change anythings?

**Comment by AuxXxilium** [comment]
i tried every model since your report! EVERY

**Comment by TTTnas** [comment]
Ths!
