### ISSUE TITLE
Wrong CPU clock rate

### ISSUE THREAD

**Issue by ydrob** [AuxXxilium/arc#3299]
**Describe the Bug**
Wrong CPU clock rate, show 800 Mhz all the time, but CPU info is correct. cpuinfo addon has been applied.

**Screenshots**
![image](https://github.com/user-attachments/assets/dfa243e8-372d-4b4e-9206-0fdcac356215)

**Hardware**
Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz

**Comment by AuxXxilium** [comment]
only optical and is the speed while boot at the time the clock will be read by script.

no bug
