### ISSUE TITLE
I update the loader and it doesn't start anymore..

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/arc#33]
hello I have loader 22.12.05 and work ! 
After loader update and rebuild, it doesn't start anymore but why?

this is my configuration:

![image](https://user-images.githubusercontent.com/31816231/208456763-3cfe3583-e3fc-4eb9-9bf2-65e3f1e104ea.png)

**Comment by AuxXxilium** [comment]
Image size has changed from 500M to 1G. So you have to change the img file.

**Comment by wifi75** [comment]
I resized the disk to 1Gb then I did the update and rebuild.
The loader starts but not the dsm.

**Comment by AuxXxilium** [comment]
Please do not only resize, please use new image and change your old.

**Comment by wifi75** [comment]
> Please do not only resize, please use new image and change your old.

after new installation:

![image](https://user-images.githubusercontent.com/31816231/208868314-8586bf9b-b5ab-4f0d-ba83-05acf2b70969.png)

**Comment by AuxXxilium** [comment]
Your image is not mounted at sata 0:0. 

Btw it's proxmox related, so you should use google. it's not arc related. i know about this crap in proxmox and unraid.

**Comment by wifi75** [comment]
![image](https://user-images.githubusercontent.com/31816231/208890779-73ed8fa2-8cc3-47dc-a2ba-789011030b91.png)

**Comment by AuxXxilium** [comment]
Try the v22.12.21 after build is ready. all issue should be fixed.

**Comment by AuxXxilium** [comment]
any update with the latest versions?

**Comment by wifi75** [comment]
hello i still have to try...

**Comment by wifi75** [comment]
> any update with the latest versions?

![image](https://user-images.githubusercontent.com/31816231/209527967-f8ca89e1-9ed1-4506-a551-47422bccd7b6.png)

**Comment by AuxXxilium** [comment]
With only a picture i can't know anything. so describe what you have done before.

**Comment by wifi75** [comment]
I tryed to install fresh installation but i have same this error:
![image](https://user-images.githubusercontent.com/31816231/209552849-c0b75170-dede-4a30-b25e-17b190187708.png)

with loader 22.12.05 and same configuration all work fine.

**Comment by wifi75** [comment]
hello, I finally managed to install the latest version, but I had to convert the loader to the DS1621+ model, unfortunately with the DS3622xs model it is not possible to start the dms.
While with the ds1621+ yes, it worked right away.
