### ISSUE TITLE
Issue with DSM recovery

### ISSUE THREAD

**Issue by MartinKuhl** [AuxXxilium/arc#332]
**Describe the bug**
I try to migrate my old ARPL installation to your ARC version. Therefore I changed to bootloader to the lastest arc version.
There I wanted to use the DSM recovery function to determine the build and model version an the SN as well.
As you can see in the screenshot, the function is some kind broken and not able to extract these information.
The arpl-i18n fork and the fork of jimmyGALLAND are able to recover this information without any problems. 

**Screenshots**

<img width="339" alt="Bildschirmfoto 2023-06-15 um 08 50 31" src="https://github.com/AuxXxilium/arc/assets/55736453/cfe6096c-6b65-4a08-a4ef-3fe5b32e4a5e">

**Additional context**
I testet all of your versions since arc-23.6.31a

**Comment by AuxXxilium** [comment]
Which model is your old system? It is possible that restore will not work. havn‘t tried this, because we need more things in config than we can restore from syno config.

**Comment by MartinKuhl** [comment]
My old one is a DS3622xs+ with DSM version 42962. The other mentioned loaders are able to restore the build and model version an the SN. Did your function work so differently from the other ones?

**Comment by AuxXxilium** [comment]
23.6.35 incoming ;)
