### ISSUE TITLE
network card does not work after boot dsm

### ISSUE THREAD

**Issue by urobasa** [AuxXxilium/arc#337]
The network card receives ip on the boot arc and works.
after setting up the arc and building dsm, I restarted my computer.
arc boots up and gets ip via realtec 8169 network card.
when the arc shows DSM kernel loading, network card hang, stopped flashing lights on the network card, boot process hang, the port speed switches to 100M (normal speed 1G).
this happens when I insert a raid controller, without it the network card works fine, both pci-e and built-in.
If at this moment you switch the cable to another card, it starts working at full speed, but does not receive an address.
Raid adapter in raid mode and another adapter in it(jbod) mode does not affect, the built-in network card and the pci-E network card stop working after loading the dsm kernel. 

**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.

**Additional context**

**Comment by AuxXxilium** [comment]
Looks like, you have an issue in you pcie config of your bios

**Comment by AuxXxilium** [comment]
do you have tried .40a? if not, you can try .41
