### ISSUE TITLE
Can't build any version

### ISSUE THREAD

**Issue by ciddikedi** [AuxXxilium/arc#339]
![image](https://github.com/AuxXxilium/arc/assets/44272243/6bc4af23-f580-42f9-a76e-3b6d9d80db25)
![image](https://github.com/AuxXxilium/arc/assets/44272243/81bb007e-c8df-4c65-ad1e-8e1f6477c021)

I tried older versions but the result is the same. Loader has internet access.

**Comment by AuxXxilium** [comment]
- Your SataPortMap is wrong - look for recommended option while selection
- Your Buildnumber 64561 is removed from Syno server - reselect model

**Comment by ciddikedi** [comment]
Ok thank you
