### ISSUE TITLE
Getting IP too long

### ISSUE THREAD

**Issue by ciddikedi** [AuxXxilium/arc#340]
![image](https://github.com/AuxXxilium/arc/assets/44272243/3035489e-eec5-4c0a-925a-70ecc08c28fd)
After showing this error loop for about 1 minute, the network adapter is identified.
23.6.36a on proxmox and virtio network adapter.

**Comment by AuxXxilium** [comment]
it's an issue from your dhcp/router

**Comment by ciddikedi** [comment]
Changed model from DS3622xs+ to RS3621xs+. Problem fixed.

**Comment by AuxXxilium** [comment]
Funny, its the same config and modules.
