### ISSUE TITLE
Ixgbe is removed  only with 23640 can send log files if needed

### ISSUE THREAD

**Issue by nemesis122** [AuxXxilium/arc#343]
I have with the version 23640 ixgbe driver is removed in the log over and over 49 times then the loader boot but with 23635 there is no such issue 

**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.

**Additional context**

**Comment by AuxXxilium** [comment]
use latest please

**Comment by nemesis122** [comment]
hI 
Yes with 23.6.40a it is fixed 
thank you
