### ISSUE TITLE
Error cant mount DSM partition after ARC loader update

### ISSUE THREAD

**Issue by viktortrass** [AuxXxilium/arc#3575]
Hello,

I have just updated arc loader via menu, after the update it gave me a key to restore the config!
After rebooting I try to restore but the option say error cant mount DSM partition!!

I need help please I have the server inaccesible!!

**Comment by AuxXxilium** [comment]
reading releasenotes at github and warnings inside arc will help. reflash loader, configure from scratch, use it!

**Comment by viktortrass** [comment]
but where is the information about that located?please help me I can't access the server right now, I had my original mac and SN so I would like to restore previous info!!is the key restore not working?

**Comment by viktortrass** [comment]
When I select now Choose Model it show me only Show beta models
