### ISSUE TITLE
No DSM Image found

### ISSUE THREAD

**Issue by RJSUTH** [AuxXxilium/arc#363]
Ich habe V 23.6.51a Image neu erstellt, aber bei "Build loader" kommt die Meldung "no DSM Image found"

![image](https://github.com/AuxXxilium/arc/assets/122780513/45f16913-fbaa-4a9d-a02a-e62193fd4eb2)

![image](https://github.com/AuxXxilium/arc/assets/122780513/120b923d-1da1-404f-b67f-7159e2e9868a)

**Comment by AuxXxilium** [comment]
I don't know what you do, it's again only you.

**Comment by AuxXxilium** [comment]
![Screenshot 2023-06-26 195801](https://github.com/AuxXxilium/arc/assets/67025065/60bac978-f68e-4dd3-9cdc-200f2b19976b)

new setup 5 min ago

**Comment by RJSUTH** [comment]
Von wo werden die DSM Images heruntergeladen? Nach mehrmaligen Versuchen funktioniert es dann.

**Comment by AuxXxilium** [comment]
Dann blockst du irgendwo die Verbindung zu Github. Kann eine DNS Server Einstellung oder Adguard/PiHole sein.

**Comment by RJSUTH** [comment]
Es liegt wohl an der Hardware Fujitsu Futro S720. Mit Version 23.5.30 funktionierte es problemlos. Ich habe dann die Versionen bis 23.6.51a übersprungen. AB dieser Version wird auch kein Update gefunden.
Gibt es eine Empfehlung ARC ständig up zu daten, oder kann man auf einer funktionierenden Version verbleiben?

**Comment by AuxXxilium** [comment]
Wenn du Discord nutzen würdest oder in den Release etwas runter blättern, würdest du sehen, dass mit der .50 eine Clean Install notwendig ist.

Du musst Nichts updaten wenn dein System läuft.

**Comment by RJSUTH** [comment]
Ich habe deine Info sehr wohl gelesen und befolgt, ich vermute die Futro Hardware als Ursache, weil meine VM Installation ja funktioniert. Ich schätze deine gute Arbeit und deinen Einsatz und möchte nicht rum nölen, sondern dir nur Feedback geben, das dir vielleicht hilfreich ist. Vielen Dank an dieser Stelle, das du ARC mit uns teilst

**Comment by RJSUTH** [comment]
Der Fehler lag am Server 2022 DHCP Server, ein löschen der Leases führte zum Erfolg, Was auch immer da passierte

**Comment by AuxXxilium** [comment]
Danke für die Info. Da waren wohl irgendwie falsche Daten im Cache

**Comment by RJSUTH** [comment]
Ich habe eine Frage zu Original Synology Diskstation, da es kein Fehler ist möchte ich kein neues Issue aufmachen.

Das DS1515+ hat 5 Bays und ist mit seiner Intel Atom CPU sehr performant.
Leider hat Synology scheinbar die Unterstützung mit DSM 7.1.1 beendet.

Besteht die Möglichkeit mit ARC ein anders Bootimage zu laden um wieder die Aktualisierungen zu bekommen?

**Comment by AuxXxilium** [comment]
Du kannst die Updates jederzeit manuell installieren oder machst wie ich es überall geschrieben hatte, einen CLEAN INSTALL.

**Comment by RJSUTH** [comment]
Frage zu unterstützten HDD Controllern:

Werden der Adaptec ASR-71605 und ASR-8805 unterstützt? 
Auch zusätzlich zum OnBoard Sata Controller?

Man kann diese im Setup von RAID auf HBA Modus umstellen, was sehr komfortabel ist.

**Comment by AuxXxilium** [comment]
dann hat syno wohl den link zu der dsm datei die im loader hinterlegt ist gelöscht.
