### ISSUE TITLE
Latest image Cannot boot via proxmox. not a bootable image

### ISSUE THREAD

**Issue by Buster14** [AuxXxilium/arc#369]
**Describe the bug**
I'm following [This guide.](https://www.youtube.com/watch?v=ysZicaoztEA)
Using the latest image 23.6.54b
But upon booting it says not a bootable image.
Am i missing something? Proxmox is v7

**Comment by AuxXxilium** [comment]
wrong place for loadet disk. Sata 0:0?

There is a video in Wiki linked for Proxmox. Please check your settings.

**Comment by Buster14** [comment]
> wrong place for loader disk. Sata 0:0?
> 
> There is a video in Wiki linked for Proxmox. Please check your settings.

Hmm the video uses Windows VM to attach 2GB hdd then burn the image using balena.
I can't generate another windows VM due to HDD limitation, but I have a running windows machine.
How would this translate to physical installation? Create new partition then burn it with balena?

**Comment by AuxXxilium** [comment]
simple way: mount the loader disk at sata 0:0 and nothing else.

**Comment by Buster14** [comment]
It works finally with the latest version, I think I may need to extract it first.

https://www.youtube.com/watch?v=_ZZcd1_jh00

Btw I'm trying to achieve this actually, but would it work on DSM 7.2 64570 and the 16 core version broadwell? That's what I'm running right now.

**Comment by AuxXxilium** [comment]
yes it will work. also with the latest update of surveillance station.
