### ISSUE TITLE
DSM Update now shows "Connection failed. Please check your Internet connection."

### ISSUE THREAD

**Issue by OiCkilL** [AuxXxilium/arc#370]
**Describe the bug**
https://raw.githubusercontent.com/AuxXxilium/arc/main/rss/7.2/rss.xml has been removed and the status of DSM Update now shows "Connection failed. Please check your Internet connection."
**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/613988/b5b7a4e2-36db-4b7b-8f8e-768c0a9244da)

**Comment by AuxXxilium** [comment]
is everything fine. is blocked because of syno changes the last weeks.

**Comment by AuxXxilium** [comment]
Or you use a clean install and everything is fine again
