### ISSUE TITLE
suggest change the background to #2b2b2b to make it same with page background

### ISSUE THREAD

**Issue by Brian099** [AuxXxilium/arc#373]
![image](https://github.com/AuxXxilium/arc/assets/80375397/c8ef772a-1537-4ec6-9393-510189068faf)

**Comment by Brian099** [comment]
or full black
![image](https://github.com/AuxXxilium/arc/assets/80375397/fdaa5988-3c55-49c6-85b8-ea3850df9a8d)

**Comment by AuxXxilium** [comment]
in my case, the webterminal is full black.

**Comment by Brian099** [comment]
> in my case, the webterminal is full black.

There is also a gray background after terminal ,could make it black, too,?

**Comment by AuxXxilium** [comment]
set to all black for all browser

23.7.2
