### ISSUE TITLE
ReBoot stuck

### ISSUE THREAD

**Issue by Canh3800** [AuxXxilium/arc#3762]
When computer reboot, it stucked. I have to turnoff computer, after turn on again, it worked.

**Comment by Canh3800** [comment]
![photo_2024-09-27_16-09-24](https://github.com/user-attachments/assets/6c9090eb-35da-4bae-8011-deeccdc8ebeb)
![Arc - Sysinfo](https://github.com/user-attachments/assets/9dd64531-0b60-4e19-8d3a-f82463b9076d)

Here are you, stucked pictures when I reboot DSM

**Comment by AuxXxilium** [comment]
Supported with at 2. Gen Core i, bot earlier
