### ISSUE TITLE
Vmware workstation installation, Unable to add extra drives once the system is installed and built?

### ISSUE THREAD

**Issue by kundeng** [AuxXxilium/arc#3797]
**Describe the Bug**
Vmware workstation installation, Unable to add extra drives once the system is installed?  I tried to add 3 more SATA virtual drives, but they are not detected after I shutdown and restarted the system. 

**Screenshots**
everything is default.  

**Hardware**
This is VMware!  No actual hardware is involvewd. 

DSM:
Model: DS3622xs+
Platform: broadwellnk
Uersion: 7.2 (72806)
System:
Uendor: UMware, Inc. UMware20,1/440BX Desktop Reference Platform, BIOS UMW201.00U.21805430.B64.2305221830 05/22/2023
CPU: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 4GB
Location:
Keymap: us
Timezone: America/Detroit
Detected 1 NIC. Waiting for Connection:
umxnet3 (10000Mb/s): Access http://192.168.1.69:5000 to comnect to DSM uia web.
Loading DSM kernel...

**Comment by kundeng** [comment]
Note the  4 virtual sata drives excluding the boot disks are connected. 
![image](https://github.com/user-attachments/assets/4d771a9f-ce0c-4c1a-824c-81fe49e88730)

**Comment by kundeng** [comment]
![image](https://github.com/user-attachments/assets/85c8bd84-dbe2-4911-b7b7-e9a2ff2cdf11)

**Comment by AuxXxilium** [comment]
RTFM

**Comment by kundeng** [comment]
For your information, no need to be so arrogant and rude.   I did read all the browser translated docs on your website to try to figure out whether there is an answer , and I still can't figure out.  Not everybody knows this subject from inside out.
