### ISSUE TITLE
How to Disable FMA check?

### ISSUE THREAD

**Issue by dimadusk** [AuxXxilium/arc#383]
Hello, is it possible to disable FMA check in loader? My N2807 can run dva3221 on TCRP 9.0.3 but it doesn't run with this loader. The reason why I want to use this specific loader is because it has dva3219 same architecture as 3221 but both of them cannot run. Even dva1622 cannot be installed while it is working fine in TCRP.
When in UI I hit Run Loader it just freezes, and after manual reboot it shows ip but never connects to it. DS918+ however works fine.

Edit: Update
After DS918+ I went to edit config and changed model to dva3221 and it worked. Then migrated and loaded.
![Screenshot_2023-07-05-02-15-05-397_com android chrome](https://github.com/AuxXxilium/arc/assets/60470490/15bf1e07-3c52-4608-a87b-e145b9974348)

Update2:
Dva3219 works as well. Thank you for your hard work you can close issue.

**Comment by AuxXxilium** [comment]
For next time, you can select incompatible models as well.

**Comment by dimadusk** [comment]
Thank you, will know 🙂
