### ISSUE TITLE
error checking new version

### ISSUE THREAD

**Issue by MartinKuhl** [AuxXxilium/arc#384]
since version 23.6.51a I always get the error: error checking new version for all update options. That happens in my VM and on my real NAS as well.

**Comment by AuxXxilium** [comment]
Update Loader

**Comment by MartinKuhl** [comment]
@AuxXxilium 
which version should fix that issue. I am also nut able to update from loader 23.7.2b to the newest one.

**Comment by AuxXxilium** [comment]
Replace boot image

**Comment by MartinKuhl** [comment]
I replaced the boot image with the newest version (23.7.4c). The update error is still there. Looks like the function is not able to access the right endpoint.

**Comment by AuxXxilium** [comment]
than it's an issue in your network. you mean update inside loader? if you mean update inside dsm, this function is blocked because of syno changes to many things and you can destroy all your data if you update at the wrong time.

that the dsm inside update is blocked is written multiple time in changelog and releasenotes as well as my discord

**Comment by MartinKuhl** [comment]
I try to update the loader inside the loader's update menu:
I changed nothing for months in my local network and a few loader versions ago, the update functions was working proberly. 

<img width="821" alt="image" src="https://github.com/AuxXxilium/arc/assets/55736453/c7d0adb2-1c61-423c-843d-092bc3eb5379">

**Comment by MartinKuhl** [comment]
the build process and everything else is working fine.

**Comment by AuxXxilium** [comment]
diskspace issue? looks like your disk has not enough space and your ram settings are to low for ramcache

**Comment by MartinKuhl** [comment]
After increasing my VM memory it is working now. 
Now I was able to Uprade the loader. On thing what I observed there is, that after the config restore the ARC Patch is set to N now.

**Comment by MartinKuhl** [comment]
The only change is the memory but after a reboot the ARC patch is now set to true.
