### ISSUE TITLE
Proxmox : Config Update failed, use local config

### ISSUE THREAD

**Issue by Buster14** [AuxXxilium/arc#392]
Hi, the latest version 23.7.15 got me stuck in Ethernet request something, so i tried last working version for me which is arc-23.7.2b.
But after choosing loader model now I'm getting Config Update failed, use local config!
any ideas why? 

Ah i think i know why, I need dhcp server, unfortunately I'm in environment without dhcp server, is there anyway to set Ip through command line?

**Comment by AuxXxilium** [comment]
Simple: No

**Comment by Buster14** [comment]
> try 23.7.15a

Just tried this version few hours ago with my dhcp server enabled.
It works but strangely it always asks for dhcp server everytime it reboots even after i set static ip. Kinda troublesome if an outage occurs i think.

Also whats the correct procedure for passthru hdd? Ive tried sata passthrough 4tb seagate but dsm 7.2 wont detect it

**Comment by Buster14** [comment]
Scratch that ip issue, looks like it will automatically set to the static ip address.
Only hdd issue left.
Very strange i've tried sata 2 and 3 but none works.
But the hdd appears in proxmox hardware page, and it showed up previously on windows VM so it's not hdd issue.
Is there any sata setting i should be aware of when building the loader?
This is only a single sata connected 4tb seagate hdd

**Comment by AuxXxilium** [comment]
don‘t ask me with this proxmox trash. i added a video from a community member to wiki. don‘t know if this will help you.

**Comment by Buster14** [comment]
Okay thanks that did the trick! Looks like i need to choose sataportmax.
One last thing, What settings do I need to tweak if I need to add secondary NIC to my DSM?
I think i screw up my installation after adding second NIC.
Now it wont login and it says "system is getting ready please login later"

**Comment by Buster14** [comment]
Sorry forgot to update, it was working but need to wait around 5 mins.
I've been testing SS for few hours but I keep getting "stopping" status change... maybe it needs bare metal after all?
This time i gave it 2 cores and 4 threads. 7 cams h264.

**Comment by AuxXxilium** [comment]
the cams should restart every hour, that take them down for about 2-3sec. but you need to use one oc the latest arc.

**Comment by Buster14** [comment]
I'm on 23.7.16 now, just updated few hours ago through the loader, it gave me code, then i  reboot.
Live stream and playback seems faster, 
but stopping bug is still there though.. after about an hour I think, it wont re-enable by itself..

**Comment by AuxXxilium** [comment]
the loader need dhcp. we can not read settings from dsm. 2 different systems. 

the ss restart is not a bug. we need to trigger the restart, if we don‘t do this, recording will stop.

**Comment by Buster14** [comment]
Sorry i don't understand about SS,
When i left it on "stopping" state it wont restarted by itself so that makes it unusable, 
My fix was disable and enable it, but it happens again an hour after that.
Is there anything else needed to do to prevent this?

**Comment by AuxXxilium** [comment]
there is a restart timer for camera service. the service restart should only take between 2-5 seconds and restore the last working state.

**Comment by Buster14** [comment]
> there is a restart timer for camera service. the service restart should only take between 2-5 seconds and restore the last working state.

So in my case it doesn't work? Is it because it's on VM?
Or maybe I need to fully rebuild the loader from scratch instead of updating?
