### ISSUE TITLE
DVA3219 arc patch not work

### ISSUE THREAD

**Issue by PMCXtreme** [AuxXxilium/arc#394]
**Describe the bug**
ARC patch not work on DVA 3219. I cant use syno service. Pls fix this. Thank you very much

**Comment by AuxXxilium** [comment]
it will work. i used it yesterday.

**Comment by AuxXxilium** [comment]
23.7.15c

**Comment by PMCXtreme** [comment]
I'm sorry. Will test again tomorrow. Thank you a lot
