### ISSUE TITLE
Surveillance patch doesn't work in the last realeade

### ISSUE THREAD

**Issue by Cseb62** [AuxXxilium/arc#396]
With the last release surveillance patch doesn't work.
License appears but time bomb is execute each hour

**Comment by AuxXxilium** [comment]
it is working. but the reset every hour is needed. so no need to open a bugreport.

**Comment by Cseb62** [comment]
Hi it's not the hourly reset... The camera stop working.I must install the previous version (4 day ago) and now it's working Le 10 juil. 2023 23:28, Christian Schulthess ***@***.***> a écrit :
it is working. but the reset every hour is needed. so no need to open a bugreport.

**Comment by AuxXxilium** [comment]
but this version will loose the ss functions after some time. because the restart isn‘t triggered and will lock your nas to prevent new ss install. it‘s only posible to resolve this with a full reset of the system.

**Comment by Cseb62** [comment]
a full reset ? a reboot of the nas?

**Comment by Cseb62** [comment]
What is a full reset for you?

**Comment by AuxXxilium** [comment]
a full reset - format everything

**Comment by AuxXxilium** [comment]
let me try something today. i already spend my whole weekend to find a solution.

**Comment by Cseb62** [comment]
OK thank you 👍

**Comment by Buster14** [comment]
Would the patch work on older version on SS? SS8 maybe?

**Comment by AuxXxilium** [comment]
no. it‘s only for this version.

**Comment by Buster14** [comment]
Is it fixed yet in latest release?
