### ISSUE TITLE
wol not working at 7.2,in 7.1 working perfect

### ISSUE THREAD

**Issue by chrisrer** [AuxXxilium/arc#400]
Hi team little help there....my server pc was i7 3770k with asrock z77 fatal1ty proffessional-m 16gb ram with DSM 7.1 (DS 3617xs) and working perfectly with ARPL loader....today i decide to make new bootloader with new DSM 7.2 (big mistake) ...first try with tinycore unsuccesfuly then try with ARC bootloader Succesful but my big problem was that WOL not working...in 7,1 works perfect.......make different things nothing then try to install DS 3622xs+ works great but WOL nothing......i suppose to make wol is clearly with original MAC from motherboard to take command.....why this issue? any suggestions?

**Comment by AuxXxilium** [comment]
for me it is working on all tested platforms with 7.2.

**Comment by chrisrer** [comment]
> for me it is working on all tested platforms with 7.2.

What kind of hardware? What i must check?

**Comment by chrisrer** [comment]
Update from 7.1 to 7.2  ok when i go home ill send screenshot

**Comment by chrisrer** [comment]
![Screenshot 2023-07-15 102703](https://github.com/AuxXxilium/arc/assets/43493721/d8f4391a-9af8-495a-af1c-802679b129e1)

**Comment by chrisrer** [comment]
> Updated system from 7.1 or clean install with 7.2?
> 
> Screenshot from sysinfo in arc is needed.

can i make downgrade to 7.1 ??????? if yes how pls??

**Comment by AuxXxilium** [comment]
Yes you can. Select "Advanced - Allow Downgrade DSM".

**Comment by chrisrer** [comment]
Ok i'll find the problem and fixit..........It was on the lan mac addresses.....when i make the bootloader change mac addresses from lan card's......the steps is make configuration the arc.......go to Sho advanced options -cmdline - Define a custom MAC and write the psysical Addresses in the correct card.......How to check the correct Mac one easy way is to download on windows program called WakeMeOnLan and check ip;s of your network and mac addresses from each hardware.

**Comment by AuxXxilium** [comment]
The mac needs to be changed to get arc patch working. and you can create loader also without this. so you don‘t have to edit something. on the most nic the mac change is working, but some cards doesn’t support this. even the same type and model but different date of manufaction.
