### ISSUE TITLE
line delimeters in resolv.conf

### ISSUE THREAD

**Issue by asmomegr** [AuxXxilium/arc#4105]
**Describe the Bug**
In an environment where a DHCP server offers only an IP address for ARC and no DNS server, ARC uses its own hardcoded nameservers in resolv.conf, 8.8.8.8 and 8.8.4.4. However, the nameservers in that resolv.conf are unusable for programs that use libresolv.so like ping or curl due to incorrect line delimiters (you can see them as ^M in vi). It is okay for nslookup, but not for ping (see screenshots). Therefore, init.sh finishes unsuccessfully.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/9e51098c-5fd5-47ab-8160-370b7f6f81cc)
![изображение](https://github.com/user-attachments/assets/e3882735-7eaa-4bac-b609-5de4e6c2c117)

**Hardware**
Any hardware.

**Comment by AuxXxilium** [comment]
fixed in upcoming release
