### ISSUE TITLE
DSM does not start, appears on the network for 3 seconds and disappears.

### ISSUE THREAD

**Issue by upais** [AuxXxilium/arc#416]
After building the bootloader and rebooting, DSM does not start, appears on the network for 3 seconds and disappears.
BIOS is configured according to information from the wiki. Tried Direct boot.

MSI Z590 TORPEDO
i5 11400
i225-v\i219-v
HDD in the first slot. HDD without partitions.

Screenshots:
![2023-07-21 213831](https://github.com/AuxXxilium/arc/assets/86227709/07cbb126-45a5-4538-8698-33ec352acda8)
![photo_2023-07-21_21-37-59](https://github.com/AuxXxilium/arc/assets/86227709/84d33b86-9ecc-4649-8578-714f6943eca4)
![photo_2023-07-21_21-37-49](https://github.com/AuxXxilium/arc/assets/86227709/af160bc2-f611-4329-bb2b-03ca73f50552)

**Comment by AuxXxilium** [comment]
Try DS3622xs+ please and report back.

**Comment by upais** [comment]
The same.
Tried DS3615, DS3622, DS920, UEFI and Legacy.
It is interesting that on I219 the LEDs are off, but on I225 one is on, the other is blinking, but DSM does not appear on the network.

**Comment by AuxXxilium** [comment]
do you have checked the IP in  your router?

**Comment by upais** [comment]
Of course. Yesterday I was doing this for half a day, I tried all the current loaders. The result is always one.
I will not try again, I returned the old motherboard. Let it be for information to others that there are some problems on the MSI Z590 TORPEDO board.

Did you have an LGA1200 on hand for testing? If so, can you write motherboards that you can recommend?

**Comment by AuxXxilium** [comment]
is use h670m-itx/ax with 12500
