### ISSUE TITLE
When plugging in USB - DSM detects as new drive not USB.

### ISSUE THREAD

**Issue by QuickSwitchLK** [AuxXxilium/arc#419]
**Describe the bug**
When I plug in any USB device, DSM sees it as new drive not a USB device.

I did not change any advanced settings on install. I am running version 23.7.22

I loaded into the config of the loader, found in advanced arc settings change usb and set to load as USB.
Rebuilt the loader, but no change.

Need some help with this one please.

Plus what is the best method to update your loader on a work setup?
 
Thanks Luke.

**Comment by AuxXxilium** [comment]
to first: do the correct steps for a bugreport, than i can help you.

to second: best is make new stick, but you can also use: fullupgrade loader.

**Comment by QuickSwitchLK** [comment]
Updated info. Have also updated the loader to 23.7.30b
Same issue.

Also tried booting with USB Mount = true with no change.

![Screenshot 2023-07-25 173104](https://github.com/AuxXxilium/arc/assets/34122743/dbc3b33c-64f4-4381-8069-33882b00c37c)

![Screenshot 2023-07-25 174347](https://github.com/AuxXxilium/arc/assets/34122743/74498f37-657a-4b92-87de-a050bdefc12c)

![Screenshot 2023-07-25 173518](https://github.com/AuxXxilium/arc/assets/34122743/5fa8f174-e766-4924-9aef-104e3faff741)

Thanks Luke.

**Comment by AuxXxilium** [comment]
USB Mount true makes the different from that you want. Unplug USB, reboot and Plugin USB again. Everything will be fine.

**Comment by AuxXxilium** [comment]
than it should work with 7.2, too. there are no changes between 7.1 and 7.2 in usb. except the changes in dsm.

**Comment by QuickSwitchLK** [comment]
usbportcfg="0xff0000" is the current setting on my config.
I never changed it.

I did some research, converting that that to binary is...

111111110000000000000000

1 = USB
0 = Internal Drive.

That configures the first 16 dives as internal. I would have thought that was set when selecting the max disks.

My unit only has 10 drives, and is set with active disks in the menu. So I would have to plug in 7 USB's to see the final one load as an actual USB.

**Comment by QuickSwitchLK** [comment]
also esataportcfg="0x00" is set in my current config.

**Comment by smulle48** [comment]
> also esataportcfg="0x00" is set in my current config.

Try to use "Use SataPortMap (max Ports)" to see if it helps

**Comment by QuickSwitchLK** [comment]
OK, so the solution was to set hex codes manually.
I tried "Use SataPortMap (max Ports)" no change.

When you select, Advanced, USB Config, and set USB as Internal.

sysconf file has the values for...
maxdisks="24"
usbportcfg="0xff0000" ? I think will need to check.
esataportcfg="0x00"
internalportcfg="0xffffff"

makes sense...

but when you select USB as Normal.

sysconf file has none of these listed at all, so on reboot DSM must just look at what was set in the original file b4 any modification and hence why I had my issues above.

usbportcfg="0xff0000"

Looks like the solution is to set HEX codes based on what is left over out of 24 disks when setting up SataPortMap

**Comment by AuxXxilium** [comment]
yes we shouldn't need this settings if usb should work normaly and not as storage. the settings values will be computed by disks addon.

**Comment by AuxXxilium** [comment]
try 23.7.34
