### ISSUE TITLE
Vmware issue

### ISSUE THREAD

**Issue by partola** [AuxXxilium/arc#4197]
**Describe the Bug**
All new versions starting from 24.10.dev to 24.10.13 including custom and arc-dyn not working with vmware virtual machine.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
Need more informations. Because in my ESXi 8 is everything working.

**Comment by partola** [comment]
Vmware workstation 17.6.1, trying older version, result is the same. Intel
NUC 7i3bnh, i3, 16gb, 240 ssd as system, 3 tb usb as volume drive
configuring as virtual disk using physical disk. Arc standart and next
versions work awesome including last working next version. All eternity
versions resets after displying menu window, impossible to enter in config
mode. I trying another host 8i3bek, but not successful. Arc reseting. Thank
you.

вт, 15 окт. 2024 г., 07:52 AuxXxilium ***@***.***>:

**Comment by AuxXxilium** [comment]
UA? if yes, goodbye

**Comment by partola** [comment]
RU?

**Comment by partola** [comment]
I am not military man, i am disabled 64 yo
