### ISSUE TITLE
Bad ram recognition

### ISSUE THREAD

**Issue by Rick4hun** [AuxXxilium/arc#420]
I have a Topton N1 pro with a non- booting xpenology, we are discussed about my issues, tried anything i see at wiki and you wrote, nothing happens, it still stuck at boot the loader, but never boot, and never visible on LAN. So i am tried your new loader, and hope, it will once booting without issues,  but now  get error message about my RAM quantity. I have 16GB DDR4 RAM, and use a 32GB TF card, so i am wondering about that message! 
Thanks! 
![IMG_20230724_232514](https://github.com/AuxXxilium/arc/assets/139920348/70839810-5619-469e-afce-bd7e1f97a02b)

**Comment by AuxXxilium** [comment]
TF/MMC/SD Boot is not possible. Use USB or SATA

**Comment by Rick4hun** [comment]
My bios shows, it's an usb storage, so it can boot completely same, as other usb flash driver, sata ssd, ot any other device. 
![IMG_20230725_121513](https://github.com/AuxXxilium/arc/assets/139920348/e84ca6cf-9f94-46d8-b9d6-5cded95ca7e0)

**Comment by Rick4hun** [comment]
If i burn image to a 32GB TF (microSD card), and burn once again a flash drive, i get same result, loader can boot all two, and i can choose what media boot first. 
Loader can boot from  TF card without any issues. 
![IMG_20230725_121917](https://github.com/AuxXxilium/arc/assets/139920348/875fde17-10d1-4aaf-b1fe-a2d9be3d0d5b)

**Comment by AuxXxilium** [comment]
if you can boot from both, everything is correct. the ram message can be ignored if you have 16gb installed.

**Comment by AuxXxilium** [comment]
Try it with: LKM „dev“ and connect your cable to second LAN Port. It looks like some adapter don‘t accept mac changes.

**Comment by AuxXxilium** [comment]
so it‘s a kernel panic caused by cpu or board. other options:

- try with disabled HT
- try Memory Remap enabled and disabled
- try Directboot

**Comment by Rick4hun** [comment]
HT on AMD site is  SVT mode, that disabled with others you wrote at wiki, after many more unsuccesful boot,  tried to disabled more pci lanes, until  i got only one LAN card.., 
memory remap is a very strange thing, because  omv, truenas,  freenas, rockstor, win11, win server 22,  nextcloud+ casa os, etc etc works with many more feature disabled you requested, but tried to boot all after a bios default settings, same result, others can boot and work with default settings. 
Just tried to find memory remap, but found only "write CRC enable" and "dram ECC enable" , that set to OFF, dot nottings happened, same result only! finally doesn't affercted. Tried memtest, over 3 hours i gor final green PASS word on screen.. 
Tried more different size/ vendor memory modules, same result. 
Tried directboot, doesn't affected.
