### ISSUE TITLE
Can't build the loader on new 24.10.17. DS920+. Plz help

### ISSUE THREAD

**Issue by TTTnas** [AuxXxilium/arc#4224]
**Describe the Bug**
First read Wiki to find a Solution. If you can't find a Solution, provide a clear and concise description of what the bug is.

**Screenshots**
Actual Screenshot from Systeminfo (Config Mode - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
<img width="722" alt="Screenshot 2024-10-18 190805" src="https://github.com/user-attachments/assets/0725c7dc-9853-4946-a301-7064d2926623">

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
Read update notice

**Comment by TTTnas** [comment]
replace Bootimage or Reflash stick - i did

**Comment by AuxXxilium** [comment]
configured from scratch?

**Comment by TTTnas** [comment]
no. i never choose automatic configure. I dont use ARC patch. I have real SN and MAC

**Comment by AuxXxilium** [comment]
possible the issue is there, don't know without more informations.

**Comment by TTTnas** [comment]
24.10.07 - normal build. But now it automatic update to newest build
