### ISSUE TITLE
Question on NMVE addon operability as a storage pool and network connectivity problem

### ISSUE THREAD

**Issue by lev666** [AuxXxilium/arc#424]
**Describe the bug**
Question on NMVE addon operability as a storage pool and network connectivity problem

**Screenshots**
![Снимок экрана 2023-07-26 211619](https://github.com/AuxXxilium/arc/assets/63856055/517dd26b-b0cf-40f9-ba39-22878f1846fb)

**Additional context**
Good afternoon. 

1)On the latest bootloader updates, I noticed that the maximum speed in the local network over the wire reaches only 100 mbps than 1000 mbps before. A full and clean reinstallation of the system did not solve this situation

2)Noticed in your loader recently addon to make m2 work as a storage pool instead of just a cache. But after applying this addon only the name of my M2 in the DSM changed (Namely, that next to the name of my m2 appeared a signature (SSD), but it still works the same as a regular M2 and only as a cache).

I have a Samsung 970 evo plus 250gb as M2

**Comment by AuxXxilium** [comment]
1) can't tell you why. need serial log to find why

2) nvme addons are still experimental and not working on every hardware.

**Comment by lev666** [comment]
> 1) can't tell you why. need serial log to find why
> 
> 2) nvme addons are still experimental and not working on every hardware. select both addons is simply wrong. 

1) I don't know what it was related to, but while I was testing the NVMe addons separately - the connection speed stabilised 

2) I tested both addons separately and alas for me they were not working (I understand that they are still under development and I believe that you will succeed!).

I think this is the end of this discussion thread. Thank you for your replies!
