### ISSUE TITLE
Syno High Availabilty problem! PLZ Help

### ISSUE THREAD

**Issue by Babaguna** [AuxXxilium/arc#4255]
**Describe the Bug**
Synology High Availability setup crashes with Drive1 error. Drive1 is the downloaded 24.10.20-flat vmdk. 

**Screenshots**
![Syno_HA_Drive1_fail](https://github.com/user-attachments/assets/874e421e-57a5-4bf6-b7a2-b4a7ef39f84f)
![Syno_Drive1+Drive2](https://github.com/user-attachments/assets/a26eaae1-65ab-4d59-9c49-d139d0262904)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
Read wiki and find your issue, i guess it is written there.
