### ISSUE TITLE
Support for Dell T7610 Precision network adapters

### ISSUE THREAD

**Issue by RvN73** [AuxXxilium/arc#4262]
Trying to install on a Dell T7610 Precision with 2 network adaptert of type Intel 82579 og Intel 82754.

Arc is unable to locate these adapters

Any chance to implement drivers for these :)

**Comment by AuxXxilium** [comment]
e1000e linux module is included. nothing to do for me. check your bios settings. fyi: some oem need directboot to get it working, because they did something we can't figure out inside bios/uefi firmware.

**Comment by RvN73** [comment]
Yes, got it working :)

But now there seems to be another issue. If i put more than 2 memory modules into the machine, DSM starts to complain about ECC memory error. I have tried several different modules, also different sizes.

**Comment by AuxXxilium** [comment]
sounds like bios issue or bios settings issue
