### ISSUE TITLE
NIC Virtual Function Not Working Correctly

### ISSUE THREAD

**Issue by whoshoe** [AuxXxilium/arc#429]
**Describe the bug**
When passthrough a VF to the DSM VM in KVM, it correctly recognize it in the loader but failed to build loader. 

**Screenshots**
I got multiple entries in the log. Maybe it failed to set the MAC address of the VF but I couldn't set "Not set MAC at boot" to true in the loader config.

`Jul 30 17:29:12 kernel: ixgbe 0000:01:00.1 eth3: VF Reset msg received from vf 1`
`Jul 30 17:29:12 kernel: ixgbe 0000:01:00.1 eth3: VF 1 requested invalid api version 6`
`Jul 30 17:30:20 kernel: ixgbe 0000:01:00.1 eth3: VF 1 attempted to override administratively set MAC address`
`Jul 30 17:30:20 kernel: Reload the VF driver to resume operations`

**Comment by AuxXxilium** [comment]
Remove arc patch and try again

**Comment by whoshoe** [comment]
I am using unRAID as my hypervisor and I am able to set the MAC of the VF from the host itself. Just did some googling but couldn't any info on allowing mac changes from a guest os in KVM. 

Any idea how to set the "Not set MAC address at boot" to true in the loader config? I was unable to set it during testing.

**Comment by AuxXxilium** [comment]
use latest build. is fixed

**Comment by whoshoe** [comment]
I'll try the new build. Thank you!
