### ISSUE TITLE
Face recognition not working after latest patch

### ISSUE THREAD

**Issue by MartinKuhl** [AuxXxilium/arc#4317]
With the latest patch (https://github.com/AuxXxilium/arc-addons/commit/f5c6f6ccf1b19ce9cdf485fabd92e4583f3f2edb)
the Face recognition is not working for me anymore.
When I now setup a new DSM with ARC patch version 24.10.17 the face recognition is not working like before.

**Comment by AuxXxilium** [comment]
wrong photos version

**Comment by MartinKuhl** [comment]
@AuxXxilium I used the latest version which was available in the syno App Store for 7.2.1. which version should I use than?

**Comment by AuxXxilium** [comment]
not the latest. syno is moving everything to online validation.

**Comment by MartinKuhl** [comment]
I installed version V1.6.2-0710 which is from January this year and this version was working all the time before.

**Comment by MartinKuhl** [comment]
@AuxXxilium if I just apply https://github.com/jinlife/Synology_Photos_Face_Patch/blob/main/bin/patch.sh (the original patch) everything is working as intended. I am on DSM 7.2.1 U5 and Synology Photos 1.6.2-0720.

**Comment by AuxXxilium** [comment]
you saw there is a fix on .29

**Comment by MartinKuhl** [comment]
you are fast. I added the info that I was already using .29 in the hope that this update will fix the issue.
