### ISSUE TITLE
problem with loader v23.7.38

### ISSUE THREAD

**Issue by dib8670** [AuxXxilium/arc#433]
I have a problem with the latest version v23.7.38, the loader does not display information in the info in the DSM and reads it to me and shows it as a USB drive. The USB loader also shows the HDD status warning that the HDD has not been vaporized, but when I go in to read the HDD status, it shows that everything is fine, so far I have not never had any problems with any version except this one now. How can I solve this problem?

**Comment by AuxXxilium** [comment]
reflash your stick. i have many reports that the loader is working.

**Comment by dib8670** [comment]
Work with new releases
