### ISSUE TITLE
Checksum mismatch when running update ARC Loader?

### ISSUE THREAD

**Issue by HHawk** [AuxXxilium/arc#4365]
Hi there. Thank you for your work! Highly appreciated. Kinda inexperienced with your loader, so my issue is probably because I am an idiot. But...

I decided to update to a new ARC Loader version. So I selected the update option from the boot. However it downloads, but gives me a "Checksum Mismatch" on all downloads? See also included screenshots.

No clue if it's important. The NIC is a PCIe Realtek RTL8125 2.5G card. Works fine for everything else and has been stabel for quite some time. Any idea? In the meantime I will re-run the update once again. In the meantime (my other issue got closed automatically) I retried it again, but exact same issue.
![photo_2024-11-02_10-06-28](https://github.com/user-attachments/assets/56a5452e-fd83-4de7-8061-6410b39507c1)
![photo_2024-11-02_10-06-29 (2)](https://github.com/user-attachments/assets/2f6fba11-e5a6-449c-af6c-5f98e7db5c7d)
![photo_2024-11-02_10-06-29](https://github.com/user-attachments/assets/750409c7-7ab0-44bc-b317-cbb3d5b1df22)

Uploading video_2024-11-02_10-26-52(1).mp4…

Maybe it's just coincedende though...

**Comment by HHawk** [comment]
Apparently video is not uploaded? 

https://github.com/user-attachments/assets/58d1c03b-1a7b-4f0a-bd15-4d226f24b096

**Comment by AuxXxilium** [comment]
read releasenotes!

**Comment by HHawk** [comment]
Oooooops. Sorry. I am new and I choose this loader because it was easy to upgrade. Didn't know I had to re-flash. :-)
Thank you, working now. Regards.
