### ISSUE TITLE
Problem with connecting to the ARC loader via LAN for customisation 

### ISSUE THREAD

**Issue by lev666** [AuxXxilium/arc#440]
**Describe the bug**

Problem with connecting to the ARC loader via LAN for customisation 

**Screenshots**

![IMG_20230806_184525_085.jpg](https://github.com/AuxXxilium/arc/assets/63856055/db608714-f732-48bd-8cd5-a9c97b6a520a)

**Additional context**

Good afternoon, since version 23.8.2 I can't connect to the bootloader for configuration via LAN from another computer, what can this be due to?

**Comment by AuxXxilium** [comment]
Read wiki first

**Comment by lev666** [comment]
> Read wiki first

You mean you want a detailed log? 

Since re-reading the wiki, that's all I can assume you mean.

**Comment by AuxXxilium** [comment]
have you updated loader? have you tried to connect to the correct port and not only ip?

**Comment by AuxXxilium** [comment]
the fun is, there is nothing changed that can cause this.

**Comment by AuxXxilium** [comment]
only if usb storage is detected

**Comment by lev666** [comment]
> have you updated loader? have you tried to connect to the correct port and not only ip?

I was able to run the latest downloader, but I just had to enter the ipi without port, and otherwise entering 7681 or 5000 it did not open the page for some reason. Problem solved, thanks
