### ISSUE TITLE
tbao r3 still can't boot after compile

### ISSUE THREAD

**Issue by Rick4hun** [AuxXxilium/arc#444]
"tbao r3" mini nas server  still can't boot after compile, but if i install it to same machine  through proxmox, everything's works. Pls check, have you any driver to 2.5LAN "8086:125c"? I get only 10MB/S (100Mbit) speed r/W, but all other function works good. 
 
![prox ok1](https://github.com/AuxXxilium/arc/assets/139920348/7db225b1-8a32-4e56-9b5a-c31d622793f0)

**Comment by AuxXxilium** [comment]
Is working. I use I225, R8125 and AQC in my systems. Everything is working.
