### ISSUE TITLE
Failed to install DSM

### ISSUE THREAD

**Issue by alepodj** [AuxXxilium/arc#454]
**Describe the bug**

DMS fails during initialization process with error messages below at 55% everytime:

```
Failed to install DSM
Failed to install the file. The file is probably corrupted.
```

**Screenshots**

![image](https://github.com/AuxXxilium/arc/assets/24709042/bc4a1318-3034-4486-ae98-d9e61f0ec9cb)
![image](https://github.com/AuxXxilium/arc/assets/24709042/8fa7982f-90f4-45de-8248-eeff16e544b3)
![image](https://github.com/AuxXxilium/arc/assets/24709042/8404fe7a-cbc8-4b10-b927-3036370b07f0)

**Additional context**

- Arc: Running on a USB to M.2 Sata adapter/case, connected via USB to the back of the server but i have also tried in an internal M.2 slot with the same results.
- System: HP DL380 Gen10, 10 drives detected, connected to the onboard sata controller
- Tried both .pat via internet or manually
- arc-23.8.11.img.zip

**Comment by alepodj** [comment]
Ok somehow it went thru now, i dont know if the amount of times i tried between the last 2 days, but the only thing i changed was booting from a different USB device type. I was using a USB to M.2 Adapter and went directly to a regular USB drive, but i swear i thought i tried that 1st lol

**Comment by AuxXxilium** [comment]
For boot, you need an usb stick if you want to use it baremetal, for dsm installation you need an internal/external disk that is not a nvme!
