### ISSUE TITLE
Some addons and add-ons have the same name. DVA3219

### ISSUE THREAD

**Issue by ITNetSystem** [AuxXxilium/arc#455]
![image](https://github.com/AuxXxilium/arc/assets/135026873/29f63fd2-542d-4de1-949d-bb2b85db967e)
![image](https://github.com/AuxXxilium/arc/assets/135026873/dfea075e-3e88-4d1e-91c5-05c27409900e)
![image](https://github.com/AuxXxilium/arc/assets/135026873/edd5c45b-c95c-4d2f-92fc-14fa709598fe)

**Comment by ITNetSystem** [comment]
![image](https://github.com/AuxXxilium/arc/assets/135026873/5c5dbe87-11ce-43ef-944c-dbeff2655718)
Also, when choosing the oob add-on, it is written in the config not to use

**Comment by ITNetSystem** [comment]
After a complete update of the loader, there is no doubling. The question about oobctl, why was it removed from the config? Is it enough to include only the oob extension?

**Comment by AuxXxilium** [comment]
Yes the oob addon do the same while boot as the commit in config. the config will be added in the same place and time in boot ways. but with the new way, user have more control.
