### ISSUE TITLE
arc-reboot

### ISSUE THREAD

**Issue by ITNetSystem** [AuxXxilium/arc#456]
I have such a question. I assembled the loader, and clicked boot, after booting I get to ip:5000 with offers of migration, recovery, and so on. Everything happens on the physical hardware, but there is no access to it now, for example, and I want to edit the config again without clicking reinstall. I log in using telnet and root account without password and run the script arc-reboot.sh config, the PC restarts and I get into the config, but after a few seconds it continues to load the DSM. How can I force a pause?

![image](https://github.com/AuxXxilium/arc/assets/135026873/bdc4bca3-2ef9-4481-894f-523f09a2a97e)

**Comment by AuxXxilium** [comment]
If it force to boot, reflash your stick.

**Comment by ITNetSystem** [comment]
![image](https://github.com/AuxXxilium/arc/assets/135026873/45637888-cc9b-4f20-bb11-ad27f05f754b)
I understand that I can do this when I am near the computer, but I would like to do it remotely. As I said earlier, after building the loader and clicking load dsm, I want to get back into configuration mode when the dsm is not loaded yet.

**Comment by AuxXxilium** [comment]
no way if dsm isn't loaded
