### ISSUE TITLE
syntax error when loading 

### ISSUE THREAD

**Issue by rickiedinsdale** [AuxXxilium/arc#468]
Syntax error when loading before detecting ethernet once detected ethernet goes back to configuration screen tried doing a full install but does same thing

**Comment by AuxXxilium** [comment]
Please provide all informations that are mentioned that i need to help.

**Comment by ttlandcmos** [comment]
Syntax error loading boot.sh | line 22... double "&&" After removing the extra, boot loads fine... but console doesn't load :(

I remember two modes, junior mode for first install or migration and DSM mode when DSM is fully loaded.

NOTE: Console does not load from version arc-23.8.6a...

**Comment by AuxXxilium** [comment]
This typo is correct, is removed in 23.8.12c.

Console has some issues, this is known.
