### ISSUE TITLE
Patched surveillance station cause desktop app freezing/ lost cam video

### ISSUE THREAD

**Issue by Rick4hun** [AuxXxilium/arc#495]
Hello! finally it can boot my mini nas server Topton n1pro, the only one bios setting caused freezing boot, after i set "amd cbs uart" to disabled, everytings went very fast.   
But unfortunately, tried your image  on more baremetal servers, if i patch surveillance, get 58 cams, but the desktop app after a half hour begin freezing, stopping camera. Tried everything, all case finished same result, if i uninstall and reinstall surveillance station to nas without files and settings, get 2 cams, but  everything's works fine. If i reinstall it with 58 lic, after 30-40 mins began freezing. Tick to X at right corner on my pc, close desktop app surveillance station client, then  start again, and then works without any issues,  another 30-40 mins. Get same result with clean install, and same with restored backup settings.   
What will be the solution? Thank You! 

![camlost](https://github.com/AuxXxilium/arc/assets/139920348/1d525c75-19b2-41ba-b53a-c763c062c386)

**Comment by Rick4hun** [comment]
So again, tried everything, after i patch, but use only one camera, so
there's no too much data, but unfortunately everytime got freezing with
patch, and works like a charm  without patch, checked  it can  works from
am 8:00 until pm 10:00 without any freezing. After patching, freezing begin
again.
I am understand, if  it will be a restarting hourly, it's not bug, it's a
feature! :-))
Have you any other method, to bypass that hourly freezing, or it's an only
one method to fix?

Thank you very much for your work!

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 18:58):

**Comment by AuxXxilium** [comment]
Provide the informations i mentioned if you will report a bug or i can't do anything.

**Comment by AuxXxilium** [comment]
first: there is a preset for issues!
second: i wrote on arc page:

```
ARC Redpill Loader for DSM 7.x
Bugreport
Before you report an issue or bug please read the [Wiki](https://github.com/AuxXxilium/AuxXxilium/wiki) and make sure your setting are correct.
If you have to report an issue or bug:
Hardware you use (Networkchip, Sata/HBA/Raid Controller)
Screenshot the Systeminfo (Arc - Sysinfo) !!! <- IMPORTANT
Links
[Overview](https://github.com/AuxXxilium)
[Wiki and Informations](https://github.com/AuxXxilium/AuxXxilium/wiki)
[Download Release Build](https://github.com/AuxXxilium/arc/releases?q=prerelease%3Afalse&expanded=true)
[Download Development Build](https://github.com/AuxXxilium/arc/releases?q=prerelease%3Atrue&expanded=true)
Thanks
All code was based on the work of TTG, pocopico, jumkey, fbelavenuto and others involved in continuing TTG's original redpill-load project.
```

Is reading such a problem for you?

**Comment by Rick4hun** [comment]
Okay, i can understand. But i wrote, it's an universal issue, get same
result with patched only,  an get same if i use newest, or older itx config.
Actual hardware is: Topton N1pro AMD Ryzen5-5500u, (6C/12T), 2X8GB
DDR4-3200 SoDIMM RAM, 2X2.5G i226V dual lan ports,  8TB WD red plus, 2X 512
Kingston NVME SSd to R/W cache. Boot from a 8GB microSD card through i/o
shield microSD slot.
tried before: Node 304 case, i3-10100 CPU, Asrock H470m- ITX AC 2X8GB
DDR4-3200 GSkill memory modules, 6TB WD purple. Boot from a 20GB Intel 510
SSD
I haven't any additional infos about hardware, hope this will help!

Thank you!


Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 19:15):

**Comment by AuxXxilium** [comment]
And now i need the Screenshot!

**Comment by Rick4hun** [comment]
Screenshot about what? Webinterface, desktop app with lost connection icon
or log center? Checked log center, there's no log about that issue.

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 19:39):

**Comment by AuxXxilium** [comment]
Screenshot the Systeminfo (Arc - Sysinfo) !!! <- IMPORTANT

Do you read what i write?

```
ARC Redpill Loader for DSM 7.x
Bugreport
Before you report an issue or bug please read the [Wiki](https://github.com/AuxXxilium/AuxXxilium/wiki) and make sure your setting are correct.
If you have to report an issue or bug:
Hardware you use (Networkchip, Sata/HBA/Raid Controller)
Screenshot the Systeminfo (Arc - Sysinfo) !!! <- IMPORTANT
Links
[Overview](https://github.com/AuxXxilium)
[Wiki and Informations](https://github.com/AuxXxilium/AuxXxilium/wiki)
[Download Release Build](https://github.com/AuxXxilium/arc/releases?q=prerelease%3Afalse&expanded=true)
[Download Development Build](https://github.com/AuxXxilium/arc/releases?q=prerelease%3Atrue&expanded=true)
Thanks
All code was based on the work of TTG, pocopico, jumkey, fbelavenuto and others involved in continuing TTG's original redpill-load project.
```

**Comment by Rick4hun** [comment]
Attached before under the description.. :-)

Attach again:


Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 20:02):

**Comment by AuxXxilium** [comment]
There is no picture if you answer with email.

**Comment by Rick4hun** [comment]
[image: image.png]

[image: image.png]


Once and second.

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 20:43):

**Comment by AuxXxilium** [comment]
upload per mail does not show anything!!!

**Comment by Rick4hun** [comment]
Strange, i upload it  to that site: https://kephost.net/p/OTcwNDky.jpg

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 20:53):

**Comment by AuxXxilium** [comment]
than i can tell you, you will loose connection every hour after booting dsm

**Comment by Rick4hun** [comment]
Okay, i can understand that, if you haven't plan to made any solution in
the future, i will try another method, i have a 10ch 4K NVR, uninstall
surveillance station, and plug that nvr to main power.

Thanks, for your informations, best regards!

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 21:13):

**Comment by Rick4hun** [comment]
Okay, thank you!

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 21., H, 21:39):
