### ISSUE TITLE
Question on Intel Geminilake based models.

### ISSUE THREAD

**Issue by navhawk80** [AuxXxilium/arc#501]
Hello. I just find out at Wiki for Arc Loader that synology models based on Intel Geminilake (for example [DS920+](https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Model-List-for-Arc#ds920)) have up to 16 Threads. Is it correct or just typo and thay have only 8 threars maximum? Unfortunatelly I do not have physical access to my xpenology at the moment and can not check it myself but if it is true I will move to arc loader next opportunity.
I'm asking because I have intel Xeon with 16 threads and iGPU but now I have to choose: 16 threads and no hw transcoding or just 8 threads and hw transcoding. It will be really the best if I'll have 16 threads and hw transcoding.
Thank you.

**Comment by AuxXxilium** [comment]
https://www.youtube.com/watch?v=vflLJb4WMAU
