### ISSUE TITLE
Keyboard layout selected in loader, doesn't work on "Console Output for DSM" addon.

### ISSUE THREAD

**Issue by ttlandcmos** [AuxXxilium/arc#504]
**Describe the bug**
Keyboard layout selected in arc loader, does not work in "Console Output for DSM" addon... but in the "arpl" console work without problem.

**Screenshots**
![1](https://github.com/AuxXxilium/arc/assets/111214957/a0e5daa2-db51-4394-8299-1a43f685a666)
![2](https://github.com/AuxXxilium/arc/assets/111214957/8f6efb2c-cb14-4b70-9eee-8c90035d1379)
![3](https://github.com/AuxXxilium/arc/assets/111214957/c06b91ed-10f3-40f9-841c-ff694c3f9f8a)
![4](https://github.com/AuxXxilium/arc/assets/111214957/a2ab92ab-5662-404e-bc21-d5f5b9ce7475)

**Additional context**
Tested in the arc loader release 23.8.18.

PD: Sorry for my bab english.

**Comment by AuxXxilium** [comment]
please look in "advanced" - "edit user config" if you value will be set.
