### ISSUE TITLE
denverton i915 support

### ISSUE THREAD

**Issue by navhawk80** [AuxXxilium/arc#506]
Please advise how to get i915 (Intel Graphics) in [DVA3219](https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Choose-a-Model#denverton---nondt) working. Info from WiKi. Or is it support only nvidia?

**Comment by navhawk80** [comment]
Thanks. I do have J5005 with iGPU uhd605. It is working with DS918+ and DS920+ but with DVA3219 /dev/dri is empty. 
DVA3219 doesn't support uhd605?

**Comment by AuxXxilium** [comment]
Is supported yes. You have selected the i915 Addon?

**Comment by navhawk80** [comment]
I did not select i915 addon as it is not available for DVA3219 as you wrote. For DS918+ and DS920+ i915 addon even is nor required to get igpu working. 
Is uhd P630 or uhd 630 supported by DVA3219?

**Comment by AuxXxilium** [comment]
Only the stock iGPU from DVA are supported, so you have to look which one is supported.

**Comment by AuxXxilium** [comment]
As i see, 3219 is Nvidia GPU so you can only go for 1622

**Comment by navhawk80** [comment]
hm.... DVA3219 has Intel Atom C3538 which does not have igpu yet. Only nvidia GPU is available.

> As i see, 3219 is Nvidia GPU so you can only go for 1622
That was my main question. So it doesnt support intel igpu yet as written in [WiKi](https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Choose-a-Model#denverton---nondt) and support only nvidia gpu.
All is clear now.

**Comment by dj-nsk** [comment]
Hi ! 
AuxXxilium, can You add CPU 2 I9-9900K support in the i915 addon?
CoffeeLake-S GT2 [UHD Graphics 630]
Device ID 0x3e98

And now I have to manually fix i915.ko every time after the update...
Thanks!
