### ISSUE TITLE
No booting Loader

### ISSUE THREAD

**Issue by zlodeychik** [AuxXxilium/arc#5079]
Good afternoon!
I can't load into Loader.
After booting from USB, the main Loader window appears.
Select Arc Config Mode.
![1](https://github.com/user-attachments/assets/aab1035e-96e3-4be3-a0aa-c269d5615074)
Nothing happens next. The cursor does not blink after "Booting...". The USB flash drive is also not flashing.
![2](https://github.com/user-attachments/assets/e1d20efa-f838-40da-bcb8-fe42cccb89d9)
I tried to change the USB flash drive and different versions of **arc-1.1.18 ... arc-24.10.27** do not work. Memtest86+ doesn't start either, stops on Booting.

**Hardware**
Fujitsu Esprimo c720 MB: FUJITSU D3224-A1, Intel Q85 chipset
QuadCore Intel Xeon E3-1265L v3, 2500 MHz, 16GB RAM
Intel(R) Ethernet Connection I217-V

**Comment by dyter69** [comment]
same problem, arc not boot with 16GB on J5040

( boot ok with 8GB but not with 16GB)

**Comment by dyter69** [comment]
I found, Aperture Size in SOC-Bridge (BIOS) doesn't exced 256MB for IGPU
