### ISSUE TITLE
Arc console does not load again

### ISSUE THREAD

**Issue by ttlandcmos** [AuxXxilium/arc#509]
**Describe the bug**
Arc console does not load again...  But in the arc loader v23.8.18 loads without problem.

**Screenshots**
![Not load](https://github.com/AuxXxilium/arc/assets/111214957/659980d5-1ff4-4321-a570-ecc6b2a2b2b1)

**Additional context**
Tested in arc loader v23.8.19

**Comment by AuxXxilium** [comment]
wrong. tested yesterday and made video that will be online today. console is working.

**Comment by ttlandcmos** [comment]
I understand, I try to replace the loader and add the serial port... I share the log

**Comment by AuxXxilium** [comment]
and why do you use legacy in a hypervisor?

**Comment by ttlandcmos** [comment]
I test the arc loader with the minimum possible architecture only for flexibility tests... but for future updates is it recommended to use UEFI boot?

**Comment by AuxXxilium** [comment]
Like i wrote: UEFI recommended

**Comment by ttlandcmos** [comment]
Try fresh install, boot uefi, vmware hypervisor and console doesn't start.
![Fresh install](https://github.com/AuxXxilium/arc/assets/111214957/4d96899f-f3aa-4468-86c7-812350f4f3cf)

I attach the serial log:
[serial log.txt](https://github.com/AuxXxilium/arc/files/12433733/serial.log.txt)

**Comment by AuxXxilium** [comment]
than you have an issue in your settings. you selected console in addons?

i update all my systems today, 13x vm and 5x native and on every system console is working.

**Comment by ttlandcmos** [comment]
My custom settings are:
![Addons settings](https://github.com/AuxXxilium/arc/assets/111214957/35eeda59-3dd0-4bd7-8fae-80f6ddab3bca)
![DSM extensions](https://github.com/AuxXxilium/arc/assets/111214957/265f49bf-b374-4c8b-aa15-6664084a4b8b)

Do not modify any other parameter...

PD. Those configurations I use in the arc loader v23.8.18 and the arc console loads without problem.

It's strange...

**Comment by ttlandcmos** [comment]
Sorry! attached sysinfo...

![sysinfo](https://github.com/AuxXxilium/arc/assets/111214957/29c0a49a-de47-48a0-a364-c6f96f098cdd)

**Comment by AuxXxilium** [comment]
> My custom settings are:
> 
> ![Addons settings](https://github.com/AuxXxilium/arc/assets/111214957/35eeda59-3dd0-4bd7-8fae-80f6ddab3bca)
> 
> ![DSM extensions](https://github.com/AuxXxilium/arc/assets/111214957/265f49bf-b374-4c8b-aa15-6664084a4b8b)
> 
> 
> 
> Do not modify any other parameter...
> 
> 
> 
> PD. Those configurations I use in the arc loader v23.8.18 and the arc console loads without problem.
> 
> 
> 
> It's strange...

first these 2 nvme extensions are not possible to use together. only use one here.

**Comment by ttlandcmos** [comment]
Again, try clean installation, UEFI boot with vmware hypervisor, but now with the new version of the arc loader v23.8.20 and the arc console does not load :(

Attached video and serial log...

https://youtu.be/trwy3w9hTCk

[arc-serial.txt](https://github.com/AuxXxilium/arc/files/12444535/arc-serial.txt)


What am I doing wrong? :(

**Comment by AuxXxilium** [comment]
your are kidding me. .20 is a recompiled .18
