### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by anschein** [AuxXxilium/arc#510]
CPU:intel w-3323
PVE:8.0.3
I have a brand new DSM installation on PVE. When using arc, CPU selects HOST, DSM GUEST will be stuck in infinite restart. When I change the CPU to other types such as qemu64, it can start normally. Does it support w-3323? Is it the CPU or is something wrong with one of my settings?

**Comment by AuxXxilium** [comment]
looks like there is something wrong with your settings. cpus doesn't need any support. but please don't ask me for pve settings. i linked a community video in wiki. don't know if this will help you.

**Comment by anschein** [comment]
According to further tests, other settings remain unchanged. When using direct boot, you can enter the installation interface. What is the difference between direct boot and normal boot?

**Comment by AuxXxilium** [comment]
direct boot load directly dsm kernel without any changes.
