### ISSUE TITLE
Problem with changing MAC addresses on network cards.

### ISSUE THREAD

**Issue by veskoaj** [AuxXxilium/arc#5104]
Hello, until now I was using arcloader version 23.10.27, which I had configured for the DVA3221 and used my own MAC addresses and serial number to register the server. In fact, this version only changed the MAC address on LAN1, while the others remained unchanged, but that was fine for me.
I decided to upgrade to a newer version of arcloader, version 1.1.19, and I used two different disks (not the existing RAID) to configure the system in the same way. However, it turned out that the loader does not change the actual MAC addresses to the ones I specified, resulting in many services not working. I made another configuration using the ARC patch and automatically assigned MAC addresses and serial number, but again the MAC addresses remained the original ones from the network cards, with only the serial number being changed.
I used arc-control_x64-7.0_1.1-0 and tried to change the MAC address via the DSM interface, but after a restart, nothing changed again. I looked at the XML file where the desired MAC addresses are listed.
I am attaching the system info and some other screenshots.  If more details are neded , Im ready to provide.
Thanks !
![1](https://github.com/user-attachments/assets/92a35752-2b20-43cb-aee3-f184ad3c086e)
![2](https://github.com/user-attachments/assets/9e5b1ecb-b5d7-4f1c-8050-5f206537b8a6)
![3](https://github.com/user-attachments/assets/e48c7917-97b4-463a-a3a5-03fcb92acfe2)
![4](https://github.com/user-attachments/assets/297a50c7-b54e-49e9-8b61-d1e190d73767)
![5](https://github.com/user-attachments/assets/39fe3ac8-528a-407e-8e67-5d52240b0117)

**Comment by veskoaj** [comment]
So, in short
**With old loader Arc23.10.27**, after installation my xpenology DSM was with:
sinology valid serial number ................................................- 2070SJRYX….
and sinology valid mac address (related to serial).......- 9009D02A......
like this:

![Picture1](https://github.com/user-attachments/assets/3eba6ad1-6a17-4670-9a74-ca8719baa4d5)
![Picture2](https://github.com/user-attachments/assets/aacf95eb-2557-4112-a5cd-ee13ba057a43)

**Now with Arc 1.1.19**, after installation my DSM have:
sinology valid serial number..................................................- 2070SJRYX….
**but mac address is sinology non valid (fake)** ..............- 3CECEF02E…
even though I entered sinology valid mac ( 9009D02A....), it remains unchanged (Lan card mac), like this: 
![3](https://github.com/user-attachments/assets/29593183-e632-4a33-827e-2ff3fd58e20a)

As result many services like QC, sinology DDNS etc. does not work.
Thanks!
Regards.

**Comment by AuxXxilium** [comment]
> So, in short **With old loader Arc23.10.27**, after installation my xpenology DSM was with: sinology valid serial number ................................................- 2070SJRYX…. and sinology valid mac address (related to serial).......- 9009D02A...... Serial number and MAC number was my own , entered by me like this:
> 
> ![Picture1](https://private-user-images.githubusercontent.com/190822574/393336829-3eba6ad1-6a17-4670-9a74-ca8719baa4d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDQ4NDAsIm5iZiI6MTczMzUwNDU0MCwicGF0aCI6Ii8xOTA4MjI1NzQvMzkzMzM2ODI5LTNlYmE2YWQxLTZhMTctNDY3MC05YTc0LWNhODcxOWJhYTRkNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNzAyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTQ0MzYxNjk1ODNhZGEzYjQwZWQ1Nzk4MTVkMzkyNGI5NjE1Yzk1NDhhN2JiZTNmMzVkYjU1ZTg3MGJhNGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0swnK5D8Kqsob_n7TkvRFKUp4qmoZdfSI6Q0PyB0fMA) ![Picture2](https://private-user-images.githubusercontent.com/190822574/393336879-aacf95eb-2557-4112-a5cd-ee13ba057a43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDQ4NDAsIm5iZiI6MTczMzUwNDU0MCwicGF0aCI6Ii8xOTA4MjI1NzQvMzkzMzM2ODc5LWFhY2Y5NWViLTI1NTctNDExMi1hNWNkLWVlMTNiYTA1N2E0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNzAyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTEzYzZiZDA2ODA5ODE2MjFmOWI2YzExMmQ5NTZiYjliM2I0M2Y2N2E4N2MwZjEyOWE1YjU0MzY3OWE5MDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FvISOf-Mf7hEHY83uZuzVUc0eNr9KNPoyMrcCX7Q5rE)
> 
> **Now with Arc 1.1.19**, after installation my DSM have: sinology valid serial number..................................................- 2070SJRYX…. **but mac address is sinology non valid (fake)** ..............- 3CECEF02E… even though I entered sinology valid mac ( 9009D02A....), it remains unchanged (Lan card mac), like this: ![3](https://private-user-images.githubusercontent.com/190822574/393337057-29593183-e632-4a33-827e-2ff3fd58e20a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDQ4NDAsIm5iZiI6MTczMzUwNDU0MCwicGF0aCI6Ii8xOTA4MjI1NzQvMzkzMzM3MDU3LTI5NTkzMTgzLWU2MzItNGEzMy04MjdlLTJmZjNmZDU4ZTIwYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNzAyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTk2MzU4ZDkzYjJkZWZiODVkMDQ5NjVkODY2OGYyZWZkYWZkMGUxYmYwOGYxMWEzOTBjM2RjODg4MjljYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4fa0oP-g17ISb-97MvodiSi-i2PdcqQiIbPeH3l55s8)
> 
> As result many services like QC, sinology DDNS etc. does not work. Thanks! Regards.

and again: it was only for usersetting enabled, but we DON'T need it. if you set your values in correct place, everything will work! like other ppl answered you in discord also!
