### ISSUE TITLE
Surveillance Station Restart Every Hour

### ISSUE THREAD

**Issue by whoshoe** [AuxXxilium/arc#511]
**Describe the bug**
After patching the SS, SS restarts itself every hour and causes lost of connection .

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/10238980/9e0ea2e5-c508-4482-8df2-674f081c05de)

**Additional context**
The log is flooded with entries of "Surveillance Station is launched.".

**Comment by AuxXxilium** [comment]
it's not a bug!
