### ISSUE TITLE
Question about Synology NAS models

### ISSUE THREAD

**Issue by teslaweiler** [AuxXxilium/arc#518]
Dear AuxXxilium team,

I hope this message finds you well. I am a user of your loader and I have a question about Synology NAS models. I noticed that some Synology NAS models have "DT" in their names, while others do not. I was wondering if your loader supports both types of models, and if there are any differences between them.

Additionally, I would like to know what "DT" stands for in Synology NAS models. I tried searching for information online, but I could not find a clear answer.

Thank you for your time and assistance. I appreciate your help.

Best regards,
Weiler

**Comment by AuxXxilium** [comment]
You will find everything in Wiki.
