### ISSUE TITLE
cpu freq scaling doesn't work 

### ISSUE THREAD

**Issue by Rick4hun** [AuxXxilium/arc#519]
CUP freq scaling doesn't work, my cpus runs at full speed. 
I have 3 cpu frequencies, 1400, 1700, 2100, set scaling under dsm extensions, save, build loader, reboot,  but doesn't work tried with latest 4 versions. I have a ryzen5-5500u CPU, tried kernel load  power and  kexek, tried  other methods, trauma scaler works, and finally worked, but stuck at lowest speed, ant i get very low points under geekbench. Completely formad disk, and rebuild all, now works, but has slightly higher power consumption. 
Pls check it. Thanks!

 

![IMG_20230827_111826](https://github.com/AuxXxilium/arc/assets/139920348/030874ba-e019-4209-90b7-5058a8ad673f)
![sys1](https://github.com/AuxXxilium/arc/assets/139920348/85cf2194-5b1b-452f-88b3-391347875c33)
![sys2](https://github.com/AuxXxilium/arc/assets/139920348/7d17d28d-1e36-4dd5-baa3-81532aeb7428)
![no scuscaler](https://github.com/AuxXxilium/arc/assets/139920348/b730cb9b-a372-40b8-89f6-74bddbb876ec)

**Comment by AuxXxilium** [comment]
yes, is possible because of amd and depends on your bios settings.

**Comment by Rick4hun** [comment]
Why closed? :D
Without change anything in bios, trauma scaler works. Yours not, so it's
not a bios issue.

Thanks!

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 27., V, 15:12):

**Comment by AuxXxilium** [comment]
what is trauma scaler?

**Comment by Rick4hun** [comment]
https://xpenology.com/forum/topic/19846-cpu-frequency-scaling-for-ds918/

Christian Schulthess ***@***.***> ezt írta (időpont: 2023.
aug. 27., V, 15:43):
