### ISSUE TITLE
Remove Surveillance Station Patch

### ISSUE THREAD

**Issue by whoshoe** [AuxXxilium/arc#525]
Hi,

I have been trying to disable the license path for Surveillance Station but couldn't figured out a way to do it. It seems to me some info is saved to the data disk. I tried:

1. Deselect from addon and rebuild the loader (not working)
2. A new usb flash drive with another DSM model (not working)

How to disable the patch so that it doesn't restart SS every hour?

Thanks!

**Comment by AuxXxilium** [comment]
reinstall dsm

**Comment by AuxXxilium** [comment]
or remove extension and remove ss, reboot and install ss

**Comment by whoshoe** [comment]
> or remove extension and remove ss, reboot and install ss

I created a new flash drive and replaced the first drive, then DSM  was migrated (from DS3622xs to DS920+). All the app previously installed were missing and I uninstalled and reinstalled them but the 58 license was still there.

**Comment by whoshoe** [comment]
I also checked the cron job and was not able to find the task associate with the SS hourly restart

**Comment by whoshoe** [comment]
It's working. Thanks!
