### ISSUE TITLE
add info line "ip from DHCP during Boot" after eth0 in Boot Loader Console/screen

### ISSUE THREAD

**Issue by s0nic9** [AuxXxilium/arc#531]
after "eth0" , informations line in the Boot Loader Console/Screen like :

ip from DHCP during Boot
Not used if ip is set static in DSM

are good reminders !

**Comment by AuxXxilium** [comment]
i think this i clear because noone will set static in dsm (only set them in router or dhcp server)

**Comment by s0nic9** [comment]
and "Active Directory Server+DNS Server"

**Comment by AuxXxilium** [comment]
okay don't know that someone use this trash. but i will add an info.
