### ISSUE TITLE
Error about {BOOTCOUNT} variable appear during ARC/DSM boot

### ISSUE THREAD

**Issue by bandit400** [AuxXxilium/arc#542]
**Describe the bug**
Booting DSM, an error in /opt/arc/boot.sh appear:
![VirtualBox_Synology DSM_10_09_2023_00_54_10](https://github.com/AuxXxilium/arc/assets/52614292/ff14f0d0-7449-4d96-92fc-f9965db9ff40)

Booting ARC configurator, an error in /opt/arc/init.sh appear:
![VirtualBox_Synology DSM_10_09_2023_00_58_04](https://github.com/AuxXxilium/arc/assets/52614292/d8d406ad-2e4a-43c5-9b1a-4184abf4b4da)

**Sysinfo Screenshots** (the {BOOTCOUNT} variable error is also present here)
![VirtualBox_Synology DSM_10_09_2023_00_58_18](https://github.com/AuxXxilium/arc/assets/52614292/1c19e7de-a072-4881-bc96-1c2830cb119f)
![VirtualBox_Synology DSM_10_09_2023_00_58_31](https://github.com/AuxXxilium/arc/assets/52614292/e859ca71-a7ac-495e-b71f-7e4de7cff0b5)

**Additional context**
Running Synology DSM in a VirtualBox virtual machine. VirtualBox version 7.0.6 r155176 (Qt5.15.2)

**Comment by LegionCanadian** [comment]
Glad I'm not the only one getting this. Just fixed a NIC Issue, and now I'm getting this argument.
