### ISSUE TITLE
No drive detected in DVA3221

### ISSUE THREAD

**Issue by teslaweiler** [AuxXxilium/arc#545]
Hi everyone,

I'm having a problem with my HP Zbook Studio G5. It came with three M.2 ports only, and I'm using an Intel i7-9750H Processor and a NVIDIA P2000 GPU. When I select the Dva3221 NAS model in the loader, after booting to the OS, it tells me "No drive detected in dva3221". However, when I select the dva1622 NAS model, it detects the SSD (M.2 hard drive). I even tried to patch the M.2 volume in the loader module and add the HDD to the database, but it still doesn't detect it.

I would really appreciate any advice on how to fix this problem.

Thank you in advance!
![Screenshot from 2023-09-14 07-19-12](https://github.com/AuxXxilium/arc/assets/68001202/4e714a2a-9acb-4a8e-b851-41807deb98d3)

**Comment by AuxXxilium** [comment]
no way for nvme only. is written in wiki too. you need sata drive for dsm installation.
