### ISSUE TITLE
Bug Patching Ramdisk on DSM 7.2

### ISSUE THREAD

**Issue by leroyconstant** [AuxXxilium/arc#562]
Hello,

I want report a bug on ARC Loader with this configuration:

DSM 7.2 > DS3622xs+ and other models
Ramdisk not patch (screenshot)
![image](https://github.com/AuxXxilium/arc/assets/146106162/d544075b-706e-4621-9f4d-986bb994d64e)

The same configuration works with DSM 7.1
Hardware: VMware Platform with 6Gb RAM and SATA controller

Thanks for in advance for review

**Comment by AuxXxilium** [comment]
do you see that syno released an update some hours ago? i can't perform magic.

**Comment by leroyconstant** [comment]
I understand very well.
It was more of a feedback.
Otherwise, it's really a very good basis to work from.
Good luck for the future
