### ISSUE TITLE
Problem with usb

### ISSUE THREAD

**Issue by dib8670** [AuxXxilium/arc#569]
![16959481592764157485490890064128](https://github.com/AuxXxilium/arc/assets/54912239/688f55b6-e7cd-4ad5-9212-a5bb6c87d84e)
I have a problem with the latest version 23.9.10.b not load usb disk in DSM

**Comment by AuxXxilium** [comment]
Use Option "Mount USB as internal" in Arc and try again.

**Comment by dib8670** [comment]
I tried that option and then it sees it as an internal hard disk, not as an external USB, and when I set the option to normal, it doesn't see it at all, as if it doesn't exist, with version 23.9.5 I didn't have any problems and everything works perfectly. And the newer version of DSM 7.2.1 works as it should, although it is a little slower than with the latest loader. I apologize in advance for the broad description

**Comment by AuxXxilium** [comment]
if quickconnect won't work, there is an issue with your settings.

if it is slower, there is something with your dsm. speed can't change and depends on dsm.

the usb issue, you are the only one who has this. :/
