### ISSUE TITLE
9P Support

### ISSUE THREAD

**Issue by brunomgalmeida** [AuxXxilium/arc#572]
Hey, many thanks for the awesome repo. I was trying to set it up locally with qemu, and I noticed that you removed 9P support on this [commit](https://github.com/AuxXxilium/arc-addons/commit/b39e96bf0fe0aaf2b62cfac903a226f474a23708].

What was the reason for the remove? Did you face some issues with it?

**Comment by AuxXxilium** [comment]
i removed 9p and we moved to virtio. every hypervisor that can use 9p should be able to use virtio, too.

**Comment by brunomgalmeida** [comment]
Thanks for the prompt reply. I tried that too and does not work. The virtio/virtiofs is not avalable to mount

``sh
cat /proc/filesystems 
nodev	sysfs
nodev	rootfs
nodev	ramfs
nodev	bdev
nodev	proc
nodev	cpuset
nodev	cgroup
nodev	tmpfs
nodev	devtmpfs
nodev	binfmt_misc
nodev	configfs
nodev	debugfs
nodev	tracefs
nodev	securityfs
nodev	sockfs
nodev	bpf
nodev	pipefs
nodev	devpts
	ext3
	ext4
	ext2
nodev	pstore
nodev	mqueue
nodev	ecryptfs
	btrfs
	hfsplus
	iso9660
	udf
	vfat
nodev	aufs```

nor the linux module exists

```sh
lsmod | grep -i virt
virtio_scsi            10859  0 
virtio_net             20164  0 
virtio_pci             13902  0 
virtio                  5442  3 virtio_net,virtio_pci,virtio_scsi
virtio_ring             6903  3 virtio_net,virtio_pci,virtio_scsi
```

Can you guide me on what I am doing wrong? Thanks

**Comment by AuxXxilium** [comment]
there are multiple guides only for qemu and virtio.
