### ISSUE TITLE
Driver for LCD Display for QNAP TS-869 ?

### ISSUE THREAD

**Issue by ithakaa** [AuxXxilium/arc#577]
First and foremost, I'd like to express my gratitude for the incredible work with the ARC bootloader. Thank you!

Is there any chance of obtaining a driver for the QNAP LCD display TS-869?

**Comment by AuxXxilium** [comment]
no. this will not work with dsm. but good idea.

**Comment by ithakaa** [comment]
There is a driver for TrueNAS, I was hoping to DSM

**Comment by AuxXxilium** [comment]
truenas is completely different than dsm. dsm uses linux as kernel base but much features are removed.

**Comment by ithakaa** [comment]
yes I know that :-)
