### ISSUE TITLE
I9-9900K support in the i915

### ISSUE THREAD

**Issue by dj-nsk** [AuxXxilium/arc#579]
Hi !
Can You add CPU I9-9900K support in the i915 addon?
CoffeeLake-S GT2 [UHD Graphics 630]
Device ID 0x3e98

And now I have to manually fix i915.ko every time after the update...
Thanks!

**Comment by AuxXxilium** [comment]
line 171: https://github.com/AuxXxilium/arc-addons/blob/main/i915/all/usr/bin/i915ids

is allready included.

**Comment by dj-nsk** [comment]
Thanks, but for some reason it doesn't work for me - every time after updating the DSM version, the /dev/dri folder disappears. I have to manually fix i915.ko

**Comment by dj-nsk** [comment]
For information: in my case, the patch did not work, because I have a second video card (NVIDIA) installed and it was set in the BIOS that the priority video adapter is "PCI". In this case, the lspci -n command outputs for iGPU: **0380**: 8086:3e98 (not 0300).
Replacing the priority video adapter in the BIOS with the built-in one returned "0300" to me. Now the patch is working (but you can also adjust the processing of such an option in this line: _GPU="$(${LSPCI_PATH} -n | grep **0300** | grep 8086 | cut -d " " -f 3 | ${SED_PATH} -e 's/://g')"_)

**Comment by AuxXxilium** [comment]
i can change these line yes, but it will not work, dsm need gpu at 0300 or dsm will not use it.

**Comment by dj-nsk** [comment]
it worked for me as with 0380 - the /dev/dri directory is there, the trascoding in Jellyfin works. 
I use a DSM like virtual machine in ESXi, for some reason VideoStation does not want to work with hardware transcoding in this case (even 0300, even 0380), but Jellyfin works

**Comment by AuxXxilium** [comment]
for my systems only 0300 is working, because dsm kernel is fixed to 0300 for igpu.

**Comment by dj-nsk** [comment]
OK, thanks. but so far I have not been able to understand why VideoStation does not transcode under the ESXi virtual machine, even when 0300. I'll keep looking...

**Comment by AuxXxilium** [comment]
there was a config entry for vm needed, but i don't know it anymore.
