### ISSUE TITLE
MB Asus Q170S1: a problem with determining the configuration of modules when creating a bootloader

### ISSUE THREAD

**Issue by SSerhy** [AuxXxilium/arc#580]
the intel i219-lm network adapter is not initialized, because of this, the bootloader is not created. Instead of the e1000e module, the e1000 should be loaded, perhaps??

**Screenshots**
Sysinfo menu:
![IMG_1047](https://github.com/AuxXxilium/arc/assets/129271063/0d808f42-0dd7-408f-a838-757332b60a58)

**Additional context**
please solve this problem, I really want to run DSM on this motherboard.

**Comment by AuxXxilium** [comment]
e1000e is correct for your nic. check bios settings with wiki.

**Comment by vinphan** [comment]
> e1000e is correct for your nic. check bios settings with wiki.
> 
> and update your loader.

Hi Aux,
I know it's not related this issue, but which key i use to save and quit the user config
<img width="585" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/5e3c8ba1-f9f8-4d09-acc7-a96bfd20526f">

**Comment by AuxXxilium** [comment]
TAB to OK and Enter?

**Comment by vinphan** [comment]
> TAB to OK and Enter?

Thank you sir

**Comment by SSerhy** [comment]
please help, I checked all the settings in the bios, it still doesn't work (
Network: 0 Adapter
![IMG_1047](https://github.com/AuxXxilium/arc/assets/129271063/20103653-71bc-40d6-a1e9-5fa769cb8b4a)

**Comment by AuxXxilium** [comment]
there are 2 options, because i have the same chip and this is working. 

1. update firmware on nic
2. you have an asus custom version that will not work with latest linux kernel. (multiple reports in different linux development forum)

**Comment by SSerhy** [comment]
thanks for the help, 
only after the bios update was started, since I had a modified bios, I had to solve the issue of modifying the new bios, so I answer with a delay,
thanks again for the help, you are doing a great job!
