### ISSUE TITLE
Update and restore with code issues

### ISSUE THREAD

**Issue by flemur** [AuxXxilium/arc#581]
Current config: I'm currently on Arc 23.8.12c with model set as DS1520+ and DSM 7.2, 4.4.302, running over ESXi 8.0u2. System runs well as-is.

Steps: When I attempt to update Arc, I see the following steps:
- Boot Arc 
- Choose Configure Loader
- Choose Update
- Choose Full Upgrade Loader
- Arc installs 23.10.1b with no errors
- Arc reports successful and provides a code and says to restore with code
- Reboot
- Configure Loader, Restore with code, Build loader now, Boot arc loader now, Boot DSM
- System comes up with the notice that the interface will not be operational
- DSM never comes online. It changes IP and that new IP never loads in a web browser. The page stays "loading" forever. It is pingable, but that is the only indication that it's up.

I'm not aware of any other steps required to do these updates, but I cannot update without installing a fresh loader from scratch.

**Comment by AuxXxilium** [comment]
Is not possible with latest versions because of config changes
