### ISSUE TITLE
Customize 2 Nic's with custom MAC address

### ISSUE THREAD

**Issue by mahmoudhamadeh** [AuxXxilium/arc#582]
Moving from fbelavenuto/arpl to ARC, I have 2 nic's, both should be connected to network, each with a custom MAC address.  It used to be working with fbelavenuto/arpl by adding command line netif_num: "2" then listing mac1/mac2. With ARK, I tried everything and was not able to get the custom mac address to show in DSM. Eventually, I managed to get mac1 to custom by installing ARC with patch, the second nic still showing the physical MAC. It is also confusing because if you look at sysinfo herewith, you can see IP address assigned to physical card but the custom MAC showing disconnected, but see in screenshot in DSM it is the other way around!

How I can make 2 nic's to show in DSM with custom MAC address?

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/26927138/8f12147b-a248-4562-90ab-f77a5c653174)
![image](https://github.com/AuxXxilium/arc/assets/26927138/c074d38d-8042-4c41-8037-380d98ba249b)

**Comment by AuxXxilium** [comment]
we only need mac1 as fake and everything is working. no need to change second and with only first faked, everything is more fluid and stable.

**Comment by Cyber-Snoop** [comment]
Hello,
Thank you for your work, really appreciated,
I have the same problem with my config,
I tested with this commands:

![PXL_20231003_054329585](https://github.com/AuxXxilium/arc/assets/146823814/42dbf889-49ae-453a-aae0-09ccc5b719f0)

![capture_2023-10-03 13h37_20](https://github.com/AuxXxilium/arc/assets/146823814/0e68ff44-b807-4164-b465-6332904f6f10)

but when I creat a bond with this two, I lose the connection to my DSM
i tried without the command describe above and same problem

Thanks by advance for your help

**Comment by AuxXxilium** [comment]
no i won’t because we destroy more than we win.
