### ISSUE TITLE
Creating LAN Bond   (Customize 2 Nic's with custom MAC address)

### ISSUE THREAD

**Issue by Cyber-Snoop** [AuxXxilium/arc#583]
From this comment : https://github.com/AuxXxilium/arc/issues/582#issue-1923277459

Hello,
Thank you for your work, really appreciated,
I have the same problem with my config,
I tested with this commands:

![PXL_20231003_054329585](https://github.com/AuxXxilium/arc/assets/146823814/42dbf889-49ae-453a-aae0-09ccc5b719f0)

![capture_2023-10-03 13h37_20](https://github.com/AuxXxilium/arc/assets/146823814/0e68ff44-b807-4164-b465-6332904f6f10)

but when I creat a bond with this two, I lose the connection to my DSM
i tried without the command describe above and same problem

Thanks by advance for your help

**Comment by AuxXxilium** [comment]
it's normal that you loose the connection if you create bond. bond uses mac from first nic. fake or not. it takes some time to to get an ip, sometimes dsm need a reboot.

your custom settings won't work anymore. because of dsm changes and we had to change cmdline for 7.2.1. also the new cmdline provides less issues with mac and nic and more stability.

**Comment by AuxXxilium** [comment]
![Screenshot 2023-10-03 161128](https://github.com/AuxXxilium/arc/assets/67025065/7d66fbc3-d6a5-4240-8a80-c116d4c48326)
![Screenshot 2023-10-03 161017](https://github.com/AuxXxilium/arc/assets/67025065/42553824-63a0-41f9-86dd-301215ea1de5)
![Screenshot 2023-10-03 161044](https://github.com/AuxXxilium/arc/assets/67025065/0ce69eb7-8e8c-49ff-9077-4e0f51e69f6b)

Bond is working like it should

**Comment by Cyber-Snoop** [comment]
Hello,

Thank you very much for your answer !

So, I made a fresh install with ARC v23.10.1b
My steps: Select DS923+ / 7.2 / ARC Patch / Extensions : amepatch, cpuinfo,
multismb3, powersched, reboot / All modules / Build loader / Load DSM
Setup DSM then create Bond with Adaptive Load Balancing
ALL WORK PERFECT ! :)

(capture_1.png)

But...
When I activate LAG mode on my netgear GS308EP, the DSM begins very slowly,
when I disable LAG mode, ALL RE-WORK PERFECT ! :)

I have tested with too ethernet card, Intel PRO dual port (e1000e) and
intel 82576 dual port (igb) = same symptoms

here some screenshot:

(capture_2.png)

I notice this:

- The fake MAC is on the second ethernet port (eth1) but on my DHCP server,
it's the first ethernet port (eth0)

(capture_3.png)

- When LAG mode on my netgear is enabled

(capture_4.png)

we can't synchronize time and surf on package center

(capture_5.png)

but we can continue to navigate on the DSM.

- When DSM Loader is starting

(capture_6.png)

You can't see network addresses on eth0 and eth1, but you can connect to
the DSM :)

I test with and without multismb3 extension.

All is ok with https://github.com/fbelavenuto/arpl/releases but it's for
7.1.1 and no ARC Patch... :)

If you need more information, please let me know :)

Thank you very much for your help

**Comment by Cyber-Snoop** [comment]
Hello,

Thank you very much for your answer !

So, I made a fresh install with ARC v23.10.1b
My steps: Select DS923+ / 7.2 / ARC Patch / Extensions : amepatch, cpuinfo,
multismb3, powersched, reboot / All modules / Build loader / Load DSM
Setup DSM then create Bond with Adaptive Load Balancing
ALL WORK PERFECT ! :)

![image](https://github.com/AuxXxilium/arc/assets/146823814/3d345064-fe63-4327-a266-7d38bda70653)

But...
When I activate LAG mode on my netgear GS308EP, the DSM begins very slowly,
when I disable LAG mode, ALL RE-WORK PERFECT ! :)

I have tested with too ethernet card, Intel PRO dual port (e1000e) and
intel 82576 dual port (igb) = same symptoms

here some screenshot:

![image](https://github.com/AuxXxilium/arc/assets/146823814/821454de-9507-4126-9cf6-1d62b1d7e577)

I notice this:

- The fake MAC is on the second ethernet port (eth1) but on my DHCP server,
it's the first ethernet port (eth0)

![image](https://github.com/AuxXxilium/arc/assets/146823814/93715251-b7fe-48ef-bff3-744071b69326)

- When LAG mode on my netgear is enabled

![image](https://github.com/AuxXxilium/arc/assets/146823814/76be9f9a-564a-4979-8aaf-0e1bb58b35ab)
we can't synchronize time and surf on package center

![image](https://github.com/AuxXxilium/arc/assets/146823814/35d0551d-46d9-469b-87fc-c6bc1f5c2842)

but we can continue to navigate on the DSM.

- When DSM Loader is starting

![image](https://github.com/AuxXxilium/arc/assets/146823814/56c98b2a-0387-444f-ae47-c84c75089210)

You can't see network addresses on eth0 and eth1, but you can connect to
the DSM :)

I test with and without multismb3 extension.

All is ok with https://github.com/fbelavenuto/arpl/releases but it's for
7.1.1 and no ARC Patch... :)

If you need more information, please let me know :)

Thank you very much for your help

**Comment by AuxXxilium** [comment]
if you can't see address, set timeout higher. looks like your dhcp is to slow.

**Comment by Cyber-Snoop** [comment]
ok, strange, I have a pfsense under AMD A4 and with your previous version it was show... are ypu modified timeout in the last relase? if not, where is the parameter please ?
![image](https://github.com/AuxXxilium/arc/assets/146823814/72312eba-adcc-4861-98b4-59d2f4fdf18c)

And for the LAG / Bond, you have an idea ?

**Comment by AuxXxilium** [comment]
> ok, strange, I have a pfsense under AMD A4 and with your previous version it was show... are ypu modified timeout in the last relase? if not, where is the parameter please ? ![image](https://user-images.githubusercontent.com/146823814/273005962-72312eba-adcc-4861-98b4-59d2f4fdf18c.png)
> 
> And for the LAG / Bond, you have an idea ?

1. look in loader, you will find it.
2. LAG don't know, are you sure you selected the correct while create the bond?

**Comment by Cyber-Snoop** [comment]
Hello,

I made a fresh install with v23.10.3a

1. I found this:
![PXL_20231009_143702382~2](https://github.com/AuxXxilium/arc/assets/146823814/9b41b968-1e74-4fc0-ad10-5b4038205ef4)

No change with v23.10.1b.
With v23.10.3a without change anythings, it's ok, cool 🙂

2. Yes, retested too with v23.10.3a but same symptoms, very strange 

Thank you for your work !! Really so well !!
