### ISSUE TITLE
VMware workstation 17 VM vmxnet3 

### ISSUE THREAD

**Issue by noodlenoggan** [AuxXxilium/arc#584]
When setting up a new vm, the default network adapter e1000 is detected by default by the loader. When I change the vmx file network adapter to vmxnet3 and rebuild the loader, it still shows e1000.

When I create a new vm and change the vmx network adapter to vmxnet3 before I run loader, vmxnet3 is detected.

Is there a way to change the network adapter after the loader is built?

Thanks.

**Comment by AuxXxilium** [comment]
if the loader is showing e1000e than the vm runs with e1000e and if it is showing vmxnet3 it is running with vmxnet3. the nic will be dedected at every boot and there is no option to save them.

so if your vm is showing e1000e after setting it to vmxnet3, your old vm config is still present at your cache.
