### ISSUE TITLE
More licenses on DVA 1622 models

### ISSUE THREAD

**Issue by vinphan** [AuxXxilium/arc#585]
I really appreciate your bootloader with many useful addons. I'm currently using DVA1622 model on my old PC. The model just have 8 licenses for 8 cams. My house has 9 cams. Ouch! Do you know anyway to extend more licenses on this model? I hope that the number of licenses on DVA 1622 will be considered as an addons, or core feature on next update! 👍

**Comment by AuxXxilium** [comment]
No way for DVA. Only possibility is to create a cms (cluster) with second dva in vmm and add this to your main ss.
