### ISSUE TITLE
23.10.2 - the reverse proxy stopped working

### ISSUE THREAD

**Issue by upais** [AuxXxilium/arc#590]
In version 23.10.2, the reverse proxy in DSM stopped working, the page does not open, as if the rules did not exist, re-creating the rules does not change the situation. Having compiled version 23.10.1b - there is no problem, everything works. 
Same thing on arpl-i18n. I believe the problem is related to changes in the MAC configuration.

![Screenshot_1](https://github.com/AuxXxilium/arc/assets/86227709/69e33a4e-5b24-4543-8bb8-9db895eb3da0)
![Screenshot_2](https://github.com/AuxXxilium/arc/assets/86227709/3d99de4a-a096-495c-a568-837808d29658)

P.S. The screenshot from 23.10.2 is old, in the latest tests only e1000e is used. The rest is the same.

**Comment by AuxXxilium** [comment]
@wjz304 do you know anything about this?

**Comment by AuxXxilium** [comment]
@upais dsm version before upgrade the loader?

**Comment by upais** [comment]
All testing on 7.2.1

**Comment by AuxXxilium** [comment]
> All testing on 7.2.1

clean installation - same issue?

**Comment by upais** [comment]
I loaded a test (almost clean) DSM on 10.23.2 - the same problem.

**Comment by AuxXxilium** [comment]
clean without any datadisk with dsm installation connected?

**Comment by upais** [comment]
There was an empty disk there, only recently DSM installed it and tested a few things.
Tomorrow I'll format it, install it again and check it.

**Comment by AuxXxilium** [comment]
i looked thru dsm files, there is no mac binding for nginx proxy / everything is on ip binding. so the issue is somewhere else.

**Comment by upais** [comment]
Forgot.
I use a valid sn\mac and change it to them before building.

**Comment by AuxXxilium** [comment]
> Forgot. I use a valid sn\mac and change it to them before building.

you don't need this if you select arc patch.


do you have enabled the dsm firewall? in config files, it looks like there is a mac binding in firewall.

**Comment by upais** [comment]
Enabled. But I also tried disabling it.

**Comment by AuxXxilium** [comment]
how can you try disabled firewall if you can't connect to dsm?

**Comment by upais** [comment]
Disabled, no effect.
Tomorrow I'll try again with a clean install and several bootloaders. If you still can't reproduce the problem.
It's too late now and returned 23.10.1b

**Comment by AuxXxilium** [comment]
try 23.10.2/2a on a complete clean system without any preinstallation of dsm on a disk.

**Comment by wjz304** [comment]
> @wjz304 do you know anything about this?
> 
> fyi: 23.10.1b was with old mac setting and apply to nic / 23.10.2 is with new system without apply mac to nic

I haven't tested this, I will test it today yet

**Comment by wjz304** [comment]
Are you using the reverse proxy that comes with your system or nginx of docker?

**Comment by upais** [comment]
> Are you using the reverse proxy that comes with your system or nginx of docker?

System reverse proxy .

**Comment by wjz304** [comment]
What is the application of proxy? Is it convenient to take a screenshot?

My test is also OK
![image](https://github.com/AuxXxilium/arc/assets/5615843/cb89a28e-5319-4684-a67c-ba02ff0b9782)
![image](https://github.com/AuxXxilium/arc/assets/5615843/f147c4d9-aaac-4291-8660-f31fde7a00de)
![image](https://github.com/AuxXxilium/arc/assets/5615843/058c07c3-2fc3-44ee-ba06-17db39ebd27f)
![image](https://github.com/AuxXxilium/arc/assets/5615843/9cce5d51-ba86-4f1a-a628-68e00ef7e7d6)

**Comment by upais** [comment]
@AuxXxilium, @wjz304 
I started testing other rules for the reverse proxy and discovered that I forgot to change the forwarding to another device on the router (the router addresses by MAC, not by IP address). That was the problem.
Sorry for my stupidity...
