### ISSUE TITLE
DSM/ARC Upgrade Question

### ISSUE THREAD

**Issue by whoshoe** [AuxXxilium/arc#602]
I am currently on ARC 23.8.19, DSM 7.2-64570 Update 3 and I wanted to upgrade to DSM 7.2.1. How do I find out what DSM versions are supported by a specific ARC version and what's the recommended way/process to upgrade DSM/ARC? Thanks!

**Comment by AuxXxilium** [comment]
Arc is always loading latest dsm of specified version.
