### ISSUE TITLE
More fun and attractive ;)

### ISSUE THREAD

**Issue by Cyber-Snoop** [AuxXxilium/arc#606]
Hello, Thanks again for your work, BIG UP :1st_place_medal:

What do you things about this addon:
https://github.com/FOXBI/ch_cpuinfo
it could be possible to have it in your loader-addons please?

and it's possible to have the DSM logo on your DSM loader screen as wjz304 arpl have ?
https://github.com/wjz304/arpl-i18n
![266022413-58e0d4e3-8463-44ea-ad3c-06b51ce926e0](https://github.com/AuxXxilium/arc/assets/146823814/6b7dd8d3-d95b-46a5-8f16-6be1d3965b20)
![8058897b92caf4e4ef864c0572a096e3](https://github.com/AuxXxilium/arc/assets/146823814/004a7a96-1300-4d3f-aed1-3f871190f9bb)
Option "Show dsm logo: true"

Have a good day :+1:

**Comment by AuxXxilium** [comment]
no i won't at this trash. sorry but this is absolutly useless.

**Comment by Cyber-Snoop** [comment]
_**> cpu info is always default selected and i was the first who had added this!**_
Ah ok, it was just for add the link to cpu specs, your addon is perfect!

**_> logo? no i won't at this trash. sorry but this is absolutly useless._**
No problem, it's was just for fun, if it's a trash, we don't wan't that too :)
