### ISSUE TITLE
DynDNS

### ISSUE THREAD

**Issue by RonnyB1978** [AuxXxilium/arc#608]
**Describe the bug**
I cann't register a special DDNS Account.

**Screenshots**
DS918 is the "normal" DS918
DS3622 runs with Arc Bootloader

**Additional context**
The special DDNS account work perfect with my normal DS918. If I take the same settings in my DS3622 (with Arc Bootloader), it doesn't work.

Is it a mistake on my part?
![DS918](https://github.com/AuxXxilium/arc/assets/101010267/80cd4fe6-24db-47d9-8ea6-479bb848b9a5)
![DS3622](https://github.com/AuxXxilium/arc/assets/101010267/c8d7c432-6803-4b72-b748-4e0bc5913fd1)
![pict1](https://github.com/AuxXxilium/arc/assets/101010267/eb9f3cf7-7b4e-4d9a-8f64-a82df8a3b985)
![pict2](https://github.com/AuxXxilium/arc/assets/101010267/c63191e4-2b0e-4340-b5bf-0c036b9984d9)

Thanks for help a lot.

Ronny

**Comment by AuxXxilium** [comment]
why do you try to use dyndns andf not quickconnect?

**Comment by RonnyB1978** [comment]
Hello Christian.

Many thanks for your quick reply. I use DynDNS also for Videostation and Audiostation. In this case DynDNS and port forwarding in my firewall is quicker as Quickconnect over the relay server of Synology.

Thanks a lot again and have a nice weekend.

Ronny
