### ISSUE TITLE
problem with the loader

### ISSUE THREAD

**Issue by dib8670** [AuxXxilium/arc#615]
![Screenshot_20231016_190808_Chrome](https://github.com/AuxXxilium/arc/assets/54912239/5c5f2cc9-3bc7-4d14-89f3-f63d6555b57a)
![Screenshot_20231016_190729_Chrome](https://github.com/AuxXxilium/arc/assets/54912239/d63df2cf-0b2c-46a5-ac08-2fa8d36e7635)

I don't know why my post was deleted

after the update, quickconnect won't work, it says problem with the internet. In the arc loader, the patch will not turn on yes

**Comment by AuxXxilium** [comment]
clean flash boot image and do not restore old config. do not change mac/sn!

**Comment by dib8670** [comment]
Thanks, I tried a clean install, I didn't change anything, and it's still the same problem. Sorry for the wrong form.

**Comment by AuxXxilium** [comment]
so your system has an issue or something else went wrong.

**Comment by dib8670** [comment]
Thank you very much, everything works perfectly until I made a mistake, I did a clean installation again and everything works perfectly. Thank you so much for help. All the Best
