### ISSUE TITLE
Quickconnect server is bussy

### ISSUE THREAD

**Issue by LCBO** [AuxXxilium/arc#618]
Hello
I am running DSM 7.2.1-69057 Update 1 on model RS4021xs+, directly from usb.
Strange enough, when I try to setup the Quickconnect I receive this error: Quickconnect server is bussy

At the same time, I was able to login in the Synology account.
Any idea on how to get over it? 
PS> beside RS4021xs+ I tried a few others as well.

Thank you.

**Comment by nikos222** [comment]
It's not recommended to setup QuickConnect unless you have your own unique serial number (S/N) and MAC address for your chosen model.

**Comment by LCBO** [comment]
Thank you. How can I add a real SN and MAC?

**Comment by AuxXxilium** [comment]
first: nikos22 is wrong, use arc patch and everything is working.
second: you can change mac and serial in edit user config. -> next update: you can change this while config step.

**Comment by LCBO** [comment]
Thank you, AuxXxillium.
PS: I knew that it should work as it worked in the past. You have the only one solution for this.
Thank you for your fantastic work.

**Comment by AuxXxilium** [comment]
syno has api issues the last days, so everything is possible atm.

**Comment by LCBO** [comment]
It worked fine right now. no issues. Fully registered.
