### ISSUE TITLE
SATA controller not detected / not supported yet

### ISSUE THREAD

**Issue by SvenLudwig202** [AuxXxilium/arc#625]
Hey,
so I was trying to install on my system that is using an addin-pcie card for a couple of sata disks.

The Arc-installer isn't picking up on the controller and disks (not showing in the menu).

![arcdsm](https://github.com/AuxXxilium/arc/assets/34524443/52068f60-3a01-4b18-ad4e-d26a1b6c3c36)

Yet I'm able to see them when using the installer's shell executing lscpi and lsscsi.

lspci -v is reporting the following details.

	02:00.0 RAID bus controller: Marvell Technology Group Ltd. 88SE9230 PCIe 2.0 x2 4-port SATA 6 Gb/s RAID Controller (rev 01)
		Subsystem: Dawicontrol GmbH 88SE9230 PCIe 2.0 x2 4-port SATA 6 Gb/s RAID Controller
		Flags: bus master, fast devsel, latency 0, IRQ 27, NUMA node 0
		I/O ports at e800 [size=8]
		I/O ports at e400 [size=4]
		I/O ports at e000 [size=8]
		I/O ports at d800 [size=4]
		I/O ports at d400 [size=32]
		Memory at fe8ff800 (32-bit, non-prefetchable) [size=2K]
		Expansion ROM at fe8e0000 [disabled] [size=64K]
		Capabilities: [40] Power Management version 3
		Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit-
		Capabilities: [70] Express Legacy Endpoint, MSI 00
		Capabilities: [e0] SATA HBA v0.0
		Capabilities: [100] Advanced Error Reporting
		Kernel driver in use: ahci

Is there any chance to get support for this controller (or the 88SE9XXX family of marvell chips)?

Thanks for considering
Sven

**Comment by AuxXxilium** [comment]
It is supported but looks like it is set to Raid Mode. I use these controllers in some systems and they work.

**Comment by AuxXxilium** [comment]
But first check bios settings with wiki. can be an option rom issue.

**Comment by SvenLudwig202** [comment]
Thanks for the quick feedback.

Worked through the bios settings from the wiki, looks like that everything that applied to my system (and configurable) was already as recommended.
I wasn't able to disable the onboard sata controller (I want to use it anyway, but for testing purposes it would've been nice).
I did try if a disk being present on the onboard controller changes anything, but to no avail.

Looking into raid mode on the controller, I can confirm that it was indeed in raid mode. Checked the manufacturers documentation and disabled boot mode which in turn also disables raid mode it seems.
Messages on boot do confirm this:
![arcdsm2](https://github.com/AuxXxilium/arc/assets/34524443/3b4107b8-9701-4cd4-9eb1-0bbc6eea4a13)

lspci does still report it as being a "RAID bus controller" though.
Also have to report no change in arc-installer's menu.

Do you have any ideas?

**Comment by AuxXxilium** [comment]
option rom / oprom? enabled in bios?

**Comment by AuxXxilium** [comment]
but why do you use an external controller in microserver? no need for this.

**Comment by SvenLudwig202** [comment]
Double checked the bios, but the options are super limited on the microserver bios. There's nothing related to option roms or basically anything related to addin cards.
I've worked through all the settings on how the disks are being presented inside the controllers configuration, but doesn't change anything about it not being picked up in arc's menu.

The external controller in the microserver was actually supposed to host a bunch of 2.5" drives (more specific SSDs) that I have in a 4x enclosure in the optical drive bay.

But yeah, this might not be worth the effort, given the age of the hardware. Still kind of a shame though, as the individual drives are being passed through to the system on that controller.

**Comment by AuxXxilium** [comment]
It uses the ahci module in your lspci output and this is correct: https://linux-hardware.org/index.php?id=pci:1b4b-9230-1b4b-9230

the only option to verify the controller settings are correct is: download ubuntu install image, load this as live image and look for your disks in ubuntu.

**Comment by SvenLudwig202** [comment]
Hi,
so I'd been busy this weekend, hence the late reply.

I've spun up a current Ubuntu LTS 22.04.3 and collected the available info booted into the system.

Ubuntu seems to have no trouble working with the controller whatsoever and is working as expected. This is for both the raid bios being enabled and disabled.

Full lspci -v
[lspci.txt](https://github.com/AuxXxilium/arc/files/13063966/lspci.txt)

Full fdisk -l on the disks
[fdisk.txt](https://github.com/AuxXxilium/arc/files/13063967/fdisk.txt)

And a screencap from the installer
![installer](https://github.com/AuxXxilium/arc/assets/34524443/8b11632f-537c-45b5-9475-e46540e66502)
