### ISSUE TITLE
NIC Issue

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#631]
![WhatsApp Image 2023-10-26 at 00 20 09_328444ed](https://github.com/AuxXxilium/arc/assets/101920742/2875857b-5db2-4c9d-8398-f39a4351efce)
![WhatsApp Image 2023-10-26 at 00 20 10_f4943138](https://github.com/AuxXxilium/arc/assets/101920742/427da40a-8067-4397-8add-262fbeb88e13)

I have Two E1000 NIC as they both show in ARC setting but unfortunetly I can't find the second. so it's messing with getting IP address,

**Comment by AuxXxilium** [comment]
if they have a cable connected, check your bios settings. looks like initialization is to late. 

and please provide all informations i mentioned for bug reports.

**Comment by AuxXxilium** [comment]
and what you have to check is, that your cables are correct. because both systems, arc and dsm showing not connected. these 2 systems are independent from each other and using different modules/driver. so i guess your cables are the issue.

**Comment by Edwardpge** [comment]
Yes correctly I'm using a single NIC cause my network switch got some issues with the hardware some can't able to use other lines, but the point is in loader it shows 4 NIC and in DSM as you can see only three NIC is showing up which is messing with the mac address and DHCP Server after reboot. As LAN 1 Shows connected but didn't get the ip address from DHCP

**Comment by AuxXxilium** [comment]
send screenshot from arc - sysinfo, that i mentioned in guidelines for bugreport and send screenshot from network info tab in dsm to check which nic is missing.

**Comment by AuxXxilium** [comment]
and why do you have set them to static? it's only needed if there is no dhcp server.

**Comment by AuxXxilium** [comment]
and if you can't get an ip in arc, i wrote something in wiki. please follow these steps.

**Comment by Edwardpge** [comment]
> and why do you have set them to static? it's only needed if there is no dhcp server.

I used Static don't want to wait for getting new ip address from DHCP Server, and as i encountered that MAC address of devices are switching everytime

**Comment by Edwardpge** [comment]
![Screenshot 2023-10-26 141158](https://github.com/AuxXxilium/arc/assets/101920742/7feb4659-b0ba-45af-acdf-69114becfa8a)
![Screenshot 2023-10-26 141902](https://github.com/AuxXxilium/arc/assets/101920742/6ff37890-c2d0-477d-adf5-5e53a1bdcd79)
![WhatsApp Image 2023-10-26 at 14 19 53_aa12d628](https://github.com/AuxXxilium/arc/assets/101920742/0df75236-1113-4a26-bfaa-07cd951ecafe)

as you can see in the shell eth0 is R8169 which has 32 in last of mac
eth1 tg3 has E9 in last of mac
eth2 e1000 has f7 in last of mac
eth3 e1000 has 6e in last of mac
as in sysinfo MAC are differ from actual and i'm not using custom MACs

**Comment by Edwardpge** [comment]
i think that missing NIC is TG3 cause can't find E9 MAC address in DSM

**Comment by AuxXxilium** [comment]
1. your nic connected to dsm is 32 in the end: this mac is for tg3
2. one of the e1000 is missing. 
3. do you have connected a cable to r8169 and tg3? because arc tells that r8169 is connected and dsm tells us tg3 is connected.

**Comment by Edwardpge** [comment]
> 1. your nic connected to dsm is 32 in the end: this mac is for tg3
> 2. one of the e1000 is missing.
> 3. do you have connected a cable to r8169 and tg3? because arc tells that r8169 is connected and dsm tells us tg3 is connected.

r8169 is connected it's an onboard NIC
in sysinfo MAC are exchaged between each other the physical address of r8169 is 94:de:80:21:4c:32 but in loader it shows as tg3

**Comment by AuxXxilium** [comment]
than the initialization is wrong. the realtek should be the first but tg3 init is in the time that he is getting the ip and on a lower pcie path. it's not possible to fix this, remove additional nic from system or look in bios for settings.

**Comment by Edwardpge** [comment]
> than the initialization is wrong. the realtek should be the first but tg3 init is in the time that he is getting the mac and on a lower pcie path. it's not possible to fix this, remove additional nic from system or look in bios for settings.

As this was working fine with previous versions

**Comment by Edwardpge** [comment]
is there any way to fix this issue?

everything was working fine with the past versions!

**Comment by Edwardpge** [comment]
why tg3 not showing in DSM can you fix that?

**Comment by Edwardpge** [comment]
> **### lspci -Q**


00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02)
00:02.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GFX port 0)
00:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0)
00:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1)
00:09.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 4)
00:0a.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 5)
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 SATA Controller [AHCI mode] (rev 40)
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:12.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:13.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller (rev 42)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller (rev 40)
00:14.4 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 PCI to PCI Bridge (rev 40)
00:14.5 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
00:16.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:16.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor HyperTransport Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Miscellaneous Control
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Link Control
01:00.0 VGA compatible controller: NVIDIA Corporation G86 [GeForce 8400 GS] (rev a1)
02:00.0 USB controller: Etron Technology, Inc. EJ168 USB 3.0 Host Controller (rev 01)
03:00.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 03)
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
**05:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express**
06:06.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05)
06:07.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05)

**Comment by Edwardpge** [comment]
### **lspci -k**
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02)
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge
00:02.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GFX port 0)
        Kernel driver in use: pcieport
00:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0)
        Kernel driver in use: pcieport
00:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1)
        Kernel driver in use: pcieport
00:09.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 4)
        Kernel driver in use: pcieport
00:0a.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 5)
        Kernel driver in use: pcieport
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 SATA Controller [AHCI mode] (rev 40)
        Subsystem: Device 1458:b002
        Kernel driver in use: ahci
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
        Subsystem: Device 1458:5004
00:12.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
        Subsystem: Device 1458:5004
        Kernel driver in use: ehci-pci
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
        Subsystem: Device 1458:5004
00:13.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
        Subsystem: Device 1458:5004
        Kernel driver in use: ehci-pci
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller (rev 42)
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller (rev 40)
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller
00:14.4 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 PCI to PCI Bridge (rev 40)
00:14.5 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
        Subsystem: Device 1458:5004
00:16.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
        Subsystem: Device 1458:5004
00:16.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
        Subsystem: Device 1458:5004
        Kernel driver in use: ehci-pci
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor HyperTransport Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Miscellaneous Control
        Kernel driver in use: k10temp
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Link Control
01:00.0 VGA compatible controller: NVIDIA Corporation G86 [GeForce 8400 GS] (rev a1)
        Subsystem: NVIDIA Corporation Device 0472
02:00.0 USB controller: Etron Technology, Inc. EJ168 USB 3.0 Host Controller (rev 01)
        Subsystem: Device 1458:5007
        Kernel driver in use: etxhci_hcd-170202
03:00.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 03)
        Subsystem: Device 1028:0498
        Kernel driver in use: xhci_hcd
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
        Subsystem: Device 1458:e000
        Kernel driver in use: r8169
05:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
        Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
06:06.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05)
        Subsystem: Intel Corporation Device 1376
        Kernel driver in use: e1000
06:07.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05)
        Subsystem: Intel Corporation Device 1376
        Kernel driver in use: e1000

**Comment by Edwardpge** [comment]
> ### **lspci -k**
> 00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02) Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge 00:02.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GFX port 0) Kernel driver in use: pcieport 00:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0) Kernel driver in use: pcieport 00:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1) Kernel driver in use: pcieport 00:09.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 4) Kernel driver in use: pcieport 00:0a.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 5) Kernel driver in use: pcieport 00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 SATA Controller [AHCI mode] (rev 40) Subsystem: Device 1458:b002 Kernel driver in use: ahci 00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller Subsystem: Device 1458:5004 00:12.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller Subsystem: Device 1458:5004 Kernel driver in use: ehci-pci 00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller Subsystem: Device 1458:5004 00:13.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller Subsystem: Device 1458:5004 Kernel driver in use: ehci-pci 00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller (rev 42) Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller 00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller (rev 40) Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller 00:14.4 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 PCI to PCI Bridge (rev 40) 00:14.5 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI2 Controller Subsystem: Device 1458:5004 00:16.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller Subsystem: Device 1458:5004 00:16.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller Subsystem: Device 1458:5004 Kernel driver in use: ehci-pci 00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor HyperTransport Configuration 00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Address Map 00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor DRAM Controller 00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Miscellaneous Control Kernel driver in use: k10temp 00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Link Control 01:00.0 VGA compatible controller: NVIDIA Corporation G86 [GeForce 8400 GS] (rev a1) Subsystem: NVIDIA Corporation Device 0472 02:00.0 USB controller: Etron Technology, Inc. EJ168 USB 3.0 Host Controller (rev 01) Subsystem: Device 1458:5007 Kernel driver in use: etxhci_hcd-170202 03:00.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 03) Subsystem: Device 1028:0498 Kernel driver in use: xhci_hcd 04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06) Subsystem: Device 1458:e000 Kernel driver in use: r8169 05:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express 06:06.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05) Subsystem: Intel Corporation Device 1376 Kernel driver in use: e1000 06:07.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05) Subsystem: Intel Corporation Device 1376 Kernel driver in use: e1000

Can't find the kernal driver for 05:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express

**Comment by AuxXxilium** [comment]
it's the same chip as on hp microserver and they all are working. is firmware on tg3 up to date?

**Comment by Edwardpge** [comment]
> it's the same chip as on hp microserver and they all are working. is firmware on tg3 up to date?

Don't know about that!

**Comment by Edwardpge** [comment]
**what would be the issue?**

**Comment by AuxXxilium** [comment]
it's the same base. so flash clean stick and rebuild from scratch. without setting static ip.

**Comment by Edwardpge** [comment]
> it's the same base. so flash clean stick and rebuild from scratch. without setting static ip.

Okay Let me Try!

**Comment by Edwardpge** [comment]
Nothing Same as before!

**Comment by AuxXxilium** [comment]
and if arpl is working, use this.

**Comment by Edwardpge** [comment]
> and if arpl is working, use this. 

I believe arpl have limited features as compared to yours, really appreciate your work brother, i just want a fix for TG3 i have tried a different TG3 NIC, same issue happens

**Comment by AuxXxilium** [comment]
there must be something else. same module/driver as arpl and tg3 is working on all microserver with tg3. have multiple user with this. all on .21a/.21v. do you have used arpl before? i ask because of we use different init scripts, so it is possible that arpl scripts mismatch with arc scripts. so the only poit i see is: "force reinstall dsm" in grub

**Comment by Edwardpge** [comment]
> there must be something else. same module/driver as arpl and tg3 is working on all microserver with tg3. have multiple user with this. all on .21a/.21v. do you have used arpl before? i ask because of we use different init scripts, so it is possible that arpl scripts mismatch with arc scripts. so the only poit i see is: "force reinstall dsm" in grub

I was using arpl in the beginning as a week ago I shifted to arc. in arpl NICs works fine.

**Comment by AuxXxilium** [comment]
yes because the arpl init scripts are in your dsm installation. try with "force reinstall dsm"

**Comment by Edwardpge** [comment]
> yes because the arpl init scripts are in your dsm installation. try with "force reinstall dsm"

Okay let me try

**Comment by Edwardpge** [comment]
> yes because the arpl init scripts are in your dsm installation. try with "force reinstall dsm"

Nope still not working!

**Comment by new-indy** [comment]
tg3 not working on microserver g7 n36l with arc ver 23.10.10 (may be with later ver. too)
Arc can see nic, dsm 7.2 not.

**Comment by AuxXxilium** [comment]
> tg3 not working on microserver g7 n36l with arc ver >= 23.10.10 (may be with previous ver. too) Arc can see nic, dsm 7.2 not.

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Workarounds

**Comment by Edwardpge** [comment]
Kernel panics after updating to the latest version...

**Comment by AuxXxilium** [comment]
> Kernel panics after updating arpl to latest version 23.10.25...

Do you have read my message above? ->

> > tg3 not working on microserver g7 n36l with arc ver >= 23.10.10 (may be with previous ver. too) Arc can see nic, dsm 7.2 not.
> 
> https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Workarounds

**Comment by Edwardpge** [comment]
> > Kernel panics after updating arpl to latest version 23.10.25...
> 
> Do you have read my message above? ->
> 
> > > tg3 not working on microserver g7 n36l with arc ver >= 23.10.10 (may be with previous ver. too) Arc can see nic, dsm 7.2 not.
> > 
> > 
> > https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Workarounds

Yes i have fixed the kernel panics, it was the settings, but i can't find tg3 still and now i also can't find the r8169 internal NIC in DSM

**Comment by Edwardpge** [comment]
> > Kernel panics after updating arpl to latest version 23.10.25...
> 
> Do you have read my message above? ->
> 
> > > tg3 not working on microserver g7 n36l with arc ver >= 23.10.10 (may be with previous ver. too) Arc can see nic, dsm 7.2 not.
> > 
> > 
> > https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Workarounds

i have tried your methods but don't have such luck!

**Comment by AuxXxilium** [comment]
DS3622xs+ with directboot does not work?

**Comment by Edwardpge** [comment]
> DS3622xs+ with directboot does not work?
> 
> and you know it can take up to 20 minutes with slow cpu at first boot?

my e1000 NIC is working porperly and tried that i can access DSM with e1000 but can't find r8168/r8169 and tg3




And can DS3622xs+ works with AMD CPU? currently i'm using DS2422+

**Comment by AuxXxilium** [comment]
> > DS3622xs+ with directboot does not work?
> > and you know it can take up to 20 minutes with slow cpu at first boot?
> 
> my e1000 NIC is working porperly and tried that i can access DSM with e1000 but can't find r8168/r8169 and tg3 NICs
> 
> And can DS3622xs+ works with AMD CPU? currently i'm using DS2422+

Best is DS3622xs+ because all AMD based DS/RS need later generation of AMD CPU (missing instruction set in older Models)

**Comment by AuxXxilium** [comment]
Discord User tried the following:

German:
Also bei mir läuft folgendes:
HP N54L mit bestehender Installation (23.10.22a) und Update auf 23.10.25
HP N54L komplette Neuinstallation mit dem arc 23.10.25
HP N54L komplette Neuinstallation mit dem arc 23.10.dev

English: 
So this is what works for me:
HP N54L with existing installation (10/23/22a) and update to 10/23/25
HP N54L complete reinstallation with arc 10/23/25
HP N54L complete reinstallation with arc 23.10.dev

Settings: DS362xs+ with Directboot

**Comment by new-indy** [comment]
> > Kernel panics after updating arpl to latest version 23.10.25...
> 
> Do you have read my message above? ->
> 
> > > tg3 not working on microserver g7 n36l with arc ver >= 23.10.10 (may be with previous ver. too) Arc can see nic, dsm 7.2 not.
> > 
> > 
> > https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Workarounds
 
Of course. I know about google'ing and wiki'ing ). I fix problem with external Intel NIC.
PS I forget important thing. tg3 not work after 7.2 update 1 (try directboot, prod/dev, clean install). Unfortunately i can't test with 7.2
