### ISSUE TITLE
Synology Photos Face Recognition Feature 

### ISSUE THREAD

**Issue by nadeem4g** [AuxXxilium/arc#632]
Hi guys after updating ARC bootloader sinology photos face recognition is not working I have uninstalled synology Photos and seen it after restarting the system. If there is any solution I would be very grateful

**Comment by nadeem4g** [comment]
![Untitled.jpg](https://github.com/AuxXxilium/arc/assets/116666640/566b8165-68bb-4f6a-af8c-531d48f11c45)

**Comment by AuxXxilium** [comment]
arc isn't changing anything in apps, so i can't do anything.
