### ISSUE TITLE
 Does not detect network card on Asrok j4205 board

### ISSUE THREAD

**Issue by Nakamichidts** [AuxXxilium/arc#636]
*After generating the entire boot process correctly, when DSM loads it stops detecting the network card and does not continue.
I have tried different configurations and the same thing happens in all of them.
The board is an Asrock J4205 and the integrated network card is an RTL8111GR (as indicated in the manufacturer's specifications).
I have another Asrock j1900 board that theoretically has the same network card and it does work.

Thank you so much.*

**Comment by AuxXxilium** [comment]
it's not nic related. it looks like a kernel panic. wrong model selection, bios settings, ...

**Comment by Nakamichidts** [comment]
Thank you so much.
On this board I have a dsm 6.1.7 running on a ds3615xs configuration with six disks, but I can't get any arc configuration to work. I will continue testing with future versions.

**Comment by AuxXxilium** [comment]
Send Screenshot from Arc - Sysinfo than i can find your issue. Recommended Bios Settings are mentioned in wiki,
