### ISSUE TITLE
Realtek RTL811H 100MB instead of 1GB

### ISSUE THREAD

**Issue by punisher89** [AuxXxilium/arc#648]
Problem on ASUS PRIME J3355I-C board
 the network only works 100mb/s although the router shows 1gb.  Network controller: Realtek RTL8111H

**Comment by AuxXxilium** [comment]
check your cables and real speed while copy files.

**Comment by punisher89** [comment]
Okay, I'll check.  Then I will write the result.

**Comment by punisher89** [comment]
There was a problem with the cable
