### ISSUE TITLE
aacraid driver

### ISSUE THREAD

**Issue by SquirmN** [AuxXxilium/arc#65]
Anyway to add the adaptec driver to your modules?

https://raw.githubusercontent.com/pocopico/rp-ext/master/aacraid/rpext-index.json

**Comment by AuxXxilium** [comment]
I can add them back. Removed them because of noone were using this. pocopico modules won‘t work here.

**Comment by SquirmN** [comment]
LOL, I guess i am the only person on the planet that still uses my old faithful adaptec card.  Sorry, for the link I did not realize you had them before.

**Comment by AuxXxilium** [comment]
![86F64744-B9B8-4B05-B59D-11829ADAFFA0](https://user-images.githubusercontent.com/67025065/213996032-2f61eb64-908a-42ee-a61f-5655c1652f6c.png)

Were inside in Version 23.01.15. I will add them back today.

**Comment by SquirmN** [comment]
OK, that makes since. I swear I was using a version that worked... then updated and started looking and did not see the driver and figured I was losing my mind.  Thank you for adding them back in!

**Comment by AuxXxilium** [comment]
Added to new release. Online in some hours.

**Comment by SquirmN** [comment]
Thank you will test tonight!

**Comment by SquirmN** [comment]
aacraid.ko missing from broadwellnk-4.4.180?

**Comment by AuxXxilium** [comment]
oh i see. compile missed it

**Comment by AuxXxilium** [comment]
give me 30 min

**Comment by SquirmN** [comment]
Prefect! No rush... your work is much appreciated!
