### ISSUE TITLE
Request to add temperature sensor

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#658]
Hey Brother, Just want to ask a question regarding, temprature sensor is there any way to add temperature sensor driver to read accurate temprature of CPU, i have noticed my bios is showing different temperature then temperature at setting(info) in DSM and can we control FANS in DSM?

**Comment by AuxXxilium** [comment]
temperature is working for drives, cpu temp is not shown and managed by bios, no way to use fan settings inside dsm, the commands in dsm are only working with syno devices!
