### ISSUE TITLE
Code Backup does not work when Upgrade ,on Proxmox 7.x, Xpenology 7.2.x

### ISSUE THREAD

**Issue by yurrosh** [AuxXxilium/arc#661]
**Describe the bug**
When upgrading ARC from the menu, it generates the backup code successfully, but after the upgrade and reboot it fails to restore configuration, saying "No config backup found"

**Additional context**
it used to work 1-2 months ago. 

just invented a workaround, the idea is go to command prompt, cd /mnt/p1, cat user-config.xml, and save the contents in notepad... and restoring after the upgrade

**Comment by AuxXxilium** [comment]
https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Usage-&-Update
