### ISSUE TITLE
Can the URL of "arc build" be modified?

### ISSUE THREAD

**Issue by CBAnother** [AuxXxilium/arc#663]
Hello, I noticed that during the Arc Build, there is a prompt:
```
Successfully got PAT Data.
Please confirm or modify as needed.
URL: https://global/synologydonwload.com/download/DSM/release/...
HASH: ...
```
It mentions that it can be modified. Due to my unstable network, sometimes I cannot access Synologydownload. Therefore, I want to save the PAT file locally in advance and access it through a static website so that I can access this PAT file anytime. However, on that page, there are only three options: OK, Retry, Cancel. How should I modify this URL?

**Comment by AuxXxilium** [comment]
this url is only for automated download option in dsm recovery screen. you can modify this or leave it as it is. the loader is only loading 10mb file from my github. and if you upload tge file in recovery locally, there is no problem.

**Comment by CBAnother** [comment]
> this url is only for automated download option in dsm recovery screen. you can modify this or leave it as it is. the loader is only loading 10mb file from my github. and if you upload tge file in recovery locally, there is no problem.

Thanks.
According to what you mentioned, it seems that during the process of building the loader, it doesn't download the pat file from the Synology official website. However, sometimes I receive a "No DSM Image found. Try alternate Link" message here, and the alternate link also fails to download. What could be the reason for this? Is it possible that it's because the 10MB file in your GitHub cannot be accessed?

**Comment by CBAnother** [comment]
> > this url is only for automated download option in dsm recovery screen. you can modify this or leave it as it is. the loader is only loading 10mb file from my github. and if you upload tge file in recovery locally, there is no problem.
> 
> Thanks. According to what you mentioned, it seems that during the process of building the loader, it doesn't download the pat file from the Synology official website. However, sometimes I receive a "No DSM Image found. Try alternate Link" message here, and the alternate link also fails to download. What could be the reason for this? Is it possible that it's because the 10MB file in your GitHub cannot be accessed?

This happened on July 29, 2023. Since I haven't encountered this situation recently and I'm not sure if it's due to my improved network or if there have been fixes.

**Comment by AuxXxilium** [comment]
The alternate link is original syno file, that we need to extract the correct data for dsm. but this only should happens if github files can not be loaded. so check your dns server.

**Comment by CBAnother** [comment]
thanks

**Comment by CBAnother** [comment]
> The alternate link is original syno file, that we need to extract the correct data for dsm. but this only should happens if github files can not be loaded. so check your dns server.

thanks
