### ISSUE TITLE
Can't download pat file

### ISSUE THREAD

**Issue by vasyna** [AuxXxilium/arc#664]
**Describe the bug**
build 23.11.12
DVA1622, DSM 7.2

Can't download pat file.

jq: parse error: Invalid numeric literal at line 1, column 10

**Comment by AuxXxilium** [comment]
looks like an issue in your environment or config. rebuild bootstick and try again.

**Comment by vasyna** [comment]
> looks like an issue in your environment or config. rebuild bootstick and try again.

sorry. im testing on other location and its ok. Apparently I have problems with the DNS server
