### ISSUE TITLE
set a fake mac

### ISSUE THREAD

**Issue by FrozzenRod** [AuxXxilium/arc#676]
Hello, when I install arc loader in its latest version, I would like to have synology connect ect services and it asks me if I want to put a fake mac or not.

No matter what I put, I can't connect to my dsm for the first connection. 
![image](https://github.com/AuxXxilium/arc/assets/73665630/d714712c-58a9-445e-a367-2c57fb7d6a86)

**Comment by FrozzenRod** [comment]
when I look at any tutorial on the internet nobody has this message...

**Comment by FrozzenRod** [comment]
![image](https://github.com/AuxXxilium/arc/assets/73665630/6e2767ec-80b9-4527-9a6d-13de1fc62d0f)

**Comment by AuxXxilium** [comment]
If your Bios and Firmware is not at latest version, you need to enable directboot for hp microserver. explained in wiki as well.

**Comment by FrozzenRod** [comment]
where is the directboot option ? i have modded bios v02.61

**Comment by FrozzenRod** [comment]
I just activated directboot in arc but it keeps restarting. I don't know if this is normal.

**Comment by FrozzenRod** [comment]
when I follow the instructions in the wiki, I boot the first time with boot dsm but then it doesn't give me direct boot but Boot DSM directly...

**Comment by FrozzenRod** [comment]
when i boot the first time with directboot, i have the error "DSM not installed, boot with directboot"
After a reboot with boot dsm "DSM installed, make directboot persistent"

**Comment by qwe33gthb** [comment]
I have same problem. Please help us.

**Comment by drumntetris** [comment]
Last Working version for me is 23.11.20.

**Comment by FrozzenRod** [comment]
With directboot or normal boot ?

**Comment by drumntetris** [comment]
> With directboot or normal boot ?

Always using Directboot, cause it works more stable for me.

**Comment by FrozzenRod** [comment]
I've just reformatted my loader.

I setup the model
choose the version
select "Yes Install with arc patch".
I select mac1
I select "No Do not set (fake) mac
select 1: SataPortMap: ActivePort *
I leave the addons by default
I cancel the build installation to select the directboot
I select Directboot: true in boot parameters
I do build loader
I download the image and click ok to boot

**Comment by FrozzenRod** [comment]
when I boot DSM, 
DSM installed make directboot persistent and it reboots and normally I would do directboot but I have
- Directly boot DSM kernel
- Boot DSM
- Force re-install DSM
- Configure Loader
- Change Vesa to text mode

**Comment by AuxXxilium** [comment]
All is correct. 1. Option should be default and loading.

**Comment by FrozzenRod** [comment]
To be clear, I'm going to use the .23 version of the loader on a DS3622xs+ in DSM 7.1 with directboot.

**Comment by FrozzenRod** [comment]
okay i try it

**Comment by FrozzenRod** [comment]
I have to use finds.synology.com when I boot with "Directly boot DSM Kernel"?

**Comment by AuxXxilium** [comment]
or you check your dhcp for ip. it should be the same as arc.

**Comment by FrozzenRod** [comment]
nothing in my dhcp
![IMG_0124](https://github.com/AuxXxilium/arc/assets/73665630/88d832d3-b9bb-4a5f-a062-140c8da041e6)

**Comment by FrozzenRod** [comment]
i don't ping it with arc's ip or with other ip's in my dhcp

**Comment by AuxXxilium** [comment]
Let us use: #677
