### ISSUE TITLE
Infinite reboot on 23.11.26

### ISSUE THREAD

**Issue by upais** [AuxXxilium/arc#677]
Clean bootloader version 23.11.26 on VMM, DSM is not installed, constant reboot after assembly.
I also met your people with this problem, both on VMM and hardware.
Rolling back to version 23.11.23 solves the problem.
Video, screenshot.

![2023-11-27 191032](https://github.com/AuxXxilium/arc/assets/86227709/4715b187-3981-49d4-8bd4-45a8d876e1af)

https://github.com/AuxXxilium/arc/assets/86227709/7fdbf79c-b659-4396-a343-230ae2f0662a

**Comment by qwe33gthb** [comment]
![20231127_233322](https://github.com/AuxXxilium/arc/assets/152189256/50d2ad6b-8b63-4653-9abc-9679f2802984)

**Comment by qwe33gthb** [comment]
When I try to access finds.synology.com after booting, a page like this appears.  It says some information is not available.

![20231127_234756](https://github.com/AuxXxilium/arc/assets/152189256/16513f1d-571f-40c1-9abf-bf5fa6059e8e)

**Comment by Yevrashka** [comment]
Updated loader from .23 to .26 and got the same bug with infinite reboot. DSM 7.2.1 on Terramaster F4-423. Had to downgrade to fix this issue.

**Comment by qwe33gthb** [comment]
> Could you put your step by step procedure of your installation pls

Cant install. Only i can find the device with finds.synology.com. But when i click to install, i am getting error.

**Comment by AuxXxilium** [comment]
guys: downgrade to .23 and select "force-reinstall dsm" in grub or wait!

**Comment by FrozzenRod** [comment]
![IMG_0125](https://github.com/AuxXxilium/arc/assets/73665630/05053397-341c-4b32-87e8-57f41c73d7be)

With force-reinstall dsm

**Comment by FrozzenRod** [comment]
no ping, no detection in finds.synology.com

**Comment by AuxXxilium** [comment]
it should reboot into directboot and not only show this message

**Comment by qwe33gthb** [comment]
> guys: downgrade to .23 and select "force-reinstall dsm" in grub or wait!

No any problem with .26 loader and dsm 7.1 version. The problem occure when select dsm 7.2 version.

**Comment by upais** [comment]
> No any problem with .26 loader and dsm 7.1 version. The problem occure when select dsm 7.2 version.

I can't confirm from myself. Tested the version of .26 and DSM 7.1 - it does not work for me.

**Comment by AuxXxilium** [comment]
correct, i will fix this later today, busy days until new year for me.

**Comment by AuxXxilium** [comment]
23.11.28 should fix latest reboot loop bug. if hope it will work for you all.

**Comment by FrozzenRod** [comment]
I'll let you know tonight when I can try out this new version. Thanks

**Comment by upais** [comment]
> 23.11.28 should fix latest reboot loop bug. if hope it will work for you all.

In my tests, this problem no longer exists in the new version.
Thank you!

**Comment by qwe33gthb** [comment]
I tested it. The same issue continues for DSM 7.2. When I install DSM 7.1, there is no problem.

**Comment by AuxXxilium** [comment]
> I tested it. The same issue continues for DSM 7.2. When I install DSM 7.1, there is no problem.

possible that you have to use force-reinstall dsm.

**Comment by qwe33gthb** [comment]
I implemented what you wrote.  Problem not solved. For dsm 7.2 version.

**Comment by qwe33gthb** [comment]
> > > I implemented what you wrote. Problem not solved. For dsm 7.2 version.
> > 
> > 
> > I think you have a different problem. Describe it in detail.
> > Does version .23 with DSM 7.2 not work either?
> 
> ![image](https://private-user-images.githubusercontent.com/73665630/286682488-a099ba37-a307-465c-baf3-a67e046c6e76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzgyNTksIm5iZiI6MTcwMTI3Nzk1OSwicGF0aCI6Ii83MzY2NTYzMC8yODY2ODI0ODgtYTA5OWJhMzctYTMwNy00NjVjLWJhZjMtYTY3ZTA0NmM2ZTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjFlODMyNDFhZjI1ZmEzMTBiNjJmMjdlZWQ3ZjQ2NTQ0YmVhZDViZGY5ZWE2ZTMxMTJjMTkwNzJlMzc4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzQbQ5J4yAph0iAaTN-v_5DRoclLt7_EeOyDbyiNCcM)

No.  7.2 not work on latest or .23 loader version.

**Comment by AuxXxilium** [comment]
> I implemented what you wrote.  Problem not solved. For dsm 7.2 version.

do you had changed your bootimage or only used update loader?

**Comment by qwe33gthb** [comment]
No.  I'm trying to download your latest img file and install it from scratch.

**Comment by AuxXxilium** [comment]
than it should work.

**Comment by FrozzenRod** [comment]
not work for me

**Comment by qwe33gthb** [comment]
My syno info

![20231127_233322](https://github.com/AuxXxilium/arc/assets/152189256/d204c3a2-8838-4e56-9143-7a59a35dfcbf)

**Comment by AuxXxilium** [comment]
remove not preselected addons and try again

**Comment by FrozzenRod** [comment]
![IMG_0135](https://github.com/AuxXxilium/arc/assets/73665630/367cd0fd-29f2-41b7-ab2b-75b72a941ca7)

**Comment by FrozzenRod** [comment]
nothing in finds.synology.com

**Comment by AuxXxilium** [comment]
deactivate directboot and look if system is still rebooting

**Comment by FrozzenRod** [comment]
Could there not be a link with that?
![image](https://github.com/AuxXxilium/arc/assets/73665630/8cd2f459-3545-4939-b996-95e805dda09a)

**Comment by FrozzenRod** [comment]
![image](https://github.com/AuxXxilium/arc/assets/73665630/dbfd0b0d-899a-4ae6-b51d-c9022aabcd7d)

Before the loader build

**Comment by FrozzenRod** [comment]
no ping, no finds.synology.com....

**Comment by FrozzenRod** [comment]
![IMG_0136](https://github.com/AuxXxilium/arc/assets/73665630/fc870b5b-64e1-4227-9da1-a216922a2984)

**Comment by AuxXxilium** [comment]
looks like tg3 issue. try to find atm.

**Comment by FrozzenRod** [comment]
tg3 issue ?

**Comment by AuxXxilium** [comment]
i tried native install on dl360 gen9 and everything is working. including tg3.

**Comment by FrozzenRod** [comment]
what is tg3 ? network interface ?

**Comment by qwe33gthb** [comment]
https://github.com/AuxXxilium/arc/assets/152189256/1f35897f-0e33-4400-a93d-63768348a325

**Comment by AuxXxilium** [comment]
why is directboot enabled?

**Comment by qwe33gthb** [comment]
> why is directboot enabled?

I try all. No change.

**Comment by FrozzenRod** [comment]
i will test with other network adapter

**Comment by AuxXxilium** [comment]
latest build and clean loader flash?

**Comment by FrozzenRod** [comment]
yes for me

**Comment by FrozzenRod** [comment]
nothing more with other network adapter

**Comment by qwe33gthb** [comment]
![20231130_001236](https://github.com/AuxXxilium/arc/assets/152189256/29260e8f-d607-49cd-ba87-109dfb2a54e9)

Kernelpanic behavior???

**Comment by FrozzenRod** [comment]
it's just because I want to access Synology services otherwise I would have stayed on my installation which worked well before....

**Comment by AuxXxilium** [comment]
don't know what you guys have done, need serial log to find out whats wrong.

**Comment by FrozzenRod** [comment]
tell me how I give it to you and I'll do it

**Comment by AuxXxilium** [comment]
now to be clear: what are your systems doing?

**Comment by FrozzenRod** [comment]
When i build the loader, I reboot and a boot in boot dsm 
He say: dsm not installed, reboot in direct boot
The system reboot in directly boot to dsm and he say to Check find.synology.com and we don’t have the synology in this website

**Comment by qwe33gthb** [comment]
The interesting thing is that there is no problem for DSM 7.1, but it occurs for DSM 7.2.  Anyway, using DSM 7.1 is not bad either.

**Comment by AuxXxilium** [comment]
> When i build the loader, I reboot and a boot in boot dsm He say: dsm not installed, reboot in direct boot The system reboot in directly boot to dsm and he say to Check find.synology.com and we don’t have the synology in this website

check dhcp for ip if you use directboot. find.syno doesn't show evrything.

**Comment by AuxXxilium** [comment]
> The interesting thing is that there is no problem for DSM 7.1, but it occurs for DSM 7.2. Anyway, using DSM 7.1 is not bad either.

can you provide a sysinfo screenshot?

**Comment by AuxXxilium** [comment]
and for hp micro NxxL it can take up to 30 minutes for first boot.

**Comment by qwe33gthb** [comment]
> > The interesting thing is that there is no problem for DSM 7.1, but it occurs for DSM 7.2. Anyway, using DSM 7.1 is not bad either.
> 
> can you provide a sysinfo screenshot?

![Uploading 20231127_233322.jpg…]()

**Comment by qwe33gthb** [comment]
> > The interesting thing is that there is no problem for DSM 7.1, but it occurs for DSM 7.2. Anyway, using DSM 7.1 is not bad either.
> 
> can you provide a sysinfo screenshot?

![20231127_233322](https://github.com/AuxXxilium/arc/assets/152189256/efb098dc-a2a6-408b-9a39-aafca4fd2f0e)

**Comment by AuxXxilium** [comment]
> > > The interesting thing is that there is no problem for DSM 7.1, but it occurs for DSM 7.2. Anyway, using DSM 7.1 is not bad either.
> > 
> > 
> > can you provide a sysinfo screenshot?
> 
> ![20231127_233322](https://private-user-images.githubusercontent.com/152189256/286754396-efb098dc-a2a6-408b-9a39-aafca4fd2f0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTU1NjIsIm5iZiI6MTcwMTI5NTI2MiwicGF0aCI6Ii8xNTIxODkyNTYvMjg2NzU0Mzk2LWVmYjA5OGRjLWEyYTYtNDA4Yi05YTM5LWFhZmNhNGZkMmYwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQyMjAxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmI2NzJlYjU0NWYxNWViYmQ3NmE5ODM0MjYxMTFlZDM4ZWQ1Mzc2YmFkY2E0OTEwYTQ4ZjJlNDg2MzY0ODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wXzVqgxlpgvV6s3xR1SEGBSi7eCIkjLZIXLjD53JkDA)

flash new arc image, create loader, don't select additional addons. try to boot. do nothing else for now. it can be an issue with your nvme, 7.1 and 7.2 use different partition layouts for nvme.

bios setting checked with wiki?

**Comment by qwe33gthb** [comment]
Tomorrow i will try

**Comment by FrozzenRod** [comment]
I will Check one thing, set the bootloader in a external ssd
Actually I have a external nvme

**Comment by FrozzenRod** [comment]
![image](https://github.com/AuxXxilium/arc/assets/73665630/04addb15-bec5-4efe-912d-a47017497fcc)
😁

**Comment by FrozzenRod** [comment]
https://xpenology.com/forum/topic/18601-tuto-dsm-7-pour-hp-n40l-et-hp-n54l-gen7/
https://xpenology.com/forum/topic/69718-tuto-dsm-7-pour-tous/

**Comment by qwe33gthb** [comment]
I tried everything that could be done.  Unfortunately the problem is not solved.

**Comment by FrozzenRod** [comment]
Take a good look at the bios settings, that's what was wrong for me I think.

**Comment by Yevrashka** [comment]
Works for me with DSM 7.2.1 after updating to the latest 23.12.1 and force-reinstall DSM. I think it's fixed. 
![IMG_20231202_133718](https://github.com/AuxXxilium/arc/assets/24300377/b55998bd-b591-45b0-8061-63badc9da35d)
![IMG_20231202_133801](https://github.com/AuxXxilium/arc/assets/24300377/e08c9578-1aaf-46f8-b996-fc0cf7ab87eb)

**Comment by qwe33gthb** [comment]
> Take a good look at the bios settings, that's what was wrong for me I think.

What changes did you make to the bios?

**Comment by iron8706** [comment]
Do you fix it? i have the same problem,and i tried all the loaders and almost all the  i can find.

> > Take a good look at the bios settings, that's what was wrong for me I think.
> 
> What changes did you make to the bios?
Have the same problem

**Comment by iron8706** [comment]
> > Take a good look at the bios settings, that's what was wrong for me I think.
> 
> What changes did you make to the bios?

Do you fix it? i have the same problem,and i tried all the loaders and almost all the versions i can find.
