### ISSUE TITLE
SataPortMap issue

### ISSUE THREAD

**Issue by zfdang** [AuxXxilium/arc#684]
**Describe the bug**
I'm using ARC to boot my HP GEN8 Server. I have installed 3 HDDs (1~3), and another one SSD attached to cdrom port (port 5).
All these drivers could be detected properly during booting period.

If I use "Use SataPortMap (controller active Ports)", the SSD could not be detected by DSM. 
If I use "Use SataPortMap (controller max Ports)", everything works well.

Is this a bug, or a design?

**Comment by AuxXxilium** [comment]
Yes because of your blank port. I guess the Loader tells you, you should use SataRemap in Selection.
