### ISSUE TITLE
loader 23.12.3 not boot to DSM

### ISSUE THREAD

**Issue by dib8670** [AuxXxilium/arc#692]
![Screenshot 2023-12-04 152128](https://github.com/AuxXxilium/arc/assets/54912239/0020bf99-845a-4787-8ecb-8c16d82f2f74)
![Screenshot 2023-12-04 151642](https://github.com/AuxXxilium/arc/assets/54912239/0ce068d8-2b0b-45ce-9bc3-24b34a45c06f)
Won't find DSM how to solve this problem I tried everything but same problem always
Thanks in advance

**Comment by dib8670** [comment]
> First: Use the IP:Port for connection. If you use the find page, your browser cache can make some issues.
tried the same

**Comment by AuxXxilium** [comment]
do not activate fake mac. is a point to choose after model selection.

**Comment by dib8670** [comment]
> do not activate fake mac. is a point to choose after model selection.

he tried and it's still the same at all, he can't find the DSM, it throws out the ip address, but nothing else, the DSM can't be accessed, until version 23.11.23 everything works without problems, but on all versions higher than this, it won't

**Comment by AuxXxilium** [comment]
update modules to 23.12.4 and try again

**Comment by dib8670** [comment]
> update modules to 23.12.4 and try again

Thank you very much, everything works perfectly now without any problems
