### ISSUE TITLE
Not show "g) Storage Map" in "4) Arc Options" in "Arc Menu" 

### ISSUE THREAD

**Issue by kornalexandr2** [AuxXxilium/arc#699]
I was install DS920+ on proxmox 8.1.3. It works! I was plug new HDD. DSM has not detect new HDD. After reboot system I was enter to Arc Menu. Choose "g) Storage Map" in "4) Arc Options" in "Arc Menu". But screen was clear and then (after abuot half second) show "Arc Menu". Options for "Storage Map" not show. I cant plud new HDD

![arc](https://github.com/AuxXxilium/arc/assets/7520361/fc471db6-1e0c-4ef6-97d6-a6215270a709)

**Comment by AuxXxilium** [comment]
There is no Storage Map for DT. DT is doing this inside DSM.

**Comment by kornalexandr2** [comment]
I thought so. But DSM did not detect the new HDD

**Comment by AuxXxilium** [comment]
check cable, bios ...
