### ISSUE TITLE
After the update, the second network interface stopped working   Help!

### ISSUE THREAD

**Issue by cherr07** [AuxXxilium/arc#703]
After updating the Arc loader arc-23.6.36a and updating the DSM to 7.2.1-69057, the second network interface was no longer detected. When booting, two network interfaces are defined, and there is only one in the DSM. I ask for help to connect the second network interface.
![photo_2023-12-11_16-57-59](https://github.com/AuxXxilium/arc/assets/95305100/d246ad2f-338c-45fc-a3e4-2c5ca4c5317b)
![Screenshot 2023-12-11 at 16-55-29 MainPc - Synology NAS](https://github.com/AuxXxilium/arc/assets/95305100/e0fcb722-acee-4c78-a8c3-627e2f6502b5)

**Comment by AuxXxilium** [comment]
which one is shown?

follow guidelines for bugreport!

**Comment by cherr07** [comment]
The first one is active. Where can I view the guidelines for bugreport?

**Comment by AuxXxilium** [comment]
mentioned in readme of arc and of you open a new bugreport with preset.

**Comment by AuxXxilium** [comment]
and for your system to try: arc - update modules - enter version - Enter: 23.12.4 - rebuild loader and boot.

**Comment by cherr07** [comment]
> mentioned in readme of arc and of you open a new bugreport with preset. this is why there is a question what you wan't to do.

Arc sees two network interfaces (screenshot 1), both working on the bootloader configuration. But the DSM sees only one network interface (screenshot 2). How do I make the DSM see two network interfaces?

**Comment by AuxXxilium** [comment]
FYI: Arc and DSM are 2 completely different systems. so provide the correct informations or i can't help.

**Comment by cherr07** [comment]
Кристиан добрый день. 

Я использую Ваш Arc  более года.
Прежде чем писать сюда, я внимательно прочитал wiki. Ответа на свой вопрос не нашел.

Модули обновил до 23.12.4. DSM видит один сетевой интерфейс. У меня в машине два сетевых интерфейса. Один на плате, второй в слот PCI. DSM видит только один сетевой интерфейс на материнской плате. Версия DSM 7.2 видела оба сетевых интерфейса. После обновления arc (23.12.10) и DSM (7.2.1) видит только один сетевой интерфейс. Вопрос: как мне восстановить два сетевых интерфейса? 

Скорость была и есть 1G.

Какие данные мне нужно Вам  предоставить, чтобы вы могли мне помочь?

**Comment by AuxXxilium** [comment]
First tell me: Is the r8168/9 or the r8125 shown in dsm?

Second: I need a Screenshot from Sysinfo in Arc.

Third: You can try without setting fake mac to adapter. Is an option while Model Selection.

**Comment by AuxXxilium** [comment]
Fourth: Do you have made a cold boot and disabled Fastboot/Quietboot in Bios?

**Comment by cherr07** [comment]
1. В DSM работает сетевой интерфейс r8168.
2. Скриншот приложил.
3. Поддельный mac не использовал. 
4. Быстрая загрузка отключена. Перезагрузка только холодная.
![photo_2023-12-12_14-47-46](https://github.com/AuxXxilium/arc/assets/95305100/a9bc1259-5e7c-4163-ad2c-eab0bb2635a9)
![photo_2023-12-12_14-47-56](https://github.com/AuxXxilium/arc/assets/95305100/111a39bb-da5f-407d-85f5-391dfc9de75d)

**Comment by AuxXxilium** [comment]
So the issue is about the r8125. now i can take a look at this.

**Comment by AuxXxilium** [comment]
you can try to build loader with deselected module: r8125_v9

**Comment by cherr07** [comment]
I've already tried, it didn't work out.

**Comment by cherr07** [comment]
> Итак, проблема в r8125. теперь я могу взглянуть на это.
> 
> на вашем старом скриншоте загрузки для macsys был установлен пользовательский режим, поэтому вы активировали поддельный Mac.

I'm using a real mac right now

**Comment by cherr07** [comment]
> you can try to build loader with deselected module: r8125_v9

I'm using a real mac right now

**Comment by cherr07** [comment]
The router defines r8125 like this
![Screenshot 2023-12-12 at 15-14-24 ASUS Wireless Router RT-AX88U - Карта сети](https://github.com/AuxXxilium/arc/assets/95305100/36a4c2c1-b53f-4e8c-b42b-0465501899d5)

**Comment by cherr07** [comment]
The router defines r8125 like this
![Карта сети](https://github.com/AuxXxilium/arc/assets/95305100/2a231d1d-ada8-496d-9d9f-bd7ce9794813)

**Comment by AuxXxilium** [comment]
are you able to grep serial log?

**Comment by AuxXxilium** [comment]
and can you do "lspci -nnk" over ssh in dsm?

**Comment by cherr07** [comment]
> are you able to grep serial log?

How to do it?

**Comment by cherr07** [comment]
> and can you do "lspci -nnk" over ssh in dsm?
I'll try it now

**Comment by cherr07** [comment]
If I disable all modules. Enable only r8125_v9 connection works. But there is only one network interface in the DSM.

**Comment by AuxXxilium** [comment]
than disable the old r8125 and enable all other

**Comment by cherr07** [comment]
If I enable all modules except the old r8125. Only the r8168 connection works. But there is only one network interface in the DSM.

Why is there only one network interface?

**Comment by cherr07** [comment]
> > and can you do "lspci -nnk" over ssh in dsm?
> > I'll try it now

:~$ lspci -nnk
0000:00:00.0 Class [0600]: Device [8086:4c53] (rev 01)
        DeviceName: Onboard - Other
        Subsystem: Device [1458:5000]
0000:00:02.0 Class [0300]: Device [8086:4c8a] (rev 04)
        DeviceName: Onboard - Video
        Subsystem: Device [1458:d000]
0000:00:06.0 Class [0604]: Device [8086:4c09] (rev 01)
        Kernel driver in use: pcieport
0000:00:14.0 Class [0c03]: Device [8086:43ed] (rev 11)
        DeviceName: Onboard - Other
        Subsystem: Device [1458:5007]
        Kernel driver in use: xhci_hcd
0000:00:14.2 Class [0500]: Device [8086:43ef] (rev 11)
        DeviceName: Onboard - Other
0000:00:16.0 Class [0780]: Device [8086:43e0] (rev 11)
        DeviceName: Onboard - Other
        Subsystem: Device [1458:1c3a]
0000:00:17.0 Class [0106]: Device [8086:43d2] (rev 11)
        DeviceName: Onboard - SATA
        Subsystem: Device [1458:b005]
        Kernel driver in use: ahci
0000:00:1b.0 Class [0604]: Device [8086:43c4] (rev 11)
        Kernel driver in use: pcieport
0000:00:1c.0 Class [0604]: Device [8086:43bc] (rev 11)
        Kernel driver in use: pcieport
0000:00:1c.5 Class [0604]: Device [8086:43bd] (rev 11)
        Kernel driver in use: pcieport
0000:00:1d.0 Class [0604]: Device [8086:43b0] (rev 11)
        Kernel driver in use: pcieport
0000:00:1f.0 Class [0601]: Device [8086:4387] (rev 11)
        DeviceName: Onboard - Other
        Subsystem: Device [1458:5001]
0000:00:1f.3 Class [0403]: Device [8086:43c8] (rev 11)
        DeviceName: Onboard - Sound
        Subsystem: Device [1458:a194]
0000:00:1f.4 Class [0c05]: Device [8086:43a3] (rev 11)
        DeviceName: Onboard - Other
        Subsystem: Device [1458:5001]
0000:00:1f.5 Class [0c80]: Device [8086:43a4] (rev 11)
        DeviceName: Onboard - Other
0000:01:00.0 Class [0108]: Device [126f:2263] (rev 03)
        Subsystem: Device [126f:2263]
        Kernel driver in use: nvme
0000:03:00.0 Class [0200]: Device [10ec:8168] (rev 15)
        Subsystem: Device [1458:e000]
        Kernel driver in use: r8169
0000:04:00.0 Class [0200]: Device [10ec:8125] (rev 05)
        Subsystem: Device [10ec:0123]
        Kernel driver in use: pgtool
0001:09:00.0 Class [0106]: Device [1b4b:9235] (rev 11)
0001:0c:00.0 Class [0106]: Device [1b4b:9235] (rev 11)

**Comment by AuxXxilium** [comment]
don't know whats wrong with your system, possible firmware to old, bios update needed. 

try to disable r8169 and r8125.

**Comment by cherr07** [comment]
> don't know whats wrong with your system, possible firmware to old, bios update needed.
> 
> try to disable r8169 and r8125.

I've tried this. The DSM is not available.

**Comment by cherr07** [comment]
The Arc version arc-23.6.36a and DSM 7.2 worked correctly. There were two network interfaces r8168 and r8125.

Where can I see which modules have been changed? To compare them.

**Comment by AuxXxilium** [comment]
No driver in use:

0000:03:00.0 Class [0200]: Device [10ec:8168] (rev 15)
Subsystem: Device [1458:e000]
Kernel driver in use: r8169
0000:04:00.0 Class [0200]: Device [10ec:8125] (rev 05)

so the most possible issue is, that the firmware isn't supported by updated r8125.

**Comment by cherr07** [comment]
https://github.com/tabrezm/r8125-synology/tree/main
There is a possible solution here. Please take a look. My knowledge does not allow me to do this. I only use Windows.

**Comment by cherr07** [comment]
> If I disable all modules. Enable only r8125_v9 connection works. But there is only one network interface in the DSM.

I think there is a driver conflict here. I think there is a driver conflict here. The new driver version is working and there is access to the DSM via r8125

**Comment by AuxXxilium** [comment]
this is why i wrote you should try to disable r8169 and r8125

**Comment by cherr07** [comment]
> this is why i wrote you should try to disable r8169 and r8125
Christian, I have disabled both drivers, but the DSM is not available over the network.

**Comment by AuxXxilium** [comment]
good to know. so your realtek hardware id is placed in both modules. i will try to find a way to remove them from one of them. 

one thing at the end: can you try modules version: 23.12.1a

this includes different realtek modules.

**Comment by cherr07** [comment]
All versions after arc-23.9.10b assign one IP to both network adapters.
![photo_2023-12-12_14-47-46](https://github.com/AuxXxilium/arc/assets/95305100/f41f21cf-e3d9-43cd-8c49-3b36bb74e5be)

**Comment by cherr07** [comment]
Christian, I think this is a bug at the kernel compilation level. Please check it out.

Pay attention to the loading order (black screenshot above).

**Comment by AuxXxilium** [comment]
if i see this, your nic firmware is outdated, this cause the issues with updated drivers and fix issues for many other. 🙈

**Comment by cherr07** [comment]
Now I forgot to connect 2 HDD after the tests (there are 4 of them in the pool). And it booted with version arc-12/23/10. DSM returned a disk error. But! Amazing! The system showed two network interfaces that work

After connecting the hdd, one network is active again.

**Comment by cherr07** [comment]
> you can try to use latest version but update/downgrade modules to 23.9.10b

I'll try it tomorrow.

**Comment by AuxXxilium** [comment]
> Christian, I think this is a bug at the kernel compilation level. Please check it out.
> 
> Pay attention to the loading order (black screenshot above). And compare it with the first screenshot in the topic.

fyi: we don't change anything in dsm kernel, because it isn't open source. so this is impossible.

**Comment by cherr07** [comment]
> you can try to use latest version but update/downgrade modules to 23.9.10b

I tried it. It works with one test HDD. The DSM defines
two network connections, but they do not work quite correctly.
When installing four HDDs, one network is determined.

**Comment by cherr07** [comment]
Christian, all problems were solved by replacing the loader with PeterSuh-Q3 Tinycore-Red Pill
https://github.com/PeterSuh-Q3/tinycore-redpill/releases/tag/v1.0.0.5

There are definitely errors in your loader. Thank you for your work.
I really like your loader, but in the theme on xpenology.com many people write about problems with network cards.

I will be happy to return to your loader if the errors are fixed.
![Screenshot 2023-12-13 at 21-13-55 MainPc - Synology NAS](https://github.com/AuxXxilium/arc/assets/95305100/19c321af-085b-4f7a-b054-02df3a3a149a)
![Screenshot 2023-12-13 at 21-14-19 MainPc - Synology NAS](https://github.com/AuxXxilium/arc/assets/95305100/0a510a70-7d8f-4e42-a1c2-7195e4bb5a04)
