### ISSUE TITLE
sudden reboot of 2nd cluster node after failover from 1st node

### ISSUE THREAD

**Issue by turbolooser** [AuxXxilium/arc#707]
**Describe the bug**
I am running a 2 node cluster on proxmox and during failover I do see the 2nd node rebooting although its serving as active node at that time. As a result the whole cluster is down which is not the intention for a cluster.
This does not happen if node1 is active and node2 is being shutdown.
any ideas?

**Screenshots**

**Additional context**
- 2 cluster nodes up and running (node1 is active)
- manual failover (via dsm) to node2 as we wanna run maintanenace on node 1
- wait for node 2 to become the active node
- shutdown node 1 (passive node)
- once node 1 is shutdown after a couple of seconds node 2 will reboot without any intervention

not sure which additional debug parameters would help to collect required information for troubleshooting
just let me know

**Comment by AuxXxilium** [comment]
dsm issue. not to fix from me.
