### ISSUE TITLE
enable Hibernation Log extremely slows down DSM

### ISSUE THREAD

**Issue by Hamzter89** [AuxXxilium/arc#708]
**Describe the bug**
If the entries enable_hibernation_debug="yes" and hibernation_debug_level="2" are present in /etc/synoinfo.conf. 
The system becomes extremely slow and therefore partially unusable. 
As soon as you delete these entries and restart the system, it is fast as usual. 

**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.

**Additional context**
I have set these values to find out what wakes the HDDs from hibernation or why they do not go into hibernation at all. Unfortunately, no logs about the hibernation are stored in the log center. (Which is not necessarily due to the loader)

My hardware:
arc_4GB-23.12.16.img
ASRock J5040-ITX
Crucial RAM 16GB (2x8GB) DDR4 2400MHz CL17
4x 4TB Seagate IronWolf NAS
Additional PCIE card:
Realteak R8125 2.5Gbits

**Comment by AuxXxilium** [comment]
check your bios setting, remove docker and vmm, add hibernation addon, ... can be caused by many things, is working on the most system <- got multiple reports! so look at your settings.

**Comment by Hamzter89** [comment]
again for clarification, I was not talking about the hibernation mode, but about the fact that if you set these values in /etc/synoinfo.conf, the system becomes unusable, extremely slow. 

This error does not occur with TCRP or ARPL Loader. That's why I thought it was a bug in the ARC loader. 
Without modifying the synoinfo.conf the system works very performant and reliable! 

BTW thanks for your work :)
