### ISSUE TITLE
Stuck at migratable loop

### ISSUE THREAD

**Issue by everwisher** [AuxXxilium/arc#714]
**Describe the bug**
Model: DS918+
Host: Intel N100 / 16G RAM / PROXMOX 8.0.6
ARC version: 23.12.22 (ARC_4G)
DSM version: 7.2.1 (Auto-detected and unchangeable when making bootloader)

After the initial install with auto downloaded PAT, it reboots into migratable status as shown in the screenshot below.

**Screenshots**
<img width="800" alt="image" src="https://github.com/AuxXxilium/arc/assets/12667683/55302ca5-5f88-49ee-9801-826ed149dc58">
<img width="800" alt="image" src="https://github.com/AuxXxilium/arc/assets/12667683/6165f018-a4f6-4f38-9fa1-a0338588c3f7">
<img width="1026" alt="image" src="https://github.com/AuxXxilium/arc/assets/12667683/e6b180d2-fb99-4dba-b2ac-96a019068343">

**Additional context**

**Comment by AuxXxilium** [comment]
migrate it,

**Comment by everwisher** [comment]
> migrate it,

Did a few times but didn't get rid of the loop

**Comment by AuxXxilium** [comment]
is your config a restore or full new? did you changed bootimage or only use upgrade loader ....

**Comment by everwisher** [comment]
> is your config a restore or full new? did you changed bootimage or only use upgrade loader ....

Newly imported disk image from arc_4G.img and a newly created logical volume attached to sata0

**Comment by AuxXxilium** [comment]
And rebuild your portmap, it's complete trash.

**Comment by everwisher** [comment]
> And rebuild your portmap, it's complete trash.

I used the maxport option in arc so that later after installation completed I can passthrough the SATA controller to DSM. Is that the cause of the problem?

**Comment by AuxXxilium** [comment]
your disk is on a port that is outside maxdisks of selected model. so this is possible

**Comment by everwisher** [comment]
> your disk is on a port that is outside maxdisks of selected model. so this is possible

Thanks for your reminder. I attached two sata drives on proxmox. I have no idea why proxmox treats them as two separate sata controllers.

**Comment by AuxXxilium** [comment]
this is proxmox, i know there is a setting to set them to one controller, but please don't ask me how.

**Comment by everwisher** [comment]
> this is proxmox, i know there is a setting to set them to one controller, but please don't ask me how.

```
sata0: local-lvm:vm-101-disk-0,backup=0,cache=writeback,discard=on,replicate=0,size=4G,ssd=1
sata1: local-lvm:vm-101-disk-1,backup=0,cache=writeback,discard=on,replicate=0,size=32G,ssd=1
```
ChatGPT says this will place both drives on the same controller. I don't know why there are two controllers (00:1f.2, 06:07.0) on the guest side as shown in the screenshots.

**Comment by AuxXxilium** [comment]
chatgpt is not the best way, data is to old.

**Comment by AuxXxilium** [comment]
and please do not use find.syno.... this page is trash and has to many cached data.
