### ISSUE TITLE
not working nvme/ssd cash

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#715]
Hello, thanks for good work. Do you test nvme/ssd cash on esxi vm Xpenology? I have no problem to add cash in Xpenology, but when I check speed test with or without cash  - its no working.
I thing it will be work with passthrough nvme/ssd but not working from VMware datastore.

To test pool I am used vmm - ubuntu with kdisk

without cash
<img width="777" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/d20e77c3-032e-4f43-a392-a90963038586">

with cash
<img width="725" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/e2887088-ee57-47c5-9811-98d1839a0a7b">

and check speed with iSCSI LUN  - cash not working but in interface its all good.

<img width="676" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/346fe375-7f16-4305-b718-71fdb02143a2">
<img width="1198" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/64862f51-6ff6-4542-a083-058b1b5d4e32">

**Comment by AuxXxilium** [comment]
read syno manual to find out which files are cache cached and not. 1 gb lan? so your data rate is near the cap.

**Comment by uroopek** [comment]
> read syno manual to find out which files are cache cached and not. 1 gb lan? so your data rate is near the cap.

Not understand what about you talking. I ee manual, and it say that work with iscsi lun. lan I have 40gb - 4 x 10gb. its high speed.

If you say about cash for vmm, check please this video, test was correct, but cash not work.

https://www.youtube.com/watch?v=beDjiEc6fRk

**Comment by uroopek** [comment]
I understand you see pictures and think it's from iscsi. No I have few vmm with Xpenology, nvme have speed 5000/2000mb/sec. Speed lan 40gb.

Pictures for my first post from virtual machine manager on Xpenology. I test speed for HDD.

**Comment by uroopek** [comment]
https://kb.synology.com/en-us/DSM/tutorial/What_are_Some_Considerations_for_Creating_SSD_Cache

<img width="1097" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/d794db2e-a48c-42db-8f02-1db26749253b">
