### ISSUE TITLE
failed to get pat data

### ISSUE THREAD

**Issue by mnm000** [AuxXxilium/arc#719]
Issues.
Proxmox & ARC 
arc build 23.12.23 failed to get pat data please manually fill in the url and hash of pat

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/76624177/c2ebaf62-1f81-4e7c-bfe3-7c84ea1aafb8)

![image](https://github.com/AuxXxilium/arc/assets/76624177/7413497e-70df-4918-886b-0a579e1ef49d)

**Comment by AuxXxilium** [comment]
connection issue in your network, maybe dns, firewall, adblock, ....
