### ISSUE TITLE
Offline Loader 

### ISSUE THREAD

**Issue by nemesis122** [AuxXxilium/arc#721]
Hi AuxXxilium
thank you for the best Loader.
only a Question is it possible that the loader is creating without the internet connection as example when the .pat files are stored on a location of the usb stick ? 

because at the moment i create backups of the loader with USB Imager.

Happy New Year  i wish you all the best for you and your family in the next year thank you very much for your work !
Michael

**Comment by nemesis122** [comment]
and pls send me your paypal adress thank you

**Comment by AuxXxilium** [comment]
i can't build it full offline, because we need Api connection. Sorry

**Comment by nemesis122** [comment]
and it has already done thank you very much for that :-) and it is working great :-) now im a member on your youtube channel gizmometegizmo9267

**Comment by AuxXxilium** [comment]
thank you and have fun ;)
