### ISSUE TITLE
aqc111u  slow speed

### ISSUE THREAD

**Issue by mnlk2** [AuxXxilium/arc#723]
**Describe the bug**
my usb / ethernet controler aqc111u  link is at 1gbs instead of 5 gbs  and link speed not showed in dsm setting, only ip
my isp connect me at 8gbs, my nas is connected to an RT-AX89X on 10Gbs port 

maybe base hardware / model choose incompatibilty but i dont know what to don i've try DS3622xs, Ds918+ and some more models

**Additional context**
i install dsm on a Dell OptiPlex XE2 SFF  here is hardware list: 
Core i3-4330
8 Go DDR 3 
2To baracuda hdd 
1Go ssd seagate s2000DM008

**Comment by AuxXxilium** [comment]
i need to know which modules are loaded in dsm: connect with ssh to your dsm and do: "lspci -nnk"

**Comment by mnlk2** [comment]
here is the outpout: 

mnlk2@NAS_Ludo:~$ lspci -nnk
0000:00:00.0 Class [0600]: Device [8086:0c00] (rev 06)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: hsw_uncore
0000:00:02.0 Class [0300]: Device [8086:0412] (rev 06)
        DeviceName:  Onboard IGD
        Subsystem: Device [1028:05c1]
        Kernel driver in use: i915
0000:00:03.0 Class [0403]: Device [8086:0c0c] (rev 06)
        Subsystem: Device [1028:05c1]
0000:00:14.0 Class [0c03]: Device [8086:8c31] (rev 04)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: xhci_hcd
0000:00:16.0 Class [0780]: Device [8086:8c3a] (rev 04)
        Subsystem: Device [1028:05c1]
0000:00:19.0 Class [0200]: Device [8086:153a] (rev 04)
        DeviceName:  Onboard LAN
        Subsystem: Device [1028:05c1]
        Kernel driver in use: e1000e
0000:00:1a.0 Class [0c03]: Device [8086:8c2d] (rev 04)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: ehci-pci
0000:00:1d.0 Class [0c03]: Device [8086:8c26] (rev 04)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: ehci-pci
0000:00:1f.0 Class [0601]: Device [8086:8c4e] (rev 04)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: lpc_ich
0000:00:1f.2 Class [0106]: Device [8086:8c02] (rev 04)
        DeviceName:  Onboard SATA controller #1
        Subsystem: Device [1028:05c1]
        Kernel driver in use: ahci
0000:00:1f.3 Class [0c05]: Device [8086:8c22] (rev 04)
        Subsystem: Device [1028:05c1]
        Kernel driver in use: i801_smbus
0001:00:12.0 Class [0106]: Device [8086:5ae3]
0001:00:13.0 Class [0000]: Device [8086:5ad8]
0001:00:14.0 Class [0000]: Device [8086:5ad6]
0001:00:15.0 Class [0c03]: Device [8086:5aa8]
0001:00:16.0 Class [1180]: Device [8086:5aac]
0001:00:18.0 Class [1180]: Device [8086:5abc]
0001:00:19.0 Class [1180]: Device [8086:5ac6]
        DeviceName:  Onboard LAN
0001:00:19.2 Class [1180]: Device [8086:5ac6]
0001:00:1f.0 Class [0c05]: Device [8086:5ad4]
0001:00:1f.1 Class [0c05]: Device [8086:5ad4]
0001:01:00.0 Class [0106]: Device [1b4b:9215] (rev 11)
0001:02:00.0 Class [0200]: Device [8086:1539] (rev 03)
0001:03:00.0 Class [0200]: Device [8086:1539] (rev 03)

**Comment by AuxXxilium** [comment]
```
Private flags
This driver support additional options.

Disable thermal throttling
Link speed is configured to 100Base when the internal chip overheats automatically by default. This option disables that behavior.
ethtool --set-priv-flags eth2 "Thermal throttling" off
Enable Low Power 5G
Entering to low heat generation mode at the expense of throughput. This option should be enabled when thermal throttling is disabled.
ethtool --set-priv-flags eth2 "Low Power 5G" on
```

try this, but eth2 should be replaced with the eth number that is it in your system

**Comment by mnlk2** [comment]
those commands respond : 
mnlk2@NAS_Ludo:~$ ethtool --set-priv-flags eth1 "Low Power 5G" on
`No private flags defined`

when i type sudo ethtool eth0 return is :    (i mean it's on board eth) 
```
Settings for eth0:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Advertised pause frame use: No
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 1
        Transceiver: internal
        Auto-negotiation: on
        MDI-X: on (auto)
        Supports Wake-on: pumbg
        Wake-on: g
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes
```

when i type ethtool eth1  (usb aqc111u i think)  it return : 
```
Settings for eth1:
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes
```

**Comment by AuxXxilium** [comment]
usb3 connected? i think it is using the wrong module

**Comment by mnlk2** [comment]
yes it's on usb 3.0

**Comment by AuxXxilium** [comment]
update your modules in arc and try again. if this will not work, we have to give a look to your bios settings.

**Comment by mnlk2** [comment]
ok i'll try

**Comment by mnlk2** [comment]
after full upgrade nothing change

**Comment by AuxXxilium** [comment]
if this will not work, try this: https://github.com/bb-qq/aqc111

**Comment by mnlk2** [comment]
install work but  fail to launch already try

**Comment by AuxXxilium** [comment]
than i don't know whats wrong

**Comment by AuxXxilium** [comment]
and latest modules havn't worked?

**Comment by mnlk2** [comment]
that why i said mayby i choose wrong model on dsm install in arc loader, but i dont know wich one to choose, my cpu is close to DS3615xs have (Intel Core i3-4130). 
maybe i need a bromolow version of dsm but not fuond, maybe too old

> and latest modules 23.12.28a havn't worked?

nop dsm work but always only 1gbs on my acq111u

**Comment by AuxXxilium** [comment]
is the cable correct? tried a different?

**Comment by mnlk2** [comment]
cat 7 factory new   delivered  with my Qnap

**Comment by mnlk2** [comment]
if it help  when plug / unplug  i have this logs: 

```
[ 1126.433348] usb 4-6: USB disconnect, device number 2
[ 1126.438352] cdc_ether 4-6:2.0 eth1: unregister 'cdc_ether' usb-0000:00:14.0-6, CDC Ethernet Device
[ 1128.043516] usb 4-6: new SuperSpeed USB device number 3 using xhci_hcd
[ 1128.069957] cdc_ether 4-6:2.0 eth1: register 'cdc_ether' at usb-0000:00:14.0-6, CDC Ethernet Device, 24:5e:be:65:ea:3
```

**Comment by AuxXxilium** [comment]
deselect cdc_ether in modules of loader.

btw: i can't find any information that this router supports 5gbps ethernet. i only find informations for 100/1000mpps and 10gbps.

**Comment by AuxXxilium** [comment]
you know that syno removed the most usb support in dsm 7?

**Comment by mnlk2** [comment]
> deselect cdc_ether in modules of loader.
> 
> btw: i can't find any information that this router supports 5gbps ethernet. i only find informations for 100/1000mpps and 10gbps.

10gbps port can work at 10 / 5 /2.5 / 1  n i force it at 5 gbs   in settings 
<img width="584" alt="Capture d'écran 2023-12-28 203421" src="https://github.com/AuxXxilium/arc/assets/543030/0a9e2672-1ff5-4c79-8241-7d7eae356d8f">

> you know that syno removed the most usb support in dsm 7?
yes i saw it,  but i others can make my usb card work

**Comment by AuxXxilium** [comment]
> deselect cdc_ether in modules of loader.
> 
> btw: i can't find any information that this router supports 5gbps ethernet. i only find informations for 100/1000mpps and 10gbps.

do this please

**Comment by mnlk2** [comment]
must i rebuid loader? after deselect it?

**Comment by AuxXxilium** [comment]
yes, you have no boot option i guess

**Comment by mnlk2** [comment]
yes i dont have

**Comment by mnlk2** [comment]
with  cdc_ether  unselected my card look unpluged in dsm

**Comment by mnlk2** [comment]
i have to go,  i'll come back tomorrow

**Comment by AuxXxilium** [comment]
please try latest modules 23.12.29 with update modules in arc. i blacklisted your aqc111 for this module, to force load the aqc111 module.

**Comment by mnlk2** [comment]
after this update in first case my card look disconnected,  i try the 2 commands ethtool with sudo (without : permission denied)  and my card work. 
 now it look like work better i can reach 200+ mb/s

**Comment by AuxXxilium** [comment]
if this happens, there is something wrong with your loader disk.

**Comment by mnlk2** [comment]
i'll recreate it with last  version and try it

**Comment by mnlk2** [comment]
with recreated key, new clear install (hdd formated both)  my acq111 appear disconnected at reboot until i re sens eth tool commands

**Comment by AuxXxilium** [comment]
let me think about it

**Comment by AuxXxilium** [comment]
please try latest modules, they include latest version of aqc111 driver/module, if this will not help, i don't know

**Comment by mnlk2** [comment]
no change with new modules :/

**Comment by AuxXxilium** [comment]
than i don't know whats wrong, it should load the correct module.

**Comment by mnlk2** [comment]
i wanted to do a baremetal, i'll try in wm i think 
thx for time past to help me

**Comment by AuxXxilium** [comment]
i looked in module code, i think your bios or firmware of nic is forcing a non full linux compatible mode.

**Comment by mnlk2** [comment]
when i plug in dsmeg show this : 

```
[  775.574833] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
[  776.848282] usbnet: Unknown symbol mii_ethtool_sset (err 0)
[  776.853860] usbnet: Unknown symbol mii_link_ok (err 0)
[  776.859035] usbnet: Unknown symbol mii_nway_restart (err 0)
[  776.864634] usbnet: Unknown symbol mii_ethtool_gset (err 0)
```
i hope it can help

**Comment by mnlk2** [comment]
good news i make it work 

i reinstall all from 0 but i choose the oldest model in list  DS3617xs  at first it dont work, i install  bb-qq broadwell driver and now it work like he does 

so my 1rst idea : wrong model / hardware couple was true
