### ISSUE TITLE
AMD CPU displays incorrectly and CPU and RAM do not refresh automatically

### ISSUE THREAD

**Issue by xsj684135** [AuxXxilium/arc#726]
**Describe the bug**
My device is hpe microserver gen10, the CPU is X3421, and it runs in a PVE virtual machine.
The actual allocated CPU is 1 socket and 2 cores, but in Synology it shows 2 sockets and 1 core.
The task manager and the tools in the lower left corner will not update the status of the CPU and RAM in real time. They will be updated once after pressing F5 to refresh.
I'm not sure if this issue is boot related or if it's caused by a CPU display error.
**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.
![image](https://github.com/AuxXxilium/arc/assets/50570049/3fc7f5b8-a0d3-425c-b6be-7234844bf7f3)
![image](https://github.com/AuxXxilium/arc/assets/50570049/e338849d-423c-4dab-a1ab-0daff56b30e9)
![image](https://github.com/AuxXxilium/arc/assets/50570049/0e46aecd-2d0c-401f-b07c-9a023c176b69)

If you have any information you need from me, please let me know.
thank you！

**Comment by xsj684135** [comment]
![image](https://github.com/AuxXxilium/arc/assets/50570049/3fc7f5b8-a0d3-425c-b6be-7234844bf7f3)
![image](https://github.com/AuxXxilium/arc/assets/50570049/e338849d-423c-4dab-a1ab-0daff56b30e9)
![image](https://github.com/AuxXxilium/arc/assets/50570049/0e46aecd-2d0c-401f-b07c-9a023c176b69)

> **描述bug** 我的设备是hpe microserver gen10，CPU是X3421，运行在PVE虚拟机中。 实际分配的 CPU 是 1 个插槽和 2 个核心，但在 Synology 中显示为 2 个插槽和 1 个核心。 任务管理器和左下角的工具不会实时更新CPU和RAM的状态。按F5刷新后会更新一次。 我不确定这个问题是否与启动相关，或者是否是由 CPU 显示错误引起的。 **屏幕截图** 如果适用，请从 Arc - Sysinfo 菜单添加屏幕截图。 ![图像](https://private-user-images.githubusercontent.com/50570049/293286529-3fc7f5b8-a0d3-425c-b6be-7234844bf7f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTIiLCJleHAiOjE3MDM4MDUyNTgsIm5iZiI6MTcwMzgwNDk1OCwicGF0aCI6Ii81MDU3MDA0OS8yOTMyODY1MjktM2ZjN2Y1YjgtYTBkMy00MjVjLWI2YmUtNzIzNDg0NGJmN2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIzMDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNTQ5NTljZTgxYmNhYjQyZDBjYmVkYjZmMjA2MDg4Yzk5NGEyNjk4ZjE3MjA0ZWM4ODYxMzQyNDE5NjhkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k3KXHufUnvnZRV7AZX3Npim6mRZSD86JX8GyX-UDP58) ![图像](https://private-user-images.githubusercontent.com/50570049/293286609-e338849d-423c-4dab-a1ab-0daff56b30e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTIiLCJleHAiOjE3MDM4MDUyNTgsIm5iZiI6MTcwMzgwNDk1OCwicGF0aCI6Ii81MDU3MDA0OS8yOTMyODY2MDktZTMzODg0OWQtNDIzYy00ZGFiLWExYWItMGRhZmY1NmIzMGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIzMDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOGVlYmQ5OWQ5YjYwMzc5MzUzODRmMGJhZTNhNTdjYzQ0ZGM3MTY5ZTU1ZmIxYmYyY2UzYTQzMmMzMDJjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.caYUXF_yrLBlMpP1_FufK61u1Mwa1L2M7sZISPCqCBE) ![图像](https://private-user-images.githubusercontent.com/50570049/293286699-0e46aecd-2d0c-401f-b07c-9a023c176b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTIiLCJleHAiOjE3MDM4MDUyNTgsIm5iZiI6MTcwMzgwNDk1OCwicGF0aCI6Ii81MDU3MDA0OS8yOTMyODY2OTktMGU0NmFlY2QtMmQwYy00MDFmLWIwN2MtOWEwMjNjMTc2YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIzMDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZmRjNzEwZDY1YjNhZGQ3NTIxOTg5ZTcwN2Y5ZDg3NjliN2JiNzlhZjlkZGE5NzE2MTQ5MTIxOWI5ZjdjMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSOSQU0hnizFiYa9ODgnyP36tYP5CJSP6IPknof6unQ)
> 
> 如果您需要我提供任何信息，请告诉我。 谢谢你！

![image](https://github.com/AuxXxilium/arc/assets/50570049/3fc7f5b8-a0d3-425c-b6be-7234844bf7f3)
![image](https://github.com/AuxXxilium/arc/assets/50570049/e338849d-423c-4dab-a1ab-0daff56b30e9)
![image](https://github.com/AuxXxilium/arc/assets/50570049/0e46aecd-2d0c-401f-b07c-9a023c176b69)

**Comment by xsj684135** [comment]
I don’t know why the pictures can’t be loaded.
https://github.com/AuxXxilium/arc/assets/50570049/3fc7f5b8-a0d3-425c-b6be-7234844bf7f3
https://github.com/AuxXxilium/arc/assets/50570049/e338849d-423c-4dab-a1ab-0daff56b30e9
https://github.com/AuxXxilium/arc/assets/50570049/0e46aecd-2d0c-401f-b07c-9a023c176b69

**Comment by AuxXxilium** [comment]
cpu display is only optical issue because of your old and unsupported cpu
