### ISSUE TITLE
Realtek Lan doesnt works

### ISSUE THREAD

**Issue by Netember** [AuxXxilium/arc#728]
**Describe the bug**
When loader built, Realtek Lan not responding.(Onboard or PCI Express gigabit)
If I use PCIe Intel card, works well. Realtek works when select loader option, but after first boot Realtek Lan doesnt works.

**Screenshots**
If applicable, add screenshots from Arc - Sysinfo menu.

**Additional context**

**Comment by AuxXxilium** [comment]
wrong: first boot takes some time to activate network. read wiki: can take up to 20 minutes.

for more help: i need a screenshot of arc - sysinfo

**Comment by AuxXxilium** [comment]
![Screenshot 2023-12-29 194620](https://github.com/AuxXxilium/arc/assets/67025065/d0ef5c2c-273e-4dc9-a720-7026bd85cd82)

**Comment by Netember** [comment]
Thank you so much for your hard work, this is my favorite loader!
Still waiting for the first boot...
One more question, how does the Surveillance Station patch work?
I installed the version you provided, but it only allows 2 cameras.

**Comment by Netember** [comment]
Oops!
First boot,
After a long time the assistant sees it!

**Comment by AuxXxilium** [comment]
> Thank you so much for your hard work, this is my favorite loader! Still waiting for the first boot... One more question, how does the Surveillance Station patch work? I installed the version you provided, but it only allows 2 cameras.

patch will be applied while boot after installation of ss. please check and use correct version, that is mentioned while addon selection.

**Comment by Netember** [comment]
Thank You, i trying..
It already installs DSM 7.2 version 69057.
Happy New Year!

**Comment by AuxXxilium** [comment]
> Thank You, i trying.. It already installs DSM 7.2 version 69057. Happy New Year!

not dsm version, surveillance version. it is mentioned while addon selection.

**Comment by Netember** [comment]
Ok, I understand, just i happy for works my ugly realtek 8168 NIC.
ss version recommended other DSM (my home)

**Comment by AuxXxilium** [comment]
why? install ss 9.1.2 and everything would be fine.

**Comment by Netember** [comment]
testing it now
