### ISSUE TITLE
HP DL380 G9 Smart Array p440ar

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#733]
Hello, can I passthrough Smart Array p440ar into xpenology with SAS disk? I try do that with SATA disk and all work is good, but when I put SAS disk  - DSM see that disk but not work, and can't create pool. Try for DVA, DS, FS loaders - not work.

**Comment by AuxXxilium** [comment]
my sas disks in dl360 gen9 with p440ar are working without any issue.

**Comment by uroopek** [comment]
> my sas disks in dl360 gen9 with p440ar are working without any issue.

So you enter in HBA mode in p440ar? Or you use raid hardware?

I see all your video on YouTube, but you always give place from datastore in vm, not with pass through all controller p440ar like pci in vm.

**Comment by AuxXxilium** [comment]
hba mode

**Comment by uroopek** [comment]
> hba mode
> 
> https://youtu.be/rmmBK-uBLsA

Yes, I saw that video, it’s use Baremetal and load from usb? But I am use esxi, and try passthrought controller in esxi to vm.

**Comment by AuxXxilium** [comment]
These are my disks for testing: https://www.kimbrer.de/hp-sltn0900s5xnn010-7-s.html

passthru should not make any difference. please send diag code from arc - sysinfo - full diag - upload or screenshot from sysinfo.

**Comment by uroopek** [comment]
![Synology DVA 2023](https://github.com/AuxXxilium/arc/assets/16857877/ed2eb0f7-0433-49fd-a558-4d26d7a8896e)
![Synology DVA 2023-2](https://github.com/AuxXxilium/arc/assets/16857877/35234cd2-c244-43aa-b43f-5b248a81128d)

**Comment by AuxXxilium** [comment]
1. Update LKM in Arc
2. Choose a broadwellnk model

**Comment by uroopek** [comment]
1. going to update
2. I am try use all loaders and not work. now use dva because have GTX 1650 and use AI in SS.
3. PVSCI I am use to load DSM, bacause it not install in SAS disk. So I am add PVSCI to install DSM.

<img width="1238" alt="Synology-DVA - Synology NVR" src="https://github.com/AuxXxilium/arc/assets/16857877/b141835d-d580-43ff-ad9d-4557aa2ee274">

**Comment by AuxXxilium** [comment]
makes no sense, dsm will be installed on all disks while formatting/creating storage pool in dsm. try to deselect: scsi_transport_sas module in modules and rebuild <- only if updated lkm does not work.

**Comment by uroopek** [comment]
> makes no sense, dsm will be installed on all disks while formatting/creating storage pool in dsm. try to deselect: scsi_transport_sas module in modules and rebuild <- only if updated lkm does not work.

thanks, going to try this

**Comment by uroopek** [comment]
> makes no sense, dsm will be installed on all disks while formatting/creating storage pool in dsm. try to deselect: scsi_transport_sas module in modules and rebuild <- only if updated lkm does not work.

update LKM  not work, check all modules but not see scsi_transport_sas in modules, its the same name?

**Comment by AuxXxilium** [comment]
![Screenshot 2023-12-31 195311](https://github.com/AuxXxilium/arc/assets/67025065/eb5df100-db51-4711-ae26-660686c5be73)
![Screenshot 2023-12-31 195251](https://github.com/AuxXxilium/arc/assets/67025065/8b9957e3-4098-447f-81b4-9ec30704419d)

**Comment by AuxXxilium** [comment]
in broadwellnk the module is removed but you said you need to use dva3221 and there is the module included.

**Comment by uroopek** [comment]
> in broadwellnk the module is removed but you said you need to use dva3221 and there is the module included.

Hi, Happy New Year. I am delete vm and install new with new loader from 31.12, check broadwellnk and its not work, try few loaders. Maybe you know what also need to work? Or can you check this from esxi on your HP?
![Synology RS](https://github.com/AuxXxilium/arc/assets/16857877/f2ac8e9f-b099-4673-95bc-57f73a19db86)

**Comment by AuxXxilium** [comment]
if i install esxi on this, i can't passthru the controller.

**Comment by uroopek** [comment]
> if i install esxi on this, i can't passthru the controller.


Maybe you know what else I can try to do and make SAS disks work? If I insert a SATA drive, there are no problems, DSM sees it and creates a RAID without problems. On SAS it cannot even format the disk.

**Comment by AuxXxilium** [comment]
let me try something. i will report back soon.

**Comment by uroopek** [comment]
> let me try something. i will report back soon.

Thanks, waiting

**Comment by AuxXxilium** [comment]
It's possible a bios issue. All firmware at latest? p440ar and bios?

HBA Mode: enabled
Boot Mode: UEFI
UEFI Optimized Boot: enabled
Virtualization Technology: enabled
Intel VT-d: enabled
SR-IOV: enabled

Native install of DVA3221 successful. SAS Disks are detected and formatting is working.

<img width="1680" alt="Bildschirmfoto" src="https://github.com/AuxXxilium/arc/assets/67025065/3f48f06b-039d-4aa9-819a-02fb8dd15671">

**Comment by AuxXxilium** [comment]
<img width="1680" alt="Bildschirmfoto" src="https://github.com/AuxXxilium/arc/assets/67025065/0555fcd9-877b-438f-8d69-bddf8cbabaaf">

**Comment by uroopek** [comment]
> It's possible a bios issue. All firmware at latest? p440ar and bios?
> 
> HBA Mode: enabled Boot Mode: UEFI UEFI Optimized Boot: enabled Virtualization Technology: enabled Intel VT-d: enabled SR-IOV: enabled
> 
> Native install of DVA3221 successful. SAS Disks are detected and formatting is working.
> 
> <img alt="Bildschirmfoto" width="1680" src="https://private-user-images.githubusercontent.com/67025065/293599481-3f48f06b-039d-4aa9-819a-02fb8dd15671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzA0ODEsIm5iZiI6MTcwNDEzMDE4MSwicGF0aCI6Ii82NzAyNTA2NS8yOTM1OTk0ODEtM2Y0OGYwNmItMDM5ZC00YWE5LTgxOWEtMDJmYjhkZDE1NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE3Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzdjOWVhOTE3MzlmZDY5ZmJkMzQ5YmZlYTczYmFjZDUzYzcxNTc0ZWNhMzRmMjlmNjQwMTYwOGM3YzIwNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._eoQX8b5AzkaPiXckw-d0QUZJXTrH8pijQWBXWaY-Vk">

amazing, going to test.

**Comment by uroopek** [comment]
> It's possible a bios issue. All firmware at latest? p440ar and bios?
> 
> HBA Mode: enabled Boot Mode: UEFI UEFI Optimized Boot: enabled Virtualization Technology: enabled Intel VT-d: enabled SR-IOV: enabled
> 
> Native install of DVA3221 successful. SAS Disks are detected and formatting is working.
> 
> <img alt="Bildschirmfoto" width="1680" src="https://private-user-images.githubusercontent.com/67025065/293599481-3f48f06b-039d-4aa9-819a-02fb8dd15671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzA0ODEsIm5iZiI6MTcwNDEzMDE4MSwicGF0aCI6Ii82NzAyNTA2NS8yOTM1OTk0ODEtM2Y0OGYwNmItMDM5ZC00YWE5LTgxOWEtMDJmYjhkZDE1NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE3Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzdjOWVhOTE3MzlmZDY5ZmJkMzQ5YmZlYTczYmFjZDUzYzcxNTc0ZWNhMzRmMjlmNjQwMTYwOGM3YzIwNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._eoQX8b5AzkaPiXckw-d0QUZJXTrH8pijQWBXWaY-Vk">

I change boot in vm on esxi from EFI to BIOS, run and check DVA3221, passthrough PCI - Smart Array p440ar  - but not work. I see on your screen you also used usb for loader and baremetal HP. In my configuration - Smart Array p440ar ni HBA mode. ESXI 8.0U2 and VM (loader last DVA3221).

![3](https://github.com/AuxXxilium/arc/assets/16857877/b297c75e-ada5-493e-b5e4-49f62374387b)
<img width="857" alt="2" src="https://github.com/AuxXxilium/arc/assets/16857877/5c75b0e5-3e6e-4f86-bfa0-130c081ae02e">
<img width="856" alt="1" src="https://github.com/AuxXxilium/arc/assets/16857877/5f1c8b23-0780-4607-bb8c-fb4051fe65eb">

**Comment by AuxXxilium** [comment]
first switch back to uefi, is your host set to uefi? the settings above are RBSU settings from HP.

**Comment by AuxXxilium** [comment]
[Storage.zip](https://github.com/AuxXxilium/arc/files/13805492/Storage.zip)

This is my VM config. look if you find something.

**Comment by uroopek** [comment]
hi, I am find the problem. Synology on site say that use disk with 512e/4096 block, but my SAS disk Hitachi have 520 block, so I am passthrough in HBA mode to Ubuntu VM and use sg3-utils to format disk in 512 block and its good work. Thanks for answers and help.

**Comment by AuxXxilium** [comment]
nice to know. thanks for telling me.
