### ISSUE TITLE
Hibernation does not work on ARC - DS2422+

### ISSUE THREAD

**Issue by AdictiK5** [AuxXxilium/arc#734]
Hello,
I just installed your launcher, I was under ARPL then RR and now ARC, thank you for your work.

Everything works fine except hibernation. This worked well with my configuration under ARPL but it no longer works with RR or ARC.
In the log center we do not see any attempt at Hibernation, although the option is activated.

I have an Asrok Q2900M in bare metal, 14 HD with a PCI controller - DS2422+
I think I disabled everything that is useless in the BIOS

Here is the screenshot and code : A9F6M34E

<img width="1659" alt="Capture d’écran 2023-12-31 à 14 21 31" src="https://github.com/AuxXxilium/arc/assets/107766027/d9378257-2a50-4acf-aca0-19edbf29fde6">

If you have an idea I would like to try it. Thanks in advance.
Sincerely.

**Comment by AuxXxilium** [comment]
if you add hibernation addon, all logs for hibernation will be killed, because they wake up disks after some time or prevent hibernation. so you will not see any log entry for hibernation.

**Comment by AdictiK5** [comment]
Ok very well I understand.
Whether this addon is activated or not, hybernation does not activate after 10 minutes as I configured it.

**Comment by AuxXxilium** [comment]
1. dsm makes multiple background tasks after installation or reboot
2. so it takes some time before the system tries to hibernate the disks
3. if you don't have done, enable sata linkpower management

**Comment by AdictiK5** [comment]
OK I activated the recommended option and deactivated the rest.
Here is my config.

![IMG_4129](https://github.com/AuxXxilium/arc/assets/107766027/65df63c0-67c7-4205-8d00-8a07ba758650)
![IMG_4130](https://github.com/AuxXxilium/arc/assets/107766027/76bab5b3-03b7-480d-953e-731196a097be)
![IMG_4131](https://github.com/AuxXxilium/arc/assets/107766027/9274e90b-475e-48ec-b904-65206073c27c)
![IMG_4132](https://github.com/AuxXxilium/arc/assets/107766027/8c6e77f4-b1b2-4bee-beff-4854c9119710)
![IMG_4133](https://github.com/AuxXxilium/arc/assets/107766027/741c164f-236a-42e5-ac80-3ee0ab3ba20f)
![IMG_4134](https://github.com/AuxXxilium/arc/assets/107766027/090c08dc-bc49-4ea6-8e7b-6bae070c4da5)

I'll let it run and see if it works.

**Comment by AuxXxilium** [comment]
enable speedstep and c states (not c1e)

**Comment by AdictiK5** [comment]
Ok it's done.
![IMG_4135](https://github.com/AuxXxilium/arc/assets/107766027/d6742fac-cee2-4958-93bc-fb4212fa9f4c)

I'm waiting.

**Comment by AdictiK5** [comment]
I left it running all night and at no time did it go into hibernation.
An other idea?
Thanks

**Comment by AdictiK5** [comment]
Some news. 
By deactivating SMB, the NAS goes into hibernation.
What can I do?

**Comment by AuxXxilium** [comment]
Than you have an active smb connection. this is an absolutely normal behavior.

**Comment by AdictiK5** [comment]
I didn't have any SMB connections running.
Oddly enough, by deactivating SMB and all the default settings and reactivating them, the hibernation function works. 
But I don't know why because I put everything back as it was.

**Comment by AuxXxilium** [comment]
multi smb enabled?

**Comment by AdictiK5** [comment]
Here are the settings I activated and deactivated. Sorry it's in French.
<img width="602" alt="Capture d’écran 2024-01-01 à 15 15 30" src="https://github.com/AuxXxilium/arc/assets/107766027/8538891d-c397-4302-933f-b60a697db0e5">
<img width="604" alt="Capture d’écran 2024-01-01 à 15 15 38" src="https://github.com/AuxXxilium/arc/assets/107766027/6226d27a-4334-4434-9c5b-966315c3d541">
<img width="603" alt="Capture d’écran 2024-01-01 à 15 16 05" src="https://github.com/AuxXxilium/arc/assets/107766027/213a14c9-1386-49f2-84cf-5e615f419117">
<img width="604" alt="Capture d’écran 2024-01-01 à 15 16 12" src="https://github.com/AuxXxilium/arc/assets/107766027/35caf087-8aaa-4e29-9a88-296f23430ecc">
