### ISSUE TITLE
HP Microserver N36L without network after update or, maybe, stuck on boot

### ISSUE THREAD

**Issue by PRO100GREEK** [AuxXxilium/arc#737]
After update loader from 23.9.11a to 24.1.2 a system can't boot. Also on device list on my router a system is not displayed. I was tried directboot option, but there isn't any effect (i tried on arc-24.1.dev, arc-23.12.31, arc-23.12.10 and arc-23.12.1). If I downgrade the loader to 23.9.11a system will start normaly

![image](https://github.com/AuxXxilium/arc/assets/29138248/0d030533-a858-4b5d-b7a4-f15ad49ba585)

**Hardware**
HP ProLiant MicroServer Gen 7
CPU - AMD AthlonII NEO N36L
Mainboard - proprietary from HP
Chipset - AMD RS785E
Network controller - HP NC107i PCIe Gigabit Server Adapter
Storage controller - integrated on chipset

**Comment by AuxXxilium** [comment]
Do you have made a new config? or tried to restore your old? What way to update do you have used?

**Comment by PRO100GREEK** [comment]
Yes, I do. But I also tried to restore an old config via restore from code. 
Firstly, I tried upgrade loader from arc menu, then I tried update via rewrite a usb flash

**Comment by AuxXxilium** [comment]
reconfigure loader without backup and try again

**Comment by PRO100GREEK** [comment]
I have tried configure loader without backup, but it haven't any effect

**Comment by AuxXxilium** [comment]
don't know what you doing wrong.

Report from my Discord:

Alexander_Kaden — 01.01.2024 17:56
Hardware

Type: HP N54L
CPU: AMD Turion II Neo N54L, 2x 2.20GHz
Chipsatz: AMD RS785E/SB820M
RAM: 16GB
Disks: 2x 4TB WD RED
Network: HP NC107i mit Broadcom Chip
HP Microserver Remote Access Card


DSM

Model: DS3622xs+
DSM Version: 7.2.1 Update 3
Arc Version: 23.12.31
Arc Patch: yes
Macsys: hardware
AME: working
Drivesleep: untested

**Comment by PRO100GREEK** [comment]
I have tried DS3622xs+ but it haven't ant effect. I have tried any flash drives that i have but also no effect. I have tried flash usb drives on linux with etcher, set default settings on bios, select/deselect any modules, selecting different models (DS923+, DS1621+, DS3622xs+), select/deselect any addons but still no effect. On 23.9.11a system works fine, but after update it doesn't boot. All attempts that i have tried was without restore from backup from elder versions

**Comment by AuxXxilium** [comment]
can you prodive full diag of arc loader

**Comment by PRO100GREEK** [comment]
![image](https://github.com/AuxXxilium/arc/assets/29138248/944b4084-5959-4488-bed3-210561325879)

I also have uploaded with code 2JJCNSV98

**Comment by AuxXxilium** [comment]
He tried latest versions, clean install, DS3622xs+ and it is working on N54L. We can't find the issue with your system.
