### ISSUE TITLE
System Installation on a NVMe Drive

### ISSUE THREAD

**Issue by tomas123** [AuxXxilium/arc#739]
**Describe the Bug**
I know, it's not a bug but after booting Arc I get the message
"Please insert at least one Sata/SAS Disk for System Installation.."

Arc shows three drives: 
1. 256GB eMMC as /dev/mmcblk1
2. 256GB M.2 NVMe as / dev/nvme0n1
3. and the USB Stick as /dev/sda

The onboard M.2 slots accepts only a NVMe Drive.
I can't use a M2 SATA Drive.
There are no SATA ports on the board.

**Screenshots**
![boot](https://github.com/AuxXxilium/arc/assets/222947/fc0cd635-6bf9-4b66-ac78-ae98b74767a2)
![sysinfo](https://github.com/AuxXxilium/arc/assets/222947/22321402-b462-45db-817f-b50da341d5e9)
![format](https://github.com/AuxXxilium/arc/assets/222947/f7899bd0-b66b-4b15-bd96-e127c1a4d353)
![board](https://github.com/AuxXxilium/arc/assets/222947/c9af3e0c-3238-4396-84da-e7f081a0ab13)

**Hardware**
A fanless mini PC: MeLE Quieter 3C with Intel N5105 and 16GB RAM with very low power consumption.
I successful installed DSM with Proxmox on this board 
- as LXC Container (Docker vdsm/virtual-dsm with 3 Watt DSM idle) 
- and a Debian VM with Redpill (4 Watt with DSM idle)

But I want to install DSM directly on the hardware to better pass through external devices

https://store.mele.cn/collections/mini-pc/products/mele-quieter-3c-fanless-mini-pc-n5105-small-computer-portable-ddr4-windows11-hdmi-4k-wi-fi-6-gigabit-ethernet-bt-5-2-usb-3-2-3-type-c-dp-sd-card-ssd-support-vesa-mount

**Comment by AuxXxilium** [comment]
DSM install on NVMe is blocked by Kernel, we can't resolve this atm.

**Comment by tomas123** [comment]
I suspected so. 
Such great hardware and no SATA port…

Thanks for your great work

**Comment by AuxXxilium** [comment]
there are nvme to sata adapter ;) or wait until someone found a fix.

**Comment by tomas123** [comment]
wow
I can't imagine that the adapted SATA SSD would be set up as a SATA drive in the BIOS
![IMG_3043](https://github.com/AuxXxilium/arc/assets/222947/7d4af438-fde1-42e4-8309-857b040d646e)

**Comment by tomas123** [comment]
I solved the NVMe problem by switching the device:
- MeLE Quieter HD3Q Fanless Mini PC N5105
- the same fanless PC but with SATA port
- DS224+ works fine (disable in BIOS / SCS Configuration / eMMC 5.1 Controller)

**Comment by tmm1** [comment]
Looks like some work is happening to make this possible: https://github.com/AuxXxilium/arc-addons/commits/main/nvmeinstall

**Comment by tomas123** [comment]
Version: ARC 24.4.13

Thanks for your tip, but the host installation on NVMe is still not possible ...

![Bildschirmfoto 2024-04-14 um 17 51 14](https://github.com/AuxXxilium/arc/assets/222947/f8d410d0-e3c6-4f19-8f8c-4e11c0be5dab)
![Bildschirmfoto 2024-04-14 um 17 57 28](https://github.com/AuxXxilium/arc/assets/222947/b1fc15cb-d91f-4924-9909-1d2b6c6a96a8)

**Comment by AuxXxilium** [comment]
and it will never be working on these models!!!

**Comment by tomas123** [comment]
sorry
