### ISSUE TITLE
Ethernet not working in VMM

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#740]
Hi, try to use fake Mac or real Mac on esxi, but ethernet  not work in vmm (I try install ubuntu and windows vmm). Do you have any idea how to fix that?

**Comment by AuxXxilium** [comment]
looks like an issue in your network settings.

https://github.com/AuxXxilium/AuxXxilium/wiki/Settings:-Virtual-and-VM

`VMware ESXi Settings
Networking - vSwitch - Edit - Security - MAC address changes - ACCEPT
Networking - vSwitch - Edit - Security - Allow forged transmits - ACCEPT`

**Comment by AuxXxilium** [comment]
And to make this clear, VMM inside a Hypervisor need more changes in ESXi System and VM Settings.

**Comment by uroopek** [comment]
> looks like an issue in your network settings.
> 
> https://github.com/AuxXxilium/AuxXxilium/wiki/Settings:-Virtual-and-VM
> 
> `VMware ESXi Settings Networking - vSwitch - Edit - Security - MAC address changes - ACCEPT Networking - vSwitch - Edit - Security - Allow forged transmits - ACCEPT`

Yes, its accept.
Open vm tools I am installed in DSM

I see your video, you said to good work need accept only Mac changes in esxi. so, I do that. but now going to test another accepts. I am accept Mac changes and forget transmits - not working. but when I am accept Promiscuous mode - its working. thanks

<img width="816" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/7498e6cd-40d8-4c08-ae8c-fb9169e70c58">

**Comment by AuxXxilium** [comment]
yes, dsm will work with this settings, but if you use a vm inside a vm, there are different settings necessary.

**Comment by uroopek** [comment]
> yes, dsm will work with this settings, but if you use a vm inside a vm, there are different settings necessary.

Thanks, ps if some have use passthought raid controller in esxi to DSM and vmm inside DSM xpenology - VMware don't save this options, need to do this instructions:

As a workaround, please shut down the VM, then try to add the following two line in the VM configuration file whose extension is vmx:
vhv.allowPassthru="TRUE"
vhv.enable="TRUE"
Once you save the changes, re-register the VM using vim-cmd command, or remove it from the inventory, and add it again.
This should allow you to power on the VM with both Nested Virtualization and PCI Passthrough options enabled, however it's not supported by VMware GSS.

than all work good.
