### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by partola** [AuxXxilium/arc#742]
Hi, WMware virtual machine, virtual keyboard not working properly in versions 24.1.2 and 24.1.3. Version 23.12.31 and below working like a charm. Can i fix this? Thanx!

**Comment by AuxXxilium** [comment]
23.12.31 is working and all other not?

**Comment by AuxXxilium** [comment]
there are no changes that can cause this, possible you have to delete your nvram file and clean your cache.

**Comment by partola** [comment]
sorry, trouble was not here
