### ISSUE TITLE
DVA1622 video out only on first bootup

### ISSUE THREAD

**Issue by mtaiit** [AuxXxilium/arc#743]
**Describe the Bug**
Installing of DVA1622 with i915 addon works flawless. On the first time DSM bootup the (real hardware) display shows up the Synology splash screen and later the Surveillance Station Login-Screen. After setting up DSM and next reboot however, video output stays at the Arc screen and will never work again. DSM itself works fine.

**Screenshots**
Arc - Sysinfo or use new "Full Sysinfo - Upload" Function provide the Code!!! - Where to do this? Sorry

**Hardware**
Core i5 9400, Core i5-9400, ASUS H310M-A, 8GB RAM, Realtek LAN, Onboard SATA with 2 Drives

**Comment by AuxXxilium** [comment]
Use directboot.

**Comment by mtaiit** [comment]
Does not work. Screen stays now at "Directly Boot DSM Kernel", but still no Synology video output, DSM itself still working fine.

**Comment by AuxXxilium** [comment]
The problem here is, that this isn't supported by redpill module and it's a wonder that screen appears on first boot.

**Comment by mtaiit** [comment]
Okay, good to know. Last time I used dsm 7.1 with redpill - that worked fine with display out. Tried PeterSuh-Q3/tinycore-redpill too, but it trashes Synology Apps after the first boot. So I have to wait, but thank you very much :-)

**Comment by AuxXxilium** [comment]
peter is using same redpill version, so i can try to fix it.

**Comment by AuxXxilium** [comment]
1. Is your Local Display App inside SS running?
2. I formated my testsystem and rebooted 5 times now, everytime display comes back without any issue.

**Comment by mtaiit** [comment]
Yes, is running. But even before Surveillance Station is starting, the gray Synology Spalsh Screen does not show up. The Arc (or Direct Boot) text Screen stays and the blinking Cursor freezes. Maybe incompatible Hardware/BIOS at some point? Maybe I can build up antother test system

**Comment by AuxXxilium** [comment]
disable directboot, rebuild loader and try again, maybe dsm installation went wrong

**Comment by mtaiit** [comment]
Tried another System with an i5-4440 on a H81 Gigabyte Board - works fine. Very Strange
