### ISSUE TITLE
Unable to find device using synology assistant

### ISSUE THREAD

**Issue by fengyuan213** [AuxXxilium/arc#748]
**Describe the Bug**

I am unable to find the device using the Synology assistant
here is the screenshot
![image](https://github.com/AuxXxilium/arc/assets/26819159/3666e37a-2b13-49bb-8588-8c0b822b4a1c)

**Screenshots**
Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
![image](https://github.com/AuxXxilium/arc/assets/26819159/6573dcc5-49dc-45d6-95d4-ef9523c6ffee)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

![image](https://github.com/AuxXxilium/arc/assets/26819159/aa535ce2-b38e-4a6b-af3c-382a1e4910c7)

**Comment by AuxXxilium** [comment]
synology assistant is still trash and has much cache data. some of my official are also not shown, btw.
