### ISSUE TITLE
MIGRATION TO NEW ARC VERSION

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/arc#751]
Hello, I've been trying for days to perform a new installation of the new version of arc on my proxmox.
Unfortunately I get this error:

![image](https://github.com/AuxXxilium/arc/assets/31816231/8c961c81-2053-4437-92c2-c3f721c2e3b4)
![image](https://github.com/AuxXxilium/arc/assets/31816231/9c90aadf-3a39-4619-88f9-72647c341cd2)
![image](https://github.com/AuxXxilium/arc/assets/31816231/99e8d107-2377-403f-ae01-4059477cb5b7)
![image](https://github.com/AuxXxilium/arc/assets/31816231/8491f949-c718-4263-8670-628d540eaf7e)

**Comment by wifi75** [comment]
> nothing changed that can cause this. is a full upgrade with new clean config?

yes new loader installation and fresh configuration, while on the fisical hard disk was already present OS.

**Comment by AuxXxilium** [comment]
screenshot from arc - sysinfo and screenshot from proxmox vm config and settings

you can try to update the modules alone. possible the new modules can fix this, but atm it looks like a config issue.

**Comment by wifi75** [comment]
> screenshot from arc - sysinfo and screenshot from proxmox vm config and settings
> 
> you can try to update the modules alone. possible the new modules can fix this, but atm it looks like a config issue.

![image](https://github.com/AuxXxilium/arc/assets/31816231/e9254488-488a-4f81-90d7-605e2c7493a0)

![image](https://github.com/AuxXxilium/arc/assets/31816231/93bf17c1-c6ad-4608-bdc6-bee9c9dc23df)

**Comment by wifi75** [comment]
![image](https://github.com/AuxXxilium/arc/assets/31816231/2573e6b8-0782-434d-a824-062e93827d5f)

**Comment by AuxXxilium** [comment]
i see you use a serial controller, can you provide serial log?

do you have tried updated modules?

**Comment by AuxXxilium** [comment]
i don't know so much about prox(trash)mox. so you have to use google.

**Comment by AuxXxilium** [comment]
https://pve.proxmox.com/wiki/Serial_Terminal

**Comment by wifi75** [comment]
yes but I don't understand what you want me to do?
what log do you need?

**Comment by AuxXxilium** [comment]
serial log, the output from your serial console in proxmox.

**Comment by wifi75** [comment]
but the serial you see in the vm is used to have the synology OS terminal

**Comment by AuxXxilium** [comment]
Simply no. You added serial0 console, that will show all bootmessage, look at the link above.

**Comment by wifi75** [comment]
hello unfortunately I didn't understand what I have to do to show you the log, from my console I can only access the synology OS.
I'm stuck and I can't recover the NAS anymore

**Comment by wifi75** [comment]
I tried to force reinstall but it reaches 7% and then the usual network error appears.

**Comment by AuxXxilium** [comment]
use `qm terminal 125 ` and send me the output, you connected a serial console and this is not for display output!

**Comment by AuxXxilium** [comment]
and to make it clear, you tried 24.1.14?

**Comment by AuxXxilium** [comment]
![Screenshot 2024-01-14 200016](https://github.com/AuxXxilium/arc/assets/67025065/b1395931-9bfc-4d6a-a629-c01ee429f16d)

now it's up on you!

**Comment by wifi75** [comment]
version installed it is 24.1.14
then from proxmox shell I sent qm terminal 125 


![image](https://github.com/AuxXxilium/arc/assets/31816231/a42546bc-b4de-48ba-a21d-8ed44ac32b5a)

**Comment by wifi75** [comment]
![image](https://github.com/AuxXxilium/arc/assets/31816231/af472d89-826a-4cae-8576-a6030bafec23)

**Comment by wifi75** [comment]
bingo!

![image](https://github.com/AuxXxilium/arc/assets/31816231/06a988e3-d869-4e32-aadd-d43aef671117)

**Comment by wifi75** [comment]
hello I sent to you log as post before....

**Comment by wifi75** [comment]
hello , no news?

**Comment by AuxXxilium** [comment]
no because it is working for all other. don't know where your issue is.

**Comment by wifi75** [comment]
ok...
