### ISSUE TITLE
Multiple loader disks found, please insert only one

### ISSUE THREAD

**Issue by BarndB** [AuxXxilium/arc#754]
Hi,
With release 24.1.6, fresh install in VM (ESXi), installation of DSM is ok and I can reboot the VM without problem as long as I don't create a volume.
If a volume is created (JBOD, basic, Raid...) the loader will not "load" if the VM is rebooted.

"Multiple loader disks found, please insert only one loader disk"

Full Sysinfo:
![SysInfo](https://github.com/AuxXxilium/arc/assets/156379249/630b57c9-d934-4867-9f06-aed45c45a4f9)
![SysInfo_code](https://github.com/AuxXxilium/arc/assets/156379249/7d59a398-23fb-4bed-9756-10f6cf2ef007)

![start2](https://github.com/AuxXxilium/arc/assets/156379249/3e5c86c4-c05c-49f7-bb3f-a72defbe9a35)

With release 23.10.22a same VM same model, no problem.
If I upgrade the loader from this old version to the 24.1.6, the previously working installation (with volumes...) will print the same "error" when the VM is rebooted.

What do I have to perform ?
I'll try with releases in between 23.10.22a and 23.12.16 (same "multiple loader" problem)

Thanks for the amazing work

**Comment by AuxXxilium** [comment]
Do you have replaced the arc-flat.vmdk file? This check isn't in Code anymore. So i guess your Loader disk is bricked or something else like this. Replace the 2 vmdk files in ESXi and try again.

**Comment by BarndB** [comment]
Hi, good news, I am current not able to reproduce the default anymore.
My first thought was: DSM is messing with the disk of  the loader when the volume was created.
