### ISSUE TITLE
Can't get IP on e1000e

### ISSUE THREAD

**Issue by HittyStorm** [AuxXxilium/arc#755]
Hello. I'm trying to install DSM on Lenovo desktop with i7.
NIC was detected as e1000e, but it can't get IP-address and always skips by timeoot (no mattter what options is set in Advanced tab).
Quick boot in BIOS are disabled.
On PXE the NIC works fine...

I'm able to use USB Realtec nic while installing, but even on direct boot option I can't get adapter to work.

**Comment by AuxXxilium** [comment]
First: No Help without the mentioned informations for bugreports!
Second: Remove the Device from your DHCP/Router in Software and let them get a new IP.

**Comment by AuxXxilium** [comment]
FYI: If your i219 is not working, you have the same issue like me, your i219 id is more recent than the latest e1000e update for kernel 4.4.x is released, atm i try to backport the updated module from 6.x kernel, but this is not as simple as i thought.
