### ISSUE TITLE
Upgrade gives "check the network connection and try again" 

### ISSUE THREAD

**Issue by atillier** [AuxXxilium/arc#756]
**Describe the Bug**
I attempted an upgrade from 7.0 to 7.1 by keeping my previous loader (TCRP) and after the installation (from UI) it wasn't able to book. I tried numerous options to recover, with other boot loaders, and ended up here with ARC which seems promising. 

When I do the upgrade right now it stops around 40% and complain about the network connection. Is this a problem with ARC?

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/14177484/7d217546-1b89-4b4a-9040-dbe896d84caa)

![image](https://github.com/AuxXxilium/arc/assets/14177484/e723473f-ddde-41ce-a4bd-f9f1fb2d55d3)

**Hardware**
VM via ESXI 7

**Comment by AuxXxilium** [comment]
Look wiki to find your issue.

**Comment by atillier** [comment]
Thanks @AuxXxilium , sorry for not checking the wiki for the ESXi specifics. I didn't have the options turned on and never had to.

I switched them on now but are you suggesting the upgrade from my previous installation will fail? Will "force-reinstall dsm" lose my apps / settings?

**Comment by atillier** [comment]
So I gave it a go and I suspect the previous installation left in a stale state. As in it left data on the system partition:
<img width="956" alt="image" src="https://github.com/AuxXxilium/arc/assets/14177484/dd943db0-d84e-4e1e-a21e-9ebf5d5bd908">

Any idea how that can be flushed?

**Comment by AuxXxilium** [comment]
you can wipe the first 2 partitions (only if disk has 3 partitions) of disk from inside arc, dev options, format disks. but if you do this, you will loose your settings.

**Comment by atillier** [comment]
Thanks for helping @AuxXxilium , in the end I went back to my previous loader and managed to process with an upgrade. I should give ARC another shot later!
