### ISSUE TITLE
Static IP not work

### ISSUE THREAD

**Issue by Musyanon** [AuxXxilium/arc#757]
Hello,

I have try to add a Static IP for Loader here :

<img width="375" alt="Capture d’écran 2024-01-12 à 23 07 04" src="https://github.com/AuxXxilium/arc/assets/6967679/2435dc4c-bf92-4d2b-a37e-7f90d682d1e8">

But after that, I have lost internet on DSM. So I have restart to Loader to set DHCP and now I have internet but I can't set Static IP on DSM and it dosen't show the IP from DHCP : 

<img width="1853" alt="Capture d’écran 2024-01-12 à 23 13 08" src="https://github.com/AuxXxilium/arc/assets/6967679/3d5130a9-ef48-4602-b65c-f060a7abf8bb">

If I set Static IP, is just ignored and I can access to DSM only on DHCP IP.

<img width="1853" alt="Capture d’écran 2024-01-12 à 23 14 50" src="https://github.com/AuxXxilium/arc/assets/6967679/cdcbc3d7-f0b5-4c07-8eca-e3689c9bdbe0">

**Screenshots**
<img width="1205" alt="Capture d’écran 2024-01-12 à 23 18 36" src="https://github.com/AuxXxilium/arc/assets/6967679/f3b62def-b523-412e-bfef-599821b9d4e2">

<img width="150" alt="Capture d’écran 2024-01-12 à 23 20 39" src="https://github.com/AuxXxilium/arc/assets/6967679/824198c3-29eb-4d5c-9f2a-f9937f043e2c">

**Hardware**
I use a QNAP TS-671.

**Comment by AuxXxilium** [comment]
"Static IP for Loader" <- Loader not DSM

**Comment by Musyanon** [comment]
But all work fine on DSM before I have set Static IP from Loader.

I think I have lost internet when I have set IP on Loader because it claim only IP and Mask but not Gateway and DNS.
And now I have set Loader to DHCP, DSM ignore Static IP...

**Comment by AuxXxilium** [comment]
Static IP is for Loader and not for DSM.

**Comment by Musyanon** [comment]
Ok, so it's strange, because I have try to set 192.168.1.200 to Static IP Loader and then I can access to DSM for the same IP :(

**Comment by AuxXxilium** [comment]
you can use same ip. set static in dsm and in loader. so both are on same ip.
