### ISSUE TITLE
HBA - HDDs are not visible under DSM

### ISSUE THREAD

**Issue by paskovitch** [AuxXxilium/arc#759]
I have a Dell R210 II server. I am running Xpenology natively from a USB. The HDDs are visible during server boot, also in Xpenology system info. However, DSM recognizes only the HDD connected to the onboard SATA. The HBA has a mix of SATA and SAS HDDs. I am using ARC version 24.1.6.
What could be the problem?
![HBA](https://github.com/AuxXxilium/arc/assets/44291654/7f1f25d0-2ff4-43ab-8ecf-1fdd8191d2a1)
![info](https://github.com/AuxXxilium/arc/assets/44291654/442be11a-a12e-4bd4-8dca-cc70353715ba)

**Comment by AuxXxilium** [comment]
HBA Mode? Has every disk an own serial? Or is it only done by Raid0 for every disk?

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Notice-&-Workarounds

**Comment by paskovitch** [comment]
This is a Perc H200 card in IT mode. The HDDs are completely formatted, and there is no RAID configuration. I haven't configured anything on the HBA card either. I could format them under DSM, but I can't do it because they are not visible.

**Comment by AuxXxilium** [comment]
If both is true you can try with update modules:

Try version: 24.1.3 and 24.1.13 and report back which is working.

**Comment by paskovitch** [comment]
24.1.3 works fine :)
![fine](https://github.com/AuxXxilium/arc/assets/44291654/0a7326f7-0ea3-4383-8ba8-b5d79e521af0)
Thank you!

**Comment by AuxXxilium** [comment]
no problem. have fun ;)
