### ISSUE TITLE
Cant boot synology after arc update

### ISSUE THREAD

**Issue by michalkulik** [AuxXxilium/arc#763]
**Describe the Bug**

After updating arc loader using update all from 24.1.3 to 24.1.4 when I try to boot into synology I receive only "Sorry, page cannot be found" and after about 30 seconds system powers off. I tried force reinstall, directboot, downloading 24.1.3 to USB again - nothing works.

**Screenshots**
Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

![image](https://github.com/AuxXxilium/arc/assets/121319543/d144241d-7e3e-49e5-827b-a5ee6550e453)

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...

HP 800 G3 SFF, Intel i5-7500.

**Comment by AuxXxilium** [comment]
can't help without mentioned informations

**Comment by AuxXxilium** [comment]
Screenshot from Arc - Sysinfo !!!

**Comment by michalkulik** [comment]
I'll provide it tomorrow, but to be honest I don't think, that it'll help - as I wrote earlier configuration doesn't matter, I've tried to reflash USB with 24.1.3 img, force reinstall DSM, nothing helps - after 30 seconds from booting to DSM system powers off (like there is some kind of kernel panic or something) - it's defenitely not browser cache since server goes down.

**Comment by AuxXxilium** [comment]
> ![image](https://github.com/AuxXxilium/arc/assets/25863699/965a95d8-4551-4bef-b9a2-cc86a6d38d43)
> 
> **and here is my arc-sysinfo screenshot**

do you gave tried your intel nic?

**Comment by AuxXxilium** [comment]
Update to .17
