### ISSUE TITLE
SaS disk SMART

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#766]
Hello, I am passtrought HP Smart Array 440ar in my HP DL380, Smart Array in HBA mode, use last version arc loader with DVA3221. I see that DSM not work SMART in disk, but if I install scrutiny - I see all smart information, temperature, etc.
in DSM Cli - smartctl also see all disk and all SMART information. How can I fix that in DSM?

<img width="1345" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/0d03786a-3f8b-49b8-93dc-4d9b69dcd592">
<img width="1000" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/27e1961f-3913-4f7a-8af5-21957f2a5cd2">
<img width="1229" alt="image" src="https://github.com/AuxXxilium/arc/assets/16857877/d2c15007-6596-47f3-88eb-f6508cf2fafc">

**Comment by AuxXxilium** [comment]
since dsm 7.2 smart informations are removed from dsm. use google you will find multiple posts about this.

**Comment by uroopek** [comment]
> since dsm 7.2 smart informations are removed from dsm. use google you will find multiple posts about this.

I am not about this. in 7.2 you will not see smart, but smart is work, she check temperature and other for smart and if you have bad sector  - its says about this. I see massages about smart on xpenelogy, they says about drivers, its work for us and arc loaders?

https://xpenology.com/forum/topic/13910-xpe-in-esxi-with-rdm-passthrough-and-smart/
https://xpenology.com/forum/topic/12391-nvme-optimization-baremetal-to-esxi-report/#comment-88690
