### ISSUE TITLE
DVA3221 and disk panel x24 in new loader not working

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#769]
Hi, I am passthrough HBA controller in esxi, use DVA3221 and loader 24.1.6 with disk x24 and all good work in DSM, but when I user latest 24.1.16 loader  - disk24 not work in DSM, I am install previous 24.1.14f and this same not work in DSM. Then I am install 24.1.6 again - and its good work.

**Comment by uroopek** [comment]
and can't activate AME in 24.1.14-24.1.16, go back to 24.1.6

**Comment by AuxXxilium** [comment]
ame is possible that it will not work on some models, atm. 

disks should work and storagepanel need a reboot.

**Comment by uroopek** [comment]
I am take patch AME in addon and it’s work now, but I am use arc patch and see massage don’t use ame patch if use arc patch. So it’s not broken dam?

**Comment by AuxXxilium** [comment]
no some idiot reported the way to patch to syno. but actually they only block ame, quickconnect is working so far.

**Comment by uroopek** [comment]
> no some idiot reported the way to patch to syno. but actually they only block ame, quickconnect is working so far.

so its same patch not work in addon? Going to test quckconnect and its always says - buy, try within 5 minutes. and not work

**Comment by AuxXxilium** [comment]
than you havn't selected correct config with arc patch.

**Comment by uroopek** [comment]
> than you havn't selected correct config with arc patch.

I try other loaders like 24.1.6-24.1.13-24.1.13-24.1.16 and in DVA3221  - it's not working. How do I am correct install arc patch for this DVA? 
When I test it in DS loaders - work fine, but I need DVA because use GPU

**Comment by AuxXxilium** [comment]
use .17 after release

**Comment by uroopek** [comment]
> use .17 after release

ok, waiting for release, thanks

**Comment by uroopek** [comment]
not work. but I remember its work month ago, so I am update loader to version 23.12.16 and its work. can you fix this in new loader versions?
