### ISSUE TITLE
offline upgrade via update package

### ISSUE THREAD

**Issue by Kool-Shine** [AuxXxilium/arc#770]
**Is your feature request related to a problem? Please describe.**
Hi there, I noticed that the release files include an update package, but I couldn't find any instructions for offline upgrades on the wiki. May I ask if offline upgrades are supported?

**Additional context**

**Comment by AuxXxilium** [comment]
Update package or something like this, will not work. Offline you have change bootimage.

**Comment by Kool-Shine** [comment]
Got it. Thanks for reply.
