### ISSUE TITLE
Hardware transcoding not working

### ISSUE THREAD

**Issue by oz666** [AuxXxilium/arc#772]
***Not sure if this is a loader problem, apologies if this is not the right place to address it ***
Hardware transcoding not working on DS918+ with Intel iGPU 11th generation.
Additional information on the problem:
https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/?do=findComment&comment=455246

https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/?do=findComment&comment=455277

**Hardware**

CPU: N5095
https://www.intel.com/content/www/us/en/products/sku/212322/intel-celeron-processor-n5095-4m-cache-up-to-2-90-ghz/specifications.html?wapkw=n5095
 Mainboard:
https://www.globalsources.com/product/nas-board_1208861130f.htm

**Comment by AuxXxilium** [comment]
Up to 10th gen, not 11th gen!
