### ISSUE TITLE
DVA3221 installation stuck at 55% screen

### ISSUE THREAD

**Issue by olegcarguy** [AuxXxilium/arc#774]
I am trying to install DVA3221 on ESXi and am stuck at 55% installation screen.

![image](https://github.com/AuxXxilium/arc/assets/29559821/ea63ac7d-8fba-4df1-96ba-bdebfeef694e)

I have uploaded full sysinfo and the code is 39MNUD8S4

**Comment by AuxXxilium** [comment]
Update loader

**Comment by olegcarguy** [comment]
Hi @AuxXxilium that's for posting a new release.  I've tried it and I'm stuck on the same 55% screen as before.  Can you suggest something else to try?

**Comment by AuxXxilium** [comment]
if you vm and arc config is correct, there is no way to stuck. so you have done something wrong.

**Comment by olegcarguy** [comment]
@AuxXxilium I'm not sure what I'm doing wrong.  I'm using RDMs in esxi to mount existing disks that had DSM 7.x on it via tinycore loader as DS918+.  My VM is set up exactly like this link: https://xpenology.com/forum/topic/62547-tutorial-install-dsm-7x-with-tinycore-redpill-tcrp-loader-on-esxi/ and RDMs are supported.

What does it actually mean when it stops install at 55%? can't find disks? can't download pat?

**Comment by AuxXxilium** [comment]
i just installed a dva3221 and everything is working without an issue. if you have an old installation on disk, it is possible that installation will fail. because tcrp uses different boot scripts. 

next check wiki for correct settings.

**Comment by olegcarguy** [comment]
@AuxXxilium here are my VM hard disk settings.  I have also checked your wiki and update ESX settings, but still the same problem.  
![image](https://github.com/AuxXxilium/arc/assets/29559821/14565f22-0639-43e6-ac8c-1916b4456721)

are there any logs from the boot process that I can send?

**Comment by AuxXxilium** [comment]
So for your information:

- DSM will be installed on every Disk
- TCRP used different Bootscripts and Filepatches for DSM installation -> they are copied to every Disk
- So you can't switch loader as simple as you think.

**Comment by olegcarguy** [comment]
Hi, I eventually figured this out.  The problem was the old OS on the RDMS.  I had to repeat the installation a few times and then also upload the .pat file during the install wizard to not get the 55% error.  Eventually I got the loader working properly. thanks for your quick help
