### ISSUE TITLE
How to get "normal" USB mount with LSI2008 ?

### ISSUE THREAD

**Issue by Loweack** [AuxXxilium/arc#782]
**Describe the Bug**
I recently migrated to the Arc Loader for DSM 7.x but the USB behavior changed quite a lot. Before I could plug and external HDD and it was recognize as external. Now with Arc, I can't mount it as external (it is shown as internal even a simple USB drive). I tried to change the "USB Mount Options" but either is doesn't see my **internal HDD** (on a LSI SAS2008) when I select "Mount USB as device" or it remains as internal drive when I choose "Mount USB as internal" or "Mount USB automatically".

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/64659299/73697ff9-73a7-4dde-9fa4-8d7171b3d377)

**Hardware**
Dell OptiPlex 7010 with integrated SATA disabled. I used a IT flashed PERC H200 (LSI SAS2008). On this card I have 6 disks.

**Comment by AuxXxilium** [comment]
Build your own usbportcfg and internalportcfg. set them in loader config.

the usb mount switch is in early testing state.

arc is force usb drives as internal because of to much user request for this. so i will never change this back.

**Comment by Loweack** [comment]
> Build your own usbportcfg and internalportcfg. set them in loader config.
Do you have any guide that could help? Because I understood I need to change some hexa values, but I don't understand of to get those values. Thank you!

> arc is force usb drives as internal because of to much user request for this. so i will never change this back.
No problem ;-)

**Comment by Loweack** [comment]
Should I follow this tutorial? >> https://hedichaibi.com/fix-xpenology-problems-viewing-internal-hard-drives-as-esata-hard-drives/

**Comment by AuxXxilium** [comment]
nice, actually i try to find a why for user to switch usb mount option
