### ISSUE TITLE
DSM 7.2 Control panel not opening after updating to 24.1.20-next (reproductible also using 24.1.21-next)

### ISSUE THREAD

**Issue by JANogueira** [AuxXxilium/arc#783]
**Describe the Bug**
After updating ARC to 24.1.20-next DSM webUI started to throw some errors on the Broser debug console.
![image](https://github.com/AuxXxilium/arc/assets/22750391/0af1bbbc-a553-461d-b23c-f62449ca6e80)

Control panel doesn't open, and the last error (bottom) is the respective error for that.

**Screenshots**
![image](https://github.com/AuxXxilium/arc/assets/22750391/0e370639-7444-49ae-9a82-c24fd2deb574)
When clicking on control panel, the icon keeps in definitely like this:
Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT

Full Sysinfo code: 
![image](https://github.com/AuxXxilium/arc/assets/22750391/b31b03a0-027b-4f57-ab32-866769a7633e)
G22EHCBVX

**Hardware**
VM running on proxmox 8.1.4 (CPU: host, system CPU: intel i5-10500T).
No problems seen until 24.1.14f.
After upgrading to 24.1.20-next (and performing clean configuration as suggested), this started happening. Reinstall DSM didn't fix the problem.

DSM version: 7.2.1-69057 update 4

Attaching HAR trace for reference:
[192.168.50.30.har.txt.zip](https://github.com/AuxXxilium/arc/files/14001784/192.168.50.30.har.txt.zip)

**Comment by AuxXxilium** [comment]
DSM force reinstall will help! See messages in .19-next .20-next release. If you do everything right, it will work after this.

**Comment by AuxXxilium** [comment]
And i know it is working, because we had this multiple times in discord the last days!

**Comment by JANogueira** [comment]
Thanks. I will try again.

**Comment by JANogueira** [comment]
OK, now I understand what went wrong.
I reinstalled DSM, but went immediately back again to the loader menu, forced reinstalling the loader version along with respective addons, modules, etc (all manually configured), and due to this, DSM reinstallation was not being done.
Now I tried again and waited for the normal boot process, and after reinstallation, all is working.

Thanks
