### ISSUE TITLE
No model shown on the "Choose model" configuration menu

### ISSUE THREAD

**Issue by Tratosca** [AuxXxilium/arc#784]
When booting the latest release `arc-24.1.21-next` on Proxmox, I can't see any model, as below: 
![CleanShot 2024-01-21 at 21 53 52@2x](https://github.com/AuxXxilium/arc/assets/34960953/5d9297b5-1ec2-424a-8091-da3201031866)

Here are the VM settings I'm using currently (`sata0` being the Arc bootloader image)
![CleanShot 2024-01-21 at 21 55 15@2x](https://github.com/AuxXxilium/arc/assets/34960953/c6b3cc12-7799-4ca4-9e3a-08b3d64628d6)
I tried messing around with those settings (BIOS types, SCSI controllers,...) without success.

Here are the VM options, if needed:
![CleanShot 2024-01-21 at 21 58 47@2x](https://github.com/AuxXxilium/arc/assets/34960953/90eac2be-1829-453b-af0a-2105a5b0af3f)

Some infos about my environment: 
Version: PVE 8.1.3
CPU: Intel(R) Xeon(R) CPU E5-1607 v4 @ 3.10GHz (1 Socket)
Boot: EFI

Thanks a lot for this project tho ! 

EDIT: the `bug` label has been assigned automatically, I'm sorry if this is a misconfiguration on my end rather than a bug.

**Comment by AuxXxilium** [comment]
upgrade loader and try again. something with your update went wrong.
