### ISSUE TITLE
How to remove addons Misc?

### ISSUE THREAD

**Issue by Yurause** [AuxXxilium/arc#786]
It doesn't work correctly with MB Asrock j3455-itx.

**Comment by AuxXxilium** [comment]
can't be removed, is necessary for boot

**Comment by Yurause** [comment]
On RR you can delete. And why is it needed when loading? The script does not correctly detect the processor and disables acpi-cpufreg :-\

**Comment by AuxXxilium** [comment]
if the script is disabling acpi on you system, you turned some needed acpi function off in bios.
