### ISSUE TITLE
Dell sas 6 poweredge

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#796]
08:00.0 SCSI storage controller: Broadcom / LSI SAS1068E PCI-Express Fusion-MPT SAS (rev 08)
        Subsystem: Dell SAS 6/iR Adapter RAID Controller
        Flags: bus master, fast devsel, latency 0, IRQ 16, NUMA node 0
        I/O ports at b000 [size=256]
        Memory at f7210000 (64-bit, non-prefetchable) [size=16K]
        Memory at f7200000 (64-bit, non-prefetchable) [size=64K]
        Expansion ROM at f7100000 [disabled] [size=1M]
        Capabilities: [50] Power Management version 2
        Capabilities: [68] Express Endpoint, MSI 00
        Capabilities: [98] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [b0] MSI-X: Enable- Count=1 Masked-
        Capabilities: [100] Advanced Error Reporting
        Kernel driver in use: mptsas
        Kernel modules: mptsas

This card is not working with arc not even showing hard drives in the arc menu

**Comment by Edwardpge** [comment]
![Screenshot 2024-01-24 211037](https://github.com/AuxXxilium/arc/assets/101920742/9b130382-b853-42a1-adee-31e2496e826b)

**Comment by AuxXxilium** [comment]
DT Model, will not work with SAS/SCSI Controller. Check wiki, pls.

**Comment by Edwardpge** [comment]
i don't get it! you mean this is card not support by my DSM model or all DSM models?

**Comment by AuxXxilium** [comment]
not supported by DT model. so read wiki and find a platform/model you can use with this.

**Comment by Edwardpge** [comment]
Will the intel model work with amd processors?

**Comment by AuxXxilium** [comment]
read wiki!
