### ISSUE TITLE
jq: parse error: Invalid numeric literal at line 1, column 10

### ISSUE THREAD

**Issue by Ssyleric** [AuxXxilium/arc#797]
**Describe the Bug**
From the version 23.12 to 24.1.22-next
After updated i have this error
jq: parse error: Invalid numeric literal at line 1, column 10

**Screenshots**
<img width="484" alt="Screenshot 2024-01-24 at 17 17 14" src="https://github.com/AuxXxilium/arc/assets/47066760/1327c324-2762-4358-a556-2252a59ff7d7">
<img width="890" alt="Screenshot 2024-01-24 at 17 17 41" src="https://github.com/AuxXxilium/arc/assets/47066760/ac199100-0170-42c0-9871-7d6c74070112">
<img width="425" alt="Screenshot 2024-01-24 at 17 21 42" src="https://github.com/AuxXxilium/arc/assets/47066760/a3f54687-fe5b-4119-9113-fc632ff2838b">
<img width="819" alt="Screenshot 2024-01-24 at 17 22 11" src="https://github.com/AuxXxilium/arc/assets/47066760/7d78ec0b-65f8-4288-9584-a59fbfcc18fc">

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
<img width="419" alt="Screenshot 2024-01-24 at 17 24 45" src="https://github.com/AuxXxilium/arc/assets/47066760/7e636234-6be5-40d0-8d68-33c7a401b3ee">

**Comment by AuxXxilium** [comment]
i would never boot a system like this in legacy mode!

if it fails at this step, your connection to syno api is broken, so check adblocker, firewall and dns.
