### ISSUE TITLE
TG3 not showing up in DSM! DS2422+

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#798]
06:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
        Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
        Flags: bus master, fast devsel, latency 0, IRQ 47, NUMA node 0
        Memory at f7400000 (64-bit, non-prefetchable) [size=64K]
        Expansion ROM at <ignored> [disabled]
        Capabilities: [48] Power Management version 3
        Capabilities: [50] Vital Product Data
        Capabilities: [58] Vendor Specific Information: Len=78 <?>
        Capabilities: [e8] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [d0] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [13c] Virtual Channel
        Capabilities: [160] Device Serial Number 00-10-18-ff-fe-77-62-5f
        Capabilities: [16c] Power Budgeting <?>
        Kernel driver in use: tg3
        Kernel modules: tg3

**Comment by Edwardpge** [comment]
<img width="484" alt="299383898-1327c324-2762-4358-a556-2252a59ff7d7" src="https://github.com/AuxXxilium/arc/assets/101920742/88283e47-82b2-4e61-8ce5-c01039bcee3a">
in previous bud aboud SAS you mean these DT models? or you mean this card is not gonna run on any DSM model?

**Comment by AuxXxilium** [comment]
tg3 is working (use it here in different systems!) but your system run in kernel panic because of you selected an unsupported model for your hardware. there are about 3 warnings that this will not work, first in wiki, second in model selction (force incompatible models), third onscreen message. i don't know why you try to do this.
