### ISSUE TITLE
I'm still have problem with fake MACs on DVA 3221

### ISSUE THREAD

**Issue by vinphan** [AuxXxilium/arc#800]
**Describe the Bug**
Although I set fake mac for DVA 3221, but it does not work to use Synology services

**Screenshots**
Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
<img width="896" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/06562dea-32ee-4df3-8480-a642a9a40cd0">

**Hardware**
Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...
<img width="578" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/bf6f754e-61f5-464c-a5f8-ad310b42d02a">

**Comment by AuxXxilium** [comment]
not the informations i need to help.

**Comment by vinphan** [comment]
> not the informations i need to help.

Really? Come on

**Comment by AuxXxilium** [comment]
"Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT"

**Comment by vinphan** [comment]
> "Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT"

Oh I see
<img width="475" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/2cc457d7-f9ab-43e0-a01e-497fd7a034df">
<img width="469" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/46c0d73d-a062-4aa0-b87f-b82facd7c0bd">
<img width="283" alt="image" src="https://github.com/AuxXxilium/arc/assets/144933689/24b4b746-a770-4f44-956c-f20dc8149b7c">

**Comment by AuxXxilium** [comment]
check your portmap, is not the option that has the *! please read the description of the step before choose something.

and set your system to uefi mode.

**Comment by AuxXxilium** [comment]
other option is to set dns to: 1.1.1.1 or try with 8.8.8.8. some dns server are blocking syno connection.

**Comment by uroopek** [comment]
have same problem in dva3221, not work AME, have problem like in screenshot. try all loader from January 2024.
