### ISSUE TITLE
 SA6400 USB UART Driver

### ISSUE THREAD

**Issue by error105** [AuxXxilium/arc#801]
Hi, there is any option to use CH340 USB (like Zigbee coordinator) for build SA6400 and DSM7.2 ?
I cant find any info :(

**Comment by AuxXxilium** [comment]
try it, but should not be possible because of syno changes in kernel and limitations (removed most of the usb support)

**Comment by AuxXxilium** [comment]
2 possible options are:

- use docker
- use: https://mariushosting.com/synology-how-to-add-usb-support-on-dsm-7/

support can't be added to kernel/loader again, you need to install community package or use docker!

**Comment by error105** [comment]
I know that, and it works perfect on my J4125, now im migrate to N100 CPU so im need to install SA6400 if i want use iGPU acceleration....
I cant find proper modules on similar page:
https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules

Thats why im ask there about option to use USB in Docker.

**Comment by AuxXxilium** [comment]
you can add them manually. look into loader.

**Comment by error105** [comment]
Im dont get it, in loader is option to add USB driver?

**Comment by error105** [comment]
> you can add them manually. look into loader.

Can u tell me how? And which one i should use for SA6400? Im trying add from r1000 and v1000 - both not works and i dont have /dev/ttyUSB or /dev/ttyACM :(

**Comment by AuxXxilium** [comment]
and again, it isn't loader related! all modules to support this are included, but syno removed most usb support with dsm 7. i can't tell you what is working or not.
