### ISSUE TITLE
open-vm-tools-7.x-12.3.0 not work

### ISSUE THREAD

**Issue by uroopek** [AuxXxilium/arc#803]
open-vm-tools-7.x-12.3.0 not work  - in esxi/vcenter try shutdown - not work. use DVA loader and DS, can you fix that?

**Comment by AuxXxilium** [comment]
than you made something wrong. i ise them in esxi 7 and 8 and they work!

**Comment by uroopek** [comment]
I am use 7 and 8 version - not work. previous open-vm-tools version I try 1 month ago and he is work, but this not work in my system.

**Comment by AuxXxilium** [comment]
do you have entered the ssh command?

**Comment by AuxXxilium** [comment]
![Screenshot 2024-01-27 114600](https://github.com/AuxXxilium/arc/assets/67025065/c1b1ff9b-d4f2-48af-a02e-1fdfd32502b5)

Just installed

**Comment by uroopek** [comment]
> do you have entered the ssh command?

What command I need to use?
Do you try shutdown guest ?

**Comment by AuxXxilium** [comment]
yes and everything is working. cmd is in release notes of open-vm package

**Comment by uroopek** [comment]
> yes and everything is working. cmd is in release notes of open-vm package

on your wiki or need find original open-vm package? Previous time I am not use any command and work fine. Can you send link about this command?

**Comment by AuxXxilium** [comment]
https://github.com/AuxXxilium/synology-dsm-open-vm-tools/releases/tag/open-vm-tools-7.x-12.3.0

**Comment by AuxXxilium** [comment]
for me it is working, this doesn't have to do anything with loader.

**Comment by uroopek** [comment]
> for me it is working, this doesn't have to do anything with loader.

maybe its problem with passthrough GPU, try reload and off passthrough.
