### ISSUE TITLE
Error in network.sh line 22 during setup

### ISSUE THREAD

**Issue by bandit400** [AuxXxilium/arc#809]
During the setup process, an error occur in **network.sh** at line **22**:

![Immagine 2024-01-27 182232](https://github.com/AuxXxilium/arc/assets/52614292/3ead680d-386e-465f-af01-34e23cf39b88)

Emulated hardware: **Synology DS-920+**
Bootloader: AuxXxilium Arc **24.1.27-next**
Synology DSM: **7.2.1 build 69057**

The Synology DSM virtual machine running on **Oracle VirtualBox 7.0.6 r155176 (Qt 5.15.2)**

**Comment by bandit400** [comment]
Excuse me, Christian, but what is the solution to the problem?

Just now, in addition to this bug, I've experienced a strange malfunctionig: the DSM start in "DSM mode", it's still alive just a few second and the VM stops abruptly, spontaneously. It's the first time that i encounter this kind of behavior.

**Comment by AuxXxilium** [comment]
use latest .dev build

you ware the only 1 who has this bug. i guess your image is broken.

**Comment by bandit400** [comment]
I start with a fresh installation after the first crash. I've had the same doubt, but I think to exclude an error during the setup process. Also the VM is new, to exclude a VirtualBox VM's problems.

**Comment by AuxXxilium** [comment]
please describe what you do after arc overlay is shown, exactly!

**Comment by bandit400** [comment]
Ok, it's a fault of setup procedure. With GParted i've cleaned the DSM OS partitions and the setup process ends with succes. Excuse me for the wasted time... :D
