### ISSUE TITLE
NAS stop working

### ISSUE THREAD

**Issue by myoname** [AuxXxilium/arc#810]
Last used - arc-24.1.22-next. After stopped working Control panel, tried to update to last version of loader 24.1.27-next, but NAS is powering off after booting. Tried DSM reinstall - powering off. Erased first partition on every disk - powering off

**Comment by AuxXxilium** [comment]
complete wrong way. select force resinstall dsm and build with a clean config.

**Comment by AuxXxilium** [comment]
better you read the messages in first -next release.

**Comment by myoname** [comment]
It was working before. Please help, where resinstall dsm and build with a clean config in loader?

**Comment by myoname** [comment]
oK, DSM force Reinstall, I'll try

**Comment by AuxXxilium** [comment]
i can't help, because you destroyed your installation with format partition1

**Comment by myoname** [comment]
DSM reinstalled to 1st partition

**Comment by AuxXxilium** [comment]
guy, it's not only first!

**Comment by myoname** [comment]
1st partition is only firmware, is't it?

**Comment by AuxXxilium** [comment]
no! it's much more than this.

**Comment by bandit400** [comment]
Christian, here is another case like mine. I thought there was a problem during the upgrade and solved it by wiping the DSM OS partitions and reinstalling as DS-923+ instead of DS-920+ in a VirtualBox environment. This seems to have solved the problem, but the fact remains that the bootloader update broke the previous perfectly working installation. Please can you help us to verify that everything is in order? Thank you in advance.

**Comment by AuxXxilium** [comment]
what is broken?

**Comment by bandit400** [comment]
> what is broken?

https://github.com/AuxXxilium/arc/issues/809#issuecomment-1913577889

**Comment by AuxXxilium** [comment]
> > what is broken?
> 
> [#809 (comment)](https://github.com/AuxXxilium/arc/issues/809#issuecomment-1913577889)

i can't help, without any information. read guidelines for bugreport and do the correct steps. and describe clear and exact where the issue is!

**Comment by myoname** [comment]
Restored NAS with DSM force reinstall. Thank you. But only one thing - DSM must be reinstalled after first DSM booting, reinstall after loader building don't work.

**Comment by AuxXxilium** [comment]
this is normal. because you install disk image is clean after creation.
