### ISSUE TITLE
Addon i915 is not working (24.1.28-next)

### ISSUE THREAD

**Issue by dj-nsk** [AuxXxilium/arc#815]
Full upgrade Loader to **24.1.28-next**, clean config, add i915, build... After starting DSM (DS920+), the file is unpatched (size of i915.ko is 2096k).

Than: full upgrade Loader to **24.1.19**,  clean config, "DSM Force Reinstall" - the file is patched (size of i915.ko is 2095k, /dev/dri exists)

**Comment by AuxXxilium** [comment]
i915 will not be patched. same in the past.

**Comment by dj-nsk** [comment]
Sysinfo Upload Code: HGPASMLVW - in this config the patch works (24.1.19)

**Comment by AuxXxilium** [comment]
we havn't used an patched i915 in arc in the past. so let me know which file you use.

**Comment by dj-nsk** [comment]
I prepared the patch file myself according to this instruction - https://imnks.com/6421.html

**Comment by AuxXxilium** [comment]
this way was never used in arc. let me try something today.

**Comment by dj-nsk** [comment]
Yes! I report: in version 24.1.30-next, the problem is solved - the installation of the i915 addon on the i9-9900K is successful, /dev/dri appears. Thank you very much!
