### ISSUE TITLE
emmc device cannot be used as a loader disk 

### ISSUE THREAD

**Issue by h0we** [AuxXxilium/arc#818]
When I use the built-in emmc device as the loader disk, arc prompts me that it does not belong to the USB/SATA/Nvme type and cannot be booted.

**Code**
 
![图片_20240131201908](https://github.com/AuxXxilium/arc/assets/102644729/2a9818b5-6ad7-4f51-915e-53e718bc4716)

**Hardware**
UGREEN DX4600Pro 

- CPU:N6005 
- RAM: 16GB
- SATA 4

**Comment by AuxXxilium** [comment]
Yes, emmc is not stable so disabled.

**Comment by h0we** [comment]
> Yes, emmc is not stable so disabled.

Will it be supported in a future version?
