### ISSUE TITLE
Intel DG41AN (Aneroid Lake) motherboard chipset support

### ISSUE THREAD

**Issue by alexey-gamov** [AuxXxilium/arc#820]
**Is your Feature request related to a Problem? Please describe.**

Trying to install DSM with Arc Loader using Intel DG41AN motherboard.
This board has two chips [Intel 82G41 (GMCH)](https://theretroweb.com/expansion-chips/255) and [Intel 82801GB (ICH7)](https://theretroweb.com/expansion-chips/289).
Second one is supported - so USB devices are listed, but GMCH is not = no SATA drives presented.

**Additional Context**

Time ago DSM 6.1 (DS3615) was used with another loader (Yuan i guess). so no troubles were faced.
Is there any opportunity to add such module?

**Comment by AuxXxilium** [comment]
on this old hardware, go back and use your old loader. makes more trouble with the later models.
