### ISSUE TITLE
MacOS/U.S. Keyboard Y and Z keys are reversed in loader configuration

### ISSUE THREAD

**Issue by ichasecorals** [AuxXxilium/arc#823]
**Describe the Bug**
When I try to recover a backup with code, the Z character is typed as Y and Y is typed as Z. Other non alphabet characters have the same issue.

**Screenshots**
N/A

**Hardware**
N/A

**Comment by ichasecorals** [comment]
Are you kidding me? Why would I need to map keys just to type one letter?

**Comment by AuxXxilium** [comment]
keymap is default on qwertz - you can set it to every keyboard layout in keymap menu. don't know whats your problem.
