### ISSUE TITLE
Stuck in resintall state after loader update to next version

### ISSUE THREAD

**Issue by dusi12** [AuxXxilium/arc#824]
**Describe the Bug**

Created a new USB with loader version 24.2.1-next (I don't remember the previous one, but pre-next version for sure), built the loader from scratch, after the boot control panel was not working, SAN Manager & VMM said they needed to be repaired but they couldn't be repaired. I saw the force reinstall tip, but when I tried to do it it failed with corrputed image message, and now it says there is not enough space. What can I do to get back my DSM without losing the settings & data? VM would be especially important, my Home Assistant is installed there.
Thanks in advance!

**Screenshots**

<a href="https://ibb.co/gmPcVpQ"><img src="https://i.ibb.co/gmPcVpQ/K-perny-k-pek-2024-02-02-20-48-17.png" alt="K-perny-k-pek-2024-02-02-20-48-17" border="0"></a> <a href="https://ibb.co/5sS3BL5"><img src="https://i.ibb.co/5sS3BL5/Synology-Web-Assistant-Google-Chrome-2024-02-02-20-32-02.png" alt="Synology-Web-Assistant-Google-Chrome-2024-02-02-20-32-02" border="0"></a>

Sysinfo code: BWWGW2H8H

**Hardware**

You can see it in the Full sysinfo.

**Comment by AuxXxilium** [comment]
first: why do you select addons that you don't need? 

Boot to Config Mode -> Reset Loader -> Rebuild only with Addons you know you need!

**Comment by AuxXxilium** [comment]
looks like your system was an upgrade from DSM 6 -> 7 in the past, DSM 6 used a different partition layout and this error will occour after some time. -> is written in wiki, too.

**Comment by dusi12** [comment]
Thanks for your reply.
Tried with only acpid, cpuinfo, facepatch and multismb, same result.
My only option is to format and lose everything?

**Comment by AuxXxilium** [comment]
If you will loose your data, there will be a warning!

**Comment by dusi12** [comment]
Hi
As a follow up for anyone who may have the same issue I managed to fix my DSM without losing any data or settings.
Booted into a live Linux, deleted the autoupdate and update folders, and the logs from var folder from the 1st partition, that gave enough space to successfully reinstall the DSM.
The only way to expand the system partition is to install DSM 7 on a clean drive and manually restore my settings & data?

**Comment by AuxXxilium** [comment]
`If you switch from a non -next Release to a -next Release, you need to do a DSM force Reinstall.`

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Usage-&-Update

You can: boot into config mode -> dev section -> format disks -> select partition 1 and 2 of every disk that has more than 2 partitions -> reboot or boot dsm

**Comment by dusi12** [comment]
This will resize the partition(s)?
If I format these partitions my settings will remain?
Sorry for being a pain in the @ss but I've never done this.

**Comment by AuxXxilium** [comment]
your settings are gone. this is why i wrote it to wiki.
