### ISSUE TITLE
Control panel not opening after fresh loader install 24.2.1-next

### ISSUE THREAD

**Issue by zsdd89** [AuxXxilium/arc#825]
Hi
After updating to version 24.2.1(fresh install) Control panel cannot be opened as shown in the screenshot. Tried with 3 PCs, multiple browsers. This arc version greatly f###ed up something as after trying with latest perfectly working rr loader from last year the problem is still there... 
DSM 7.2.1 upd4, DS3622xs, Fujitsu Primergy TX1310 tower server, Xeon E3-1276v3
<img width="449" alt="Screenshot 2024-02-02 212533" src="https://github.com/AuxXxilium/arc/assets/59314976/0df1cdc7-73b5-4bf9-b1fb-a34be93ca34a">

**Comment by AuxXxilium** [comment]
if you can't read, i can't help.

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Usage-&-Update

**Comment by zsdd89** [comment]
If i cannot open the control panel how could i reboot to arc loader???

**Comment by AuxXxilium** [comment]
select reboot in upper richt corner of dsm and select DSM force Reinstall in Bootloader

**Comment by zsdd89** [comment]
How could i select force reinstall in bootloader when the reboot option only reboots the dsm?

**Comment by AuxXxilium** [comment]
select the correct option in first boot screen!
