### ISSUE TITLE
Please add the DS1821+

### ISSUE THREAD

**Issue by menfis911** [AuxXxilium/arc#83]
My friend!
Thank you for your work!
Please add the DS1821+

**Comment by AuxXxilium** [comment]
And why should i add more AMD Builds with DT?

**Comment by menfis911** [comment]
in 1821 dsm, up to 8 HDDs can be supplied according to the standard, which makes it more interesting than 1621, provided that I have a valid pair

**Comment by AuxXxilium** [comment]
Why do you not use DS3622 or RS4021 for more Disks?

**Comment by menfis911** [comment]
Because I have a DS1821+ valid pair of serial number and MAC
Please help me, I didn't figure out how to add new dsm myself, thank you!

**Comment by AuxXxilium** [comment]
And again, you know what arc patch is? you don't need an own valid pair if you use it, so you can use DS3622/RS4021.

**Comment by menfis911** [comment]
I read about this patch on your wiki, but to be honest, I didn't really understand what it does and how it works, could you tell me more in this case?

And why don't you want to add another DS, is it difficult or..?

**Comment by AuxXxilium** [comment]
actualy i have not the time for research to add this ds.

and i wrote everything i can write official in wiki.

**Comment by menfis911** [comment]
I understand you, thank you
