### ISSUE TITLE
DS1520+ wrong bays number shown when configure the loader.

### ISSUE THREAD

**Issue by jacqlittle** [AuxXxilium/arc#830]
DS1520+ shows that it has 6 bays when ARC Loader is configured, but in reality this NAS model has only 5 bays. It is not a major error, but if you can correct it it would be perfect.

This bug occurs with any hardware, both with virtual and baremetal machines.

Thanks in advance!

**Comment by AuxXxilium** [comment]
![image](https://github.com/AuxXxilium/arc/assets/67025065/f22a2a63-6b29-418b-89dd-973670aa402a)

it's set to 6 bay. so no issue from arc.
