### ISSUE TITLE
Issue with i915

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#834]
**Describe the Bug**
Hello brother, i hope you're doing well i want to know can i run IGPU inside DSM, or any wany to vm it for my Virtual machine manager for VMS? cause it causing too laggy as i check for i915 in wiki you mentioned IGPU class should be [0300] i'm using i5 2500 2nd gen Intel core processor, really appreciate your time and efforts. any thank you again for this great project proud to be able to use this..

**Screenshots**
![Screenshot (21)](https://github.com/AuxXxilium/arc/assets/101920742/68b2ee3f-60f3-4602-841c-d13760cbf4d5)

**Hardware**
Add your Hardware Informations here. I5 2500 / DQ67SW / E1000/E1000e/TG3 /24GB RAM

**Additional information**

00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:16.2 IDE interface: Intel Corporation 6 Series/C200 Series Chipset Family IDE-r Controller (rev 04)
00:16.3 Serial controller: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller (rev 04)
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b4)
00:1c.6 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 (rev b4)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev a4)
00:1f.0 ISA bridge: Intel Corporation Q67 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 04)
01:00.0 SCSI storage controller: Broadcom / LSI SAS1068E PCI-Express Fusion-MPT SAS (rev 08)
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
03:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express
04:00.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 04)
05:00.0 Ethernet controller: Intel Corporation 82541PI Gigabit Ethernet Controller (rev 05)
root@arc:/opt/arc# lspci -nnk
00:00.0 Host bridge [0600]: Intel Corporation 2nd Generation Core Processor Family DRAM Controller [8086:0100] (rev 09)
        Subsystem: Intel Corporation 2nd Generation Core Processor Family DRAM Controller [8086:2008]
        Kernel driver in use: snb_uncore
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:0101] (rev 09)
        Subsystem: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:2008]
        Kernel driver in use: pcieport
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0102] (rev 09)
        DeviceName:  Intel(R) HD Graphics Device
        Subsystem: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:2008]
00:16.0 Communication controller [0780]: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 [8086:1c3a] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller [8086:2008]
00:16.2 IDE interface [0101]: Intel Corporation 6 Series/C200 Series Chipset Family IDE-r Controller [8086:1c3c] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family IDE-r Controller [8086:2008]
00:16.3 Serial controller [0700]: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller [8086:1c3d] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller [8086:2008]
        Kernel driver in use: serial
00:19.0 Ethernet controller [0200]: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) [8086:1502] (rev 04)
        DeviceName:  Intel(R) 82579LM Gigabit Ethernet Device
        Subsystem: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) [8086:2008]
        Kernel driver in use: e1000e
        Kernel modules: e1000e
00:1a.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 [8086:1c2d] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller [8086:2008]
        Kernel driver in use: ehci-pci
00:1c.0 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:1c10] (rev b4)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:2008]
        Kernel driver in use: pcieport
00:1c.4 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:1c18] (rev b4)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:2008]
        Kernel driver in use: pcieport
00:1c.6 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [8086:1c1c] (rev b4)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [8086:2008]
        Kernel driver in use: pcieport
00:1d.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 [8086:1c26] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller [8086:2008]
        Kernel driver in use: ehci-pci
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev a4)
        Subsystem: Intel Corporation 82801 PCI Bridge [8086:2008]
00:1f.0 ISA bridge [0601]: Intel Corporation Q67 Express Chipset LPC Controller [8086:1c4e] (rev 04)
        Subsystem: Intel Corporation Q67 Express Chipset LPC Controller [8086:2008]
00:1f.2 SATA controller [0106]: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller [8086:1c02] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller [8086:2008]
        Kernel driver in use: ahci
00:1f.3 SMBus [0c05]: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller [8086:1c22] (rev 04)
        Subsystem: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller [8086:2008]
        Kernel driver in use: i801_smbus
01:00.0 SCSI storage controller [0100]: Broadcom / LSI SAS1068E PCI-Express Fusion-MPT SAS [1000:0058] (rev 08)
        Subsystem: Dell SAS 6/iR Adapter RAID Controller [1028:1f0e]
        Kernel driver in use: mptsas
        Kernel modules: mptsas
02:00.0 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express [14e4:165a]
        Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express [14e4:165a]
        Kernel driver in use: tg3
        Kernel modules: tg3
03:00.0 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express [14e4:165a]
        Subsystem: Broadcom Inc. and subsidiaries NetXtreme BCM5722 Gigabit Ethernet PCI Express [14e4:165a]
        Kernel driver in use: tg3
        Kernel modules: tg3
04:00.0 USB controller [0c03]: NEC Corporation uPD720200 USB 3.0 Host Controller [1033:0194] (rev 04)
        Subsystem: Intel Corporation uPD720200 USB 3.0 Host Controller [8086:2008]
        Kernel driver in use: xhci_hcd
05:00.0 Ethernet controller [0200]: Intel Corporation 82541PI Gigabit Ethernet Controller [8086:107c] (rev 05)
        Subsystem: Intel Corporation PRO/1000 GT Desktop Adapter [8086:1376]
        Kernel driver in use: e1000
        Kernel modules: e1000

**Comment by AuxXxilium** [comment]
read wiki and find your issue.

**Comment by Edwardpge** [comment]
> read wiki and find your issue.

Brother Can't find the solution really appreciate your help.. I just want to know does (Intel i5 2500 IGPU (Intel HD 3000)) supported by ARC and DSM?

**Comment by AuxXxilium** [comment]
yes it is!

https://github.com/AuxXxilium/AuxXxilium/wiki/Arc:-Choose-a-Model
