### ISSUE TITLE
No NIC found !d

### ISSUE THREAD

**Issue by iKoow** [AuxXxilium/arc#838]
Hello, I am trying to install DSM with arc on a virtual machine in vmware workstation but the loader does not see my network card. I dont have problem with other installs, do you have an idea? ty

![image](https://github.com/AuxXxilium/arc/assets/127955474/2bfe5dd1-5d66-4b3f-8537-2303e6d4ba89)

**Comment by AuxXxilium** [comment]
1. old image
2. wrong configuration

**Comment by iKoow** [comment]
hello, thanks for you fast reply. I am a beginner
To begin with, it's not an old image but a screen from this morning, can you comment on what's wrong with the configuration?

**Comment by iKoow** [comment]
Indeed I agree that there is a network configuration problem but I haven't found how to make it work
