### ISSUE TITLE
i915

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#843]
**Describe the Bug**
Hello Brother, Hope you're doing well i have issue with i915 which i cant find in any way

**Screenshots**
![Screenshot 2024-02-13 210746](https://github.com/AuxXxilium/arc/assets/101920742/fb6f30fe-0f11-4fb8-8c12-49e4f12aadac)
![Screenshot 2024-02-13 210647](https://github.com/AuxXxilium/arc/assets/101920742/cec05d92-2007-42a0-b83f-61d7ccd4dcf1)
![Screenshot 2024-02-13 210720](https://github.com/AuxXxilium/arc/assets/101920742/22d81272-f545-49e5-a843-f74fdd282021)

**Hardware**
i5 2500 / DQ67SW

**Comment by AuxXxilium** [comment]
read wiki!
