### ISSUE TITLE
ASRock N100DC-ITX (Intel N100 CPU) dsm not booting

### ISSUE THREAD

**Issue by gburas** [AuxXxilium/arc#851]
**Describe the Bug**
System DSM is not booting, i think that computer freezing after bootloader is loaded. 
I have tried both "arc" and "arc-a" projects in the latest versions. I have tried many syno models but the behavior is the same every time. After correctly configuring the bootloader and building it, the bootloader loads and after displaying the IP address to DSM, after a while displaying cmd line, the system hangs. It does not respond to the keyboard, it does not respond to ping at the indicated IP address (with or without a port). While loading the bootloader, it responds to pings. I have been waiting for a long time, even half an hour, but still nothing, the indicated address is not loading. Bought and tried new usb 3.0 drive. Tried many options in BIOS, finally disabled everything and still nothing.

**Screenshots**
Full Sysinfo - Upload code: 3SNY75J2U

![PXL_20240212_232549340 MP](https://github.com/AuxXxilium/arc/assets/68383101/20ffc3b0-9a5c-45b0-9318-90b5f3e7af20)
On screenshoot is version .10 but also tried .13 - result the same

**Hardware**
- motherboard: ASRock N100DC-ITX (built-in CPU Intel N100)
- RAM:  Lexar DDR4, 32 GB, 3200MHz, CL22
- NVMe: SSD Lexar NM620 256GB M.2 2280 PCI-E x4 Gen3
- 2 x 3,5inch SATA HDD 2TB
- Realtek 8111H Gigabit LAN 10/100/1000 Mb/s
- 90 watt psu

**Comment by tuanpmanh** [comment]
I have same problem on all version in my J1900, this is output of ` lspci -nnk`
![Screenshot_1](https://github.com/AuxXxilium/arc/assets/47804965/83cf8edd-155b-4921-85b3-d926e98f776a)
The network card seems to only work with the bootloader and will not work when booting into DSM

**Comment by gburas** [comment]
Problem solved it turns out that they sell motherboard with some kind of production version of BIOS. When i was searching solution,  previously check if there is maybe newer version of BIOS i saw that there is only "First released." so i didn`t follow that patch. But today i realize that i have even older version then on their webpage, i had 1.05 and they say that 1.06 is their first released. So after updating BIOS, one hour fight to disable secure boot i tried again, and it worked. So thanks anyway for Your hard work.

**Comment by qwer64** [comment]
It worked! )) thank you. I reset the bios several times. And immediately changed the settings - disabled secure boot, com & lpt ports. And now, just on the default settings, the dsm has started. Which model did you choose? SA6400 ?

**Comment by gburas** [comment]
Yes
