### ISSUE TITLE
Face recognition

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#854]
**Describe the Bug**
Hello berother, I have issue with face recognition i have tried all methods reinstall DSM, reflash ARC, i have enable face reco patch and all other can't able to solve the issue really need your help for this i'm using lastest release. As the picture is old one with the same build

**Screenshots**
![Screenshot 2024-02-13 210746](https://github.com/AuxXxilium/arc/assets/101920742/10c3ead3-d9fb-4995-83c6-9a7d8797f0f7)

**Hardware**
Add your Hardware Informations here. i5 2500 / DQ67SW / Networkcontroller / Storagecontroller / ...

**Comment by MartinKuhl** [comment]
The developer of the facepatch added in the latest version some additional patches. With that addition face recognition is working for me look here: https://github.com/jinlife/Synology_Photos_Face_Patch/blob/main/bin/patch.sh

**Comment by Edwardpge** [comment]
> The developer of the facepatch added in the latest version some additional patches. With that addition face recognition is working for me look here: https://github.com/jinlife/Synology_Photos_Face_Patch/blob/main/bin/patch.sh
> 
> Here the commit to see the recent changes: [jinlife/Synology_Photos_Face_Patch@79f0ec5](https://github.com/jinlife/Synology_Photos_Face_Patch/commit/79f0ec51fc7b47248801324555ed27ae607aacdf)
> 
> Maybe this could be added to the facepatch in ARC as well.

Thanks for reaching out, yes i believe this one is added in ARC, even i tried your referral link seems to me it's still not working!

**Comment by MartinKuhl** [comment]
I had active the personal account space and nee to wait some minutes. After something happens.
You could also check the logs here: cat /var/packages/SynologyPhotos/var/log/synofoto.log

**Comment by MartinKuhl** [comment]
Today I tried the the arc-native facepatch (arc version arc-24.2.24) but it was not working and no face were identified, even after several reboots and hours of waiting. Just a couple of minutes and a reboot after I used the original patch (https://github.com/jinlife/Synology_Photos_Face_Patch/blob/main/bin/patch.sh) face recognition is working as expected. As conclusion I think that is somewhere a bug in the ARC facepatch.

**Comment by AuxXxilium** [comment]
it's the same file and working in my test systems.

**Comment by MartinKuhl** [comment]
yesterday and today I tried to get face-detection via the ARC module working. 

In the log (/var/packages/SynologyPhotos/var/log/synofoto.log) I see several times the following error message.

`synofoto-task-center[16229]: /source/synofoto/src/lib/io/channel.cpp:81 channel[/run/synofoto/face-extraction.socket] construct failed: connect: Connection refused [system:111 at /usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/boost/asio/detail/reactive_socket_service.hpp:587:5 in function 'boost::system::error_code boost::asio::detail::reactive_socket_service<Protocol>::connect(implementation_type&, const endpoint_type&, boost::system::error_code&)']`

As a result, no face were detected.
I rebooted my NAS several times and checked that the facepatch-module is activated.

If I apply the patch manually I receive the following message:
`/usr/lib/libsynosdk.so.7 was already patched!!!
/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so patched successfully at 0x59d0 with 6 bytes!!!
/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so patched successfully at 0x54e0 with 6 bytes!!!
/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so patched successfully at 0x5960 with 6 bytes!!!`

After a restart of the Photo-App, a migration process ist starting and after a couple of minutes the first faces were detected.

**Comment by MartinKuhl** [comment]
do you need the complete synofoto.log? DSM and Loader were fresh installed and after manual applying the path it was working within couple of minutes.

**Comment by AuxXxilium** [comment]
no i need serial log from dsm.

**Comment by MartinKuhl** [comment]
could you help me and tell me where I can find it?

**Comment by MartinKuhl** [comment]
do you mean the output of dmesg?

**Comment by AuxXxilium** [comment]
no i mean serial log. not dmesg or something else. you can't find it.

**Comment by AuxXxilium** [comment]
but if you will join discord you will find all informations like this:

### First of all, i can't help without Screenshot or Code from Arc - Sysinfo (System need to be configured)

---

To Debug, if you have some Issues while Loading or in DSM:

1. Configure your System like every time
2. Add addon "dbgutils"
3. Build Loader
4. Boot Loader
5. Wait about 5 Minutes
6. Force reboot to Arc
7. Go to Arc - Dev Section - Grep Logs
8. Your logs will be copied to /tmp/logs.tar.gz
9. Connect thru SFTP client (User: root / Password: arc)
10. Navigate to /tmp and download the log.tar.gz
11. Upload log.tar.gz here

**Comment by MartinKuhl** [comment]
Hi @AuxXxilium here are the sysInfos: code CRDPC5334
Now I joined the Discard as well. 
I installed dbgutils, build and boot the loader. Booted DSM and tried than to extract the Logs, but to archive logs.tar.gz was not saved under /tmp. Any ideas on that?
<img width="479" alt="image" src="https://github.com/AuxXxilium/arc/assets/55736453/09f88794-4c7a-4b26-9fad-50c281e7d72b">

**Comment by MartinKuhl** [comment]
> it's the same file and working in my test systems.

@AuxXxilium 
can you tell the order of steps you do to install DSM, the facepatch and the photo-app to get it working?

I do the following what ha to be wrong, cause no faces where recognized:
1. create loader with face-patch.
2. install DSM
3. configure disc-pools
4. install DSM photo-app
5. restart
6. open photo-app, activate person recognition (Personbereich)
7. upload a photo
8. switch into person-folder to check when the recognition is ready
9. check the uploaded photo and see no recognized faces

**Comment by AuxXxilium** [comment]
no i can't because it is working oob for me.

**Comment by MartinKuhl** [comment]
> no i can't because it is working oob for me.

I have a valid mac & sn combination. QC & AME is working for me without ARC or any other addons but face recognition will not work for me on 3622xs+

**Comment by MartinKuhl** [comment]
Hi @AuxXxilium,

the bug with the face recognition was also present in RR. 
wjz304 was able to fix it in the latest rr version 24.5.6. in the following issue he mention some key facts.
https://github.com/RROrg/rr/issues/1043 

Could look into the topic again and fix the addon also for ARC?

**Comment by AuxXxilium** [comment]
> Hi @AuxXxilium,
> 
> the bug with the face recognition was also present in RR. wjz304 was able to fix it in the latest rr version 24.5.6. in the following issue he mention some key facts. [RROrg/rr#1043](https://github.com/RROrg/rr/issues/1043)
> 
> Could look into the topic again and fix the addon also for ARC?

i know and fix is included in next build, i'm testing it since 4 days

**Comment by MartinKuhl** [comment]
> > Hi @AuxXxilium,
> > the bug with the face recognition was also present in RR. wjz304 was able to fix it in the latest rr version 24.5.6. in the following issue he mention some key facts. [RROrg/rr#1043](https://github.com/RROrg/rr/issues/1043)
> > Could look into the topic again and fix the addon also for ARC?
> 
> i know and fix is included in next build, i'm testing it since 4 days

thanks a lot!
