### ISSUE TITLE
Addon i915 v.24.2.13 i9900K + ESXi + VM DS920+ It doesn't work again

### ISSUE THREAD

**Issue by dj-nsk** [AuxXxilium/arc#855]
Hi, Christian!
Sorry, but it's not working again - if I add an addon to the configuration, then after downloading the DSM, the i915.ko file remains unchanged. I tried to replace only addons on versions 24.2.12, 24.2.10 - everything is the same.
![2024-02-17_10-15-07](https://github.com/AuxXxilium/arc/assets/137425798/5f1a195c-f6eb-4a05-b5de-e85994e8ec12)
 
Sysinfo Code: C4MSV2FAY

As before, the only solution that helps is: disable the addon in the Arc Loader and put the patched i915.ko manually

**Comment by dj-nsk** [comment]
dj_nsk@dj_NAS:~$ lspci -n | grep 0300
0000:00:0f.0 0300: 15ad:0405
0000:03:00.0 0300: 8086:3e98

**Comment by AuxXxilium** [comment]
i need "dmesg" output from ssh in dsm.

**Comment by AuxXxilium** [comment]
enabled and no option

**Comment by dj-nsk** [comment]
[dmesg.txt](https://github.com/AuxXxilium/arc/files/14318943/dmesg.txt)

**Comment by AuxXxilium** [comment]
need full serial log from esxi after booting dsm.

**Comment by dj-nsk** [comment]
and how can I get it?

**Comment by AuxXxilium** [comment]
add serial console to your vm?

**Comment by dj-nsk** [comment]
Wow! Is it enough just to add a virtual COM 1 with output to a file? I'll do it now...

**Comment by dj-nsk** [comment]
[serial .txt](https://github.com/AuxXxilium/arc/files/14319085/serial.txt)

**Comment by dj-nsk** [comment]
"Installing addon i915 - patches
GPU:80863e98 GPU_BIN:86800000983e0000
'/usr/lib/modules/i915.ko' ->[   17.351354] raid6: avx2x2   gen() 40957 MB/s
 '/usr/lib/modules/i915.ko.bak'"

Now I have /usr/lib/modules/i915.ko - not patched (2096kb) and
/usr/lib/modules/i915.ko.bak - my patched file (2095kb) :)

**Comment by AuxXxilium** [comment]
this is not causing the issue, the file is still patched, look at date/time in "ls /usr/lib/modules"

**Comment by dj-nsk** [comment]
"i915.ko"  - Yes, the fresh date/time on this file, but it completely identical to the original file content:
fc i915.ko i915.DS920.69057.ko ---> no differences found

**Comment by dj-nsk** [comment]
(i915.DS920.69057.ko - I saved the original file for testing/experimentation)

**Comment by dj-nsk** [comment]
I understand! You need to return it the way it was before: first use xxd, then sed, and again xxd - because for sed you specify hexadecimal codes :)

**Comment by AuxXxilium** [comment]
my problem is, at my local system the file is patched and working with 8700k. should be the same for 9900k.

**Comment by dj-nsk** [comment]
I did it manually - everything worked fine:
root@dj_NAS:~# xxd -p /usr/lib/modules/i915.ko | wc -c
4362548
root@dj_NAS:~# xxd -c 4362548 -p /usr/lib/modules/i915.ko /usr/lib/modules/i915.ko.hex
root@dj_NAS:~# sed -i "s/86800000923e0000/86800000983e0000/; s/308201f706092a86.*70656e6465647e0a//" "/usr/lib/modules/i915.ko.hex"
root@dj_NAS:~# xxd -r -p /usr/lib/modules/i915.ko.hex >/usr/lib/modules/i915.ko

**Comment by dj-nsk** [comment]
now i915.ko is patched!

**Comment by AuxXxilium** [comment]
yes and on my systems it is working without xxd.

**Comment by dj-nsk** [comment]
it is possible that some of the additional packages (SynoCli... Tools)?

**Comment by AuxXxilium** [comment]
no i use clean systems for testing

**Comment by AuxXxilium** [comment]
try latest addons, i reworked some keyfunctions

**Comment by dj-nsk** [comment]
Checked - error in code. See output:
"'
/addons/i915.sh' -> '/tmpRoot/usr/arc/addons/i915.sh'
/addons/i915.sh: line 11:  -f 3 | sed -e 's/://g'): not found
/addons/i915.sh: line 13:  -f 3 | sed -e 's/://g'): not found
"
A few characters at the beginning of the lines are lost. Today:
    GPU="lspci -n | grep 0300 | grep 8086 | cut -d " " -f 3 | sed -e 's/://g')"
...
      GPU="lspci -n | grep 0380 | grep 8086 | cut -d " " -f 3 | sed -e 's/://g')"

It was before:
    GPU="$(lspci -n | grep 0300 | grep 8086 | cut -d " " -f 3 | sed 's/://g')"
...
      GPU="$(lspci -n | grep 0380 | grep 8086 | cut -d " " -f 3 | sed 's/://g')"
