### ISSUE TITLE
Virtual Machine Manager : windows 10

### ISSUE THREAD

**Issue by regi479** [AuxXxilium/arc#863]
On different computers, ARC works fine. but I can't install windows 10. during installation, at 1% the setup program comes out with an error. On different PCs, same result.

thanks for collaboration.

**Comment by regi479** [comment]
msi B85M-P33 V2 
CPU pentium G3240 @ 3,10GHz

**Comment by regi479** [comment]
![image](https://github.com/AuxXxilium/arc/assets/160513521/194e7075-c48a-4978-9f7b-fcebe001f636)

**Comment by regi479** [comment]
![image](https://github.com/AuxXxilium/arc/assets/160513521/168733fd-9cd6-47fb-9ac7-5b9d4caeb91b)

**Comment by AuxXxilium** [comment]
> **Describe the Bug** A clear and concise description of what the bug is.
> 
> **Screenshots** Screenshot the Systeminfo (Arc - Sysinfo) or use new "Full Sysinfo - Upload" Function provide the Code!!! <- IMPORTANT
> 
> **Hardware** Add your Hardware Informations here. CPU / Board / Networkcontroller / Storagecontroller / ...



> same thing with this mainboard, I highlight that this MB with DSM 6.2 work great with VMM windows 10
> 
> <img alt="Screenshot 2024-02-19 alle 17 41 37" width="690" src="https://private-user-images.githubusercontent.com/160513521/306026005-8b5a69c7-591f-4de6-b680-c7a0db6f68b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjI2NzYsIm5iZiI6MTcwODM2MjM3NiwicGF0aCI6Ii8xNjA1MTM1MjEvMzA2MDI2MDA1LThiNWE2OWM3LTU5MWYtNGRlNi1iNjgwLWM3YTBkYjZmNjhiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNzA2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjE1NWI0NDQyOWI4NDIyODQ0NmQ2NGY5NDEwYzRkMzYwMmNiYWIyZDg2Mjc1YzA5NDY4MjY3M2E5Y2I0NjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bH91rou0FKcqVzbKPU62DtzZSIEfBbZBATlfR7vddIY">

**Comment by regi479** [comment]
the problem is certainly with my hardware. thanks for support. Greetings.
