### ISSUE TITLE
V23.02.24.2 Cannot install DSM

### ISSUE THREAD

**Issue by RJSUTH** [AuxXxilium/arc#87]
Hello,
This version looks good, it boots on my Thecus N7770-10G but cannot install BS.

![image](https://user-images.githubusercontent.com/122780513/221346241-c7bcf63a-ff11-4ba6-a4e6-c393ef222f51.png)

in serial conolse i got this message:

BusyBox v1.30.1 () built-in shell (ash)

SynologyNAS> [  100.635666] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
[  100.679699] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
[  107.027578] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
[  107.057838] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
[  132.136741] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
[  132.183432] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
SynologyNAS> [  100.635666] EXT4-fs (md0): couldn't mount as ext3 d
ue to feature incompatibilities
-ash: syntax error: unexpected "("
SynologyNAS> [  100.679699] EXT4-fs (md0): mounted filesystem with ordered data
mode. Opts: (null)
-ash: syntax error: unexpected "("
SynologyNAS> [  107.027578] EXT4-fs (md0): couldn't mount as ext3 due to feature
 incompatibilities
-ash: syntax error: unexpected "("
SynologyNAS> [  107.057838] EXT4-fs (md0): mounted filesystem with ordered data

Can you fix this?

**Comment by AuxXxilium** [comment]
Can you send me a screenshot from Arc - Sysinfo (is an option in loader).

**Comment by RJSUTH** [comment]
![image](https://user-images.githubusercontent.com/122780513/221352302-f4a4a001-9289-4b8a-b984-f27094855d5f.png)

**Comment by AuxXxilium** [comment]
Thanks, i found the issue. You can use the v23.02.24 (not .2) or wait for new release.
