### ISSUE TITLE
Driver integration request for LED/fan controller for HP Mediasmart server

### ISSUE THREAD

**Issue by mlebailly** [AuxXxilium/arc#874]
### Current configuration for HP MediaSmart X510/EX495
The [old HP MediaSmart X510](https://www.smallnetbuilder.com/nas/nas-reviews/hp-storageworks-data-vault-x510-reviewed/) home server was first designed by HP to run under WHS v1 but I updated it to the Windows Home Server 2011 (Windows 7 kernel based).
As the support of Windows 7 ended, I have no more security updates from Microsoft, so I intend to move to the XPenology (I have also a synology NAS DS1515+). I configured the loader as it mentioned on your wiki and setup the DS1621xs+ model (I have only 4 bays in the HP MediaSmart) with the following configuration :

- CPU : Intel E5200 dual core Pentium CPU.
- RAM : 4GB DDR2-800 DIMM
- iGPU : Intel G33 Northbridge, Intel 82081 Southbridge, 256 MB of flash
- Realtek RTL8111 for Gigabit Ethernet.
- Port multiplier or second sata controller for eSATA port : Silicon Image Si 3531 SATA controller. **Is this port multiplier is compatible with your low-level driver for Silicon Image SATA controller (sata_sil driver) which is loaded in modules ?**

I applied the ARC patch, disable some modules that Is not useful to me in the option and set up the addon on the top before building the loader. Currently it’s working but I am still testing the setup, so if something goes wrong I can rebuild everything and setup DSM 7.2 again on top of the loader without any issues.

### New development request
The HP has a dedicated LED controller ([SMSC SCH5127-NW chip](https://www.microchip.com/en-us/product/sch5127)) with a specific driver under Windows has been developed. Fortunately, this driver has been [reverse engineering here](https://github.com/merelin/mediasmartserverd) for Ubuntu distribution and with entire source code available in C.

Do you think it would be possible to integrate this driver as new module to be used as a script by DSM ? Would it be possible to compile the driver for tinycore distribution ? This chip is also controlling the fan-speed which are currently not controllable at all by DSM and locked by a fix fan speed by the BIOS setup.

**Comment by AuxXxilium** [comment]
No and no.

LED Controll will not be added, because there are to many different chips on market. And if we add 1, others come and want another one, so we have in the end 30-40 modules. Modules for DSM are the working with all loader.

Fan Speed in DSM will not be possible, because of syno uses his own bios and there is nothing open source, so noone can reverse engineer the implamentation.

**Comment by mlebailly** [comment]
Thank you for your quick reply and all the work done! I understand your point and all your arguments about this specific controller. 

On my question related to the SATA controller, do you know if the already included sata driver can managed this SI-3135 reference ?

**Comment by AuxXxilium** [comment]
it's no sata module, it's a stock linux ahci module.
