### ISSUE TITLE
hp ams / ilo driver add on for hp server

### ISSUE THREAD

**Issue by vejta66** [AuxXxilium/arc#876]
Hi and thank you for your great work.
i was wondering if is it possible to add to this fantastic loader  a module/addon that allow to install  HPE Agentless Management (amsHelper and hpilo.ko) for those like me that have an hp server (like the gen8 line and ilo4).
best regards

**Comment by AuxXxilium** [comment]
will not work inside dsm

**Comment by vejta66** [comment]
Thank you for your fast answer
