### ISSUE TITLE
Hyper-V NIC drivers?

### ISSUE THREAD

**Issue by stevefan1999-personal** [AuxXxilium/arc#878]
**Is your Feature request related to a Problem? Please describe.**
I can use qemu-img to convert the VMDK to an VHDX and then run Arc on Hyper-V. The reason I have to use Generation 1 is that the loader disk can't be found on the SCSI controller, and so IDE has to be used, hence Generation 1. However, I can't get the NIC address even with Legacy Network Adapter, which means we are so close to getting it work. However, it is not certain if Synology kernel in the next stage would recognize the Hyper-V hard disk and NIC or not.

**Comment by AuxXxilium** [comment]
no way. because of some ms locked things in hyper-v.

**Comment by stevefan1999-personal** [comment]
The kernel packed in did not have the open source Hyper-V Linux module?

**Comment by AuxXxilium** [comment]
it has modules for hyper-v included. but hyper-v is blocking the boot execution.
