### ISSUE TITLE
Arc on AMD (HP MICROSERVER GEN10)

### ISSUE THREAD

**Issue by masyanich** [AuxXxilium/arc#879]
**Describe the Bug**
Hangs up after "loadind DSM", trying any syno models, legacy/uefi, 7.2/7.1
cant get ip from router

![U4TMvS_n03I](https://github.com/AuxXxilium/arc/assets/66204426/30f4e0e9-94a1-4788-a4fd-0ecfdc45ae8d)

**Screenshots**
uploaded as code 
DJWUBWJRQ

**Hardware**
HP MICROSERVER GEN10 v1, 
AMD Opteron™ X3216 Processor
Embedded Broadcom BCM5720 Dual Port Gbe LOM

what types of logs do I need to provide?
Thank you!

**Comment by AuxXxilium** [comment]
check wiki for bios settings. tg3 is working and should be the same ip as you got shown while boot.

so something else in bios is causing this.

**Comment by AuxXxilium** [comment]
it's also possible that dva won't load at this amd cpu. try ds3622xs+ or sa6400. they should be compatible to your system.

**Comment by masyanich** [comment]
wow! sa6400 fires up!
thank you!
