### ISSUE TITLE
Multiple loader disk found

### ISSUE THREAD

**Issue by blackbrayn** [AuxXxilium/arc#883]
Hello, after installing dsm with no problems, at first reboot i am greeted with "multiple loader disks found" , i tried both a usb and a s-ata loader disk.
Can't seem to find the root cause, and no references on various sources online.
The install is on bare-metal, j1900 motherboard + a pci to s-ata 4 drive cheap controller.DSM was installed on one single drive.

Thx.

**Comment by AuxXxilium** [comment]
reflash usb stick
