### ISSUE TITLE
VMMs ERROR

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#884]
**Describe the Bug**
I have issue with Synology VMM can't able to run VMs tried all setting as you mention in Wiki disable the VT-d and tried all other things
(VMs does start but can't load in ISO file like windows Installer tried different files too but no luck)
**Screenshots**
![Screenshot 2024-02-29 111751](https://github.com/AuxXxilium/arc/assets/101920742/01ca2848-d7c8-4635-996f-71cae23a8b8a)IMPORTANT

**Hardware**
Hardware Information here. 4570 / ASUS B85M-E/DASH

**Comment by AuxXxilium** [comment]
Does your CPU support VMX and is this enabled? If yes it will work.

**Comment by Edwardpge** [comment]
I guess NOT, it does support VT-x

**Comment by Edwardpge** [comment]
> Does your CPU support VMX and is this enabled? If yes it will work.

I guess NOT, it does support VT-x

**Comment by Edwardpge** [comment]
these are the supported flags:

flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl **vmx** smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt dtherm ida arat pln pts

**Comment by Edwardpge** [comment]
I have encountered an other thing recently i tried to change bios to LEGACY in VMM now i'm able to install the Windows 10 and it works, but when i turn it into UEFI i goes back to shell after 5 to 6 mints no Boot then!

**Comment by Edwardpge** [comment]
> with 918 you selected an old system, it is possible that it need legacy boot to run on your system.

what i meant to say that VMM BIOS not native bios! what I'm trying to do is installing windows 11 on VMM but when i set it to legacy bios in VMM it boots the ISO file but can't able to install the win 11 because it doesn't support legacy bios what i need UEFI bios in VMM, when i turn it into UEFI mode it stuck at logo and fall back to shell!

![Screenshot 2024-02-29 195739](https://github.com/AuxXxilium/arc/assets/101920742/3bf3fc8e-4756-46b4-b937-f1d0057a77c1)

**Comment by AuxXxilium** [comment]
win 11 in vmm will not work!

**Comment by Edwardpge** [comment]
> win 11 in vmm will not work!

it was working! previously!

**Comment by AuxXxilium** [comment]
and again for you and last time: arc does not change anything in dsm.

if it was working, you used a patched iso to run without tpm?

**Comment by Edwardpge** [comment]
> and again for you and last time: arc does not change anything in dsm.
> 
> if it was working, you used a patched iso to run without tpm?

Apologies for disturbing you. Actually DSM Virtual machine manager UEFI BIOS DO SUPPORT TPM 2.0 virtually, im not saying that arc is doing anything, like before KVM was causing issues in DSM VMM from running.

**Comment by AuxXxilium** [comment]
reinstall VMM and try again

**Comment by Edwardpge** [comment]
> reinstall VMM and try again

Hope you're doing well, i just want to mention that I found the  cause of VMM issue as i mentioned before it was KVM, i just disabled all three modules KVM.KO, KVM-AMD, KVM-INTEL and now VMM is running fine without any issue... I think you should reconsider these KVM modules.

**Comment by AuxXxilium** [comment]
your system is working without kvm modules? wtf? should not be possible.

**Comment by Edwardpge** [comment]
> your system is working without kvm modules? wtf? should not be possible.

Yeah bro working fine, and VMM works too

![Uploading Screenshot 2024-03-01 171110.png…]()
