### ISSUE TITLE
Can not use this loader to update to DSM 7.2

### ISSUE THREAD

**Issue by iron8706** [AuxXxilium/arc#886]
**Describe the Bug**
It runs completely normally in version 7.1.1. When I used the i5 9500t processor before, I also used version 7.2 normally. After replacing the processor (i7 9700), I tried various versions of ARC boot, but could not update to version 7.2. I tried unplugging all the hard drives and re-flashing the motherboard bios, but they all ended in failure. The specific problem is that after loading the kernel, after the cursor flashes, it automatically restarts. If it is not stopped manually, it keeps restarting. The same version of boot runs normally when booting version 7.1.1 dsm. Is version 7.2 dsm incompatible with the intel i7 9700 processor?

**Hardware**
CPU intel(R) i7-9700 @3.0GHz
Memory: 24GB
Networkcontroller RTL 8125B
Sata  Controller : Intel corporation 200 series PCH SATA controller

![1](https://github.com/AuxXxilium/arc/assets/131463898/9b73b7aa-c88f-411c-9ded-e5669375fa9b)
![2](https://github.com/AuxXxilium/arc/assets/131463898/aaff35d2-6eb4-4f82-811f-2fee5a3db1b1)
![3](https://github.com/AuxXxilium/arc/assets/131463898/3f1ee56d-e000-4be6-93b1-36d4f4143120)
![4](https://github.com/AuxXxilium/arc/assets/131463898/ed90524b-5025-4bae-a206-2822cb909e8a)

**Comment by AuxXxilium** [comment]
check your bios settings, there is an issue. it's not an arc problem, it's your hardware or bios.

**Comment by iron8706** [comment]
> check your bios settings, there is an issue. it's not an arc problem, it's your hardware or bios.

So，which bios setting or hardware ？I’m sure It‘s not the problem of nvme!

**Comment by AuxXxilium** [comment]
if the nvme was working before cpu upgrade, it's the cpu and not the nvme.

**Comment by iron8706** [comment]
> if the nvme was working before cpu upgrade, it's the cpu and not the nvme.

And why it runs well under dsm7.1.1？The dsm 7.2 ‘a kernel has bugs with some specific processor models?

**Comment by AuxXxilium** [comment]
you know about max threat count? you checked bios settings after cpu upgrade? because bios changes multiple settings if you change a cpu. 

you checked that your cpu is correctly installed and all pins in socket are good?

you know that 7.2 is more restrictive than 7.1?

...
