### ISSUE TITLE
HDD ISSUE

### ISSUE THREAD

**Issue by Edwardpge** [AuxXxilium/arc#895]
**Describe the Bug**
Hello Aux, I can't find the HDD in DSM, and i have noticed that nothing comes up at the storage map I can't find SATA maps in the config file not even max drives..., everythings works fine with 24.3.3

**Screenshots**
ARC 24.3.4

**Hardware**
Add your Hardware Information here. I5 4570 / B85 asus / Networkcontroller / Storagecontroller / ...

**Comment by AuxXxilium** [comment]
actual screenshot from sysinfo?

**Comment by Edwardpge** [comment]
> actual screenshot from sysinfo?

![Screenshot 2024-03-05 181821](https://github.com/AuxXxilium/arc/assets/101920742/1773d037-dd0e-472b-a77a-cccb2e54a680)

**Comment by Edwardpge** [comment]
![Screenshot 2024-03-05 182045](https://github.com/AuxXxilium/arc/assets/101920742/48616378-2148-4b43-b09e-f3076931dfaa)
![Screenshot 2024-03-05 182032](https://github.com/AuxXxilium/arc/assets/101920742/37c8fb21-0482-4f88-bed2-1700da9812b2)

**Comment by AuxXxilium** [comment]
whats wrong with your system? why is mpt3sas loaded but no hba connected? why are your sata drives not counted? ...

**Comment by Edwardpge** [comment]
> whats wrong with your system? why is mpt3sas loaded but no hba connected? why are your sata drives not counted? ...

not working with this version(24.3.4) though, i installed 24.3.3 and then everything's works fine!

**Comment by Edwardpge** [comment]
> whats wrong with your system? why is mpt3sas loaded but no hba connected? why are your sata drives not counted? ...

newer version never ask SATA maps setting!

**Comment by Edwardpge** [comment]
i notice you have fixed storage.sh should i upgrade the ARC?

**Comment by hyllm** [comment]
have the same issue with 24.3.4... sysinfo show 4 driver (correct) but DSM show only 2 driver (incorrect)

**Comment by Edwardpge** [comment]
> have the same issue with 24.3.4... sysinfo show 4 driver (correct) but DSM show only 2 driver (incorrect)

Aux have updated the ARC version he fixed the storage issue i guess! try update the ARC I'm updating ARC too!

**Comment by hyllm** [comment]
Ok... can confirm, that 24.3.5 fixed the problem. :)

**Comment by AuxXxilium** [comment]
in discord i got multiple reports that usb mount false is working.

**Comment by AuxXxilium** [comment]
for your information: they will be only shown as external if 2 or more disks are connected. because we need to fake these value or it will not be possible to create a storage pool.
