### ISSUE TITLE
DSM Config Panel not working

### ISSUE THREAD

**Issue by leroyconstant** [AuxXxilium/arc#901]
Good morning,

I updated the ARC Loader from version 23.9.10 to the latest 24.3.5a, and recovered my DSM. Since then, the DSM control panel is not working.
While all other software works.
Is this related to the ARC update?
thanks in advance

![image](https://github.com/AuxXxilium/arc/assets/146106162/78708c86-bf5d-41fc-a0b2-f19fdc336d09)
ARC > 24.3.5a

**Comment by AuxXxilium** [comment]
Read wiki!
