### ISSUE TITLE
how to set for run on one SATA controller

### ISSUE THREAD

**Issue by lysiong** [AuxXxilium/arc#904]
**Describe the Bug**
I can't figure up how to set for run on one SATA controller as I only have max 4 disk on model DS3622xs+
**Screenshots**
<img width="417" alt="image" src="https://github.com/AuxXxilium/arc/assets/45681255/69c3be31-bede-46f1-a9a8-77ecfb7727b3">

I want to re-map the 06 & 07 to ports 00, 01 & disable the 2nd SATA controller(06:07.0). Both 06 & 07 is the virtual hdd. 

**Hardware**
I run the xpenology on proxmox v8.1.4, arc version 24.3.2,

**Comment by AuxXxilium** [comment]
use correct storage map. the loader tells you which is recommended.

**Comment by lysiong** [comment]
I already try below

<img width="106" alt="image" src="https://github.com/AuxXxilium/arc/assets/45681255/e839cce3-24cf-4290-8f21-e0d6490ce190">

<img width="119" alt="image" src="https://github.com/AuxXxilium/arc/assets/45681255/d1f8e08c-4b1d-4b09-9408-a6b920c5e32c">

but still not able to move the SATA disk to 00 & 01 although inside Synology disk storage show the correct disk map

<img width="518" alt="image" src="https://github.com/AuxXxilium/arc/assets/45681255/70c4d14b-998e-4174-be45-6412557f723b">

is that possible to remap in the loader?

**Comment by AuxXxilium** [comment]
yes with remap. don't set on your own. use storage map inside loader. or you choose a dt model. they don't need portmaps.

**Comment by keitetran** [comment]
You can change hdd boot to scsi not sata.
On bootloader will auto map sata hdd only. 

Drive1: scsi0 - bootloader
Drive2: sata0 - vitual hdd

Satamap : 6>0
