### ISSUE TITLE
No gateway config in static network arc config

### ISSUE THREAD

**Issue by dyter69** [AuxXxilium/arc#905]
**Describe the Bug**
In static mode, I have no internet because nothing for setup a gateway

**Screenshots**
![1](https://github.com/AuxXxilium/arc/assets/74374087/afcb41a1-5bfb-4ceb-b2bf-f7dc8fe99e4b)
![2](https://github.com/AuxXxilium/arc/assets/74374087/b763ad32-27d7-47a0-af47-897472b95246)
![3](https://github.com/AuxXxilium/arc/assets/74374087/f5198898-606d-468d-96ec-8c67f842d1f1)
![4](https://github.com/AuxXxilium/arc/assets/74374087/00754eb6-ee49-44e4-bc90-2c41c4699459)

**Hardware**
![sysinfo](https://github.com/AuxXxilium/arc/assets/74374087/fb9de20d-ccfb-4843-8323-988d73ffa042)

**Comment by AuxXxilium** [comment]
we don't need, we need dhcp to get dns and gateway!

**Comment by dyter69** [comment]
buy my DHCP server is the Synology !....


too bad this configuration line is missing, any network equipment has this function however

**Comment by AuxXxilium** [comment]
set it manually, look for linux commandline, if you have read wiki, you will see that we need a dhcp for installation!

**Comment by dyter69** [comment]
not very practical, I don't understand why because it's work nice without ... I think it would be quicker to connect my old router !
