### ISSUE TITLE
flood log

### ISSUE THREAD

**Issue by dyter69** [AuxXxilium/arc#906]
**Describe the Bug**

I disable all com in bios, I changed my N3150 by a J5040 hardware with other motherboard, same problem, log is flooding with recurent messages

**Screenshots**
cat /var/log/messages

```
Mar  8 16:41:56 syno_localinstall_dsm.sh: netlink_ok=true
Mar  8 16:41:56 syno_localinstall_dsm.sh: main(), start:
Mar  8 16:42:00 syno_localinstall_dsm.sh: netlink_ok=true
Mar  8 16:42:00 syno_localinstall_dsm.sh: main(), start:
2024-03-08T16:42:04+01:00 DISKSTATION kernel: [  572.043677] synobios get empty ttyS current
Mar  8 16:42:04 syno_localinstall_dsm.sh: netlink_ok=true
Mar  8 16:42:04 syno_localinstall_dsm.sh: main(), start:
Mar  8 16:42:08 syno_localinstall_dsm.sh: netlink_ok=true
Mar  8 16:42:08 syno_localinstall_dsm.sh: main(), start:
```

**Hardware**
![sysinfo](https://github.com/AuxXxilium/arc/assets/74374087/d2840f7c-197a-42bd-95eb-602f60c76038)

**Comment by AuxXxilium** [comment]
1. use latest stable build
2. force reinstall dsm

**Comment by dyter69** [comment]
Hello,

Same problem !
