### ISSUE TITLE
Problem mit Netzwerk/Internetverknüpfung

### ISSUE THREAD

**Issue by TimBayern** [AuxXxilium/arc#923]
Hallo Christian, zunächst einmal ein großes Kompliment für dieses tolle Tool. In einem Deiner letzten Videos gibst Du Info, das sich der arcloader automatisch aktualisiert. Dies funktioniert bei mir leider nicht.
Ich habe folgendes Problem.
Ich nutze insgesamt 3 Netzwerkkarten, eine davon installiert auf dem Board. Die beiden anderen über pcie installiert.
Diese beiden nderen habe ich im dsm als bond verbunden (balance xor)
Die drei netzwerkkabel sind an einem switch angeschlossen, die beiden bond kabel an static link aggregation ports.
Im dsm funktionert dies hervorragend, im arc loader leider nicht; er zieht sich ip-adressen, kommt jedoch nicht ins internet. Nur wenn ich die original Netzwerkkarte am switch angeschlossen lasse, die beiden „bond“ kabel abziehe.
Vermutlich ist das nur eine  Kleinigkeit , aber ich bin wohl zu doof dafür.
Über den Webbrowser komm ich auch nicht ins arc :7681…
Und ich habe ab und an Probleme mit dem Internet; es lassen sich manchmal Internetseiten nicht öffnen. Ich denke das hat alles damit zu tun.
![IMG_0147](https://github.com/AuxXxilium/arc/assets/163463799/f1a44d38-4892-4a3b-96fd-a7fc137e0ca3)

**Comment by AuxXxilium** [comment]
Arc kann keine Bond nutzen, ist ganz normal und wir auch nie kommen da wir für die Unterstützung einige Inhalte integrieren müssen, welche dann das Image auf über 2GB pro Download wachsen lassen.
