### ISSUE TITLE
Request for Making Loader Installation Possible Solely on M.2 NVMe without SATA Storage Requirement

### ISSUE THREAD

**Issue by teslaweiler** [AuxXxilium/arc#925]
Dear AuxXxilium team,

I hope this message finds you well. I am writing to request assistance regarding the installation process of loaders specifically tailored to M.2 NVMe drives. Currently, many loader installations necessitate the presence of SATA storage alongside M.2 NVMe drives. However, I am seeking a solution where loader installation can be achieved solely on M.2 NVMe storage without any requirement for SATA storage.

This request stems from the desire to streamline the installation process, optimize resource utilization, and simplify configurations for systems primarily reliant on M.2 NVMe drives. By eliminating the necessity for SATA storage altogether, users like myself could benefit from enhanced efficiency and reduced complexity in setup procedures.

I understand that such a modification to loader installation processes might require adjustments to existing software or potentially the development of new tools. Nonetheless, I believe this enhancement would greatly benefit users who prioritize M.2 NVMe storage in their systems.

Therefore, I kindly ask for your expertise, insights, and suggestions on how to make loader installation possible solely on M.2 NVMe drives without any reliance on SATA storage. Any guidance, recommendations, or pointers to relevant resources would be immensely appreciated.

Thank you for your attention to this matter, and I eagerly await your valuable input.

Best regards,
Dave

**Comment by AuxXxilium** [comment]
![Screenshot 2024-03-15 203909](https://github.com/AuxXxilium/arc/assets/67025065/c6d46bfa-531a-4611-a821-a5fb8c98fd9d)
