### ISSUE TITLE
Can't mount usb as internet disk

### ISSUE THREAD

**Issue by Jaydenha09** [AuxXxilium/arc#929]
I already set USB Mount to false, but it doesn't mount usb as internal disk

Sysinfo code: EMUGRDBLE

Lenovo X260, i5 6200U
Arc: 24.3.11
DSM 7.2: DS920+

**Comment by AuxXxilium** [comment]
Read wiki

**Comment by Jaydenha09** [comment]
I already set it to USB Mount to true but still doesn't mount usb as internal disk, how can I set to force?

**Comment by AuxXxilium** [comment]
Read wiki!!!!!

**Comment by Jaydenha09** [comment]
ok I think I know why now DT isnt supported sry

**Comment by Jaydenha09** [comment]
now I switched to DS918+, and it said No drivers detected in DS918+, how can I fix that
