### ISSUE TITLE
V23.02.27 - DS2422+ tn40xx Tehuti 10GB NIC Driver missing

### ISSUE THREAD

**Issue by RJSUTH** [AuxXxilium/arc#93]
Hello again.

I switched  for my Thecus N7770-10G from DS3622xs+ broadwellnk to DS2422+ VT1000-DT because it boots reliably. 
But my 10GBit Tehuti TN9210 is not recognized.

Could you please integrate the tn40xx driver into this release?

**Comment by AuxXxilium** [comment]
All driver from DS3622xs+ are also included in 2422+. So i need a Screenshot from Arc - SysInfo Menu to find whats wrong.

**Comment by RJSUTH** [comment]
![image](https://user-images.githubusercontent.com/122780513/222363136-7c1aacdf-b16e-4f11-b9b2-9209362048e8.png)

**Comment by RJSUTH** [comment]
2 onboard, maybe Intel, in Bios they don't appear, one one PCIE-E Tehuti TN9210 10G . And the Tehuti does not appear

**Comment by AuxXxilium** [comment]
Loader knows that there are 3 Network adapter, but he only can know it, if driver are loaded. the only driver that is loaded is Intel Gigabit NIC. I don't know whats wrong, can add the driver today. 

Is the network working with DS3622? If yes, we don't need the new driver.

**Comment by RJSUTH** [comment]
yes ist works with DS3622

**Comment by AuxXxilium** [comment]
funny, because tn40xx isn't included in DS3622. 

i think there is a lock for 10G on 2422. will look to find it today.

**Comment by RJSUTH** [comment]
Ah, ok. I Hope you will find a way to activate, because this NIC consumes very low power, it doesn't even have a heatsink or fan

**Comment by RJSUTH** [comment]
Here you see below DS3622 booting and loading tn40xx, i didn't see this in 2422

![image](https://user-images.githubusercontent.com/122780513/222485944-7f263414-d1f4-4ee5-9b08-c6b6fca633b9.png)

**Comment by AuxXxilium** [comment]
found issue, update will come online the next hours

**Comment by RJSUTH** [comment]
it works

**Comment by RJSUTH** [comment]
Hello again,  V23.5.30 - DS2422+my tn40xx Tehuti 10GB NIC is missing again.
please can you fix this?

**Comment by AuxXxilium** [comment]
if i find some time today, i will do it. 

in 7.2 the modules are included. looks like i missed 7.1
