### ISSUE TITLE
Cannot build bootloader

### ISSUE THREAD

**Issue by bandit400** [AuxXxilium/arc#930]
As you can see from the videos, trying to set a basic configuration, the procedure ends and it is not possible to create the bootloader.

System Configuration:
Sysinfo Code: **BRW83FL58**
Test environment: **VirtualBox 7.0.8 r156879 (Qt5.15.2)**
ARC bootloader: **arc-24.3.16.vmdk-dyn**

[Synology DSM-screen0 - video 00.webm](https://github.com/AuxXxilium/arc/assets/52614292/33aaf55d-1a0b-4d7e-ab83-b348a5c0e89c)

[Synology DSM-screen0 - video 01.webm](https://github.com/AuxXxilium/arc/assets/52614292/ba45a770-9bb8-434b-9a29-8da90f0f0519)

![VirtualBox_Synology DSM_17_03_2024_11_36_55](https://github.com/AuxXxilium/arc/assets/52614292/89fc0e2c-a03d-436d-a2e2-53e7674258c6)

![VirtualBox_Synology DSM_17_03_2024_11_37_15](https://github.com/AuxXxilium/arc/assets/52614292/b816a12a-f0f4-4fcf-bb83-eee6154aec52)

![VirtualBox_Synology DSM_17_03_2024_11_37_26](https://github.com/AuxXxilium/arc/assets/52614292/133cc6a7-a214-4b9e-bd92-471e37c37036)

**Comment by bandit400** [comment]
Ok, what is the fix to this problem?

**Comment by AuxXxilium** [comment]
my problem is, i can‘t reproduce this. in my systems .16 and .17 is working without any issue.

**Comment by AuxXxilium** [comment]
redownload in 15 minutes from now. try again

**Comment by bandit400** [comment]
Ok, this issue seems to be solved.
