### ISSUE TITLE
Syntax error during script execution e some graphical glitch

### ISSUE THREAD

**Issue by bandit400** [AuxXxilium/arc#944]
System Configuration:
Sysinfo Code: **4H8FPLAUV**
Test environment: **VirtualBox 7.0.8 r156879 (Qt5.15.2)**
ARC bootloader: **arc-24.3.26.vmdk-dyn**

![Screenshot 2024-03-26 214008](https://github.com/AuxXxilium/arc/assets/52614292/df793562-6150-4f87-a8fd-54626590c954)

![Screenshot 2024-03-26 213857](https://github.com/AuxXxilium/arc/assets/52614292/1a4bd486-d939-439e-9ea1-809a633f86bc)

**Comment by AuxXxilium** [comment]
Macsys Setting is fixed.

Syntax Error is caused by VirtualBox. that is not fully supported and i think it never will.

**Comment by bandit400** [comment]
Christian, just to clarify. The difference between the arc.sh file version 24.3.26 and the arc.sh file version 24.3.27 is all in the first lines. In particular, line 20 of the arc.sh 24.3.26 file has a syntax error, there is a "$" character and parentheses that should not be there. In the arc.sh file version 24.3.27 you have completely rewritten this section. How can this depend on the use of VirtualBox?

![Screenshot 2024-03-27 214910](https://github.com/AuxXxilium/arc/assets/52614292/1e7dc4e9-0a34-48d7-9f72-b54e3bac8f45)

**Comment by AuxXxilium** [comment]
virtualbox does not provide dmidecode

**Comment by bandit400** [comment]
Sorry Christian, but i don't understand. From your bootloader, i've executed **dmidecode** command and this is the result:

`dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 2.5 present.
10 structures occupying 455 bytes.
Table at 0xBEFFD020.

Handle 0x0000, DMI type 0, 20 bytes
BIOS Information
        Vendor: innotek GmbH
        Version: VirtualBox
        Release Date: 12/01/2006
        Address: 0xE0000
        Runtime Size: 128 kB
        ROM Size: 128 kB
        Characteristics:
                ISA is supported
                PCI is supported
                Boot from CD is supported
                Selectable boot is supported
                8042 keyboard services are supported (int 9h)
                CGA/mono video services are supported (int 10h)
                ACPI is supported
                UEFI is supported

Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: innotek GmbH
        Product Name: VirtualBox
        Version: 1.2
        Serial Number: 0
        UUID: e35fa47f-4467-9e4b-8508-eb45b21de067
        Wake-up Type: Power Switch
        SKU Number: Not Specified
        Family: Virtual Machine

Handle 0x0008, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: Oracle Corporation
        Product Name: VirtualBox
        Version: 1.2
        Serial Number: 0
        Asset Tag: Not Specified
        Features:
                Board is a hosting board
        Location In Chassis: Not Specified
        Chassis Handle: 0x0003
        Type: Motherboard
        Contained Object Handles: 0

Handle 0x0003, DMI type 3, 13 bytes
Chassis Information
        Manufacturer: Oracle Corporation
        Type: Other
        Lock: Not Present
        Version: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Safe
        Security Status: None

Handle 0x0007, DMI type 126, 42 bytes
Inactive

Handle 0x0005, DMI type 126, 15 bytes
Inactive

Handle 0x0006, DMI type 126, 34 bytes
Inactive

Handle 0x0002, DMI type 11, 7 bytes
OEM Strings
        String 1: vboxVer_7.0.8
        String 2: vboxRev_156879

Handle 0x0008, DMI type 128, 8 bytes
OEM-specific Type
        Header and Data:
                80 08 08 00 1D 0B 20 00

Handle 0xFEFF, DMI type 127, 4 bytes
End Of Table`

What's wrong with the result obtained?

**Comment by bandit400** [comment]
Ok, I think I found the answer myself. For example, the memory size isn't present in the "dmidecode" output...

`root@arc:/opt/arc# dmidecode -t memory | grep -i "Size" | cut -d" " -f2 | grep -i "[1-9]"
root@arc:/opt/arc#`

...when, in the normal way, the output may be like this...

`root@linux ~ $ dmidecode -t memory | grep -i "Size" | cut -d" " -f2 | grep -i "[1-9]"
8
8
root@linux ~ $`

Is all this right? Thank you for your efforts in making this bootloader a very powerful tool! And thank you for giving me the opportunity to increase my knowledge!
