### ISSUE TITLE
SAN Manager not working

### ISSUE THREAD

**Issue by myoname** [AuxXxilium/arc#947]
**Describe the Bug**
Hello. Any chance to get it working without Force reinstall?
I noticed this error after updating to later builds. Previously I added a SAN Manager patch in addons in early builds of loader somewhere at the beginning of the year. The patch was excluded from addons, but the error remained.

**Screenshots**
![IMG_20240327_205244](https://github.com/AuxXxilium/arc/assets/157968912/d8ab5ebd-777a-4831-b4f3-02371a9ba1e4)
![IMG_20240327_205524](https://github.com/AuxXxilium/arc/assets/157968912/b2ce4e2d-98ca-4e7e-b95c-8404bde6231d)
![SAN](https://github.com/AuxXxilium/arc/assets/157968912/0687cb5f-d76f-43bd-8100-00e6e9964e2f)

**Hardware**
88RPD5CPE

**Comment by AuxXxilium** [comment]
disable kvm support in arc and rebuild

**Comment by myoname** [comment]
did not helped

**Comment by AuxXxilium** [comment]
than something else in your system is wrong, can't figure it out without full boot/serial logs

**Comment by myoname** [comment]
did not find info, will force reinstall remove my settings and apps?

**Comment by AuxXxilium** [comment]
yes and yes, but app settings will be restored after installation, but you know dsm settings backup function?

**Comment by myoname** [comment]
Yes, of cause, but it backup not all settings

**Comment by myoname** [comment]
ok, i'll try it later. thank you

**Comment by myoname** [comment]
just perfect, force reinstall
everything is restored, apps and settings, except LAN1, it's became dhcp
I haven't noticed anything else yet
thanx again))

**Comment by myoname** [comment]
and DSM updated to DSM 7.2.1-69057 Update 4, was Update 3
