### ISSUE TITLE
Possibility to upload a .pat file permanently

### ISSUE THREAD

**Issue by extern-int** [AuxXxilium/arc#969]
When I make any changes to the settings I have to build a loader. This requires either downloading the pat file again or uploading it again (unfortunately, after a restart the content of /tmp/upload disappears). it would be much more convenient for testing if I could upload the pat file to some permanent location. The ability to control the default upload path is enough.

**Comment by AuxXxilium** [comment]
why use .pat file? and no because the .pat is to big, to store it inside the loader image. only ramdisk is possible.

**Comment by extern-int** [comment]
Sorry, maybe I don't understand something, I'm a beginner. Each time I change the loader configuration, I am forced to upload a pat file (in offline mode) or allow the loader to download something from the synology website. If there is an alternative, I would like to know.

The loader is on my virtual disk where I can have as much space as I want. I can upload the file to, for example, /mnt/p3, but the loader will still expect the file in /tmp/upload.

The problem for me is the constant uploading of this file after each configuration change, I would also like to avoid constantly downloading something from synology servers.

**Comment by AuxXxilium** [comment]
you don't have to upload anything, this is only needed if your network/dns block connection to github. switch to online mode and everything will work. offline mode is for ppl who don't have an internet connection on their nas. best you read wiki and understand what is written.

**Comment by AuxXxilium** [comment]
the loader isn't downloading from syno, it is only checking for latest version and downloading about 12mb from my github. so i don't know why you use offline mode!

**Comment by AuxXxilium** [comment]
and no we don't have enough space on loader disk to save a .pat file permanantly!!!
